# Research data supporting "Efficient first-principles modeling of complex molecular crystals at sub-chemical accuracy"

This notebook accompanies our paper: **Efficient first-principles modeling of complex molecular crystals at sub-chemical accuracy**. It can be found on GitHub at https://github.com/benshi97/Data_LNOMBECC and explored interactively on [Colab](https://colab.research.google.com/github/benshi97/Data_LNOMBECC/blob/main/analyse.ipynb).

### Abstract

Molecules can form myriad crystalline polymorphs, each with distinct properties affecting their performance across diverse applications, from pharmaceuticals to functional materials and more.
Predicting the thermodynamically most stable polymorph from first principles remains a formidable challenge.
It requires methods that scale to large, technologically-relevant molecules while achieving very high accuracy (below 1 kJ/mol) on relative lattice energies.
Such accuracy – often termed sub-chemical accuracy – is generally beyond the reach of the workhorse density functional theory (DFT).
In this work, we introduce a framework combining several recent advances in correlated wavefunction theory (cWFT) to deliver accurate, cost-effective predictions of complex molecular crystals.
For 23 model organic molecules and 13 ice polymorphs, we predict crystal lattice energies to within experimental uncertainties at costs comparable to hybrid DFT, while being several orders of magnitude more efficient than previous cWFT approaches.
We extend this approach to a set of large, drug-like molecules including  axitinib and ROY – previously inaccessible to cWFT and where DFT is insufficient – achieving sub-chemical accuracy on the relative energies between challenging polymorphs.
With the reference data generated throughout this work, we have been able to further parametrize a DFT functional with unprecedented accuracy aligning with our predictions.
This cWFT framework as well as DFT functional are made openly available, providing new ranking tools to facilitate efficient high-throughput screening of molecular crystal polymorphs.

## Table of Contents

1. [Lattice energies of X23 dataset](#lattice-energies-of-x23-dataset)
2. [Analysis DMC costs](#analysis-dmc-costs)
3. [Lattice and relative energies of ICE13](#lattice-and-relative-energies-of-ice13)
4. [Optimizing B86bPBE50-revXDM](#optimizing-b86bpbe50-revxdm)
5. [Relative energies of pharmaceutical polymorphs](#relative-energies-of-pharmaceutical-polymorphs)
6. [DFT Benchmarks](#dft-benchmarks)

In [ ]:
# Check if we are in Google Colab environment
try:
    import google.colab
    IN_COLAB = True
    usetex = False
    import os
    os.environ["GITHUB_TOKEN"] = "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"
    import subprocess
    import sys
    def pip_install(pkg):
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "--quiet", pkg],
            check=True
        )

    pip_install("ase")
    pip_install("pyblock")
except:
    import os
    IN_COLAB = False
    if os.path.expanduser('~') == '/Users/bshi':
        usetex = True
    else:
        usetex = False

if usetex:
    def textbf(text):
        return r'\textbf{' + text + '}'
else:
    def textbf(text):
        return text

# If in Google Colab, install the necessary data and set up the necessary environment
if IN_COLAB == True:
    repo_url = "https://github.com/benshi97/Data_LNOMBECC"
    token = os.environ["GITHUB_TOKEN"]

    auth_repo_url = repo_url.replace(
        "https://", f"https://{token}@"
    )

    # Clone the repository
    %cd /content
    !rm -rf /content/Data_LNOMBECC
    !git clone {auth_repo_url}
    %cd /content/Data_LNOMBECC

replot_analysis = False

# Import necessary functions
from Scripts.analysis_scripts import *
from Scripts.plot_scripts import *

if usetex == True:
    textrue_import()
else:
    texfalse_import()

# Lattice energies of X23 dataset

## Experimental data analysis

In [2]:
# Collate the reference DMC and Experiment data
# The original data from Phys. Rev. Lett. 133, 046401 put hexamine and succinic acid at the end rather than alphabetically, which we will correct here
prl_names_order={idx+1: x for idx,x in enumerate(["1,4-cyclohexanedione" ,"Acetic Acid" ,"Adamantane" ,"Ammonia" ,"Anthracene" ,"Benzene" ,"CO$_2$" ,"Cyanamide" ,"Cytosine" ,"Ethyl carbamate" ,"Formamide" ,"Imidazole" ,"Naphthalene" ,r"Oxalic Acid $\alpha$" ,r"Oxalic Acid $\beta$" ,"Pyrazine" ,"Pyrazole" ,"Triazine" ,"Trioxane" ,"Uracil" ,"Urea" ,"Hexamine" ,"Succinic Acid" ])}
prl_to_x23_order = {idx+1: x for idx, x in enumerate([1,2,3,4,5,6,7,8,9,10,11,22,12,13,14,15,16,17,23,18,19,20,21])}
x23_labels = {x23_idx: prl_names_order[prl_to_x23_order[x23_idx]] for x23_idx in range(1,24)}


x23_dmc_data_raw=np.loadtxt('Data/X23/DMC/DMC.txt') # DMC estimates are in the PRL order
x23_dmc_elatt_dict = {x23_idx: list(x23_dmc_data_raw[prl_to_x23_order[x23_idx]-1]) for x23_idx in range(1,24)}

# Load the thermal corrections computed with vdW-DF2 MLIP from Chem. Sci., 2025,16, 11419-11433
pimd_deltah_raw =np.loadtxt('Data/X23/MLIP/DeltaH.txt',delimiter=',') # In PRL order
pimd_deltah_dict = {x23_idx: {'Elatt': pimd_deltah_raw[prl_to_x23_order[x23_idx]-1][0], 'DeltaH': -pimd_deltah_raw[prl_to_x23_order[x23_idx]-1][1], 'Etemp': -pimd_deltah_raw[prl_to_x23_order[x23_idx]-1][1] - pimd_deltah_raw[prl_to_x23_order[x23_idx]-1][0]} for x23_idx in range(1,24)}

x23_exp_enthalpy_dict = {}
x23_exp_elatt_dict = {}
# Load the experimental enthalpy data (this is also in the PRL order)
for x23_idx in range(1,24):
    system_enthalpy_data = -np.loadtxt(f'Data/X23/Experiment/expdata_{prl_to_x23_order[x23_idx]}_with_corrections.txt')
    if x23_labels[x23_idx] in ['Ammonia','Pyrazine',r'Oxalic Acid $\beta$']:
        system_enthalpy_data = system_enthalpy_data[:-1]
    x23_exp_enthalpy_dict[x23_idx] = system_enthalpy_data
    x23_exp_elatt_dict[x23_idx] = [x - pimd_deltah_dict[x23_idx]['Etemp'] for x in x23_exp_enthalpy_dict[x23_idx]]

### Correlation between standard deviation and adsorption enthalpy

In [3]:
# For a subset of systems, correlate the strength of the enthalpy and the standard deviation as well as range
x23_std_enthalpy_dict = {x23_idx: [np.std(x23_exp_enthalpy_dict[x23_idx]), np.mean(x23_exp_enthalpy_dict[x23_idx]), np.abs(np.max(x23_exp_enthalpy_dict[x23_idx]) - np.min(x23_exp_enthalpy_dict[x23_idx]))] for x23_idx in x23_exp_enthalpy_dict.keys() if len(x23_exp_enthalpy_dict[x23_idx]) > 4}

# Make a plot for the correlation between standard deviation and enthalpy as well as range and enthalpy
fig, axs = plt.subplots(1,2,figsize=(6.69,3.5),dpi=450, constrained_layout=True)
axs[0].scatter([x23_std_enthalpy_dict[x][1] for x in x23_std_enthalpy_dict.keys()], [x23_std_enthalpy_dict[x][0] for x in x23_std_enthalpy_dict.keys()], color=color_dict['black'])
# Fit a line and give the R^2 value
m, b = np.polyfit([x23_std_enthalpy_dict[x][1] for x in x23_std_enthalpy_dict.keys()], [x23_std_enthalpy_dict[x][0] for x in x23_std_enthalpy_dict.keys()], 1)
std_enthalpy_grad = m.copy()
std_enthalpy_int = b.copy()

correlation_matrix = np.corrcoef([x23_std_enthalpy_dict[x][1] for x in x23_std_enthalpy_dict.keys()], [x23_std_enthalpy_dict[x][0] for x in x23_std_enthalpy_dict.keys()])
correlation_xy = correlation_matrix[0,1]
r_squared = correlation_xy**2
axs[0].plot([x23_std_enthalpy_dict[x][1] for x in x23_std_enthalpy_dict.keys()], [m*x23_std_enthalpy_dict[x][1] + b for x in x23_std_enthalpy_dict.keys()], color=color_dict['red'], label = f'Best fit ($R^2={r_squared:.2f}$)')

for x in x23_std_enthalpy_dict.keys():
    axs[0].text(x23_std_enthalpy_dict[x][1], x23_std_enthalpy_dict[x][0] + 0.15, x23_labels[x], fontsize=6, ha='right', va='bottom')
axs[0].set_xlabel('Mean experimental enthalpy (kJ/mol)')
axs[0].set_ylabel('Standard deviation (kJ/mol)')
axs[0].text(0, 1.08, '(a)', transform=axs[0].transAxes, fontsize=10, verticalalignment='top')
axs[0].legend(fontsize=8)
axs[0].set_title('Std. dev. vs. enthalpy')



axs[1].scatter([x23_std_enthalpy_dict[x][1] for x in x23_std_enthalpy_dict.keys()], [x23_std_enthalpy_dict[x][2] for x in x23_std_enthalpy_dict.keys()], color=color_dict['black'])
for x in x23_std_enthalpy_dict.keys():
    axs[1].text(x23_std_enthalpy_dict[x][1], x23_std_enthalpy_dict[x][2] + 0.4, x23_labels[x], fontsize=6, ha='right', va='bottom')

# Fit a line and give the R^2 value
m, b = np.polyfit([x23_std_enthalpy_dict[x][1] for x in x23_std_enthalpy_dict.keys()], [x23_std_enthalpy_dict[x][2] for x in x23_std_enthalpy_dict.keys()], 1)

correlation_matrix = np.corrcoef([x23_std_enthalpy_dict[x][1] for x in x23_std_enthalpy_dict.keys()], [x23_std_enthalpy_dict[x][2] for x in x23_std_enthalpy_dict.keys()])
correlation_xy = correlation_matrix[0,1]
r_squared = correlation_xy**2
axs[1].plot([x23_std_enthalpy_dict[x][1] for x in x23_std_enthalpy_dict.keys()], [m*x23_std_enthalpy_dict[x][1] + b for x in x23_std_enthalpy_dict.keys()], color=color_dict['red'], label = f'Best fit ($R^2={r_squared:.2f}$)')
axs[1].text(0, 1.08, '(b)', transform=axs[1].transAxes, fontsize=10, verticalalignment='top')
axs[1].set_title('Range vs. enthalpy')


axs[1].set_xlabel('Mean experimental enthalpy (kJ/mol)')
axs[1].set_ylabel('Range (kJ/mol)')
axs[1].legend(fontsize=8)
plt.savefig('Figures/SI_Figure-X23_Exp_Enthalpy_Std_Range.png')

In [4]:
x23_exp_elatt_compile_dict = {}
for x23_idx in range(1,24):
    if len(x23_exp_enthalpy_dict[x23_idx]) > 4:
        enthalpy_range = np.abs(np.max(x23_exp_enthalpy_dict[x23_idx]) - np.min(x23_exp_enthalpy_dict[x23_idx]))
        enthalpy_sigma = np.std(x23_exp_enthalpy_dict[x23_idx])
        error_type = 'Real'
        error = 2*enthalpy_sigma
    else:
        enthalpy_range = np.nan
        enthalpy_sigma = np.nan
        error_type = 'Predicted'
        error = 2*(std_enthalpy_grad * np.mean(x23_exp_enthalpy_dict[x23_idx]) + std_enthalpy_int)
    x23_exp_elatt_compile_dict[x23_labels[x23_idx]] = {
        'Enthalpy measurements': ', '.join([f"{y:.1f}" for y in x23_exp_enthalpy_dict[x23_idx]]),
        'Etemp': f"{pimd_deltah_dict[x23_idx]['Etemp']:.1f}",
        'Mean enthalpy': f"{np.mean(x23_exp_enthalpy_dict[x23_idx]):.1f}",
        r"2sigma": f"{2*enthalpy_sigma:.1f}" if not np.isnan(enthalpy_sigma) else '-',
        r"Predicted 2sigma": f"{2*(std_enthalpy_grad * np.mean(x23_exp_enthalpy_dict[x23_idx]) + std_enthalpy_int):.1f}",
        "Range": f"{enthalpy_range:.1f}" if not np.isnan(enthalpy_range) else '-',
        'Lattice energy': f"{np.mean(x23_exp_elatt_dict[x23_idx]):.1f}",
        'Error': f"{error:.1f}",
        'Error type': error_type
}
x23_exp_elatt_df = pd.DataFrame.from_dict(x23_exp_elatt_compile_dict, orient='index')
display(x23_exp_elatt_df)

# Convert to LaTeX table
latex_input_str = '\n'.join(convert_df_to_latex_input(
    df = x23_exp_elatt_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_experimental_lattice_energies",
    caption = r"Experimental lattice energies of the X23 set. All values are in kJ/mol.",
    replace_input= {
        "sigma": r"$\sigma$",
        "Etemp": r"$E_\text{temp}$~\cite{dellapiaAccurateEfficientMachine2025}",
        r" & \rotatebox{90}{Enthalpy measurements}": "Systems & Enthalpy measurements",
    },
    index = True,
    rotate_column_header=True,
    column_format="lp{40mm}rrrrrrrr",
    output_str=True,
    float_fmt="%.1f").splitlines()[6:-4]) + '\n'

with open('Tables/SI_Table-X23_Experimental_Lattice_Energies.tex', 'w') as f:
    f.write(r"""\LTcapwidth=\textwidth
    
\begin{longtable}{lp{35mm}rrrrrrrrr}
\caption{\label{tab:x23_experimental_lattice_energies}Compilation of experimental lattice energies of the X23 set, together with the mean and (analyzed) error estimate. All values are in kJ/mol.} \\

\toprule
Systems & Enthalpy measurements & \rotatebox{90}{$E_\text{temp}$~\cite{dellapiaAccurateEfficientMachine2025}} & \rotatebox{90}{Mean enthalpy} & \rotatebox{90}{2$\sigma$} & \rotatebox{90}{Predicted 2$\sigma$} & \rotatebox{90}{Range} & \rotatebox{90}{Lattice energy} & \rotatebox{90}{Error} & \rotatebox{90}{Error type} \\ 
\midrule
\endfirsthead



\caption[]{(continued)} \\
\endhead

\multicolumn{11}{r}{{Continued on next page}} \\
\endfoot

\bottomrule
\endlastfoot

""")
    f.write(latex_input_str)
    f.write(r"\end{longtable}")

,Enthalpy measurements,Etemp,Mean enthalpy,2sigma,Predicted 2sigma,Range,Lattice energy,Error,Error type
"1,4-cyclohexanedione","-84.2, -75.0, -84.0",6.4,-81.1,-,6.6,-,-87.5,6.6,Predicted
Acetic Acid,"-66.2, -68.7",5.0,-67.5,-,5.4,-,-72.4,5.4,Predicted
Adamantane,"-58.5, -59.6, -56.0, -55.3, -59.5, -60.2, -59....",6.7,-58.3,4.7,4.5,9.0,-64.9,4.7,Real
Ammonia,-31.1,5.8,-31.1,-,2.0,-,-36.8,2.0,Predicted
Anthracene,"-98.8, -98.5, -99.1, -96.2, -99.7, -103.5, -97...",5.6,-98.7,7.5,8.3,13.4,-104.2,7.5,Real
Benzene,"-41.5, -45.0, -45.1, -52.5, -48.0, -45.6, -43....",7.7,-45.1,5.4,3.3,11.0,-52.8,5.4,Real
CO$_2$,"-26.1, -24.7, -25.5, -25.5, -25.0",3.8,-25.3,1.0,1.5,1.4,-29.1,1.0,Real
Cyanamide,"-75.8, -75.0",4.2,-75.4,-,6.1,-,-79.6,6.1,Predicted
Cytosine,"-168.8, -155.3, -149.8, -155.0, -167.0, -176.0",5.3,-162.0,18.5,14.1,26.2,-167.2,18.5,Real
Ethyl carbamate,"-77.2, -72.3, -89.1, -76.0",6.2,-78.6,-,6.4,-,-84.9,6.4,Predicted
Formamide,"-72.2, -71.7, -72.4",6.5,-72.1,-,5.8,-,-78.6,5.8,Predicted
Hexamine,"-78.7, -77.0, -79.1, -74.0, -80.0, -75.0, -75.0",6.7,-77.0,4.4,6.3,6.0,-83.7,4.4,Real
Imidazole,"-83.1, -80.8, -83.0, -74.0, -85.0",4.6,-81.2,7.7,6.7,11.0,-85.8,7.7,Real
Naphthalene,"-87.8, -72.3, -73.0, -79.0, -71.3, -73.7, -71....",5.3,-72.0,8.3,5.8,24.0,-77.3,8.3,Real
Oxalic Acid $\alpha$,"-93.7, -94.0",2.5,-93.8,-,7.8,-,-96.4,7.8,Predicted
Oxalic Acid $\beta$,-93.6,1.0,-93.6,-,7.8,-,-94.6,7.8,Predicted
Pyrazine,-56.3,6.9,-56.3,-,4.4,-,-63.2,4.4,Predicted
Pyrazole,"-73.9, -72.2, -74.0, -69.0",4.1,-72.3,-,5.8,-,-76.3,5.8,Predicted
Succinic Acid,"-128.7, -119.4, -121.7, -119.6, -123.0, -122.0...",-5.2,-122.0,6.0,10.4,9.3,-116.8,6.0,Real
Triazine,"-56.9, -54.2",6.6,-55.6,-,4.3,-,-62.2,4.3,Predicted
Trioxane,"-56.7, -55.6, -56.5, -56.2",7.8,-56.2,-,4.3,-,-64.1,4.3,Predicted
Uracil,"-127.4, -130.8, -129.3, -134.3, -122.2, -123.8...",4.5,-128.8,9.5,11.1,15.4,-133.3,9.5,Real
Urea,"-95.8, -96.0, -95.5, -92.3, -88.7, -97.8, -96....",5.2,-94.1,7.0,7.8,9.9,-99.2,7.0,Real

## Periodic HF analysis

In [5]:
# Analyse the periodic HF data
x23_hf_elatt_dict = {y: 0 for y in list(range(1,24))}
x23_hf_d4_elatt_dict = {y: 0 for y in list(range(1,24))}

x23_hf_elatt_contribution_dict = {y: {'VASP_Hard_Default':0,'VASP_Std_Default':0,'VASP_Std_High':0, 'Delta': 0, 'Final': 0} for y in list(range(1,24))}

for x23_idx in range(1,24):
    # Correct the order of the structures  
    molecule_ene = []
    solid_ene = []

    molecule = read(f'Data/X23/HF/VASP_Hard_Default/{prl_to_x23_order[x23_idx]:02d}/molecule/OUTCAR_HF.gz')
    solid = read(f'Data/X23/HF/VASP_Hard_Default/{prl_to_x23_order[x23_idx]:02d}/solid/OUTCAR_HF.gz')
    num_monomer = len(solid)/len(molecule)

    for calc_type in ['VASP_Hard_Default','VASP_Std_Default','VASP_Std_High']:
        molecule_ene += [get_vasp_energy(f'Data/X23/HF/{calc_type}/{prl_to_x23_order[x23_idx]:02d}/molecule/OUTCAR_HF.gz')]
        solid_ene += [get_vasp_energy(f'Data/X23/HF/{calc_type}/{prl_to_x23_order[x23_idx]:02d}/solid/OUTCAR_HF.gz')]
    
    elatt_energy = np.array(solid_ene)/num_monomer - np.array(molecule_ene)
    elatt = (elatt_energy[0] + elatt_energy[2] - elatt_energy[1])*1000
    x23_hf_elatt_dict[x23_idx] = elatt
    x23_hf_elatt_contribution_dict[x23_idx]['VASP_Hard_Default'] = (elatt_energy[0])*1000/kjmol
    x23_hf_elatt_contribution_dict[x23_idx]['VASP_Std_Default'] = (elatt_energy[1])*1000/kjmol
    x23_hf_elatt_contribution_dict[x23_idx]['VASP_Std_High'] = (elatt_energy[2])*1000/kjmol
    x23_hf_elatt_contribution_dict[x23_idx]['Delta'] = (elatt_energy[2] - elatt_energy[1])*1000/kjmol
    x23_hf_elatt_contribution_dict[x23_idx]['Final'] = elatt/kjmol

    molecule_d4 = np.loadtxt(f'Data/X23/HF/VASP_Hard_Default/{prl_to_x23_order[x23_idx]:02d}/molecule/D4_HF.out.gz')
    solid_d4 = np.loadtxt(f'Data/X23/HF/VASP_Hard_Default/{prl_to_x23_order[x23_idx]:02d}/solid/D4_HF.out.gz')
    x23_hf_d4_elatt_dict[x23_idx] = elatt + (solid_d4/num_monomer - molecule_d4)*Hartree*1000

# Convert x23_hf_elatt_contribution_dict to pandas dataframe
x23_hf_contribution_df = pd.DataFrame.from_dict(x23_hf_elatt_contribution_dict, orient='index')
x23_hf_contribution_df.index = [x23_labels[i] for i in x23_hf_contribution_df.index]
# Change the column names
x23_hf_contribution_df.columns = ['Hard (KSPACING=0.25)','Std (KSPACING=0.25)','Std (KSPACING=0.18)', r'$\Delta_k$', 'Final']
# Round to nearest integer
x23_hf_contribution_df = x23_hf_contribution_df.round(1)
display(x23_hf_contribution_df)
# Convert to latex table
convert_df_to_latex_input(
    df = x23_hf_contribution_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_hf_contributions",
    caption = r"Contributions that make up the final HF lattice energies for the X23 set. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]"
    },
    index = True,
    rotate_column_header=True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-X23_HF_Contributions.tex")

,Hard (KSPACING=0.25),Std (KSPACING=0.25),Std (KSPACING=0.18),$\Delta_k$,Final
"1,4-cyclohexanedione",-3.4,-5.7,-5.4,0.2,-3.2
Acetic Acid,-17.4,-20.1,-20.1,0.0,-17.4
Adamantane,41.5,41.5,41.4,-0.1,41.5
Ammonia,-9.1,-9.4,-9.4,-0.0,-9.1
Anthracene,54.9,55.0,55.0,-0.0,54.9
Benzene,23.0,23.0,23.0,-0.1,22.9
CO$_2$,-3.4,-4.3,-4.3,-0.0,-3.5
Cyanamide,-29.9,-30.7,-30.8,-0.1,-29.9
Cytosine,-48.0,-51.1,-51.1,0.0,-48.0
Ethyl carbamate,-17.4,-19.7,-19.8,-0.0,-17.4
Formamide,-30.3,-33.0,-33.1,-0.0,-30.4
Hexamine,18.0,18.2,18.2,-0.1,18.0
Imidazole,-14.3,-14.7,-14.7,-0.0,-14.3
Naphthalene,43.7,43.8,43.8,-0.0,43.7
Oxalic Acid $\alpha$,-35.3,-40.7,-40.8,-0.0,-35.3
Oxalic Acid $\beta$,-28.2,-33.4,-33.5,-0.0,-28.2
Pyrazine,14.5,14.1,14.0,-0.0,14.5
Pyrazole,-3.8,-4.2,-4.2,-0.0,-3.9
Succinic Acid,-22.6,-26.9,-27.1,-0.2,-22.7
Triazine,2.4,1.8,1.8,-0.0,2.4
Trioxane,6.2,4.2,4.2,0.0,6.2
Uracil,-38.5,-42.6,-42.7,-0.1,-38.6
Urea,-45.4,-49.4,-49.7,-0.3,-45.6

### GPU costs

In [6]:
x23_hf_gpu_cost_dict = {y: {'VASP_Hard_Default': 0,'VASP_Std_Default': 0,'VASP_Std_High':0} for y in list(range(1,24))}

for x23_idx in range(1,24):

    for calc_type in ['VASP_Hard_Default','VASP_Std_Default','VASP_Std_High']:
        x23_hf_gpu_cost_dict[x23_idx][calc_type] += get_vasp_walltime(f'Data/X23/HF/{calc_type}/{prl_to_x23_order[x23_idx]:02d}/molecule/OUTCAR_HF.gz')*4/3600
        x23_hf_gpu_cost_dict[x23_idx][calc_type] += get_vasp_walltime(f'Data/X23/HF/{calc_type}/{prl_to_x23_order[x23_idx]:02d}/solid/OUTCAR_HF.gz')*4/3600

# Convert to dataframe
x23_hf_gpu_cost_df = pd.DataFrame.from_dict(x23_hf_gpu_cost_dict,orient='index')
x23_hf_gpu_cost_df.index = [f"{x23_labels[idx]}" for idx in x23_hf_gpu_cost_df.index]
# Add a row for the average
x23_hf_gpu_cost_df.loc['Average'] = x23_hf_gpu_cost_df.mean()
# Rename columns
x23_hf_gpu_cost_df.columns = ['Hard (0.25)','Std (0.25)','Std (0.18)']
# Round to integer
x23_hf_gpu_cost_df = x23_hf_gpu_cost_df.round(1)

display(x23_hf_gpu_cost_df)
# Convert to latex
convert_df_to_latex_input(
    df = x23_hf_gpu_cost_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_hf_gpu_cost",
    caption = r"Estimated computational cost (in GPUh) for the composite VASP calculations used to compute the HF lattice energies of the X23 dataset on an NVIDIA A100 GPU. The three different settings correspond to different PAW potentials and plane-wave cutoffs (with $k$-point spacing given in parenthesis), as described in the text.",
    replace_input= {
        "[t]": "[c]"
    },
    index = True,
    rotate_column_header=True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-X23_Method_Costs_GPU.tex")

                      Hard (0.25)  Std (0.25)  Std (0.18)
1,4-cyclohexanedione          3.4         1.6        11.2
Acetic Acid                   2.9         1.4         8.5
Adamantane                    1.4         0.7         4.7
Ammonia                       0.2         0.2         0.9
Anthracene                    4.0         1.7         7.1
Benzene                       2.4         0.9         4.5
CO$_2$                        0.5         0.2         1.2
Cyanamide                     4.3         2.0        17.3
Cytosine                      4.2         1.7        10.4
Ethyl carbamate               2.6         1.4        15.0
Formamide                     2.3         1.2         6.8
Hexamine                      1.8         1.0         4.7
Imidazole                     2.2         1.1         7.8
Naphthalene                   3.9         1.9         6.0
Oxalic Acid $\alpha$          5.6         2.7        10.7
Oxalic Acid $\beta$           3.9         1.9         9.2
Pyrazine                      1.8         1.0         5.0
Pyrazole                      9.8         3.5        22.2
Succinic Acid                 2.5         1.2         7.9
Triazine                      8.3         2.6         7.4
Trioxane                     24.8         8.4        26.3
Uracil                       14.3         5.4         8.9
Urea                          0.7         0.3         1.6
Average                       4.7         1.9         8.9

## MBE cWFT analysis

In [7]:
# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results. This is given in the correct X23 order

x23_final_corr_elatt_dict = {y:{x:{} for x in ['MP2','CCSD','CCSD(T)','CCSD(cT)-fit']} for y in list(range(1,24))}
x23_final_corr_d4_elatt_dict = {y:{x:{} for x in ['MP2','CCSD','CCSD(T)','CCSD(cT)-fit']} for y in list(range(1,24))}
x23_final_cpuh_dict = {y: {'HF': 0, 'CCSD(T) corr.': 0} for y in list(range(1,24))}

method_basis = {
    '1B': { x: ' QZ' if x != 'MP2 Canonical' else ' CBS' for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical'] },
    '2B': { x: ' TZ' if x != 'MP2 Canonical' else ' CBS' for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical'] },
    '3B': { x: ' DZ' if x != 'MP2 Canonical' else ' CBS' for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical'] }
}

method_basis['1B']['D4'] = ''
method_basis['2B']['D4'] = ''
method_basis['3B']['D4'] = ''

for x23_idx in range(1,24):
    system_all_methods_elatt_dict = {x:{} for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'MP2 Canonical', 'MP2 Final', 'CCSD Final', 'CCSD(T) Final', 'CCSD(cT)-fit Final','D4']}
    system_total_time = 0
    for method in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'MP2 Canonical','D4']:
        method_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
        with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_1b.db') as db1:
            monomer_ene_list = []
            for i in range(2):
                row = db1.get(id=i+1)
                monomer_ene_list += [row.data[f'{method}{method_basis["1B"][method]}']]
                if method == 'MP2 Canonical':
                    system_total_time += row.data['time']
                # print(row.data[f'{method}'])
            method_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_2b.db') as db2:
            elatt_cwft = 0
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                elatt_cwft += row.data[f'{method}{method_basis["2B"][method]}']*(row.data['count'])
                if method == 'MP2 Canonical':
                    system_total_time += row.data['time']
            method_elatt_dict['2B'] = elatt_cwft

        with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_3b.db') as db3:
            elatt_cwft = 0
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                elatt_cwft += row.data[f'{method}{method_basis["3B"][method]}']*(row.data['count'])
                if method == 'MP2 Canonical':
                    system_total_time += row.data['time']
            method_elatt_dict['3B'] = elatt_cwft
        method_elatt_dict['Total'] = method_elatt_dict['1B'] + method_elatt_dict['2B'] + method_elatt_dict['3B']
        system_all_methods_elatt_dict[method] = method_elatt_dict.copy()
    
    for i in ['1B','2B','3B','Total']:
        system_all_methods_elatt_dict['MP2 Final'][i] = system_all_methods_elatt_dict['MP2 Canonical'][i]

        system_all_methods_elatt_dict['CCSD Final'][i] = system_all_methods_elatt_dict['CCSD LAF'][i] + system_all_methods_elatt_dict['MP2 Canonical'][i] - system_all_methods_elatt_dict['MP2 LAF'][i]

        system_all_methods_elatt_dict['CCSD(T) Final'][i] = system_all_methods_elatt_dict['CCSD(T) LAF'][i] + system_all_methods_elatt_dict['MP2 Canonical'][i] - system_all_methods_elatt_dict['MP2 LAF'][i]

        system_all_methods_elatt_dict['CCSD(cT)-fit Final'][i] = cT_calc(system_all_methods_elatt_dict['MP2 LAF'][i], system_all_methods_elatt_dict['CCSD LAF'][i], system_all_methods_elatt_dict['CCSD(T) LAF'][i]) + system_all_methods_elatt_dict['MP2 Canonical'][i] - system_all_methods_elatt_dict['MP2 LAF'][i]


    x23_final_corr_elatt_dict[x23_idx]['MP2'] = system_all_methods_elatt_dict['MP2 Final']
    x23_final_corr_elatt_dict[x23_idx]['CCSD'] = system_all_methods_elatt_dict['CCSD Final']
    x23_final_corr_elatt_dict[x23_idx]['CCSD(T)'] = system_all_methods_elatt_dict['CCSD(T) Final']
    x23_final_corr_elatt_dict[x23_idx]['CCSD(cT)-fit'] = system_all_methods_elatt_dict['CCSD(cT)-fit Final']
    for method in ['MP2','CCSD','CCSD(T)','CCSD(cT)-fit']:
        for x in ['1B','2B','3B','Total']:
            x23_final_corr_d4_elatt_dict[x23_idx][method][x] = x23_final_corr_elatt_dict[x23_idx][method][x] - system_all_methods_elatt_dict['D4'][x]

    x23_final_cpuh_dict[x23_idx]['CCSD(T) corr.'] = system_total_time*8/3600

### MP2, CCSD and CCSD(T) MBE contributions

In [8]:
# Plot the CCSD(T) MBE contributions for all X23 systems

x23_method_df = pd.DataFrame.from_dict({x23_labels[x23_idx]: {(method, mbe_type): x23_final_corr_elatt_dict[x23_idx][method][mbe_type] / kjmol  for method in ['MP2','CCSD','CCSD(T)'] for mbe_type in ['1B','2B','3B','Total']} for x23_idx in range(1,24)}, orient='index')

# Add row for mean signed difference compared to CCSD(T) and mean absolute difference
x23_method_df.loc['MSD'] = { (method, mbe_type): np.mean([x23_method_df.loc[x23_labels[x23_idx], (method, mbe_type)] - x23_method_df.loc[x23_labels[x23_idx], ('CCSD(T)', mbe_type)] for x23_idx in range(1,24)]) for method in ['MP2','CCSD','CCSD(T)'] for mbe_type in ['1B','2B','3B','Total']}
x23_method_df.loc['MAD'] = { (method, mbe_type): np.mean([np.abs(x23_method_df.loc[x23_labels[x23_idx], (method, mbe_type)] - x23_method_df.loc[x23_labels[x23_idx], ('CCSD(T)', mbe_type)]) for x23_idx in range(1,24)]) for method in ['MP2','CCSD','CCSD(T)'] for mbe_type in ['1B','2B','3B','Total']}


# Round to 1 d.p.
x23_method_df = x23_method_df.round(1)

display(x23_method_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = x23_method_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_mbe_contributions",
    caption = r"The MBE contributions to the lattice energy of the X23 set for several correlated wavefunction theory methods in the Composite `Full' basis approach. All values are in kJ/mol. We also report the mean signed deviation (MSD) and mean absolute deviation (MAD) of MP2 and CCSD compared to CCSD(T).",
    replace_input= {'DeltaMP2':r'Composite', "[t]": "[c]", r"{CCSD(T)} \\": r"{CCSD(T)} \\ \cmidrule(lr){2-5} \cmidrule(lr){6-9} \cmidrule(lr){10-13}"},
    float_fmt="%.1f",
    column_format="lrrrrrrrrrrrrrrrrrrrr",
    filename = "Tables/SI_Table-X23_MBE_Contributions.tex")

                       MP2                    CCSD                    CCSD(T)  \
                        1B     2B   3B  Total   1B     2B   3B  Total      1B
1,4-cyclohexanedione  -6.4  -86.7  0.7  -92.5 -4.5  -71.3  3.0  -72.8    -5.8
Acetic Acid           -4.8  -49.1  0.8  -53.1 -3.7  -42.1  2.2  -43.6    -4.5
Adamantane            -0.4 -115.3  1.2 -114.4 -0.6  -94.5  4.3  -90.9    -1.0
Ammonia               -0.9  -27.6  0.4  -28.1 -0.9  -24.2  1.3  -23.8    -1.1
Anthracene            -2.4 -212.0  1.8 -212.5 -1.8 -141.0  4.4 -138.4    -2.7
Benzene               -1.0  -92.7  2.1  -91.6 -0.9  -66.3  4.6  -62.6    -1.3
CO$_2$                 0.1  -26.8  1.0  -25.7  0.1  -22.4  2.0  -20.2     0.1
Cyanamide             -3.4  -59.6  2.2  -60.8 -2.1  -43.4  3.8  -41.7    -2.5
Cytosine             -10.7 -113.7 -0.1 -124.4 -8.3  -88.5  3.3  -93.5   -10.3
Ethyl carbamate       -2.9  -64.9  0.3  -67.4 -2.3  -56.1  2.1  -56.3    -3.0
Formamide             -7.9  -41.8  0.2  -49.5 -6.0  -37.0  2.0  -41.0    -7.5
Hexamine              -0.9 -111.7  1.0 -111.6 -0.5  -90.8  3.7  -87.6    -0.7
Imidazole             -5.0  -84.6  1.1  -88.4 -3.6  -61.5  3.4  -61.6    -4.5
Naphthalene           -1.4 -159.7  1.2 -159.9 -1.2 -109.0  2.8 -107.5    -1.8
Oxalic Acid $\alpha$   1.8  -71.1  4.1  -65.3  1.5  -58.4  4.6  -52.2     2.4
Oxalic Acid $\beta$   -3.5  -73.5  5.3  -71.7 -2.7  -59.8  4.9  -57.5    -2.7
Pyrazine              -2.4  -96.3  1.8  -96.8 -1.8  -67.7  5.4  -64.0    -2.6
Pyrazole              -4.0  -86.5  1.7  -88.8 -2.9  -62.9  3.8  -62.0    -3.7
Succinic Acid         -7.7 -100.8  3.2 -105.3 -6.3  -83.8  6.0  -84.1    -7.5
Triazine              -2.8  -71.0  2.2  -71.6 -2.0  -54.2  4.5  -51.8    -2.9
Trioxane              -4.7  -67.7  1.5  -70.9 -3.9  -58.4  3.2  -59.0    -5.1
Uracil               -12.3  -94.3 -0.5 -107.1 -8.8  -73.1  1.7  -80.1   -11.2
Urea                  -5.8  -53.7 -2.6  -62.1 -3.9  -47.3  0.6  -50.6    -4.5
MSD                   -0.2   -5.6 -2.6   -8.4  0.8   13.8 -0.6   14.0     0.0
MAD                    0.4    6.9  2.6    8.5  0.8   13.8  0.6   14.0     0.0


                         2B   3B  Total
1,4-cyclohexanedione  -86.4  3.6  -88.6
Acetic Acid           -50.5  2.6  -52.4
Adamantane           -113.1  4.7 -109.3
Ammonia               -28.7  1.4  -28.4
Anthracene           -171.7  5.3 -169.1
Benzene               -79.6  5.3  -75.7
CO$_2$                -26.9  2.3  -24.5
Cyanamide             -53.5  4.1  -51.9
Cytosine             -107.5  3.8 -114.1
Ethyl carbamate       -67.1  2.5  -67.6
Formamide             -44.8  2.6  -49.7
Hexamine             -108.9  4.0 -105.6
Imidazole             -74.1  3.9  -74.6
Naphthalene          -132.2  3.2 -130.8
Oxalic Acid $\alpha$  -71.6  5.1  -64.1
Oxalic Acid $\beta$   -74.3  6.5  -70.5
Pyrazine              -81.7  6.4  -77.9
Pyrazole              -75.6  4.3  -75.1
Succinic Acid        -101.8  7.2 -102.2
Triazine              -65.8  5.3  -63.4
Trioxane              -68.8  3.9  -70.1
Uracil                -90.1  2.7  -98.6
Urea                  -56.9  0.3  -61.2
MSD                     0.0  0.0    0.0
MAD                     0.0  0.0    0.0

### CCSD(cT) MBE contributions

In [9]:
# Plot the CCSD(cT) MBE contributions for all X23 systems

x23_method_df = pd.DataFrame.from_dict({x23_labels[x23_idx]: {(method, mbe_type): x23_final_corr_elatt_dict[x23_idx][method][mbe_type] / kjmol  for method in ['CCSD(T)','CCSD(cT)-fit'] for mbe_type in ['1B','2B','3B','Total']} for x23_idx in range(1,24)}, orient='index')

# Add row for mean signed difference compared to CCSD(T) and mean absolute difference
x23_method_df.loc['MSD'] = { (method, mbe_type): np.mean([x23_method_df.loc[x23_labels[x23_idx], (method, mbe_type)] - x23_method_df.loc[x23_labels[x23_idx], ('CCSD(T)', mbe_type)] for x23_idx in range(1,24)]) for method in ['CCSD(T)','CCSD(cT)-fit'] for mbe_type in ['1B','2B','3B','Total']}
x23_method_df.loc['MAD'] = { (method, mbe_type): np.mean([np.abs(x23_method_df.loc[x23_labels[x23_idx], (method, mbe_type)] - x23_method_df.loc[x23_labels[x23_idx], ('CCSD(T)', mbe_type)]) for x23_idx in range(1,24)]) for method in ['CCSD(T)','CCSD(cT)-fit'] for mbe_type in ['1B','2B','3B','Total']}


# Round to 1 d.p.
x23_method_df = x23_method_df.round(1)

display(x23_method_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = x23_method_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_cT_mbe_contributions",
    caption = r"The MBE contributions to the lattice energy of the X23 set between CCSD(T) and CCSD(cT)-fit in the Composite `Full' basis approach. All values are in kJ/mol. We also report the mean signed deviation (MSD) and mean absolute deviation (MAD) compared to CCSD(T).",
    replace_input= {'DeltaMP2':r'Composite', "[t]": "[c]", r"{CCSD(cT)-fit} \\": r"{CCSD(cT)-fit} \\ \cmidrule(lr){2-5} \cmidrule(lr){6-9} \cmidrule(lr){10-13} \cmidrule(lr){14-17}"},
    float_fmt="%.1f",
    column_format="lrrrrrrrrrrrrrrrr",
    filename = "Tables/SI_Table-X23_cT_Contributions.tex")

                     CCSD(T)                    CCSD(cT)-fit              \
                          1B     2B   3B  Total           1B     2B   3B
1,4-cyclohexanedione    -5.8  -86.4  3.6  -88.6         -5.6  -84.8  3.7
Acetic Acid             -4.5  -50.5  2.6  -52.4         -4.4  -49.7  2.7
Adamantane              -1.0 -113.1  4.7 -109.3         -1.0 -111.1  4.8
Ammonia                 -1.1  -28.7  1.4  -28.4         -1.1  -28.3  1.5
Anthracene              -2.7 -171.7  5.3 -169.1         -2.6 -166.6  5.4
Benzene                 -1.3  -79.6  5.3  -75.7         -1.3  -77.7  5.4
CO$_2$                   0.1  -26.9  2.3  -24.5          0.1  -26.4  2.4
Cyanamide               -2.5  -53.5  4.1  -51.9         -2.4  -52.0  4.1
Cytosine               -10.3 -107.5  3.8 -114.1        -10.1 -105.2  3.9
Ethyl carbamate         -3.0  -67.1  2.5  -67.6         -2.9  -66.1  2.6
Formamide               -7.5  -44.8  2.6  -49.7         -7.3  -44.1  2.7
Hexamine                -0.7 -108.9  4.0 -105.6         -0.6 -107.0  4.0
Imidazole               -4.5  -74.1  3.9  -74.6         -4.3  -72.3  4.0
Naphthalene             -1.8 -132.2  3.2 -130.8         -1.7 -128.5  3.3
Oxalic Acid $\alpha$     2.4  -71.6  5.1  -64.1          2.3  -70.1  5.1
Oxalic Acid $\beta$     -2.7  -74.3  6.5  -70.5         -2.7  -72.7  6.4
Pyrazine                -2.6  -81.7  6.4  -77.9         -2.5  -79.6  6.5
Pyrazole                -3.7  -75.6  4.3  -75.1         -3.6  -73.8  4.3
Succinic Acid           -7.5 -101.8  7.2 -102.2         -7.4  -99.9  7.3
Triazine                -2.9  -65.8  5.3  -63.4         -2.8  -64.4  5.4
Trioxane                -5.1  -68.8  3.9  -70.1         -5.0  -67.9  3.9
Uracil                 -11.2  -90.1  2.7  -98.6        -10.8  -88.0  2.9
Urea                    -4.5  -56.9  0.3  -61.2         -4.4  -56.1  0.5
MSD                      0.0    0.0  0.0    0.0          0.1    1.7  0.1
MAD                      0.0    0.0  0.0    0.0          0.1    1.7  0.1


                      Total
1,4-cyclohexanedione  -86.7
Acetic Acid           -51.5
Adamantane           -107.2
Ammonia               -27.9
Anthracene           -163.8
Benzene               -73.6
CO$_2$                -24.0
Cyanamide             -50.2
Cytosine             -111.3
Ethyl carbamate       -66.4
Formamide             -48.8
Hexamine             -103.5
Imidazole             -72.6
Naphthalene          -127.0
Oxalic Acid $\alpha$  -62.7
Oxalic Acid $\beta$   -69.0
Pyrazine              -75.6
Pyrazole              -73.0
Succinic Acid        -100.1
Triazine              -61.8
Trioxane              -69.0
Uracil                -96.1
Urea                  -60.0
MSD                     1.9
MAD                     1.9

### Subtractive embedding with D4 dispersion

In [10]:
x23_final_elatt_dict = {y:{x:{} for x in ['MP2','CCSD','CCSD(T)','CCSD(cT)-fit']} for y in list(range(1,24))}
x23_final_d4_elatt_dict = {y:{x:{} for x in ['MP2','CCSD','CCSD(T)','CCSD(cT)-fit']} for y in list(range(1,24))}

mad_list = []
rmsd_list = []

for method in ['MP2','CCSD','CCSD(T)','CCSD(cT)-fit']:
    for x23_idx in range(1,24):
        x23_final_elatt_dict[x23_idx][method] = (x23_hf_elatt_dict[x23_idx] + x23_final_corr_elatt_dict[x23_idx][method]['Total'])/kjmol
        x23_final_d4_elatt_dict[x23_idx][method] = (x23_hf_d4_elatt_dict[x23_idx] + x23_final_corr_d4_elatt_dict[x23_idx][method]['Total'])/kjmol
        if method == 'CCSD(T)':
            mad_list += [abs(x23_final_elatt_dict[x23_idx][method] - x23_final_d4_elatt_dict[x23_idx][method])]
            rmsd_list += [(x23_final_elatt_dict[x23_idx][method] - x23_final_d4_elatt_dict[x23_idx][method])**2]

mad = np.mean(mad_list)


# Create a DataFrame to compare the CCSD(T) estimates with and without D4 correction
x23_d4_compare_dict = {x23_labels[x23_idx]: {'Without D4': x23_final_elatt_dict[x23_idx]['CCSD(T)'], 'With D4': x23_final_d4_elatt_dict[x23_idx]['CCSD(T)'], 'Difference': x23_final_elatt_dict[x23_idx]['CCSD(T)'] - x23_final_d4_elatt_dict[x23_idx]['CCSD(T)']}  for x23_idx in range(1,24)}
x23_d4_compare_dict['Mean'] = {'Without D4': '-', 'With D4': '-', 'Difference': mad}

x23_d4_compare_df = pd.DataFrame.from_dict(x23_d4_compare_dict, orient='index')
# Round to 1 decimal place using applymap
x23_d4_compare_df = x23_d4_compare_df.map(
    lambda x: round(x, 1) if isinstance(x, (int, float)) else x
)
# Convert to latex
convert_df_to_latex_input(
    df = x23_d4_compare_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_d4_compare",
    caption = r"Lattice energy (in kJ/mol) for the X23 dataset when LNO-MBE-CCSD(T) is corrected with (and without) the D4 dispersion correction.",
    replace_input= {
        "[t]": "[c]"
    },
    index = True,
    filename = "Tables/SI_Table-X23_D4_Compare.tex",
    float_fmt = r"%.1f",)

display(x23_d4_compare_df)

                     Without D4 With D4  Difference
1,4-cyclohexanedione      -91.8   -92.2         0.4
Acetic Acid               -69.8   -70.3         0.5
Adamantane                -67.9   -67.5        -0.3
Ammonia                   -37.5   -38.6         1.1
Anthracene               -114.2  -113.9        -0.3
Benzene                   -52.8   -52.8         0.0
CO$_2$                    -27.9   -27.9        -0.0
Cyanamide                 -81.9   -82.4         0.5
Cytosine                 -162.1  -161.9        -0.2
Ethyl carbamate           -85.0   -85.0         0.1
Formamide                 -80.1   -80.8         0.7
Hexamine                  -87.6   -88.1         0.5
Imidazole                 -88.9   -88.8        -0.1
Naphthalene               -87.1   -83.8        -3.3
Oxalic Acid $\alpha$      -99.4   -99.3        -0.1
Oxalic Acid $\beta$       -98.7   -98.8         0.1
Pyrazine                  -63.4   -63.5         0.0
Pyrazole                  -78.9   -78.5        -0.4
Succinic Acid            -124.9  -125.0         0.1
Triazine                  -61.1   -61.5         0.4
Trioxane                  -63.9   -64.1         0.2
Uracil                   -137.2  -137.2        -0.0
Urea                     -106.8  -107.0         0.2
Mean                          -       -         0.4

## Comparisons to experimental and theoretical literature

In [11]:
# Make a table which compares CCSD(T), CCSD(cT), DMC and experimental values
x23_final_compare_dict = {x23_labels[x23_idx]: {'CCSD(T)': x23_final_elatt_dict[x23_idx]['CCSD(T)'], 'CCSD(cT)-fit': x23_final_elatt_dict[x23_idx]['CCSD(cT)-fit'], 'DMC': x23_dmc_elatt_dict[x23_idx][0], 'DMC Error': x23_dmc_elatt_dict[x23_idx][1], 'Expt': x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Lattice energy'], 'Expt Error': x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Error']}  for x23_idx in range(1,24)}

# Save the dictionary as npy file
np.save('Data/X23/X23_Final_Data.npy', x23_final_compare_dict)

x23_final_compare_df = pd.DataFrame.from_dict(x23_final_compare_dict, orient='index')

refs = {
    "MAD [CCSD(T)]": "CCSD(T)",
    "MAD (Expt)": "Expt",
    "MAD (DMC)": "DMC"
}

for label, ref_col in refs.items():
    row = {}
    for col in ["CCSD(T)", "CCSD(cT)-fit", "DMC", "Expt"]:
        if col == ref_col:
            row[col] = 0.0
        else:
            row[col] = np.mean([
                abs(
                    float(x23_final_compare_df.loc[x23_labels[idx], col]) -
                    float(x23_final_compare_df.loc[x23_labels[idx], ref_col])
                )
                for idx in range(1, 24)
            ])
    # constant values
    row["DMC Error"] = "-"
    row["Expt Error"] = "-"
    
    # assign row
    x23_final_compare_df.loc[label] = row

# Add row for MSD w.r.t. DMC
x23_final_compare_df.loc['MSD (DMC)'] = {
    'CCSD(T)': np.mean([x23_final_compare_df.loc[x23_labels[x23_idx], 'CCSD(T)'] - x23_final_compare_df.loc[x23_labels[x23_idx], 'DMC'] for x23_idx in range(1,24)]),
    'CCSD(cT)-fit': np.mean([x23_final_compare_df.loc[x23_labels[x23_idx], 'CCSD(cT)-fit'] - x23_final_compare_df.loc[x23_labels[x23_idx], 'DMC'] for x23_idx in range(1,24)]),
    'DMC': 0.0,
    'DMC Error': '-',
    'Expt': np.mean([float(x23_final_compare_df.loc[x23_labels[x23_idx], 'Expt']) - x23_final_compare_df.loc[x23_labels[x23_idx], 'DMC'] for x23_idx in range(1,24)]),
    'Expt Error': '-'
}


# Print the number of systems which are within 2 kJ/mol between DMC and CCSD(T), including the DMC error bars
print("Number of systems within 2 kJ/mol between DMC and CCSD(T):", sum([
    abs(x23_final_compare_df.loc[x23_labels[x23_idx], 'CCSD(T)'] - x23_final_compare_df.loc[x23_labels[x23_idx], 'DMC']) <= x23_final_compare_df.loc[x23_labels[x23_idx], 'DMC Error'] + 2
    for x23_idx in range(1, 24)
]))



# Round to 1 decimal place
x23_final_compare_df = x23_final_compare_df.map(
    lambda x: round(x, 1) if isinstance(x, (int, float)) else x
)
display(x23_final_compare_df)

# Convert to latex
convert_df_to_latex_input(
    df = x23_final_compare_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_final_compare",
    caption = r"Final lattice energy (in kJ/mol) for the X23 dataset computed with different methods, compared to experimental values. The DMC values are taken from Ref.~\citenum{dellapiaHowAccurateAre2024}. The mean absolute deviation (MAD) is also reported with respect to (LNO-MBE-)CCSD(T), experiment and DMC.",
    replace_input= {},
    index = True,
    float_fmt = r"%.1f",
    filename = "Tables/SI_Table-X23_Final_Compare.tex",
    column_format="lrrrrrr"
)

Number of systems within 2 kJ/mol between DMC and CCSD(T): 15

,CCSD(T),CCSD(cT)-fit,DMC,DMC Error,Expt,Expt Error
"1,4-cyclohexanedione",-91.8,-89.9,-88.3,1.0,-87.5,6.6
Acetic Acid,-69.8,-68.9,-71.7,0.6,-72.4,5.4
Adamantane,-67.9,-65.8,-61.0,2.3,-64.9,4.7
Ammonia,-37.5,-37.0,-38.2,0.1,-36.8,2.0
Anthracene,-114.2,-108.9,-100.2,0.5,-104.2,7.5
Benzene,-52.8,-50.7,-49.8,0.2,-52.8,5.4
CO$_2$,-27.9,-27.4,-29.4,0.2,-29.1,1.0
Cyanamide,-81.9,-80.2,-83.6,0.4,-79.6,6.1
Cytosine,-162.1,-159.3,-156.2,1.0,-167.2,18.5
Ethyl carbamate,-85.0,-83.8,-84.2,1.3,-84.9,6.4
Formamide,-80.1,-79.2,-81.0,1.0,-78.6,5.8
Hexamine,-87.6,-85.5,-86.2,0.6,-83.7,4.4
Imidazole,-88.9,-86.9,-88.2,0.8,-85.8,7.7
Naphthalene,-87.1,-83.3,-75.5,0.5,-77.3,8.3
Oxalic Acid $\alpha$,-99.4,-98.0,-102.6,1.4,-96.4,7.8
Oxalic Acid $\beta$,-98.7,-97.2,-102.3,0.6,-94.6,7.8
Pyrazine,-63.4,-61.1,-61.1,1.1,-63.2,4.4
Pyrazole,-78.9,-76.9,-77.3,0.5,-76.3,5.8
Succinic Acid,-124.9,-122.8,-125.2,0.5,-116.8,6.0
Triazine,-61.1,-59.4,-60.5,0.6,-62.2,4.3
Trioxane,-63.9,-62.8,-62.1,1.9,-64.1,4.3
Uracil,-137.2,-134.7,-134.3,0.7,-133.3,9.5
Urea,-106.8,-105.6,-108.5,0.3,-99.2,7.0
MAD [CCSD(T)],0.0,1.9,3.1,-,3.4,-
MAD (Expt),3.4,2.6,3.4,-,0.0,-
MAD (DMC),3.1,2.5,0.0,-,3.4,-
MSD (DMC),-1.8,0.1,0.0,-,0.7,-

In [12]:
# Plot comparing CCSD(T) and DMC lattice energies
fig, ax = plt.subplots(figsize=(6.65,6), dpi = 450, constrained_layout=True)
ax.scatter([x23_final_elatt_dict[x23_idx]['CCSD(T)'] for x23_idx in range(1,24)], [x23_dmc_elatt_dict[x23_idx][0] for x23_idx in range(1,24)], color=color_dict['black'])
for x23_idx in range(1,24):
    if x23_idx in [13]:
        ax.text(x23_final_elatt_dict[x23_idx]['CCSD(T)'] + -5, x23_dmc_elatt_dict[x23_idx][0] -3.0, x23_labels[x23_idx], fontsize=8, ha='right', va='bottom')
    elif x23_idx in [17]:
        ax.text(x23_final_elatt_dict[x23_idx]['CCSD(T)'] + - 6, x23_dmc_elatt_dict[x23_idx][0] - 3.0, x23_labels[x23_idx], fontsize=8, ha='right', va='bottom')
    elif x23_idx in [15]:
        ax.text(x23_final_elatt_dict[x23_idx]['CCSD(T)'] + 4, x23_dmc_elatt_dict[x23_idx][0] - 2.5, x23_labels[x23_idx], fontsize=8, ha='left', va='bottom')
    elif x23_idx in [21]:
        ax.text(x23_final_elatt_dict[x23_idx]['CCSD(T)'] + 4, x23_dmc_elatt_dict[x23_idx][0] - 3.0, x23_labels[x23_idx], fontsize=8, ha='left', va='bottom')
    elif x23_idx in [1,16,3,18,8]:
        ax.text(x23_final_elatt_dict[x23_idx]['CCSD(T)'] + 4, x23_dmc_elatt_dict[x23_idx][0] - 1.0, x23_labels[x23_idx], fontsize=8, ha='left', va='bottom')
    else:
        ax.text(x23_final_elatt_dict[x23_idx]['CCSD(T)'] - 4, x23_dmc_elatt_dict[x23_idx][0] - 1.0, x23_labels[x23_idx], fontsize=8, ha='right', va='bottom')

# Fit a line and give the R^2 value
m, b = np.polyfit([x23_final_elatt_dict[x23_idx]['CCSD(T)'] for x23_idx in range(1,24)], [x23_dmc_elatt_dict[x23_idx][0] for x23_idx in range(1,24)], 1)
correlation_matrix = np.corrcoef([x23_final_elatt_dict[x23_idx]['CCSD(T)'] for x23_idx in range(1,24)], [x23_dmc_elatt_dict[x23_idx][0] for x23_idx in range(1,24)])
correlation_xy = correlation_matrix[0,1]
r_squared = correlation_xy**2
ax.plot([x23_final_elatt_dict[x23_idx]['CCSD(T)'] for x23_idx in range(1,24)], [m*x23_final_elatt_dict[x23_idx]['CCSD(T)'] + b for x23_idx in range(1,24)], color=color_dict['red'], label = f'Best fit ($R^2={r_squared:.2f}$)')
ax.plot([-200,0],[-200,0], color=color_dict['blue'], linestyle='--', label='y=x', lw=2)
ax.set_xlabel('LNO-MBE-CCSD(T) lattice energy (kJ/mol)')
ax.set_ylabel('DMC lattice energy (kJ/mol)')
ax.set_title('CCSD(T) vs. DMC lattice energies')
ax.legend(fontsize=8)
ax.set_ylim([-200,0])
ax.set_xlim([-200,0])
plt.savefig('Figures/SI_Figure-X23_CCSDT_vs_DMC_Lattice_Energies.png')

In [13]:
multilevel_syty_references = {
    '1,4-cyclohexanedione': -94.4,
    'Acetic Acid': -71.2,
    'Adamantane': -66.0,
    'Ammonia': -37.6,
    'Anthracene': -111.4,
    'Benzene': -51.6,
    'CO$_2$': -29.4,
    'Cyanamide': -82.6,
    'Cytosine': -163.1,
    'Ethyl carbamate': -86.5,
    'Formamide': -84.0,
    'Hexamine': -88.0,
    'Imidazole': -88.4,
    'Naphthalene': -82.5,
    'Oxalic Acid $\\alpha$': -103.0,
    'Oxalic Acid $\\beta$': -101.6,
    'Pyrazine': -64.3,
    'Pyrazole': -79.3,
    'Succinic Acid': -128.2,
    'Triazine': -60.3,
    'Trioxane': -67.8,
    'Uracil': -139.7,
    'Urea': -111.0,
}
rpa_gwse_references = {
    'Adamantane': -69.4,
    'Anthracene': -112.7,
    'Naphthalene': -81.7,
    'Benzene': -55.3,
    'CO$_2$': -28.4,
    'Urea': -102.5,
    'Ammonia': -37.2,
    'Cyanamide': -79.7,
    'Oxalic Acid $\\alpha$': -96.3,
    'Oxalic Acid $\\beta$': -96.1,
}

hmbi_references = {
    'Formamide': -80.4,
    'Imidazole': -90.8,
    'Benzene': -54.0,
    'Ammonia': -40.2,
    'CO$_2$': -29.5,
}

multilevel_sherrill_references = {
    'Benzene': {
        '2B': -57.99,
        '3B': 3.63,
    },
    'CO$_2$': {
        '2B': -30.11,
        '3B': 1.43,
    },
    'Triazine': {
        '2B': -58.36,
        '3B': 4.75,
    },
}

cervinka_ccsdt_mbe_3b = {
    'Ammonia': -39.1,
    'CO$_2$': -21.2,
    'Formamide': -89.9,
    'Acetic Acid': -70.6,
}

x23_1b_cc_energies = {}

for x23_idx in range(1,24):
    with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_1b.db') as db1:
        monomer_ene_list = []
        for i in range(2):
            row = db1.get(id=i+1)
            monomer_ene_list += [row.data[f'HF CBS'] + row.data[f'MP2 Canonical CBS'] + row.data[f'CCSD(T) LAF QZ'] - row.data[f'MP2 LAF QZ']]
            # print(row.data[f'{method}'])
        x23_1b_cc_energies[x23_labels[x23_idx]] = (np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]) / kjmol

# Add 1B and total to multilevel_sherrill_references
for system in multilevel_sherrill_references.keys():
    multilevel_sherrill_references[system]['1B'] = x23_1b_cc_energies[system]
    multilevel_sherrill_references[system]['Total'] = multilevel_sherrill_references[system]['1B'] + multilevel_sherrill_references[system]['2B'] + multilevel_sherrill_references[system]['3B']

# Make a DataFrame of all of the reference data
x23_reference_df = pd.DataFrame.from_dict({
    r'\shortstack{Multilevel\\Syty \etal{}~\cite{sytyMultiLevelCoupledClusterDescription2025}}': multilevel_syty_references,
    r'\shortstack{RPA+GWSE\\(Klime\v{s}~\cite{klimesLatticeEnergiesMolecular2016})}': rpa_gwse_references,
    r'\shortstack{HMBI CCSD(T)\\1B+2B+FF($>$2B)\\(Wen and Beran~\cite{wenAccurateMolecularCrystal2011a})}': hmbi_references,
    r'\shortstack{CCSD(T)\\1B+2B+3B MBE\\(Sherrill \etal{}~\cite{sargentBenchmarkingTwobodyContributions2023a,xieAssessmentThreebodyDispersion2023a})}': {system: multilevel_sherrill_references[system]['Total'] for system in multilevel_sherrill_references.keys()},
    r'\shortstack{CCSD(T)\\1B+2B+3B+ELST($>$3B) MBE\\(\v{C}ervinka~\cite{cervinkaCCSDTCBSFragmentbased2016})}': cervinka_ccsdt_mbe_3b
}, orient='index').T


x23_reference_df = x23_reference_df.fillna('-')

# Add MAD against CCSD(T), DMC and Experiment from x23_final_compare_df
for label, ref_col in refs.items():
    row = {}
    for col in x23_reference_df.columns:
        if col == ref_col:
            row[col] = 0.0
        else:
            row[col] = np.mean([
                abs(
                    float(x23_reference_df.loc[x23_labels[idx], col]) -
                    float(x23_final_compare_df.loc[x23_labels[idx], ref_col])
                )
                for idx in range(1, 24)
                if x23_reference_df.loc[x23_labels[idx], col] != '-' and x23_final_compare_df.loc[x23_labels[idx], ref_col] != '-'
            ])
    # assign row
    x23_reference_df.loc[label] = row

# Round to 1 decimal place
x23_reference_df = x23_reference_df.map(
    lambda x: round(x, 1) if isinstance(x, (int, float)) else x
)

display(x23_reference_df)

# Convert to latex
convert_df_to_latex_input(
    df = x23_reference_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_references_compare",
    caption = r"Comparison of reference literature lattice energies (in kJ/mol) for X23. The mean absolute deviation (MAD) is reported with respect to LNO-MBE-CCSD(T), experiment and DMC~\cite{dellapiaHowAccurateAre2024}.",
    replace_input= {},
    index = True,
    float_fmt = r"%.1f",
    rotate_column_header=True,
    filename = "Tables/SI_Table-X23_References_Compare.tex",
    column_format=r"lrrrrr"
)

,\shortstack{Multilevel\\Syty \etal{}~\cite{sytyMultiLevelCoupledClusterDescription2025}},\shortstack{CCSD(T)\\1B+2B+3B+ELST($>$3B) MBE\\(\v{C}ervinka~\cite{cervinkaCCSDTCBSFragmentbased2016})},\shortstack{RPA+GWSE\\(Klime\v{s}~\cite{klimesLatticeEnergiesMolecular2016})},\shortstack{HMBI CCSD(T)\\1B+2B+FF($>$2B)\\(Wen and Beran~\cite{wenAccurateMolecularCrystal2011a})},"\shortstack{CCSD(T)\\1B+2B+3B MBE\\(Sherrill \etal{}~\cite{sargentBenchmarkingTwobodyContributions2023a,xieAssessmentThreebodyDispersion2023a})}"
"1,4-cyclohexanedione",-94.4,-,-,-,-
Acetic Acid,-71.2,-70.6,-,-,-
Adamantane,-66.0,-,-69.4,-,-
Ammonia,-37.6,-39.1,-37.2,-40.2,-
Anthracene,-111.4,-,-112.7,-,-
Benzene,-51.6,-,-55.3,-54.0,-53.8
CO$_2$,-29.4,-21.2,-28.4,-29.5,-28.7
Cyanamide,-82.6,-,-79.7,-,-
Cytosine,-163.1,-,-,-,-
Ethyl carbamate,-86.5,-,-,-,-
Formamide,-84.0,-89.9,-,-80.4,-
Hexamine,-88.0,-,-,-,-
Imidazole,-88.4,-,-,-90.8,-
Naphthalene,-82.5,-,-81.7,-,-
Oxalic Acid $\alpha$,-103.0,-,-96.3,-,-
Oxalic Acid $\beta$,-101.6,-,-96.1,-,-
Pyrazine,-64.3,-,-,-,-
Pyrazole,-79.3,-,-,-,-
Succinic Acid,-128.2,-,-,-,-
Triazine,-60.3,-,-,-,-52.2
Trioxane,-67.8,-,-,-,-
Uracil,-139.7,-,-,-,-
Urea,-111.0,-,-102.5,-,-
MAD [CCSD(T)],2.0,4.7,2.4,1.5,3.6
MAD (Expt),4.3,5.8,2.6,2.4,3.8
MAD (DMC),3.1,4.8,5.7,1.9,4.3

### H-bonded subset

In [14]:
# Get MAD for H-bonded subsets
h_bonded_x23_labels = ["Acetic Acid",
 "Ammonia",
 "Cyanamide",
 "Ethyl carbamate",
 "Formamide",
 "Urea",
 "Succinic Acid",
 r"Oxalic Acid $\alpha$",
 r"Oxalic Acid $\beta$"]

x23_h_bonded_dict = {x23_labels[x23_idx]: x23_final_compare_df.loc[x23_labels[x23_idx]] for x23_idx in range(1,24) if x23_labels[x23_idx] in h_bonded_x23_labels}

# Add rows for MAD
for label, ref_col in refs.items():
    row = {}
    for col in ["CCSD(T)", "CCSD(cT)-fit", "DMC", "Expt"]:
        if col == ref_col:
            row[col] = 0.0
        else:
            row[col] = np.mean([
                abs(
                    float(x23_h_bonded_dict[x23_labels[idx]][col]) -
                    float(x23_h_bonded_dict[x23_labels[idx]][ref_col])
                )
                for idx in range(1, 24) if x23_labels[idx] in h_bonded_x23_labels
            ])
    # constant values
    row["DMC Error"] = "-"
    row["Expt Error"] = "-"
    
    # assign row
    x23_h_bonded_dict[label] = row

# Add row for MSD w.r.t. DMC
x23_h_bonded_dict['MSD (DMC)'] = {
    'CCSD(T)': np.mean([x23_h_bonded_dict[x23_labels[x23_idx]]['CCSD(T)'] - x23_h_bonded_dict[x23_labels[x23_idx]]['DMC'] for x23_idx in range(1,24) if x23_labels[x23_idx] in h_bonded_x23_labels]),
    'CCSD(cT)-fit': np.mean([x23_h_bonded_dict[x23_labels[x23_idx]]['CCSD(cT)-fit'] - x23_h_bonded_dict[x23_labels[x23_idx]]['DMC'] for x23_idx in range(1,24) if x23_labels[x23_idx] in h_bonded_x23_labels]),
    'DMC': 0.0,
    'DMC Error': '-',
    'Expt': np.mean([float(x23_h_bonded_dict[x23_labels[x23_idx]]['Expt']) - x23_h_bonded_dict[x23_labels[x23_idx]]['DMC'] for x23_idx in range(1,24) if x23_labels[x23_idx] in h_bonded_x23_labels]),
    'Expt Error': '-'
}

x23_h_bonded_df = pd.DataFrame.from_dict(x23_h_bonded_dict, orient='index')

# Round to 1 decimal place
x23_h_bonded_df = x23_h_bonded_df.map(
    lambda x: round(x, 1) if isinstance(x, (int, float)) else x
)

display(x23_h_bonded_df)

# Convert to latex
convert_df_to_latex_input(
    df = x23_h_bonded_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_h_bonded_compare",
    caption = r"Lattice energy (in kJ/mol) for the H-bonded subset of the X23 dataset computed with different methods, compared to experimental values. The DMC values are taken from Ref.~\citenum{dellapiaHowAccurateAre2024}. The mean absolute deviation (MAD) is also reported with respect to (LNO-MBE-)CCSD(T), experiment and DMC.",
    replace_input= {},
    index = True,
    float_fmt = r"%.1f",
    filename = "Tables/SI_Table-X23_H_Bonded_Compare.tex",
    column_format="lrrrrrr"
)

,CCSD(T),CCSD(cT)-fit,DMC,DMC Error,Expt,Expt Error
Acetic Acid,-69.8,-68.9,-71.7,0.6,-72.4,5.4
Ammonia,-37.5,-37.0,-38.2,0.1,-36.8,2.0
Cyanamide,-81.9,-80.2,-83.6,0.4,-79.6,6.1
Ethyl carbamate,-85.0,-83.8,-84.2,1.3,-84.9,6.4
Formamide,-80.1,-79.2,-81.0,1.0,-78.6,5.8
Oxalic Acid $\alpha$,-99.4,-98.0,-102.6,1.4,-96.4,7.8
Oxalic Acid $\beta$,-98.7,-97.2,-102.3,0.6,-94.6,7.8
Succinic Acid,-124.9,-122.8,-125.2,0.5,-116.8,6.0
Urea,-106.8,-105.6,-108.5,0.3,-99.2,7.0
MAD [CCSD(T)],0.0,1.3,1.6,-,3.3,-
MAD (Expt),3.3,2.5,4.5,-,0.0,-
MAD (DMC),1.6,2.7,0.0,-,4.5,-
MSD (DMC),1.5,2.7,0.0,-,4.2,-

### vdW-bonded subset

In [15]:
vdw_bonded_x23_labels = ["1,4-cyclohexanedione",
 "Adamantane",
 "Anthracene",
 "Benzene",
 "Hexamine",
 "Naphthalene",
 "Pyrazine",
 "Pyrazole",
 "Triazine",
 "Trioxane",
 "CO$_2$"]

x23_vdw_bonded_dict = {x23_labels[x23_idx]: x23_final_compare_df.loc[x23_labels[x23_idx]] for x23_idx in range(1,24) if x23_labels[x23_idx] in vdw_bonded_x23_labels}

# Add rows for MAD
for label, ref_col in refs.items():
    row = {}
    for col in ["CCSD(T)", "CCSD(cT)-fit", "DMC", "Expt"]:
        if col == ref_col:
            row[col] = 0.0
        else:
            row[col] = np.mean([
                abs(
                    float(x23_vdw_bonded_dict[x23_labels[idx]][col]) -
                    float(x23_vdw_bonded_dict[x23_labels[idx]][ref_col])
                )
                for idx in range(1, 24) if x23_labels[idx] in vdw_bonded_x23_labels
            ])
    # constant values
    row["DMC Error"] = "-"
    row["Expt Error"] = "-"
    
    # assign row
    x23_vdw_bonded_dict[label] = row
# Add row for MSD w.r.t. DMC
x23_vdw_bonded_dict['MSD (DMC)'] = {
    'CCSD(T)': np.mean([x23_vdw_bonded_dict[x23_labels[x23_idx]]['CCSD(T)'] - x23_vdw_bonded_dict[x23_labels[x23_idx]]['DMC'] for x23_idx in range(1,24) if x23_labels[x23_idx] in vdw_bonded_x23_labels]),
    'CCSD(cT)-fit': np.mean([x23_vdw_bonded_dict[x23_labels[x23_idx]]['CCSD(cT)-fit'] - x23_vdw_bonded_dict[x23_labels[x23_idx]]['DMC'] for x23_idx in range(1,24) if x23_labels[x23_idx] in vdw_bonded_x23_labels]),
    'DMC': 0.0,
    'DMC Error': '-',
    'Expt': np.mean([float(x23_vdw_bonded_dict[x23_labels[x23_idx]]['Expt']) - x23_vdw_bonded_dict[x23_labels[x23_idx]]['DMC'] for x23_idx in range(1,24) if x23_labels[x23_idx] in vdw_bonded_x23_labels]),
    'Expt Error': '-'
}
x23_vdw_bonded_df = pd.DataFrame.from_dict(x23_vdw_bonded_dict, orient='index')
# Round to 1 decimal place
x23_vdw_bonded_df = x23_vdw_bonded_df.map(
    lambda x: round(x, 1) if isinstance(x, (int, float)) else x
)
display(x23_vdw_bonded_df)

# Convert to latex
convert_df_to_latex_input(
    df = x23_vdw_bonded_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_vdw_bonded_compare",
    caption = r"Lattice energy (in kJ/mol) for the vdW-bonded subset of the X23 dataset computed with different methods, compared to experimental values. The DMC values are taken from Ref.~\citenum{dellapiaHowAccurateAre2024}. The mean absolute deviation (MAD) is also reported with respect to (LNO-MBE-)CCSD(T), experiment and DMC.",
    replace_input= {},
    index = True,
    float_fmt = r"%.1f",
    filename = "Tables/SI_Table-X23_vdW_Bonded_Compare.tex",
    column_format="lrrrrrr"
)

,CCSD(T),CCSD(cT)-fit,DMC,DMC Error,Expt,Expt Error
"1,4-cyclohexanedione",-91.8,-89.9,-88.3,1.0,-87.5,6.6
Adamantane,-67.9,-65.8,-61.0,2.3,-64.9,4.7
Anthracene,-114.2,-108.9,-100.2,0.5,-104.2,7.5
Benzene,-52.8,-50.7,-49.8,0.2,-52.8,5.4
CO$_2$,-27.9,-27.4,-29.4,0.2,-29.1,1.0
Hexamine,-87.6,-85.5,-86.2,0.6,-83.7,4.4
Naphthalene,-87.1,-83.3,-75.5,0.5,-77.3,8.3
Pyrazine,-63.4,-61.1,-61.1,1.1,-63.2,4.4
Pyrazole,-78.9,-76.9,-77.3,0.5,-76.3,5.8
Triazine,-61.1,-59.4,-60.5,0.6,-62.2,4.3
Trioxane,-63.9,-62.8,-62.1,1.9,-64.1,4.3
MAD [CCSD(T)],0.0,2.3,4.4,-,3.3,-
MAD (Expt),3.3,2.4,2.1,-,0.0,-
MAD (DMC),4.4,2.6,0.0,-,2.1,-
MSD (DMC),-4.1,-1.8,0.0,-,-1.3,-

### Figure 2

In [16]:
# Indices for each group
h_bonded_indices = [x23_idx for x23_idx in range(1, 24)
                    if x23_labels[x23_idx] in h_bonded_x23_labels]
vdw_bonded_indices = [x23_idx for x23_idx in range(1, 24)
                      if x23_labels[x23_idx] in vdw_bonded_x23_labels]
mixed_bonded_indices = [x23_idx for x23_idx in range(1, 24)
                        if x23_labels[x23_idx] not in h_bonded_x23_labels + vdw_bonded_x23_labels]
mixed_bonded_indices = [9, 22, 13]


# Number of rows in each panel
n_vdw   = len(vdw_bonded_indices)
n_mixed = len(mixed_bonded_indices)
n_hbond = len(h_bonded_indices)

# Figure and axes – height_ratios proportional to number of rows
fig, axs = plt.subplots(
    3, 1,
    figsize=(4.46, 8),
    constrained_layout=True,
    dpi=600,
    sharex=True,
    height_ratios=[n_vdw, n_mixed, n_hbond]
)

count = 0
system_dist = 1.5  # vertical spacing between systems (data units)

# --- Helper: set y-limits so that each row spans the same data range ---
def set_panel_ylim(ax, x_data, dist):
    """
    x_data: list of y-positions (0, dist, 2*dist, ...)
    dist: vertical spacing between rows in data units
    """
    ymin = x_data[0] - dist / 2
    ymax = x_data[-1] + dist / 2
    ax.set_ylim(ymax, ymin)  # inverted so top item appears at top


# ======================
# Panel 0: vdw-bonded
# ======================
x_data = []
counter = 0
left_y = []
left_label = []
right_y = []
right_label = []
for x23_idx in vdw_bonded_indices:
    y0 = counter * system_dist
    x_data.append(y0)

    system_exp_elatt_list = [
        float(x) - float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Etemp'])
        for x in x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Enthalpy measurements'].split(',')
    ]

    for elatt in system_exp_elatt_list:
        axs[0].plot(elatt, y0 - 0.3,
                    marker='o', markersize=3,
                    c='black', markeredgecolor='none', alpha=0.5)

    mean_exp = np.mean(system_exp_elatt_list)
    error = float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Error'])
    elatt_max = mean_exp + error
    elatt_min = mean_exp - error

    if count == 0:
        axs[0].barh(y0 - 0.3, elatt_max - elatt_min, 0.4, elatt_min,
                    color='grey', alpha=0.7, label='Exp. range')
        count += 1
    else:
        axs[0].barh(y0 - 0.3, elatt_max - elatt_min, 0.4, elatt_min,
                    color='grey', alpha=0.7)

    if counter % 2 == 0:
        left_y.append(y0)
        left_label.append(f'{x23_labels[x23_idx]}')
    else:
        right_y.append(y0)
        right_label.append(f'{x23_labels[x23_idx]}')    

    counter += 1

# DMC
axs[0].errorbar(
    [x23_dmc_elatt_dict[x23_idx][0] for x23_idx in vdw_bonded_indices],
    np.array(x_data) + 0.3,
    xerr=[x23_dmc_elatt_dict[x23_idx][1] for x23_idx in vdw_bonded_indices],
    marker='x', markersize=6, capsize=2,
    ls='none', label='DMC', c=color_dict['blue']
)

# CCSD(T)
axs[0].plot(
    [x23_final_elatt_dict[x23_idx]['CCSD(T)'] for x23_idx in vdw_bonded_indices],
    np.array(x_data) + 0.3,
    marker='x', markersize=6, ls='none',
    label='CCSD(T)', c=color_dict['red']
)

set_panel_ylim(axs[0], x_data, system_dist)
axs[0].tick_params(axis='y', which='both', labelright=True, right=True)

ax_left = axs[0]
ax_right = ax_left.twinx()

# Left side ticks + labels
ax_left.set_yticks(left_y)
ax_left.set_yticklabels(left_label)
ax_right.set_ylim(ax_left.get_ylim())

# Right side ticks + labels
ax_right.set_yticks(right_y)
ax_right.set_yticklabels(right_label)

# Left axis gridlines
ax_left.grid(axis='y', linestyle='--', color='grey', alpha=0.5)

# Make right axis gridlines also visible
ax_right.grid(axis='y', linestyle='--', color='grey', alpha=0.5)
ax_right.set_axisbelow(True)  # ensure right gridlines draw below data

# ======================
# Panel 1: mixed-bonded
# ======================
x_data = []
counter = 0
left_y = []
left_label = []
right_y = []
right_label = []
for x23_idx in mixed_bonded_indices:
    y0 = counter * system_dist
    x_data.append(y0)

    system_exp_elatt_list = [
        float(x) - float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Etemp'])
        for x in x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Enthalpy measurements'].split(',')
    ]

    for elatt in system_exp_elatt_list:
        axs[1].plot(elatt, y0 - 0.3,
                    marker='o', markersize=3,
                    c='black', markeredgecolor='none', alpha=0.5)

    mean_exp = np.mean(system_exp_elatt_list)
    error = float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Error'])
    elatt_max = mean_exp + error
    elatt_min = mean_exp - error

    if count == 0:
        axs[1].barh(y0 - 0.3, elatt_max - elatt_min, 0.4, elatt_min,
                    color='grey', alpha=0.7, label='Exp. range')
        count += 1
    else:
        axs[1].barh(y0 - 0.3, elatt_max - elatt_min, 0.4, elatt_min,
                    color='grey', alpha=0.7)

    if counter % 2 != 0:
        left_y.append(y0)
        left_label.append(f'{x23_labels[x23_idx]}')
    else:
        right_y.append(y0)
        right_label.append(f'{x23_labels[x23_idx]}')

    counter += 1

# DMC
axs[1].errorbar(
    [x23_dmc_elatt_dict[x23_idx][0] for x23_idx in mixed_bonded_indices],
    np.array(x_data) + 0.3,
    xerr=[x23_dmc_elatt_dict[x23_idx][1] for x23_idx in mixed_bonded_indices],
    marker='x', markersize=6, capsize=2,
    ls='none', label='DMC', c=color_dict['blue']
)

# CCSD(T)
axs[1].plot(
    [x23_final_elatt_dict[x23_idx]['CCSD(T)'] for x23_idx in mixed_bonded_indices],
    np.array(x_data) + 0.3,
    marker='x', markersize=6, ls='none',
    label='CCSD(T)', c=color_dict['red']
)

set_panel_ylim(axs[1], x_data, system_dist)
# axs[1].set_yticks(x_data, [f'{x23_idx:02d}' for x23_idx in mixed_bonded_indices])
ax_left = axs[1]
ax_right = ax_left.twinx()

# Left side ticks + labels
ax_left.set_yticks(left_y)
ax_left.set_yticklabels(left_label)
ax_right.set_ylim(ax_left.get_ylim())

# Right side ticks + labels
ax_right.set_yticks(right_y)
ax_right.set_yticklabels(right_label)

# Left axis gridlines
ax_left.grid(axis='y', linestyle='--', color='grey', alpha=0.5)

# Make right axis gridlines also visible
ax_right.grid(axis='y', linestyle='--', color='grey', alpha=0.5)
ax_right.set_axisbelow(True)  # ensure right gridlines draw below data

# ======================
# Panel 2: H-bonded
# ======================
x_data = []
counter = 0
left_y = []
left_label = []
right_y = []
right_label = []
for x23_idx in h_bonded_indices:
    y0 = counter * system_dist
    x_data.append(y0)

    system_exp_elatt_list = [
        float(x) - float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Etemp'])
        for x in x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Enthalpy measurements'].split(',')
    ]

    for elatt in system_exp_elatt_list:
        axs[2].plot(elatt, y0 - 0.3,
                    marker='o', markersize=3,
                    c='black', markeredgecolor='none', alpha=0.5)

    mean_exp = np.mean(system_exp_elatt_list)
    error = float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Error'])
    elatt_max = mean_exp + error
    elatt_min = mean_exp - error

    if count == 0:
        axs[2].barh(y0 - 0.3, elatt_max - elatt_min, 0.4, elatt_min,
                    color='grey', alpha=0.7, label='Exp. range')
        count += 1
    else:
        axs[2].barh(y0 - 0.3, elatt_max - elatt_min, 0.4, elatt_min,
                    color='grey', alpha=0.7)

    if counter % 2 == 0:
        left_y.append(y0)
        left_label.append(f'{x23_labels[x23_idx]}')
    else:
        right_y.append(y0)
        right_label.append(f'{x23_labels[x23_idx]}')

    counter += 1

# DMC
axs[2].errorbar(
    [x23_dmc_elatt_dict[x23_idx][0] for x23_idx in h_bonded_indices],
    np.array(x_data) + 0.3,
    xerr=[x23_dmc_elatt_dict[x23_idx][1] for x23_idx in h_bonded_indices],
    marker='x', markersize=6, capsize=2,
    ls='none', label='DMC', c=color_dict['blue']
)

# CCSD(T)
axs[2].plot(
    [x23_final_elatt_dict[x23_idx]['CCSD(T)'] for x23_idx in h_bonded_indices],
    np.array(x_data) + 0.3,
    marker='x', markersize=6, ls='none',
    label='CCSD(T)', c=color_dict['red']
)

set_panel_ylim(axs[2], x_data, system_dist)
axs[2].set_yticks(x_data, [f'{x23_idx:02d}' for x23_idx in h_bonded_indices])

axs[2].set_xlabel('Lattice energy (kJ/mol)')
axs[2].set_xlim([-200, 0])

ax_left = axs[2]
ax_right = ax_left.twinx()

# Left side ticks + labels
ax_left.set_yticks(left_y)
ax_left.set_yticklabels(left_label)
ax_right.set_ylim(ax_left.get_ylim())

# Right side ticks + labels
ax_right.set_yticks(right_y)
ax_right.set_yticklabels(right_label)

# Left axis gridlines
ax_left.grid(axis='y', linestyle='--', color='grey', alpha=0.5)

# Make right axis gridlines also visible
ax_right.grid(axis='y', linestyle='--', color='grey', alpha=0.5)
ax_right.set_axisbelow(True)  # ensure right gridlines draw below data

for label in axs[2].get_xticklabels():
    label.set_ha('left')   # horizontal alignment

# Slight extra padding between panels (doesn't change scale inside axes)
fig.set_constrained_layout_pads(h_pad=0.2)

plt.savefig('Figures/MAIN_Figure-X23_Comparison.png', dpi=600)

### Effect of (cT)-fit

In [17]:
fig, axs = plt.subplots(figsize=(5,7),constrained_layout=True,dpi=450)

count = 0

system_dist = 1.5
x_data=np.arange(23)*system_dist

for x23_idx in range(1,24):
    system_exp_elatt_list=[float(x) - float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Etemp']) for x in x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Enthalpy measurements'].split(',')]
    len_s=len(system_exp_elatt_list)
    for elatt in system_exp_elatt_list:
        axs.plot(elatt - float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Lattice energy']) ,(x23_idx-1)*system_dist-0.3,marker='o',markersize=3,c='black',markeredgecolor='none',alpha=0.5)

    mean_exp = float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Lattice energy'])
    error = float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Error'])
    elatt_max =  error
    elatt_min = - error
    if count == 0:
        axs.barh((x23_idx-1)*system_dist - 0.3, elatt_max-elatt_min,0.4,elatt_min,color='grey',alpha=0.7, label='Expt Error')
        count += 1
    else:
        axs.barh((x23_idx-1)*system_dist - 0.3, elatt_max-elatt_min,0.4,elatt_min,color='grey',alpha=0.7)

# Plot the DMC numbers
axs.errorbar([x23_dmc_elatt_dict[x23_idx][0] - float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Lattice energy']) for x23_idx in range(1,24)],x_data + 0.3,xerr=[x23_dmc_elatt_dict[x23_idx][1] for x23_idx in range(1,24)],marker='x',markersize=6,capsize=2,ls='none',label='DMC',c=color_dict['blue'])

# Plot the CC data
axs.plot([x23_final_elatt_dict[x23_idx]['CCSD(T)'] - float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Lattice energy']) for x23_idx in range(1,24)],x_data + 0.3,marker='x',markersize=6,ls='none',label='CCSD(T)',c=color_dict['red'])

# Plot the CCSD(cT) data
axs.plot([x23_final_elatt_dict[x23_idx]['CCSD(cT)-fit'] - float(x23_exp_elatt_compile_dict[x23_labels[x23_idx]]['Lattice energy']) for x23_idx in range(1,24)],x_data + 0.3,marker='x',markersize=6,ls='none',label='CCSD(cT)-fit',c=color_dict['green'])


axs.set_yticks(x_data,[x23_labels[x23_idx] for x23_idx in range(1,24)])

axs.legend(fontsize=8,loc='lower right')

axs.set_xlabel('Lattice energy relative to experiment (kJ/mol)')
axs.set_ylim([x_data[-1] + system_dist/2,x_data[0] - system_dist/2])
axs.set_xlim([-30,30])


axs.grid(color='grey', linestyle='-', linewidth=0.5,alpha=0.5)
plt.savefig('Figures/SI_Figure-cT_Effect.png')

## Effect of D4 dispersion subtractive embedding on distance cutoffs

In [18]:
cutoff_2b_dists = np.arange(3.5,12.5,0.5)
cutoff_3b_dists = np.arange(100,310,10)

x23_cutoff_2b_elatt_dict = {y: {f'{cutoff:.1f}': 0 for cutoff in cutoff_2b_dists} for y in list(range(1,24))}
x23_cutoff_3b_elatt_dict = {y: {cutoff: 0 for cutoff in cutoff_3b_dists} for y in list(range(1,24))}

x23_cutoff_2b_d4_elatt_dict = {y: {f'{cutoff:.1f}': 0 for cutoff in cutoff_2b_dists} for y in list(range(1,24))}
x23_cutoff_3b_d4_elatt_dict = {y: {cutoff: 0 for cutoff in cutoff_3b_dists} for y in list(range(1,24))}

for x23_idx in range(1,24):
    # Get the 2b data
    with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_2b.db') as db2:
        elatt_cwft = 0
        elatt_d4_cwft = 0
        dist_reached_bool = {cutoff: False for cutoff in cutoff_2b_dists}

        for i in range(len(db2)):
            row = db2.get(id=i+1)
            dist = row.data['distance']
            for cutoff in cutoff_2b_dists:
                if dist > cutoff and dist_reached_bool[cutoff] == False:
                    dist_reached_bool[cutoff] = True
                    x23_cutoff_2b_elatt_dict[x23_idx][f'{cutoff:.1f}'] = elatt_cwft/kjmol
                    x23_cutoff_2b_d4_elatt_dict[x23_idx][f'{cutoff:.1f}'] = elatt_d4_cwft/kjmol

            elatt_cwft += (row.data[f'CCSD(T) LAF TZ'] - row.data[f'MP2 LAF TZ'] + row.data[f'MP2 Canonical CBS'])*(row.data['count'])
            elatt_d4_cwft += (row.data[f'CCSD(T) LAF TZ'] - row.data[f'MP2 LAF TZ'] + row.data[f'MP2 Canonical CBS'] - row.data['D4'])*(row.data['count'])

        for cutoff in cutoff_2b_dists:
            if dist_reached_bool[cutoff] == False:
                x23_cutoff_2b_elatt_dict[x23_idx][f'{cutoff:.1f}'] = elatt_cwft/kjmol
                x23_cutoff_2b_d4_elatt_dict[x23_idx][f'{cutoff:.1f}'] = elatt_d4_cwft/kjmol
    # Get the 3b data
    with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_3b.db') as db3:
        elatt_cwft = 0
        elatt_d4_cwft = 0
        dist_reached_bool = {cutoff: False for cutoff in cutoff_3b_dists}

        for i in range(len(db3)):
            row = db3.get(id=i+1)
            dist = row.data['distance']
            for cutoff in cutoff_3b_dists:
                if dist > cutoff and dist_reached_bool[cutoff] == False:
                    dist_reached_bool[cutoff] = True
                    x23_cutoff_3b_elatt_dict[x23_idx][cutoff] = elatt_cwft/kjmol
                    x23_cutoff_3b_d4_elatt_dict[x23_idx][cutoff] = elatt_d4_cwft/kjmol

            elatt_cwft += (row.data[f'CCSD(T) LAF DZ'] - row.data[f'MP2 LAF DZ'] + row.data[f'MP2 Canonical CBS'])*(row.data['count'])
            elatt_d4_cwft += (row.data[f'CCSD(T) LAF DZ'] - row.data[f'MP2 LAF DZ'] + row.data[f'MP2 Canonical CBS'] - row.data['D4'])*(row.data['count'])

        for cutoff in cutoff_3b_dists:
            if dist_reached_bool[cutoff] == False:
                x23_cutoff_3b_elatt_dict[x23_idx][cutoff] = elatt_cwft/kjmol
                x23_cutoff_3b_d4_elatt_dict[x23_idx][cutoff] = elatt_d4_cwft/kjmol

    if replot_analysis:
        fig, axs = plt.subplots(1,2,figsize=(6.69,2.5),constrained_layout=True,dpi=300,sharey=True)
        
        # Plot the 2B convergence
        axs[0].plot(cutoff_2b_dists,np.array([x23_cutoff_2b_elatt_dict[x23_idx][f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - x23_cutoff_2b_elatt_dict[x23_idx]['12.0'],label=r'CCSD(T) [$E_\text{int}^\text{2b}=$' + f"{x23_cutoff_2b_elatt_dict[x23_idx]['12.0']:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

        axs[0].plot(cutoff_2b_dists,np.array([x23_cutoff_2b_d4_elatt_dict[x23_idx][f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - x23_cutoff_2b_d4_elatt_dict[x23_idx]['12.0'],ls='--',label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{2b}=$' + f"{x23_cutoff_2b_d4_elatt_dict[x23_idx]['12.0']:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

        # Plot the 3B convergence
        axs[1].plot(cutoff_3b_dists,np.array([x23_cutoff_3b_elatt_dict[x23_idx][cutoff] for cutoff in cutoff_3b_dists]) - x23_cutoff_3b_elatt_dict[x23_idx][300],label=r'CCSD(T) [$E_\text{int}^\text{3b}=$' + f"{x23_cutoff_3b_elatt_dict[x23_idx][300]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

        axs[1].plot(cutoff_3b_dists,np.array([x23_cutoff_3b_d4_elatt_dict[x23_idx][cutoff] for cutoff in cutoff_3b_dists]) - x23_cutoff_3b_d4_elatt_dict[x23_idx][300],ls='--',label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{3b}=$' + f"{x23_cutoff_3b_d4_elatt_dict[x23_idx][300]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

        # Fill between -1 and 1 kJ/mol
        axs[0].fill_between(cutoff_2b_dists,-1,1,color='grey',alpha=0.3,edgecolor='none')
        axs[1].fill_between(cutoff_3b_dists,-1,1,color='grey',alpha=0.3,edgecolor='none')


        axs[0].set_ylim([-4,4])
        axs[0].set_xlim([3.5,12])
        axs[1].set_xlim([100,300])

        axs[0].set_ylabel('Energy difference (kJ/mol)')
        axs[0].set_xlabel(r'2B Distance cutoff (Å)')
        axs[1].set_xlabel(r'3B Distance cutoff (Å$^3$)')

        axs[0].legend(fontsize=8)
        axs[1].legend(fontsize=8)

        # Make a title over both plots
        fig.suptitle(f'{x23_labels[x23_idx]}',fontsize=10)

        plt.savefig(f'Figures/SI_Figure-2b_3b_distance_convergence_{x23_idx:02d}.png')

# # Make the latex input str for including these tables

# latex_input_str = ""
# for x23_idx in range(1,24):
#     if x23_idx == 1:
#         latex_input_str += r"""\begin{figure}[h!]
# \includegraphics[width=\textwidth]{"""+ f"Figures/SI_Figure-2b_3b_distance_convergence_{x23_idx:02d}.png" + r"""}
# \caption{\label{fig:""" + f"x23_d4_conv_{x23_idx:02d}" + r"""} The convergence with distance cutoff of the two-body (2B) and three-body (3B) components of the many-body expansion (MBE) for the lattice energy $E_\text{latt}$ of """ + f"{x23_labels[x23_idx].lower()}" + r""" from the X23 dataset. The red line shows the CCSD(T) result, while the blue line shows the difference to the D4 result. The shaded area indicates the range of energies between -1 and 1 kJ/mol. We use the pairwise distance $R_{12}$ between the two monomers in the 2B case, and the product of the pairwise distances $R_{12}*R_{13}*R_{23}$ in the 3B case.}
# \end{figure}
# """
#     else:
#         latex_input_str += r"""\begin{figure}[h!]
# \includegraphics[width=\textwidth]{"""+ f"Figures/SI_Figure-2b_3b_distance_convergence_{x23_idx:02d}.png" + r"""}
# \caption{\label{fig:""" + f"x23_d4_conv_{x23_idx:02d}" + r"""} The convergence of the 2B and 3B MBE components to the $E_\text{latt}$ of """ + f"{x23_labels[x23_idx].lower()}" + r""".}
# \end{figure}
# """

# print(latex_input_str)

In [19]:
# Find the number of terms which are within 1 kJ/mol of the final value for each system
print("CCSD(T) correlation # of X23 systems within 1 kJ/mol of final 2B value at 9Å:", len([idx for idx in range(1,24) if abs(x23_cutoff_2b_elatt_dict[idx]['9.0'] - x23_cutoff_2b_elatt_dict[idx]['12.0']) < 1 ]))
print("Delta^{CCSD(T)}_{D4} # of X23 systems within 1 kJ/mol of final 2B value at 9Å:", len([idx for idx in range(1,24) if abs(x23_cutoff_2b_d4_elatt_dict[idx]['9.0'] - x23_cutoff_2b_d4_elatt_dict[idx]['12.0']) < 1 ]))
print("CCSD(T) correlation # of X23 systems within 1 kJ/mol of final 3B value at 200 Å³:", len([idx for idx in range(1,24) if abs(x23_cutoff_3b_elatt_dict[idx][200] - x23_cutoff_3b_elatt_dict[idx][300]) < 1 ]))
print("Delta^{CCSD(T)}_{D4} # of X23 systems within 1 kJ/mol of final 3B value at 200 Å³:", len([idx for idx in range(1,24) if abs(x23_cutoff_3b_d4_elatt_dict[idx][200] - x23_cutoff_3b_d4_elatt_dict[idx][300]) < 1 ]))

print("CCSD(T) correlation minimum 2B contribution:", np.min([x23_cutoff_2b_elatt_dict[idx]['12.0'] for idx in range(1,24)]))
print("CCSD(T) correlation maximum 2B contribution:", np.max([x23_cutoff_2b_elatt_dict[idx]['12.0'] for idx in range(1,24)]))
print("Delta^{CCSD(T)}_{D4} minimum 2B contribution:", np.min([x23_cutoff_2b_d4_elatt_dict[idx]['12.0'] for idx in range(1,24)]))
print("Delta^{CCSD(T)}_{D4} maximum 2B contribution:", np.max([x23_cutoff_2b_d4_elatt_dict[idx]['12.0'] for idx in range(1,24)]))

print("CCSD(T) correlation minimum 3B contribution:", np.min([x23_cutoff_3b_elatt_dict[idx][300] for idx in range(1,24)]))
print("CCSD(T) correlation maximum 3B contribution:", np.max([x23_cutoff_3b_elatt_dict[idx][300] for idx in range(1,24)]))
print("Delta^{CCSD(T)}_{D4} minimum 3B contribution:", np.min([x23_cutoff_3b_d4_elatt_dict[idx][300] for idx in range(1,24)]))
print("Delta^{CCSD(T)}_{D4} maximum 3B contribution:", np.max([x23_cutoff_3b_d4_elatt_dict[idx][300] for idx in range(1,24)]))

CCSD(T) correlation # of X23 systems within 1 kJ/mol of final 2B value at 9Å: 4
Delta^{CCSD(T)}_{D4} # of X23 systems within 1 kJ/mol of final 2B value at 9Å: 18
CCSD(T) correlation # of X23 systems within 1 kJ/mol of final 3B value at 200 Å³: 18
Delta^{CCSD(T)}_{D4} # of X23 systems within 1 kJ/mol of final 3B value at 200 Å³: 20
CCSD(T) correlation minimum 2B contribution: -171.67571689968193
CCSD(T) correlation maximum 2B contribution: -26.896983912428144
Delta^{CCSD(T)}_{D4} minimum 2B contribution: -5.606987673397395
Delta^{CCSD(T)}_{D4} maximum 2B contribution: 12.34793650773434
CCSD(T) correlation minimum 3B contribution: 0.2782924224286063
CCSD(T) correlation maximum 3B contribution: 7.157543899181965
Delta^{CCSD(T)}_{D4} minimum 3B contribution: -2.6038761018343437
Delta^{CCSD(T)}_{D4} maximum 3B contribution: 2.7680081857870764

### Smaller cutoff approaches

In [20]:
# Create table for the lattice energies with small, medium and large cutoffs
# Small: 2B cutoff 6.5A, 3B cutoff 100A^3
# Medium: 2B cutoff 9.0A, 3B cutoff 200A^3
# Large: 2B cutoff 12.0A, 3B cutoff 300A^3
x23_d4_cutoff_total_elatt_dict = {y: {'Small': 0, 'Medium': 0, 'Large': 0} for y in list(range(1,25))}


small_mad_list = []
medium_mad_list = []
large_mad_list = []

for x23_idx in range(1,24):
    small_elatt = x23_hf_d4_elatt_dict[x23_idx]/kjmol + x23_final_corr_d4_elatt_dict[x23_idx]['CCSD(T)']['1B']/kjmol + x23_cutoff_3b_d4_elatt_dict[x23_idx][100] + x23_cutoff_2b_d4_elatt_dict[x23_idx]['6.5']
    medium_elatt = x23_hf_d4_elatt_dict[x23_idx]/kjmol + x23_final_corr_d4_elatt_dict[x23_idx]['CCSD(T)']['1B']/kjmol+ x23_cutoff_3b_d4_elatt_dict[x23_idx][200] + x23_cutoff_2b_d4_elatt_dict[x23_idx]['9.0']
    large_elatt = x23_hf_d4_elatt_dict[x23_idx]/kjmol + x23_final_corr_d4_elatt_dict[x23_idx]['CCSD(T)']['1B']/kjmol + x23_cutoff_3b_d4_elatt_dict[x23_idx][300] + x23_cutoff_2b_d4_elatt_dict[x23_idx]['12.0']
    small_mad_list += [np.abs(small_elatt - large_elatt)]
    medium_mad_list += [np.abs(medium_elatt - large_elatt)]
    large_mad_list += [0]
    x23_d4_cutoff_total_elatt_dict[x23_idx]['Small'] = small_elatt
    x23_d4_cutoff_total_elatt_dict[x23_idx]['Medium'] = medium_elatt
    x23_d4_cutoff_total_elatt_dict[x23_idx]['Large'] = large_elatt

x23_d4_cutoff_total_elatt_dict[24] = {'Small': np.mean(small_mad_list), 'Medium': np.mean(medium_mad_list), 'Large': np.mean(large_mad_list)}

x23_d4_cutoff_total_elatt_df = pd.DataFrame.from_dict(x23_d4_cutoff_total_elatt_dict,orient='index')
x23_d4_cutoff_total_elatt_df.index = [f"{x23_labels[idx]}" if idx < 24 else 'MAD' for idx in x23_d4_cutoff_total_elatt_df.index]
x23_d4_cutoff_total_elatt_df.columns = ['Small','Medium','Large']
# Round to 1 decimal place
x23_d4_cutoff_total_elatt_df = x23_d4_cutoff_total_elatt_df.round(1)
display(x23_d4_cutoff_total_elatt_df)
# # Convert to latex
convert_df_to_latex_input(
    df = x23_d4_cutoff_total_elatt_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_smaller_models",
    caption = r"Lattice energy (in kJ/mol) for the X23 dataset with the large (2B cutoff of $12.0\,$\AA{} and 3B cutoff of $300\,$\AA{}$^3$) LNO-MBE-CCSD(T) model, and the medium (2B cutoff of $6.5\,$\AA{} and 3B cutoff of $100\,$\AA{}$^3$) as well as small models (2B cutoff of $9.0\,$\AA{} and 3B cutoff of $200\,$\AA{}$^3$).",
    replace_input= {
        "[t]": "[c]"
    },
    index = True,
    filename = "Tables/SI_Table-X23_Smaller_CC_models.tex",
    float_fmt = r"%.1f",)

                      Small  Medium  Large
1,4-cyclohexanedione  -92.9   -92.2  -92.2
Acetic Acid           -70.9   -69.5  -70.3
Adamantane            -65.4   -66.9  -67.5
Ammonia               -37.4   -37.9  -38.6
Anthracene           -110.4  -111.3 -113.9
Benzene               -53.2   -52.3  -52.8
CO$_2$                -28.4   -28.3  -27.9
Cyanamide             -82.9   -81.8  -82.4
Cytosine             -163.8  -157.5 -161.9
Ethyl carbamate       -83.7   -85.1  -85.0
Formamide             -76.8   -81.1  -80.8
Hexamine              -85.1   -85.3  -88.1
Imidazole             -87.8   -87.9  -88.8
Naphthalene           -81.7   -82.7  -83.8
Oxalic Acid $\alpha$ -102.5   -99.1  -99.3
Oxalic Acid $\beta$  -101.2   -98.1  -98.8
Pyrazine              -64.4   -63.4  -63.5
Pyrazole              -78.5   -78.1  -78.5
Succinic Acid        -128.9  -128.5 -125.0
Triazine              -61.4   -61.5  -61.5
Trioxane              -64.1   -63.8  -64.1
Uracil               -141.6  -137.2 -137.2
Urea                 -103.7  -108.8 -107.0
MAD                     1.8     1.0    0.0

## Removing symmetrically equivalent subsystems with Coulomb matrix filter

In [21]:
# Validate that the filtering works

filtered_x23_final_corr_elatt_dict = {y:{x:{} for x in ['CCSD(T)']} for y in list(range(1,24))}

for x23_idx in range(1,24):
    system_all_methods_elatt_dict = {x:{} for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'MP2 Canonical', 'MP2 Final', 'CCSD Final', 'CCSD(T) Final', 'CCSD(cT)-fit Final','D4']}
    system_total_time = 0
    method_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
    with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_1b.db') as db1:
        monomer_ene_list = []
        for i in range(2):
            row = db1.get(id=i+1)
            monomer_ene_list += [row.data[f'MP2 Canonical CBS'] - row.data[f'MP2 LAF QZ'] + row.data[f'CCSD(T) LAF QZ']]
        method_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

    with connect(f'Data/X23/cWFT/filtered_x23_{x23_idx:02d}_2b.db') as db2:
        elatt_cwft = 0
        for i in range(len(db2)):
            row = db2.get(id=i+1)
            elatt_cwft += (row.data[f'CCSD(T) LAF TZ'] - row.data[f'MP2 LAF TZ'] + row.data[f'MP2 Canonical CBS'])*(row.data['count'])
        method_elatt_dict['2B'] = elatt_cwft

    with connect(f'Data/X23/cWFT/filtered_x23_{x23_idx:02d}_3b.db') as db3:
        elatt_cwft = 0
        for i in range(len(db3)):
            row = db3.get(id=i+1)
            elatt_cwft += (row.data[f'CCSD(T) LAF DZ'] - row.data[f'MP2 LAF DZ'] + row.data[f'MP2 Canonical CBS'])*(row.data['count'])
        method_elatt_dict['3B'] = elatt_cwft
    method_elatt_dict['Total'] = method_elatt_dict['1B'] + method_elatt_dict['2B'] + method_elatt_dict['3B']
    filtered_x23_final_corr_elatt_dict[x23_idx]['CCSD(T)'] = method_elatt_dict.copy()

## Computational cost analysis

### Analysis of distance cutoff dependence of cWFT MBE

In [22]:
cutoff_2b_dists = np.arange(3.5,12.5,0.5)
cutoff_3b_dists = np.arange(100,310,10)

# Cumulative cost in cpuh for each cutoff
x23_cutoff_2b_cpuh_dict = {y: {f'{cutoff:.1f}': 0 for cutoff in cutoff_2b_dists} for y in list(range(1,24))}
x23_cutoff_3b_cpuh_dict = {y: {cutoff: 0 for cutoff in cutoff_3b_dists} for y in list(range(1,24))}

# Collect the number of calculations for each cutoff
x23_cutoff_2b_num_calcs_dict = {y: {f'{cutoff:.1f}': 0 for cutoff in cutoff_2b_dists} for y in list(range(1,24))}
x23_cutoff_3b_num_calcs_dict = {y: {cutoff: 0 for cutoff in cutoff_3b_dists} for y in list(range(1,24))}

# Make filtered dictionaries
x23_cutoff_2b_cpuh_dict_filtered = {y: {f'{cutoff:.1f}': 0 for cutoff in cutoff_2b_dists} for y in list(range(1,24))}
x23_cutoff_3b_cpuh_dict_filtered = {y: {cutoff: 0 for cutoff in cutoff_3b_dists} for y in list(range(1,24))}
x23_cutoff_2b_num_calcs_dict_filtered = {y: {f'{cutoff:.1f}': 0 for cutoff in cutoff_2b_dists} for y in list(range(1,24))}
x23_cutoff_3b_num_calcs_dict_filtered = {y: {cutoff: 0 for cutoff in cutoff_3b_dists} for y in list(range(1,24))}

# Make full_enumeration dictionaries
x23_cutoff_2b_num_calcs_dict_full = {y: {f'{cutoff:.1f}': 0 for cutoff in cutoff_2b_dists} for y in list(range(1,24))}
x23_cutoff_3b_num_calcs_dict_full = {y: {cutoff: 0 for cutoff in cutoff_3b_dists} for y in list(range(1,24))}

for x23_idx in range(1,24):
    for mbe_type in ['filtered_','']:
        # Get the 2b data
        with connect(f'Data/X23/cWFT/{mbe_type}x23_{x23_idx:02d}_2b.db') as db2:
            cpuh_cwft = 0
            num_calcs_cwft = 0
            dist_reached_bool = {cutoff: False for cutoff in cutoff_2b_dists}

            for i in range(len(db2)):
                row = db2.get(id=i+1)
                dist = row.data['distance']
                for cutoff in cutoff_2b_dists:
                    if dist > cutoff and dist_reached_bool[cutoff] == False:
                        dist_reached_bool[cutoff] = True
                        x23_cutoff_2b_cpuh_dict[x23_idx][f'{cutoff:.1f}'] = cpuh_cwft
                        x23_cutoff_2b_num_calcs_dict[x23_idx][f'{cutoff:.1f}'] = num_calcs_cwft

                cpuh_cwft += row.data['time']*8/3600
                num_calcs_cwft += 1

            for cutoff in cutoff_2b_dists:
                if dist_reached_bool[cutoff] == False:
                    x23_cutoff_2b_cpuh_dict[x23_idx][f'{cutoff:.1f}'] = cpuh_cwft
                    x23_cutoff_2b_num_calcs_dict[x23_idx][f'{cutoff:.1f}'] = num_calcs_cwft
        # Get the 3b data
        with connect(f'Data/X23/cWFT/{mbe_type}x23_{x23_idx:02d}_3b.db') as db3:
            cpuh_cwft = 0
            num_calcs_cwft = 0
            dist_reached_bool = {cutoff: False for cutoff in cutoff_3b_dists}

            for i in range(len(db3)):
                row = db3.get(id=i+1)
                dist = row.data['distance']
                for cutoff in cutoff_3b_dists:
                    if dist > cutoff and dist_reached_bool[cutoff] == False:
                        dist_reached_bool[cutoff] = True
                        x23_cutoff_3b_cpuh_dict[x23_idx][cutoff] = cpuh_cwft
                        x23_cutoff_3b_num_calcs_dict[x23_idx][cutoff] = num_calcs_cwft

                cpuh_cwft += row.data['time']*8/3600
                num_calcs_cwft += 1

            for cutoff in cutoff_3b_dists:
                if dist_reached_bool[cutoff] == False:
                    x23_cutoff_3b_cpuh_dict[x23_idx][cutoff] = cpuh_cwft
                    x23_cutoff_3b_num_calcs_dict[x23_idx][cutoff] = num_calcs_cwft
        if mbe_type == 'filtered_':
            x23_cutoff_2b_cpuh_dict_filtered[x23_idx] = x23_cutoff_2b_cpuh_dict[x23_idx].copy()
            x23_cutoff_3b_cpuh_dict_filtered[x23_idx] = x23_cutoff_3b_cpuh_dict[x23_idx].copy()
            x23_cutoff_2b_num_calcs_dict_filtered[x23_idx] = x23_cutoff_2b_num_calcs_dict[x23_idx].copy()
            x23_cutoff_3b_num_calcs_dict_filtered[x23_idx] = x23_cutoff_3b_num_calcs_dict[x23_idx].copy()
    # Do full enumeration number of calculations (this is in PRL format)
    with connect(f'Data/X23/cWFT/full_enumeration/full_x23_{prl_to_x23_order[x23_idx]:02d}_2b.db') as db2:
        num_calcs_cwft = 0
        dist_reached_bool = {cutoff: False for cutoff in cutoff_2b_dists}

        for i in range(len(db2)):
            row = db2.get(id=i+1)
            dist = row.data['dist']
            for cutoff in cutoff_2b_dists:
                if dist > cutoff and dist_reached_bool[cutoff] == False:
                    dist_reached_bool[cutoff] = True
                    x23_cutoff_2b_num_calcs_dict_full[x23_idx][f'{cutoff:.1f}'] = num_calcs_cwft

            num_calcs_cwft += 1

        for cutoff in cutoff_2b_dists:
            if dist_reached_bool[cutoff] == False:
                x23_cutoff_2b_num_calcs_dict_full[x23_idx][f'{cutoff:.1f}'] = num_calcs_cwft
    # Get the 3b data
    with connect(f'Data/X23/cWFT/full_enumeration/full_x23_{prl_to_x23_order[x23_idx]:02d}_3b.db') as db3:
        num_calcs_cwft = 0
        dist_reached_bool = {cutoff: False for cutoff in cutoff_3b_dists}

        for i in range(len(db3)):
            row = db3.get(id=i+1)
            dist = row.data['dist']
            for cutoff in cutoff_3b_dists:
                if dist > cutoff and dist_reached_bool[cutoff] == False:
                    dist_reached_bool[cutoff] = True
                    x23_cutoff_3b_num_calcs_dict_full[x23_idx][cutoff] = num_calcs_cwft

            num_calcs_cwft += 1

        for cutoff in cutoff_3b_dists:
            if dist_reached_bool[cutoff] == False:
                x23_cutoff_3b_num_calcs_dict_full[x23_idx][cutoff] = num_calcs_cwft

#### 2B terms

In [23]:
# Convert cutoff dictionaries to table
cutoff_2b_dists = np.arange(5,13,1)
cutoff_2b_num_terms_df_dict = {}
for x23_idx in range(1, 24):
    cutoff_2b_num_terms_df_dict[(f'{x23_labels[x23_idx]}','Full Enumeration')] = {f'{cutoff:.1f}': x23_cutoff_2b_num_calcs_dict_full[x23_idx][f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists}
    cutoff_2b_num_terms_df_dict[(f'{x23_labels[x23_idx]}','pMBE')] = {f'{cutoff:.1f}': x23_cutoff_2b_num_calcs_dict[x23_idx][f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists}
    cutoff_2b_num_terms_df_dict[(f'{x23_labels[x23_idx]}','pMBE + Coulomb')] = {f'{cutoff:.1f}': x23_cutoff_2b_num_calcs_dict_filtered[x23_idx][f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists}

cutoff_2b_table = pd.DataFrame(cutoff_2b_num_terms_df_dict).T
display(cutoff_2b_table)
# Convert to latex table
latex_input_str = '\n'.join(convert_df_to_latex_input(
df = cutoff_2b_table,
start_input = '\\begin{table}',
label = "tab:x23_2b_num_terms",
caption = "The number of two-body (2B) terms as a function of distance between the center of mass of the two molecules that make up the dimer subsystem.",
replace_input= {
    "[t]": "[c]"
},
output_str = True,
index = True).splitlines()[6:-4]) + '\n'

with open('Tables/SI_Table-pMBE_Coulomb_2B_Terms.tex', 'w') as f:
    f.write(r"""\LTcapwidth=\textwidth
    
\begin{longtable}{lrrrrrrrrrr}
\caption{\label{tab:x23_2b_num_terms}The number of two-body (2B) terms as a function of distance between the center of mass of the two molecules that make up the dimer subsystem.} \\

\toprule
2B distance (\AA) &  & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\
\midrule
\endfirsthead



\caption[]{(continued)} \\
\endhead

\multicolumn{11}{r}{{Continued on next page}} \\
\endfoot

\bottomrule
\endlastfoot

""")
    f.write(latex_input_str)
    f.write(r"\end{longtable}")

                                       5.0  6.0  7.0  8.0  9.0  10.0  11.0  \
1,4-cyclohexanedione Full Enumeration    2    6   14   14   16    26    46
                     pMBE                2    6   11   11   12    18    35
                     pMBE + Coulomb      1    3    7    7    8    13    23
Acetic Acid          Full Enumeration    6   12   22   30   36    62    76
                     pMBE                5   10   18   25   31    55    69
...                                    ...  ...  ...  ...  ...   ...   ...
Uracil               pMBE                1    3   12   21   23    28    42
                     pMBE + Coulomb      1    3    8   15   16    19    30
Urea                 Full Enumeration   10   14   14   30   42    60    76
                     pMBE                9   11   11   21   33    46    58
                     pMBE + Coulomb      3    4    4    8   10    14    16

                                       12.0
1,4-cyclohexanedione Full Enumeration    50
                     pMBE                39
                     pMBE + Coulomb      25
Acetic Acid          Full Enumeration   100
                     pMBE                91
...                                     ...
Uracil               pMBE                56
                     pMBE + Coulomb      40
Urea                 Full Enumeration    96
                     pMBE                76
                     pMBE + Coulomb      20

[69 rows x 8 columns]

#### 3B terms

In [24]:
# Convert cutoff dictionaries to table
cutoff_3b_dists = np.arange(120,310,30)
cutoff_3b_num_terms_df_dict = {}
for x23_idx in range(1, 24):
    cutoff_3b_num_terms_df_dict[(f'{x23_labels[x23_idx]}','Full Enumeration')] = {cutoff: x23_cutoff_3b_num_calcs_dict_full[x23_idx][cutoff] for cutoff in cutoff_3b_dists}
    cutoff_3b_num_terms_df_dict[(f'{x23_labels[x23_idx]}','pMBE')] = {cutoff: x23_cutoff_3b_num_calcs_dict[x23_idx][cutoff] for cutoff in cutoff_3b_dists}
    cutoff_3b_num_terms_df_dict[(f'{x23_labels[x23_idx]}','pMBE + Coulomb')] = {cutoff: x23_cutoff_3b_num_calcs_dict_filtered[x23_idx][cutoff] for cutoff in cutoff_3b_dists}

cutoff_3b_table = pd.DataFrame(cutoff_3b_num_terms_df_dict).T
display(cutoff_3b_table)
# Convert to latex table
latex_input_str = '\n'.join(convert_df_to_latex_input(
df = cutoff_3b_table,
start_input = '\\begin{table}',
label = "tab:x23_3b_num_terms",
caption = "The number of three-body (3B) terms as a function of the product of the pairwise distances between the center of mass of the three molecules that make up the trimer subsystem.",
replace_input= {
    "[t]": "[c]"
},
output_str = True,
index = True).splitlines()[6:-4]) + '\n'

with open('Tables/SI_Table-pMBE_Coulomb_3B_Terms.tex', 'w') as f:
    f.write(r"""\LTcapwidth=\textwidth
    
\begin{longtable}{lrrrrrrrrr}
\caption{\label{tab:x23_3b_num_terms}The number of three-body (3B) terms as a function of the product of the pairwise distances between the center of mass of the three molecules that make up the trimer subsystem.} \\

\toprule
3B distance (\AA\textsuperscript{3}) &  & 120 & 150 & 180 & 210 & 240 & 270 & 300 \\
\midrule
\endfirsthead



\caption[]{(continued)} \\
\endhead

\multicolumn{10}{r}{{Continued on next page}} \\
\endfoot

\bottomrule
\endlastfoot

""")
    f.write(latex_input_str)
    f.write(r"\end{longtable}")

                                       120  150  180  210  240  270  300
1,4-cyclohexanedione Full Enumeration    0    0    3   15   27   48   60
                     pMBE                0    0    2   10   18   32   40
                     pMBE + Coulomb      0    0    1    5    9   16   20
Acetic Acid          Full Enumeration   30   45   87  135  177  204  279
                     pMBE               20   31   59   97  131  150  205
...                                    ...  ...  ...  ...  ...  ...  ...
Uracil               pMBE                3    7   19   30   44   52   75
                     pMBE + Coulomb      2    4   16   23   31   35   50
Urea                 Full Enumeration   24   42   78  135  183  219  255
                     pMBE               16   28   52   81  113  133  157
                     pMBE + Coulomb      3    6   10   19   23   27   31

[69 rows x 7 columns]

# Analysis DMC costs

In [25]:
# Convert csv to dict for file "Data/X23/cWFT/DMC_Expt_References/DMCcost.csv"
dmc_cost_df = pd.read_csv("Data/X23/DMC/DMCcost.csv",index_col=0)
display(dmc_cost_df)
dmc_cost_dict = dmc_cost_df.to_dict(orient='index')

,Ne,Ne_mol,simcell,Nmol,Nscell,Nmolpcell,nome,DMC[4],DMC[2],DMC[1],DMC[0.5]
mol,,,,,,,,,,,
01CYHEXO,704,44,2x2x2,16.0,8,2.0,"1,4-cyclohexanedione",297,1984,23818,317584
02acetic_acid,576,24,1x3x2,24.0,6,4.0,Acetic Acid,64,433,5198,69307
03adamantane,896,56,2x2x2,16.0,8,2.0,Adamantane,650,4334,52013,693512
04ammonia,256,8,2x2x2,32.0,8,4.0,Ammonia,2,18,219,2925
05anthracene,264,66,1x2x1,4.0,2,2.0,Anthracene,309,2065,24791,330552
06benzene,960,30,2x2x2,32.0,8,4.0,Benzene,183,1221,14657,195439
07co2,512,16,2x2x2,32.0,8,4.0,CO2,24,160,1926,25689
08cyanamide,1024,16,2x2x2,64.0,8,8.0,Cyanamide,52,349,4198,55984
09cytosine,504,42,1x1x3,12.0,3,4.0,Cytosine,192,1285,15430,205738
10ethylcarbamate,576,36,2x2x2,16.0,8,2.0,Ethylcarbamate,156,1044,12528,167046
11formamide,864,18,3x2x2,48.0,12,4.0,Formamide,54,366,4395,58600
12imidazole,832,26,2x2x2,32.0,8,4.0,Imidazole,114,764,9178,122386
13naphtalene,768,48,2x2x2,16.0,8,2.0,Naphtalene,394,2627,31534,420464
14oxalic_acid_alpha,1088,34,2x2x2,32.0,8,4.0,Oxalic Acid Alpha,276,1845,22146,295291
15oxalic_acid_beta,816,34,2x2x3,24.0,12,2.0,Oxalic Acid Beta,199,1329,15952,212701
16pyrazine,720,30,2x2x3,24.0,12,2.0,Pyrazine,132,886,10636,141823
17pyrazole,832,26,2x1x2,32.0,4,8.0,Pyrazole,114,764,9178,122386
18triazine,720,30,1x2x2,24.0,4,6.0,Triazine,132,886,10636,141823
19trioxane,864,36,1x2x2,24.0,4,6.0,Trioxane,240,1601,19214,256190
20uracil,504,42,1x1x3,12.0,3,4.0,Uracil,192,1285,15430,205738
21urea,384,24,2x2x2,16.0,8,2.0,Urea,43,290,3481,46414
22Hexamine,448,56,1x1x1,8.0,1,8.0,Hexamine,328,2191,26293,350579
23Succinic_acid,368,46,1x1x1,8.0,1,8.0,Succinic Acid,177,1182,14195,189276

### Overall comparison to periodic HF and DMC

In [26]:
# Compute the cost for periodic QE calculations

x23_method_cost_dict = {y: {'HF': 0 , 'DFT (GGA)': 0, 'CCSD(T) [low]': 0, 'CCSD(T) [moderate]': 0 , 'CCSD(T) [high]': 0, 'DMC [4]': 0 ,'DMC [2]': 0, 'DMC [1]': 0} for y in list(range(1,24))}

# QE data is in PRL order
for x23_idx in range(1,24):
    x23_method_cost_dict[x23_idx]['HF'] = get_qe_walltime(f'Data/X23/HF/QE_cost/hybrid/{prl_to_x23_order[x23_idx]:02d}/solid/pw.out.gz')*192 + get_qe_walltime(f'Data/X23/HF/QE_cost/hybrid/{prl_to_x23_order[x23_idx]:02d}/molecule/pw.out.gz')*192
    x23_method_cost_dict[x23_idx]['DFT (GGA)'] = get_qe_walltime(f'Data/X23/HF/QE_cost/GGA/{prl_to_x23_order[x23_idx]:02d}/solid/pw.out.gz')*192 + get_qe_walltime(f'Data/X23/HF/QE_cost/GGA/{prl_to_x23_order[x23_idx]:02d}/molecule/pw.out.gz')*192

    x23_method_cost_dict[x23_idx]['CCSD(T) [low]'] = x23_cutoff_2b_cpuh_dict_filtered[x23_idx]['6.5'] + x23_cutoff_3b_cpuh_dict_filtered[x23_idx][100]
    x23_method_cost_dict[x23_idx]['CCSD(T) [moderate]'] = x23_cutoff_2b_cpuh_dict_filtered[x23_idx]['9.0'] + x23_cutoff_3b_cpuh_dict_filtered[x23_idx][200]
    x23_method_cost_dict[x23_idx]['CCSD(T) [high]'] = x23_cutoff_2b_cpuh_dict_filtered[x23_idx]['12.0'] + x23_cutoff_3b_cpuh_dict_filtered[x23_idx][300]

dmc_dict_prl_labels = list(dmc_cost_dict.keys())

# DMC data is in PRL order and given 1sigma error bars, we want 2sigma error bars for 95% confidence interval
for x23_idx, x23_idx_label in enumerate(dmc_cost_dict.keys()):
    # Cost for 1 kJ/mol std
    x23_method_cost_dict[x23_idx+1]['DMC [1]'] = dmc_cost_dict[dmc_dict_prl_labels[prl_to_x23_order[x23_idx+1]-1]]['DMC[0.5]']
    # Cost for 2 kJ/mol std
    x23_method_cost_dict[x23_idx+1]['DMC [2]'] = dmc_cost_dict[dmc_dict_prl_labels[prl_to_x23_order[x23_idx+1]-1]]['DMC[1]']
    # Cost for 4 kJ/mol std
    x23_method_cost_dict[x23_idx+1]['DMC [4]'] = dmc_cost_dict[dmc_dict_prl_labels[prl_to_x23_order[x23_idx+1]-1]]['DMC[2]']

# Add a row for the mean
x23_method_cost_dict['Mean'] = {method: np.mean([x23_method_cost_dict[idx][method] for idx in range(1,24)]) for method in x23_method_cost_dict[1].keys()}

# Convert to dataframe
x23_method_cost_df = pd.DataFrame.from_dict(x23_method_cost_dict,orient='index')
x23_method_cost_df.index = [f"{x23_labels[idx]}" for idx in range(1,24)] + ['Mean']
# Round to integer
x23_method_cost_df = x23_method_cost_df.round(0).astype(int)

display(x23_method_cost_df)
# Convert to latex
convert_df_to_latex_input(
    df = x23_method_cost_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_method_cost",
    caption = r"Estimated computational cost (in CPUh) for the different methods used to compute the lattice energies of the X23 dataset. The LNO-MBE-CCSD(T) costs are given for the low (2B cutoff of $6.5\,$\AA{} and 3B cutoff of $100\,$\AA{}$^3$), moderate (2B cutoff of $9.0\,$\AA{} and 3B cutoff of $200\,$\AA{}$^3$) and high (2B cutoff of $12.0\,$\AA{} and 3B cutoff of $300\,$\AA{}$^3$) models. The DMC costs are estimated for a standard deviation of 2$\sigma$ of 1, 2 and 4 kJ/mol, respectively.",
    replace_input= {
        "[t]": "[c]"
    },
    index = True,
    rotate_column_header=True,
    filename = "Tables/SI_Table-X23_Method_Costs.tex")

np.save('Data/X23/X23_Costs.npy', x23_method_cost_dict)

,HF,DFT (GGA),CCSD(T) [low],CCSD(T) [moderate],CCSD(T) [high],DMC [4],DMC [2],DMC [1]
"1,4-cyclohexanedione",1297,3,800,2276,7824,1984,23818,317584
Acetic Acid,1684,4,139,878,2195,433,5198,69307
Adamantane,365,3,624,1795,5585,4334,52013,693512
Ammonia,93,1,50,193,411,18,219,2925
Anthracene,2496,6,2822,6586,21941,2065,24791,330552
Benzene,1201,4,241,1000,2802,1221,14657,195439
CO$_2$,162,1,24,116,277,160,1926,25689
Cyanamide,1993,5,137,465,1149,349,4198,55984
Cytosine,2778,6,754,5566,10764,1285,15430,205738
Ethyl carbamate,1048,3,484,1604,4160,1044,12528,167046
Formamide,1149,3,180,662,1505,366,4395,58600
Hexamine,1104,4,548,1045,2637,2191,26293,350579
Imidazole,1308,4,274,1575,3242,764,9178,122386
Naphthalene,1148,4,1238,3758,11119,2627,31534,420464
Oxalic Acid $\alpha$,2411,3,128,1154,2263,1845,22146,295291
Oxalic Acid $\beta$,1677,2,293,1351,2495,1329,15952,212701
Pyrazine,798,3,212,991,1750,886,10636,141823
Pyrazole,6483,8,409,2836,5588,764,9178,122386
Succinic Acid,916,5,356,1050,4786,1182,14195,189276
Triazine,6337,5,238,640,1025,886,10636,141823
Trioxane,11773,10,194,1135,1830,1601,19214,256190
Uracil,7081,9,1297,6717,13454,1285,15430,205738
Urea,170,2,108,456,736,290,3481,46414
Mean,2412,4,502,1906,4762,1257,15089,201193

## Convergence tests on Benzene

### DeltaMP2 vs LAF vs Canonical approach

In [27]:
# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results

for x23_idx in [6]:
    benzene_basis_elatt_dict = {x:{} for x in ['CCSD(T) tight','CCSD(T) vtight','CCSD(T) LAF', 'CCSD(T) Final']}
    for method in ['CCSD(T) tight','CCSD(T) vtight','CCSD(T) LAF', 'CCSD(T) Final']:
        method_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}

        with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_1b.db') as db1_1:
            with connect(f'Data/cWFT_Convergence/benzene_1b_basis.db') as db1:
                monomer_ene_list = []
                for i in range(2):
                    row = db1.get(id=i+1)
                    row_1 = db1_1.get(id=i+1)
                    if method == 'CCSD(T) LAF':
                        monomer_ene_list += [row.data[f'CCSD(T) LAF CBS']]
                    elif method == 'CCSD(T) Final':
                        monomer_ene_list += [row.data[f'CCSD(T) Canonical QZ'] + row_1.data['MP2 Canonical CBS'] - row_1.data['MP2 Canonical QZ']]
                    elif method == 'CCSD(T) tight':
                        monomer_ene_list += [row.data[f'CCSD(T) tight CBS']]
                    elif method == 'CCSD(T) vtight':
                        monomer_ene_list += [row.data[f'CCSD(T) vtight CBS']]
                        
                method_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_2b.db') as db2_1:
            with connect(f'Data/cWFT_Convergence/benzene_2b_basis.db') as db2:
                elatt_cwft = 0
                for i in range(len(db2)):
                    row = db2.get(id=i+1)
                    row_1 = db2_1.get(id=i+1)
                    if method == 'CCSD(T) LAF':
                        elatt_cwft += row.data[f'CCSD(T) LAF CBS']*(row.data['count'])
                    elif method == 'CCSD(T) Final':
                        elatt_cwft += (row.data[f'CCSD(T) Canonical TZ'] + row_1.data['MP2 Canonical CBS'] - row_1.data['MP2 Canonical TZ'])*(row.data['count'])
                    elif method == 'CCSD(T) tight':
                        elatt_cwft += row.data[f'CCSD(T) tight CBS']*(row.data['count'])
                    elif method == 'CCSD(T) vtight':
                        elatt_cwft += row.data[f'CCSD(T) vtight CBS']*(row.data['count'])

                method_elatt_dict['2B'] = elatt_cwft

        with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_3b.db') as db3_1:
            with connect(f'Data/cWFT_Convergence/benzene_3b_basis.db') as db3:
                elatt_cwft = 0
                for i in range(len(db3)):
                    row = db3.get(id=i+1)
                    row_1 = db3_1.get(id=i+1)
                    if method == 'CCSD(T) LAF':
                        elatt_cwft += row.data[f'CCSD(T) LAF CBS']*(row.data['count'])
                    elif method == 'CCSD(T) Final':
                        elatt_cwft += (row.data[f'CCSD(T) Canonical DZ'] + row_1.data['MP2 Canonical CBS'] - row_1.data['MP2 Canonical DZ'])*(row.data['count'])
                    elif method == 'CCSD(T) tight':
                        elatt_cwft += row.data[f'CCSD(T) tight CBS']*(row.data['count'])
                    elif method == 'CCSD(T) vtight':
                        elatt_cwft += row.data[f'CCSD(T) vtight CBS']*(row.data['count'])
                method_elatt_dict['3B'] = elatt_cwft
        method_elatt_dict['Total'] = method_elatt_dict['1B'] + method_elatt_dict['2B'] + method_elatt_dict['3B']
        benzene_basis_elatt_dict[method] = method_elatt_dict.copy()

In [28]:
# Benzene LNO convergence table

benzene_lno_conv_df = pd.DataFrame.from_dict(
    {
        'tight': {key: value / kjmol for key,value in benzene_basis_elatt_dict['CCSD(T) tight'].items()},
        'vtight': {key: value / kjmol for key,value in benzene_basis_elatt_dict['CCSD(T) vtight'].items()},
        'LAF': {key: value / kjmol for key,value in benzene_basis_elatt_dict['CCSD(T) LAF'].items()},
        'DeltaMP2': {key: value / kjmol for key,value in x23_final_corr_elatt_dict[6]['CCSD(T)'].items()},
        'Canonical': {key: value / kjmol for key,value in benzene_basis_elatt_dict['CCSD(T) Final'].items()}
    }, orient='index')

# Round to 1 d.p.
benzene_lno_conv_df = benzene_lno_conv_df.round(1)

display(benzene_lno_conv_df)

# Convert to LaTeX table
convert_df_to_latex_input(
    df = benzene_lno_conv_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_benzene_lno_conv",
    caption = r"Convergence of the LNO-MBE-CCSD(T) lattice energy of benzene with respect to the LNO threshold, compared to the canonical result. All values are in kJ/mol.",
    replace_input= {'DeltaMP2':r'Composite',
        r'vtight ': r'{\tt vTight} ',
        r'tight ': r'{\tt Tight} ',
        r'normal ': r'{\tt Normal} ',
        r'loose ': r'{\tt Loose} '},
    float_fmt="%.1f",
    filename = "Tables/SI_Table-X23_Benzene_LNO_Approach_Convergence.tex")

            1B    2B   3B  Total
tight     -1.3 -80.0  3.6  -77.7
vtight    -1.3 -79.3  5.8  -74.8
LAF       -1.3 -78.9  6.8  -73.4
DeltaMP2  -1.3 -79.6  5.3  -75.7
Canonical -1.3 -79.0  4.7  -75.6

### LNO thresholds

In [29]:
# Benzene LNO threshold convergence

benzene_conv_lno_dict = {(y,x): 0 for y in ['2B','3B'] for x in ['tight','vtight','LAF','Canonical'] }

with connect('Data/cWFT_Convergence/benzene_2b_lno_conv.db') as db2:
    for i in range(1,len(db2)+1):
        row = db2.get(id=i)
        benzene_conv_lno_dict[('2B','tight')] += row.data['LNO-CCSD(T) tight aug-cc-pVDZ']*row.data['count']/ (4*kjmol)
        benzene_conv_lno_dict[('2B','vtight')] += row.data['LNO-CCSD(T) vtight aug-cc-pVDZ']*row.data['count']/(4*kjmol)
        benzene_conv_lno_dict[('2B','LAF')] += (row.data['LNO-CCSD(T) vtight aug-cc-pVDZ'] + 0.5*(row.data['LNO-CCSD(T) vtight aug-cc-pVDZ'] - row.data['LNO-CCSD(T) tight aug-cc-pVDZ'])) *row.data['count']/(4*kjmol)
        benzene_conv_lno_dict[('2B','Canonical')] += row.data['DF-CCSD(T) aug-cc-pVDZ']*row.data['count']/(4*kjmol)

with connect('Data/cWFT_Convergence/benzene_3b_lno_conv.db') as db3:
    for i in range(1,len(db3)+1):
        row = db3.get(id=i)
        benzene_conv_lno_dict[('3B','tight')] += row.data['LNO-CCSD(T) tight aug-cc-pVDZ']*row.data['count']/(4*kjmol)
        benzene_conv_lno_dict[('3B','vtight')] += row.data['LNO-CCSD(T) vtight aug-cc-pVDZ']*row.data['count']/(4*kjmol)
        benzene_conv_lno_dict[('3B','LAF')] += (row.data['LNO-CCSD(T) vtight aug-cc-pVDZ'] + 0.5*(row.data['LNO-CCSD(T) vtight aug-cc-pVDZ'] - row.data['LNO-CCSD(T) tight aug-cc-pVDZ'])) *row.data['count']/(4*kjmol)
        benzene_conv_lno_dict[('3B','Canonical')] += row.data['DF-CCSD(T) aug-cc-pVDZ']*row.data['count']/(4*kjmol)

# Convert to DataFrame
benzene_conv_lno_df = pd.DataFrame(benzene_conv_lno_dict, index=['CCSD(T) aug-cc-pVDZ (kJ/mol)'])
# To nearest 1 d.p.
benzene_conv_lno_df = benzene_conv_lno_df.round(1)
# Write to latex table
display(benzene_conv_lno_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = benzene_conv_lno_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:benzene_lno_conv",
    caption = r"Convergence of 2B and 3B contributions, for the benzene molecular crystal in the X23 dataset, with LNO thresholds: {\tt Tight}, {\tt vTight} and extrapolated locality approximation free (LAF) for aug-cc-pVDZ basis set",
    float_fmt="%.1f",
    replace_input={
        r'{3B} \\': r'{3B} \\ \cmidrule(lr){2-5} \cmidrule(lr){6-9}',
        r' vtight ': r' {\tt vTight} ',
        r' tight ': r' {\tt Tight} ',
        r' normal ': r' {\tt Normal} ',
        r' loose ': r' {\tt Loose} ',
    },
    filename = "Tables/SI_Table-Benzene_LNO_Conv_Effect.tex")

                                2B                           3B              \
                             tight vtight   LAF Canonical tight vtight  LAF
CCSD(T) aug-cc-pVDZ (kJ/mol) -70.7  -70.2 -70.0     -70.0   4.7    4.6  4.5


                             Canonical
CCSD(T) aug-cc-pVDZ (kJ/mol)       5.1

### Basis set

In [30]:
# Benzene basis set convergence
benzene_basis_conv_dict = {x:0 for x in [('2B','TZ'), ('2B','QZ'), ('2B','CBS'), ('3B','DZ'), ('3B','TZ'), ('3B','CBS')]}
for x23_idx in [6]:
    with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_2b.db') as db2:
        for i in range(len(db2)):
            row = db2.get(id=i+1)
            benzene_basis_conv_dict[('2B','TZ')] += row.data['MP2 Canonical TZ']*(row.data['count'])/(4*kjmol)
            benzene_basis_conv_dict[('2B','QZ')] += row.data['MP2 Canonical QZ']*(row.data['count'])/(4*kjmol)
            benzene_basis_conv_dict[('2B','CBS')] += row.data['MP2 Canonical CBS']*(row.data['count'])/(4*kjmol)

    with connect(f'Data/X23/cWFT/x23_{x23_idx:02d}_3b.db') as db3:
        for i in range(len(db3)):
            row = db3.get(id=i+1)
            benzene_basis_conv_dict[('3B','DZ')] += row.data['MP2 Canonical DZ']*(row.data['count'])/(4*kjmol)
            benzene_basis_conv_dict[('3B','TZ')] += row.data['MP2 Canonical TZ']*(row.data['count'])/(4*kjmol)
            benzene_basis_conv_dict[('3B','CBS')] += row.data['MP2 Canonical CBS']*(row.data['count'])/(4*kjmol)

# Convert to DataFrame
benzene_basis_conv_df = pd.DataFrame(benzene_basis_conv_dict, index=['MP2 (kJ/mol)']).T
# To nearest 1 d.p.
benzene_basis_conv_df = benzene_basis_conv_df.round(1)
# Write to latex table
display(benzene_basis_conv_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = benzene_basis_conv_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:benzene_basis_conv",
    caption = r"Convergence of 2B with basis set: aug-cc-pVTZ, aug-cc-pVQZ and CBS(aug-cc-pVTZ/aug-cc-pVQZ) as well as 3B with basis set: aug-cc-pVDZ, aug-cc-pVTZ and CBS(aug-cc-pVDZ/aug-cc-pVTZ) for the MP2 level of theory.",
    replace_input= {"lr":"lrr",r'[t]': r'[c]',},
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Benzene_Basis_Conv_Effect.tex")

        MP2 (kJ/mol)
2B TZ          -22.5
   QZ          -22.9
   CBS         -23.2
3B DZ            0.5
   TZ            0.5
   CBS           0.5

# Lattice and relative energies of ICE13

## cWFT MBE analysis

In [31]:
# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results

ice13_systems = {
    1: 'Ih',
    2: 'II',
    3: 'III',
    4: 'IV',
    6: 'VI',
    7: 'VII',
    8: 'VIII',
    9: 'IX',
    11: 'XI',
    13: 'XIII',
    14: 'XIV',
    15: 'XV',
    17: 'XVII'
}

ice13_methods_dict = {
    'AFsupercell': ['MP2 LAF', 'CCSD(T) LAF'],
    'AFcell': ['MP2 Canonical', 'CCSD Canonical', 'CCSD(T) LAF','CCSD(T) Canonical', 'CCSD(T) DeltaMP2'],
    'Unitcell': ['MP2 Canonical','CCSD Canonical', 'CCSD(T) LAF','CCSD(T) Canonical', 'CCSD(T) DeltaMP2']
}

ice13_final_corr_elatt_dict = {
    'AFsupercell': {y:{x:{} for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF']} for y in [1,3,4,6,7,17]},
    'AFcell': {y:{x:{} for x in ['MP2 Canonical', 'CCSD Canonical' 'CCSD(T) LAF','CCSD(T) Canonical', 'CCSD(T) DeltaMP2']} for y in [1,3,4,7,17]},
    'Unitcell': {y:{x:{} for x in ['MP2 Canonical', 'CCSD Canonical', 'CCSD(T) LAF','CCSD(T) Canonical', 'CCSD(T) DeltaMP2']} for y in ice13_systems.keys()}
}

for cell_size in ['AFsupercell','AFcell','Unitcell']:
    for ice13_idx in ice13_final_corr_elatt_dict[cell_size].keys():
        system_all_methods_elatt_dict = {x:{} for x in ice13_methods_dict[cell_size]}
        for method in ice13_methods_dict[cell_size]:
            method_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
            with connect(f'Data/ICE13/cWFT/{cell_size}/ice13_{ice13_idx:02d}_1b.db') as db1:
                num_monomers = len(db1) - 1
                monomer_ene_list = []
                for i in range(len(db1)):
                    row = db1.get(id=i+1)
                    if 'DeltaMP2' in method:
                        monomer_ene_list += [row.data['CCSD(T) Canonical QZ'] - row.data['MP2 Canonical QZ'] + row.data['MP2 Canonical CBS']]
                    else:
                        monomer_ene_list += [row.data[f'{method} CBS']]
                method_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

            with connect(f'Data/ICE13/cWFT/{cell_size}/ice13_{ice13_idx:02d}_2b.db') as db2:
                elatt_cwft = 0
                for i in range(len(db2)):
                    row = db2.get(id=i+1)
                    if 'DeltaMP2' in method:
                        elatt_cwft += (row.data['CCSD(T) Canonical TZ'] - row.data['MP2 Canonical TZ'] + row.data['MP2 Canonical CBS'])*(row.data['count'])
                    else:
                        elatt_cwft += row.data[f'{method} CBS']*(row.data['count'])
                method_elatt_dict['2B'] = elatt_cwft/num_monomers

            if ice13_idx == 7 and cell_size == 'AFsupercell':
                with connect(f'Data/ICE13/cWFT/{cell_size}/ice13_{ice13_idx:02d}_3b_01.db') as db3_1:
                    elatt_cwft = 0
                    for i in range(len(db3_1)):
                        row = db3_1.get(id=i+1)
                        if 'DeltaMP2' in method:
                            elatt_cwft += (row.data['CCSD(T) Canonical DZ'] - row.data['MP2 Canonical DZ'] + row.data['MP2 Canonical CBS'])*(row.data['count'])
                        else:
                            elatt_cwft += row.data[f'{method} CBS']*(row.data['count'])
                with connect(f'Data/ICE13/cWFT/{cell_size}/ice13_{ice13_idx:02d}_3b_02.db') as db3_2:
                    for i in range(len(db3_2)):
                        row = db3_2.get(id=i+1)
                        if 'DeltaMP2' in method:
                            elatt_cwft += (row.data['CCSD(T) Canonical DZ'] - row.data['MP2 Canonical DZ'] + row.data['MP2 Canonical CBS'])*(row.data['count'])
                        else:
                            elatt_cwft += row.data[f'{method} CBS']*(row.data['count'])
            else:
                with connect(f'Data/ICE13/cWFT/{cell_size}/ice13_{ice13_idx:02d}_3b.db') as db3:
                    elatt_cwft = 0
                    for i in range(len(db3)):
                        row = db3.get(id=i+1)
                        if 'DeltaMP2' in method:
                            elatt_cwft += (row.data['CCSD(T) Canonical DZ'] - row.data['MP2 Canonical DZ'] + row.data['MP2 Canonical CBS'])*(row.data['count'])
                        else:
                            elatt_cwft += row.data[f'{method} CBS']*(row.data['count'])
            method_elatt_dict['3B'] = elatt_cwft/num_monomers
            method_elatt_dict['Total'] = method_elatt_dict['1B'] + method_elatt_dict['2B'] + method_elatt_dict['3B']
            system_all_methods_elatt_dict[method] = method_elatt_dict.copy()

        ice13_final_corr_elatt_dict[cell_size][ice13_idx] = system_all_methods_elatt_dict

### DeltaMP2 (or Composite), LAF and Canonical approaches

In [32]:
ice13_final_corr_elatt_dict_unitcell = {}
ice13_final_corr_elatt_dict_mediumcell = {}
for ice13_idx in ice13_final_corr_elatt_dict['AFcell']:
    ice13_final_corr_elatt_dict_mediumcell[(ice13_systems[ice13_idx])] = {(mbe_type,method.split()[1]): ice13_final_corr_elatt_dict['AFcell'][ice13_idx][method][mbe_type] / kjmol for mbe_type in ['1B','2B','3B','Total'] for method in ['CCSD(T) Canonical','CCSD(T) LAF','CCSD(T) DeltaMP2'] }

for ice13_idx in ice13_final_corr_elatt_dict['Unitcell']:
    if ice13_idx == 7:
        continue
    # for mbe_type in ['1B','2B','3B','Total']:
    ice13_final_corr_elatt_dict_unitcell[(ice13_systems[ice13_idx])] = {(mbe_type,method.split()[1]): ice13_final_corr_elatt_dict['Unitcell'][ice13_idx][method][mbe_type] / kjmol for mbe_type in ['1B','2B','3B','Total'] for method in ['CCSD(T) Canonical','CCSD(T) LAF','CCSD(T) DeltaMP2'] }


# Add MAD row
ice13_final_corr_elatt_dict_unitcell['MAD'] = {}
for mbe_type in ['1B','2B','3B','Total']:
    for method in ['CCSD(T) Canonical','CCSD(T) LAF','CCSD(T) DeltaMP2']:
        ice13_final_corr_elatt_dict_unitcell['MAD'][(mbe_type,method.split()[1])] = np.mean([abs(ice13_final_corr_elatt_dict_unitcell[x][(mbe_type,method.split()[1])] - ice13_final_corr_elatt_dict_unitcell[x][(mbe_type,'Canonical')]) for x in ice13_final_corr_elatt_dict_unitcell.keys() if x != 'MAD'])
ice13_final_corr_elatt_dict_mediumcell['MAD'] = {}
for mbe_type in ['1B','2B','3B','Total']:
    for method in ['CCSD(T) Canonical','CCSD(T) LAF','CCSD(T) DeltaMP2']:
        ice13_final_corr_elatt_dict_mediumcell['MAD'][(mbe_type,method.split()[1])] = np.mean([abs(ice13_final_corr_elatt_dict_mediumcell[x][(mbe_type,method.split()[1])] - ice13_final_corr_elatt_dict_mediumcell[x][(mbe_type,'Canonical')]) for x in ice13_final_corr_elatt_dict_mediumcell.keys() if x != 'MAD'])


methods_df = pd.DataFrame(ice13_final_corr_elatt_dict_unitcell).T
# To nearest 1 d.p.
methods_df = methods_df.round(1)
# Write to latex table
display(methods_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = methods_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:canonical_cheaper",
    caption = r"Comparison of various approaches [Canonical (Can.), LAF and Composite (Comp.) described in the text] for computing the lattice energy of several ice phases in their small-sized unit cells.",
    replace_input= {
        'DeltaMP2':r'Comp.',
        r'{Total} \\': r'{Total} \\ \cmidrule(lr){2-4} \cmidrule(lr){5-7} \cmidrule(lr){8-10} \cmidrule(lr){11-13}',
        r'MAD': r'\midrule MAD',
        r'Canonical' : r'Can.'
        },
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Unitcell_Canonical_Cheaper.tex")

methods_df_medium = pd.DataFrame(ice13_final_corr_elatt_dict_mediumcell).T
# To nearest 1 d.p.
methods_df_medium = methods_df_medium.round(1)
# Write to latex table
display(methods_df_medium)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = methods_df_medium,
    start_input = '\\begin{table}[h]\n',
    label = "tab:canonical_cheaper_medium",
    caption = r"Comparison of various approaches [Canonical (Can.), LAF and Composite (Comp.) described in the text] for computing the lattice energy of several ice phases in their medium-sized unit cells.",
    replace_input= {
        'DeltaMP2':r'Comp.',
        r'{Total} \\': r'{Total} \\ \cmidrule(lr){2-4} \cmidrule(lr){5-7} \cmidrule(lr){8-10} \cmidrule(lr){11-13}',
        r'MAD': r'\midrule MAD',
        r'Canonical' : r'Can.'
    },
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Mediumcell_Canonical_Cheaper.tex")

            1B                      2B                       3B                \
     Canonical  LAF DeltaMP2 Canonical   LAF DeltaMP2 Canonical  LAF DeltaMP2
Ih        -8.0 -8.0     -8.1     -24.0 -24.0    -23.7       0.1  0.4      0.1
II        -7.1 -7.1     -7.2     -26.7 -26.5    -26.4       1.7  1.8      1.8
III       -8.0 -8.0     -8.1     -26.0 -25.7    -25.6       0.7  0.8      0.7
IV        -7.1 -7.1     -7.1     -27.6 -27.4    -27.3       1.5  1.5      1.5
VI        -6.8 -6.8     -6.8     -29.0 -28.8    -28.7       1.9  2.0      2.0
VIII      -5.3 -5.3     -5.3     -31.0 -30.9    -30.7       2.5  1.9      2.6
IX        -7.5 -7.5     -7.6     -25.1 -24.8    -24.8       1.1  0.6      1.1
XI        -8.6 -8.6     -8.6     -24.6 -24.6    -24.2       0.0 -0.0      0.0
XIII      -6.9 -6.9     -6.9     -27.0 -26.7    -26.7       1.5  1.3      1.5
XIV       -6.6 -6.6     -6.7     -28.1 -27.7    -27.8       1.9  1.8      1.9
XV        -6.5 -6.5     -6.6     -28.4 -28.2    -28.1       1.9  1.8      1.9
XVII      -8.4 -8.4     -8.4     -23.5 -23.5    -23.1       0.3  0.4      0.3
MAD        0.0  0.0      0.0       0.0   0.2      0.3       0.0  0.2      0.0

         Total
     Canonical   LAF DeltaMP2
Ih       -31.9 -31.6    -31.7
II       -32.1 -31.8    -31.8
III      -33.3 -32.9    -33.0
IV       -33.2 -33.0    -32.9
VI       -33.8 -33.5    -33.5
VIII     -33.8 -34.3    -33.4
IX       -31.6 -31.7    -31.3
XI       -33.1 -33.2    -32.8
XIII     -32.4 -32.3    -32.1
XIV      -32.9 -32.6    -32.5
XV       -33.1 -33.0    -32.8
XVII     -31.6 -31.5    -31.3
MAD        0.0   0.3      0.3

            1B                      2B                       3B                \
     Canonical  LAF DeltaMP2 Canonical   LAF DeltaMP2 Canonical  LAF DeltaMP2
Ih        -8.6 -8.6     -8.6     -23.8 -23.9    -23.4       0.1  0.4      0.1
III       -7.5 -7.5     -7.6     -25.5 -25.2    -25.1       0.6  0.8      0.6
IV        -7.0 -7.0     -7.0     -27.3 -27.0    -27.0       1.3  1.1      1.3
VII       -5.6 -5.6     -5.6     -31.8 -31.7    -31.5       3.2  3.1      3.2
XVII      -8.4 -8.4     -8.4     -23.4 -23.5    -23.0       0.2  0.4      0.2
MAD        0.0  0.0      0.0       0.0   0.2      0.3       0.0  0.2      0.0

         Total
     Canonical   LAF DeltaMP2
Ih       -32.2 -32.0    -31.9
III      -32.4 -31.9    -32.1
IV       -33.0 -32.9    -32.7
VII      -34.2 -34.2    -33.9
XVII     -31.5 -31.5    -31.2
MAD        0.0   0.2      0.3

## Periodic HF analysis

In [ ]:
# Analyse periodic HF calculations
ice13_final_hf_elatt_dict = {
    'AFsupercell': {y:0 for y in [1,3,4,6,7,17]},
    'AFcell': {y:0 for y in [1,3,4,7,17]},
    'Unitcell': {y:0 for y in ice13_systems.keys()}
}

# The overall lattice energy of the monomer is calculated from the HF calculations
ice13_final_elatt_dict = {
    'AFsupercell': {y:0 for y in [1,3,4,6,7,17]},
    'AFcell': {y:0 for y in [1,3,4,7,17]},
    'Unitcell': {y:0 for y in ice13_systems.keys()},
    'Final': {y:0 for y in ice13_systems.keys()},
    'Final CCSD': {y:0 for y in ice13_systems.keys()},
    'Final MP2': {y:0 for y in ice13_systems.keys()}
}

for cell_size in ['AFcell','Unitcell','AFsupercell']:
    molecule = read(f'Data/ICE13/HF/Molecule/VASP_Hard_Default/OUTCAR_HF.gz')
    molecule_ene = []
    for calc_type in ['VASP_Hard_Default','VASP_Std_Default','VASP_Std_High']:
        molecule_ene += [get_vasp_energy(f'Data/ICE13/HF/Molecule/{calc_type}/OUTCAR_HF.gz')]

    for ice13_idx in ice13_final_hf_elatt_dict[cell_size].keys():
        solid = read(f'Data/ICE13/HF/{cell_size}/VASP_Hard_Default/{ice13_idx:02d}/OUTCAR_HF.gz')
        num_monomers = int(len(solid)/len(molecule))
        solid_ene = []
        for calc_type in ['VASP_Hard_Default','VASP_Std_Default','VASP_Std_High']:
            solid_ene += [get_vasp_energy(f'Data/ICE13/HF/{cell_size}/{calc_type}/{ice13_idx:02d}/OUTCAR_HF.gz')]

        elatt_ene = np.array(solid_ene)/num_monomers - molecule_ene
        elatt = (elatt_ene[0] + elatt_ene[2] - elatt_ene[1])*1000
        ice13_final_hf_elatt_dict[cell_size][ice13_idx] = elatt


for cell_size in ['AFsupercell','AFcell','Unitcell']:
    for ice13_idx in ice13_final_corr_elatt_dict[cell_size].keys():
        if cell_size == 'AFsupercell':
            ice13_final_elatt_dict[cell_size][ice13_idx] = (ice13_final_hf_elatt_dict['AFsupercell'][ice13_idx] + ice13_final_corr_elatt_dict[cell_size][ice13_idx]['CCSD(T) LAF']['Total'])/kjmol
        else:
            ice13_final_elatt_dict[cell_size][ice13_idx] = (ice13_final_hf_elatt_dict[cell_size][ice13_idx] + ice13_final_corr_elatt_dict[cell_size][ice13_idx]['CCSD(T) Canonical']['Total'])/kjmol

# Final lattice energies
for ice13_idx in ice13_final_elatt_dict['Final'].keys():
    if ice13_idx == 7:
        ice13_final_elatt_dict['Final'][ice13_idx] = ice13_final_elatt_dict['AFcell'][ice13_idx]
        ice13_final_elatt_dict['Final CCSD'][ice13_idx] = (ice13_final_hf_elatt_dict['AFcell'][ice13_idx] + ice13_final_corr_elatt_dict['AFcell'][ice13_idx]['CCSD Canonical']['Total'])/kjmol
        ice13_final_elatt_dict['Final MP2'][ice13_idx] = (ice13_final_hf_elatt_dict['AFcell'][ice13_idx] + ice13_final_corr_elatt_dict['AFcell'][ice13_idx]['MP2 Canonical']['Total'])/kjmol
    else:
        ice13_final_elatt_dict['Final'][ice13_idx] = ice13_final_elatt_dict['Unitcell'][ice13_idx]
        ice13_final_elatt_dict['Final CCSD'][ice13_idx] = (ice13_final_hf_elatt_dict['Unitcell'][ice13_idx] + ice13_final_corr_elatt_dict['Unitcell'][ice13_idx]['CCSD Canonical']['Total'])/kjmol
        ice13_final_elatt_dict['Final MP2'][ice13_idx] = (ice13_final_hf_elatt_dict['Unitcell'][ice13_idx] + ice13_final_corr_elatt_dict['Unitcell'][ice13_idx]['MP2 Canonical']['Total'])/kjmol

## Literature (DMC and experiment) analysis

In [34]:
ice13_dmc_raw_elatt = [-59.45,-59.14,-58.2,-55.62,-57.67,-54.46,-55.22,-58.85,-59.29,-57.33,-57.75,-57.71,-57.7]
ice13_dmc_raw_elatt_errors = [0.07,0.07,0.07,0.07,0.07,0.07,0.08,0.07,0.08,0.07,0.07,0.07,0.08]

ice13_dmc_elatt_dict = {i: [ice13_dmc_raw_elatt[idxi],ice13_dmc_raw_elatt_errors[idxi]] for idxi, i in enumerate(ice13_systems.keys())}

ice13_exp_elatt_dict = {
    1: [-58.87,0.01],
    2: [-58.78,0.9],
    3: [-57.92,0.05],
    6: [-57.24,0.12],
    7: [-54.68,0.23],
    8: [-55.69,1.7],
    9: [-58.45,0.9]
}

ice13_exp_elatt_dict = {
    1: [-58.87,1],
    2: [-58.78,1],
    3: [-57.92,1],
    6: [-57.24,1],
    7: [-54.68,1],
    8: [-55.69,1.7],
    9: [-58.45,1]
}

# Calculate the relative energies
ice13_final_rel_elatt_dict = {
    'AFsupercell': {y:0 for y in [3,4,6,7,17]},
    'AFcell': {y:0 for y in [3,4,7,17]},
    'Unitcell': {y:0 for y in [x for x in ice13_systems][1:]},
    'Final': {y:0 for y in [x for x in ice13_systems][1:]},
    'Final CCSD': {y:0 for y in [x for x in ice13_systems][1:]},
    'Final MP2': {y:0 for y in [x for x in ice13_systems][1:]}
}

dmc_ice13_rel_elatt_dict = {y:[0,0] for y in [x for x in ice13_systems][1:]}
exp_ice13_rel_elatt_dict = {y:[0,0] for y in [x for x in ice13_exp_elatt_dict][1:]}

# Calculate the relative energies relative to Ih (1)
for cell_size in ['AFsupercell','AFcell','Unitcell']:
    for ice13_idx in ice13_final_rel_elatt_dict[cell_size].keys():
        ice13_final_rel_elatt_dict[cell_size][ice13_idx] = ice13_final_elatt_dict[cell_size][ice13_idx] - ice13_final_elatt_dict[cell_size][1]


# Final relative energies
for ice13_idx in ice13_final_rel_elatt_dict['Final'].keys():
    if ice13_idx == 7:
        ice13_final_rel_elatt_dict['Final'][ice13_idx] = ice13_final_rel_elatt_dict['AFcell'][ice13_idx]
        ice13_final_rel_elatt_dict['Final CCSD'][ice13_idx] = ice13_final_elatt_dict['Final CCSD'][ice13_idx] - ice13_final_elatt_dict['Final CCSD'][1]
        ice13_final_rel_elatt_dict['Final MP2'][ice13_idx] = ice13_final_elatt_dict['Final MP2'][ice13_idx] - ice13_final_elatt_dict['Final MP2'][1]
    else:
        ice13_final_rel_elatt_dict['Final'][ice13_idx] = ice13_final_rel_elatt_dict['Unitcell'][ice13_idx]
        ice13_final_rel_elatt_dict['Final CCSD'][ice13_idx] = ice13_final_elatt_dict['Final CCSD'][ice13_idx] - ice13_final_elatt_dict['Final CCSD'][1]
        ice13_final_rel_elatt_dict['Final MP2'][ice13_idx] = ice13_final_elatt_dict['Final MP2'][ice13_idx] - ice13_final_elatt_dict['Final MP2'][1]

for ice13_idx in dmc_ice13_rel_elatt_dict.keys():
    dmc_ice13_rel_elatt_dict[ice13_idx][0] = ice13_dmc_elatt_dict[ice13_idx][0] - ice13_dmc_elatt_dict[1][0]
    dmc_ice13_rel_elatt_dict[ice13_idx][1] = np.sqrt(ice13_dmc_elatt_dict[ice13_idx][1]**2 + ice13_dmc_elatt_dict[1][1]**2)

for ice13_idx in exp_ice13_rel_elatt_dict.keys():
    exp_ice13_rel_elatt_dict[ice13_idx][0] = ice13_exp_elatt_dict[ice13_idx][0] - ice13_exp_elatt_dict[1][0]
    exp_ice13_rel_elatt_dict[ice13_idx][1] = np.sqrt(ice13_exp_elatt_dict[ice13_idx][1]**2 + ice13_exp_elatt_dict[1][1]**2)

## Figure 3 - Final estimates

In [35]:
# Load previous DFT numbers
jcp_dft_ice13_elatt = pd.read_csv('Data/ICE13/DFT/dmc_ice13_dft_jcp.csv', index_col=0)
xc_func_inc_list = ['B3LYP-D4','revPBE0-D3','PBE0-MBD','SCAN+rVV10','optB86b-vdW','rev-vdW-DF2','vdW-DF','revPBE-D3', 'PBE-D3(BJ)']
# Filter index to only xc_func_inc_list
jcp_dft_ice13_elatt = jcp_dft_ice13_elatt[jcp_dft_ice13_elatt.index.isin(xc_func_inc_list)]
fig, axs = plt.subplots(figsize=(6.695,2.3),dpi=1200, constrained_layout=True)

ice_structs = list(ice13_systems.keys())
struct_enumerate = {ice_structs[i]: i*0.8 for  i in range(len(ice_structs))}

axs.set_xticks([x*0.8 for x in list(range(len(ice_structs)))])
axs.set_xticklabels([ice13_systems[x] for x in ice_structs])


# axs.scatter([i*2 + 0.25]*len(dft_no_hads_list), dft_no_hads_list, marker='.', color=color_dict['black'],s=4, alpha=0.5)

for idx_x, x in enumerate(ice13_dmc_elatt_dict.keys()):
    ice_phase = ice13_systems[x]
    dft_elatt_list = jcp_dft_ice13_elatt[ice_phase].values / kjmol
    if idx_x == 0:
        axs.scatter([idx_x*0.8 + 0.1]*len(dft_elatt_list), dft_elatt_list, marker='.', color=color_dict['purple'],s=4, alpha=0.8, label='DFT')
    else:
        axs.scatter([idx_x*0.8 + 0.1]*len(dft_elatt_list), dft_elatt_list, marker='.', color=color_dict['purple'],s=4, alpha=0.6)
    axs.bar(idx_x*0.8 + 0.1, np.ptp(dft_elatt_list),bottom = np.min(dft_elatt_list),width=0.1, color=color_dict['purple'],alpha=0.3)


# axs.errorbar([struct_enumerate[x] for x in ice13_exp_elatt_dict.keys()], [ice13_exp_elatt_dict[x][0] for x in ice13_exp_elatt_dict.keys()], yerr=[ice13_exp_elatt_dict[x][1] if x > 1.0 else 1.0  for x in ice13_exp_elatt_dict.keys()], fmt='x', label='Exp.', color='gray',alpha=0.5,markersize=5)
axs.bar([struct_enumerate[x] - 0.15 for x in ice13_exp_elatt_dict.keys()], [ice13_exp_elatt_dict[x][1]*2 for x in ice13_exp_elatt_dict.keys()],bottom = [ice13_exp_elatt_dict[x][0] - ice13_exp_elatt_dict[x][1] for x in ice13_exp_elatt_dict.keys()],width=0.2, color=color_dict['grey'],alpha=0.7, label='Experiment')

axs.errorbar([struct_enumerate[x] - 0.15 for x in ice13_dmc_elatt_dict.keys()], [ice13_dmc_elatt_dict[x][0] for x in ice13_dmc_elatt_dict.keys()], fmt='x', label='DMC - Unitcell', color='blue',alpha=0.6,markersize=4)  #yerr=[ice13_dmc_elatt_dict[x][1] for x in ice13_dmc_elatt_dict.keys()]

axs.errorbar([struct_enumerate[x] - 0.15 for x in ice13_final_elatt_dict['Unitcell'].keys()], [ice13_final_elatt_dict['Unitcell'][x] for x in ice13_final_elatt_dict['Unitcell'].keys()], fmt='o', label='CCSD(T) [Small cell]', color='red',alpha=0.6,markerfacecolor='none', markersize=4)

axs.errorbar([struct_enumerate[x] - 0.15 for x in ice13_final_elatt_dict['AFcell'].keys()], [ice13_final_elatt_dict['AFcell'][x] for x in ice13_final_elatt_dict['AFcell'].keys()], fmt='^', label='CCSD(T) [Medium cell]', color='red',alpha=0.6, markerfacecolor='none', markersize=4)

axs.errorbar([struct_enumerate[x] - 0.15 for x in ice13_final_elatt_dict['AFsupercell'].keys()], [ice13_final_elatt_dict['AFsupercell'][x] for x in ice13_final_elatt_dict['AFsupercell'].keys()], fmt='s', label='CCSD(T) [Large cell]', color='red',alpha=0.6,markerfacecolor='none', markersize=4)

# Plot final numbers
axs.set_ylabel('Lattice energy (kJ/mol)')
# axs.set_xlabel('Ice Phase')

axs.set_ylim([-72,-48])
axs.grid(axis='x', linestyle='--', alpha=0.5)
axs.set_xlim([-0.4,10.0])

# axs.legend(fontsize=6,ncol=2, loc='lower right')

# Move x-labels to top
axs.xaxis.set_label_position('top')
axs.xaxis.tick_top()

plt.savefig('Figures/MAIN_Figure-ICE13_Comparison.png')

### Relative energy comparison

In [36]:
# Do relative energies
jcp_dft_ice13_elatt = pd.read_csv('Data/ICE13/DFT/dmc_ice13_dft_jcp.csv', index_col=0)

# Subtract rel_jcp_dft_ice13_elatt['Ih'] from all other columns
rel_jcp_dft_ice13_elatt = jcp_dft_ice13_elatt.drop(columns='Ih').subtract(jcp_dft_ice13_elatt['Ih'], axis=0)

fig, axs = plt.subplots(figsize=(6.695,2.3),dpi=1200, constrained_layout=True)

ice_structs = list(ice13_systems.keys())[1:]
struct_enumerate = {ice_structs[i]: i*0.8 for  i in range(len(ice_structs))}

axs.set_xticks([x*0.8 for x in list(range(len(ice_structs)))])
axs.set_xticklabels([ice13_systems[x] for x in ice_structs])


for idx_x, x in enumerate(dmc_ice13_rel_elatt_dict.keys()):
    ice_phase = ice13_systems[x]
    dft_elatt_list = rel_jcp_dft_ice13_elatt[ice_phase].values / kjmol
    if idx_x == 0:
        axs.scatter([idx_x*0.8 + 0.2]*len(dft_elatt_list), dft_elatt_list, marker='.', color=color_dict['green'],s=4, alpha=0.2, label='DFT')
    else:
        axs.scatter([idx_x*0.8 + 0.2]*len(dft_elatt_list), dft_elatt_list, marker='.', color=color_dict['green'],s=4, alpha=0.2)
    axs.bar(idx_x*0.8 + 0.2, np.ptp(dft_elatt_list),bottom = np.min(dft_elatt_list),width=0.1, color=color_dict['green'],alpha=0.1)


# axs.errorbar([struct_enumerate[x] for x in exp_ice13_rel_elatt_dict.keys()], [exp_ice13_rel_elatt_dict[x][0] for x in exp_ice13_rel_elatt_dict.keys()], yerr=[exp_ice13_rel_elatt_dict[x][1] if x > 1.0 else 1.0  for x in exp_ice13_rel_elatt_dict.keys()], fmt='x', label='Exp.', color='gray',alpha=0.5,markersize=5)
axs.bar([struct_enumerate[x] for x in exp_ice13_rel_elatt_dict.keys()], [exp_ice13_rel_elatt_dict[x][1]*2 for x in exp_ice13_rel_elatt_dict.keys()],bottom = [exp_ice13_rel_elatt_dict[x][0] - exp_ice13_rel_elatt_dict[x][1] for x in exp_ice13_rel_elatt_dict.keys()],width=0.2, color=color_dict['grey'],alpha=0.5, label='Experiment')

axs.errorbar([struct_enumerate[x] for x in dmc_ice13_rel_elatt_dict.keys()], [dmc_ice13_rel_elatt_dict[x][0] for x in dmc_ice13_rel_elatt_dict.keys()], fmt='x', label='DMC - Unitcell', color='blue',alpha=0.5,markersize=4)  #yerr=[ice13_dmc_elatt_dict[x][1] for x in ice13_dmc_elatt_dict.keys()]

axs.errorbar([struct_enumerate[x] for x in ice13_final_rel_elatt_dict['Unitcell'].keys()], [ice13_final_rel_elatt_dict['Unitcell'][x] for x in ice13_final_rel_elatt_dict['Unitcell'].keys()], fmt='o', label='CCSD(T) [Small cell]', color='red',alpha=0.5,markerfacecolor='none', markersize=4)

axs.errorbar([struct_enumerate[x] for x in ice13_final_rel_elatt_dict['AFsupercell'].keys()], [ice13_final_rel_elatt_dict['AFsupercell'][x] for x in ice13_final_rel_elatt_dict['AFsupercell'].keys()], fmt='^', label='CCSD(T) [Large cell]', color='red',alpha=0.5,markerfacecolor='none', markersize=4)

axs.errorbar([struct_enumerate[x] for x in ice13_final_rel_elatt_dict['AFcell'].keys()], [ice13_final_rel_elatt_dict['AFcell'][x] for x in ice13_final_rel_elatt_dict['AFcell'].keys()], fmt='s', label='CCSD(T) [Medium cell]', color='red',alpha=0.5, markerfacecolor='none', markersize=4)

# Plot final numbers
axs.set_ylabel('Energy relative to ice Ih (kJ/mol)')
# axs.set_xlabel('Ice Phase')

axs.set_ylim([-5,25])

axs.legend(fontsize=6,ncol=3, loc='upper right')

plt.savefig('Figures/SI_Figure-ICE13_Relative_Energy.png')

### MAD between DMC and CCSD(T)

In [37]:
# Compute MAD between DMC and CCSD(T)
mad_list = []
for ice13_idx in ice13_final_rel_elatt_dict['Final'].keys():
    mad_list += [abs(dmc_ice13_rel_elatt_dict[ice13_idx][0] - ice13_final_rel_elatt_dict['Final'][ice13_idx])]

mad_value = np.mean(mad_list)
print(f'MAD between DMC and CCSD(T): {mad_value:.2f} kJ/mol')

MAD between DMC and CCSD(T): 0.59 kJ/mol

### Raw numbers - Lattice energies

In [38]:
# The final lattice energies
final_table_elatt = {}
for ice13_idx in ice13_final_elatt_dict['Final'].keys():
    final_table_elatt[ice13_idx] = {
        'Ice Phase': ice13_systems[ice13_idx],
        'DMC (Unitcell)': f"{ice13_dmc_elatt_dict[ice13_idx][0]:.1f} ± {ice13_dmc_elatt_dict[ice13_idx][1]:.1f}",
        'Experiment': f"{ice13_exp_elatt_dict[ice13_idx][0]:.1f} ± {ice13_exp_elatt_dict[ice13_idx][1]:.1f}" if ice13_idx in ice13_exp_elatt_dict else 'N/A',
        'CCSD(T) [Small cell]': f"{ice13_final_elatt_dict['Unitcell'][ice13_idx]:.1f}",
        'CCSD(T) [Medium cell]': f"{ice13_final_elatt_dict['AFcell'][ice13_idx]:.1f}" if ice13_idx in ice13_final_elatt_dict['AFcell'] else 'N/A',
        'CCSD(T) [Large cell]': f"{ice13_final_elatt_dict['AFsupercell'][ice13_idx]:.1f}" if ice13_idx in ice13_final_elatt_dict['AFsupercell'] else 'N/A',
        'CCSD(T) [Final]': f"{ice13_final_elatt_dict['Final'][ice13_idx]:.1f}",
        'CCSD [Final]': f"{ice13_final_elatt_dict['Final CCSD'][ice13_idx]:.1f}",
        'MP2 [Final]': f"{ice13_final_elatt_dict['Final MP2'][ice13_idx]:.1f}"
    }
    
# Save final estimates
np.save('Data/ICE13/ICE13_Final_Data.npy', final_table_elatt, allow_pickle=True)

final_elatt_df = pd.DataFrame(final_table_elatt).T

# Add MAD rows
mad_dmc_row_elatt = {
    'Ice Phase': 'MAD (DMC)',
    'DMC (Unitcell)': '',
    'Experiment': '',
    'CCSD(T) [Small cell]': '',
    'CCSD(T) [Medium cell]': '',
    'CCSD(T) [Large cell]': '',
    'CCSD(T) [Final]': round(np.mean([abs(ice13_dmc_elatt_dict[ice13_idx][0] - ice13_final_elatt_dict['Final'][ice13_idx]) for ice13_idx in ice13_final_elatt_dict['Final'].keys()]),1),
    'CCSD [Final]': round(np.mean([abs(ice13_dmc_elatt_dict[ice13_idx][0] - ice13_final_elatt_dict['Final CCSD'][ice13_idx]) for ice13_idx in ice13_final_elatt_dict['Final CCSD'].keys()]),1),
    'MP2 [Final]': round(np.mean([abs(ice13_dmc_elatt_dict[ice13_idx][0] - ice13_final_elatt_dict['Final MP2'][ice13_idx]) for ice13_idx in ice13_final_elatt_dict['Final MP2'].keys()]),1)
}
final_elatt_df.loc['MAD (DMC)'] = mad_dmc_row_elatt

mad_exp_row_elatt = {
    'Ice Phase': 'MAD (Exp)',
    'DMC (Unitcell)': round(np.mean([abs(ice13_exp_elatt_dict[ice13_idx][0] - ice13_dmc_elatt_dict[ice13_idx][0]) for ice13_idx in ice13_exp_elatt_dict.keys() if ice13_idx in ice13_dmc_elatt_dict]),1),
    'Experiment': '',
    'CCSD(T) [Small cell]': '',
    'CCSD(T) [Medium cell]': '',
    'CCSD(T) [Large cell]': '',
    'CCSD(T) [Final]': round(np.mean([abs(ice13_exp_elatt_dict[ice13_idx][0] - ice13_final_elatt_dict['Final'][ice13_idx]) for ice13_idx in ice13_exp_elatt_dict.keys() if ice13_idx in ice13_final_elatt_dict['Final']]),1),
    'CCSD [Final]': round(np.mean([abs(ice13_exp_elatt_dict[ice13_idx][0] - ice13_final_elatt_dict['Final CCSD'][ice13_idx]) for ice13_idx in ice13_exp_elatt_dict.keys() if ice13_idx in ice13_final_elatt_dict['Final CCSD']]),1),
    'MP2 [Final]': round(np.mean([abs(ice13_exp_elatt_dict[ice13_idx][0] - ice13_final_elatt_dict['Final MP2'][ice13_idx]) for ice13_idx in ice13_exp_elatt_dict.keys() if ice13_idx in ice13_final_elatt_dict['Final MP2']]),1)
}
final_elatt_df.loc['MAD (Exp)'] = mad_exp_row_elatt

display(final_elatt_df)

# Convert to LaTeX table
convert_df_to_latex_input(
    df = final_elatt_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:ice13_lattice_energies",
    caption = r"Lattice energies of the ICE13 set from DMC~\cite{dellapiaDMCICE13AmbientHigh2022b}, Experiment~\cite{whalleyEnergiesPhasesIce1984} and LNO-MBE-CCSD(T). We consider the Small, Medium and Large unit cell sizes for LNO-MBE-CCSD(T) and also a Final estimate that corrects for errors in ice VII when using a Small unit cell. We also give Final estimates at the MP2 and CCSD levels. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]",
        '±': r'$\pm$',
    },
    index = False,
    rotate_column_header=True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-ICE13_Lattice_Energies.tex")

,Ice Phase,DMC (Unitcell),Experiment,CCSD(T) [Small cell],CCSD(T) [Medium cell],CCSD(T) [Large cell],CCSD(T) [Final],CCSD [Final],MP2 [Final]
1,Ih,-59.5 ± 0.1,-58.9 ± 1.0,-59.3,-58.4,-58.3,-59.3,-53.5,-59.2
2,II,-59.1 ± 0.1,-58.8 ± 1.0,-58.3,N/A,N/A,-58.3,-52.5,-57.7
3,III,-58.2 ± 0.1,-57.9 ± 1.0,-57.3,-57.0,-56.8,-57.3,-51.3,-57.1
4,IV,-55.6 ± 0.1,N/A,-56.0,-55.5,-54.8,-56.0,-50.0,-55.3
6,VI,-57.7 ± 0.1,-57.2 ± 1.0,-56.9,N/A,-56.2,-56.9,-50.8,-56.1
7,VII,-54.5 ± 0.1,-54.7 ± 1.0,-57.2,-54.6,-54.4,-54.6,-48.5,-53.1
8,VIII,-55.2 ± 0.1,-55.7 ± 1.7,-55.6,N/A,N/A,-55.6,-49.6,-54.3
9,IX,-58.9 ± 0.1,-58.5 ± 1.0,-57.7,N/A,N/A,-57.7,-52.0,-57.4
11,XI,-59.3 ± 0.1,N/A,-59.3,N/A,N/A,-59.3,-53.3,-59.4
13,XIII,-57.3 ± 0.1,N/A,-57.4,N/A,N/A,-57.4,-51.6,-56.9
14,XIV,-57.8 ± 0.1,N/A,-56.9,N/A,N/A,-56.9,-51.0,-56.2
15,XV,-57.7 ± 0.1,N/A,-56.9,N/A,N/A,-56.9,-50.9,-56.1
17,XVII,-57.7 ± 0.1,N/A,-57.7,-57.4,-57.1,-57.7,-52.0,-57.8
MAD (DMC),MAD (DMC),,,,,,0.5,6.3,0.9
MAD (Exp),MAD (Exp),0.4,,,,,0.4,6.2,1.1

### Raw numbers - Relative energies

In [39]:
# Compile a final table of relative energies containing DMC, Exp, CCSD(T) [Small cell], CCSD(T) [Medium cell], CCSD(T) [Large cell]
final_table = {}
for ice13_idx in ice13_final_rel_elatt_dict['Final'].keys():
    final_table[ice13_idx] = {
        'Ice Phase': ice13_systems[ice13_idx],
        'DMC (Unitcell)': f"{dmc_ice13_rel_elatt_dict[ice13_idx][0]:.1f} ± {dmc_ice13_rel_elatt_dict[ice13_idx][1]:.1f}",
        'Experiment': f"{exp_ice13_rel_elatt_dict[ice13_idx][0]:.1f} ± {exp_ice13_rel_elatt_dict[ice13_idx][1]:.1f}" if ice13_idx in exp_ice13_rel_elatt_dict else 'N/A',
        'CCSD(T) [Small cell]': f"{ice13_final_rel_elatt_dict['Unitcell'][ice13_idx]:.1f}",
        'CCSD(T) [Medium cell]': f"{ice13_final_rel_elatt_dict['AFcell'][ice13_idx]:.1f}" if ice13_idx in ice13_final_rel_elatt_dict['AFcell'] else 'N/A',
        'CCSD(T) [Large cell]': f"{ice13_final_rel_elatt_dict['AFsupercell'][ice13_idx]:.1f}" if ice13_idx in ice13_final_rel_elatt_dict['AFsupercell'] else 'N/A',
        'CCSD(T) [Final]': f"{ice13_final_rel_elatt_dict['Final'][ice13_idx]:.1f}",
        'CCSD [Final]': f"{ice13_final_rel_elatt_dict['Final CCSD'][ice13_idx]:.1f}",
        'MP2 [Final]': f"{ice13_final_rel_elatt_dict['Final MP2'][ice13_idx]:.1f}"
    }

# Save final estimates
np.save('Data/ICE13/ICE13_Final_Relative_Data.npy', final_table, allow_pickle=True)

final_df = pd.DataFrame(final_table).T

mad_dmc_row = {
    'Ice Phase': 'MAD (DMC)',
    'DMC (Unitcell)': '',
    'Experiment': '',
    'CCSD(T) [Small cell]': '',
    'CCSD(T) [Medium cell]': '',
    'CCSD(T) [Large cell]': '',
    'CCSD(T) [Final]': round(np.mean([abs(dmc_ice13_rel_elatt_dict[ice13_idx][0] - ice13_final_rel_elatt_dict['Final'][ice13_idx]) for ice13_idx in ice13_final_rel_elatt_dict['Final'].keys()]),1),
    'CCSD [Final]': round(np.mean([abs(dmc_ice13_rel_elatt_dict[ice13_idx][0] - ice13_final_rel_elatt_dict['Final CCSD'][ice13_idx]) for ice13_idx in ice13_final_rel_elatt_dict['Final CCSD'].keys()]),1),
    'MP2 [Final]': round(np.mean([abs(dmc_ice13_rel_elatt_dict[ice13_idx][0] - ice13_final_rel_elatt_dict['Final MP2'][ice13_idx]) for ice13_idx in ice13_final_rel_elatt_dict['Final MP2'].keys()]),1)
}
final_df.loc['MAD [DMC]'] = mad_dmc_row

mad_exp_row = {
    'Ice Phase': 'MAD (Exp)',
    'DMC (Unitcell)': round(np.mean([abs(exp_ice13_rel_elatt_dict[ice13_idx][0] - dmc_ice13_rel_elatt_dict[ice13_idx][0]) for ice13_idx in exp_ice13_rel_elatt_dict.keys() if ice13_idx in dmc_ice13_rel_elatt_dict]),1),
    'Experiment': '',
    'CCSD(T) [Small cell]': '',
    'CCSD(T) [Medium cell]': '',
    'CCSD(T) [Large cell]': '',
    'CCSD(T) [Final]': round(np.mean([abs(exp_ice13_rel_elatt_dict[ice13_idx][0] - ice13_final_rel_elatt_dict['Final'][ice13_idx]) for ice13_idx in exp_ice13_rel_elatt_dict.keys() if ice13_idx in ice13_final_rel_elatt_dict['Final']]),1),
    'CCSD [Final]': round(np.mean([abs(exp_ice13_rel_elatt_dict[ice13_idx][0] - ice13_final_rel_elatt_dict['Final CCSD'][ice13_idx]) for ice13_idx in exp_ice13_rel_elatt_dict.keys() if ice13_idx in ice13_final_rel_elatt_dict['Final CCSD']]),1),
    'MP2 [Final]': round(np.mean([abs(exp_ice13_rel_elatt_dict[ice13_idx][0] - ice13_final_rel_elatt_dict['Final MP2'][ice13_idx]) for ice13_idx in exp_ice13_rel_elatt_dict.keys() if ice13_idx in ice13_final_rel_elatt_dict['Final MP2']]),1)
}
final_df.loc['MAD [Exp]'] = mad_exp_row

display(final_df)

# Convert to LaTeX table
convert_df_to_latex_input(
    df = final_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:ice13_relative_energies",
    caption = r"Relative lattice energies of the ICE13 set with respect to ice Ih from DMC~\cite{dellapiaDMCICE13AmbientHigh2022b}, Experiment~\cite{whalleyEnergiesPhasesIce1984} and LNO-MBE-CCSD(T). We consider the Small, Medium and Large unit cell sizes for LNO-MBE-CCSD(T) and also a Final estimate that corrects for errors in ice VII when using a Small unit cell. We also give Final estimates at the MP2 and CCSD levels. All values are in kJ/mol. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]",
        '±': r'$\pm$',
    },
    index = False,
    rotate_column_header=True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-ICE13_Relative_Energies.tex")

,Ice Phase,DMC (Unitcell),Experiment,CCSD(T) [Small cell],CCSD(T) [Medium cell],CCSD(T) [Large cell],CCSD(T) [Final],CCSD [Final],MP2 [Final]
2,II,0.3 ± 0.1,0.1 ± 1.4,0.9,N/A,N/A,0.9,1.0,1.5
3,III,1.2 ± 0.1,0.9 ± 1.4,1.9,1.4,1.6,1.9,2.1,2.1
4,IV,3.8 ± 0.1,N/A,3.2,2.9,3.6,3.2,3.5,3.9
6,VI,1.8 ± 0.1,1.6 ± 1.4,2.4,N/A,2.1,2.4,2.7,3.1
7,VII,5.0 ± 0.1,4.2 ± 1.4,2.0,3.8,3.9,3.8,4.9,6.1
8,VIII,4.2 ± 0.1,3.2 ± 2.0,3.7,N/A,N/A,3.7,3.9,4.9
9,IX,0.6 ± 0.1,0.4 ± 1.4,1.6,N/A,N/A,1.6,1.5,1.8
11,XI,0.2 ± 0.1,N/A,-0.0,N/A,N/A,-0.0,0.2,-0.2
13,XIII,2.1 ± 0.1,N/A,1.8,N/A,N/A,1.8,1.9,2.3
14,XIV,1.7 ± 0.1,N/A,2.3,N/A,N/A,2.3,2.5,2.9
15,XV,1.7 ± 0.1,N/A,2.4,N/A,N/A,2.4,2.5,3.1
17,XVII,1.8 ± 0.1,N/A,1.5,1.0,1.2,1.5,1.5,1.4
MAD [DMC],MAD (DMC),,,,,,0.6,0.5,0.8
MAD [Exp],MAD (Exp),0.5,,,,,0.8,0.9,1.5

## Comparison to previous literature

### Lattice energy

In [40]:
# Compute DFT MAD on lattice energies with respect to DMC
dft_elatt_mad_dict = {dft_xc: {'MAD [DMC]': 0, 'MAD [CCSD(T)]': 0} for dft_xc in ['PBE-D3(BJ)','optB86b-vdW','SCAN+rVV10','revPBE0-D3','B3LYP-D4']}

# Compile final CCSD(T) lattice energies into an array where we use Unitcell values for all except ice VII (7) where we use AFcell values
final_ice13_elatt_dict = np.array([ice13_final_elatt_dict['Unitcell'][x] if x != 7 else ice13_final_elatt_dict['AFcell'][x] for x in ice13_final_elatt_dict['Unitcell'].keys()])

for method in dft_elatt_mad_dict:
    dft_elatt_mad_dict[method]['MAD [DMC]'] = np.mean(abs(jcp_dft_ice13_elatt.loc[method] - jcp_dft_ice13_elatt.loc['DMC']))/kjmol
    dft_elatt_mad_dict[method]['MAD [CCSD(T)]'] = np.mean(abs(jcp_dft_ice13_elatt.loc[method]/kjmol - final_ice13_elatt_dict))

# Convert to DataFrame
dft_elatt_mad_df = pd.DataFrame.from_dict(dft_elatt_mad_dict, orient='index')
# Round to 1 decimal place
dft_elatt_mad_df = dft_elatt_mad_df.round(1)
# Save to LaTeX table
convert_df_to_latex_input(
    df = dft_elatt_mad_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:ice13_dft_elatt_mad",
    caption = r"Mean absolute deviations (MAD) with respect to LNO-MBE-CCSD(T) and DMC~\cite{dellapiaDMCICE13AmbientHigh2022b} for several DFT functionals on the lattice energies of the ICE13 set. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]"
    },
    index = True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-ICE13_DFT_Elatt_MAD.tex",)


display(dft_elatt_mad_df)

             MAD [DMC]  MAD [CCSD(T)]
PBE-D3(BJ)         7.9            8.3
optB86b-vdW        9.3            9.7
SCAN+rVV10         9.6            9.9
revPBE0-D3         1.5            1.2
B3LYP-D4           2.3            2.6

### Relative energy

In [41]:
# Compute DFT MAD on relative energies with respect to DMC and CCSD(T)
dft_rel_ene_mad_dict = {dft_xc: {'MAD [DMC]': 0, 'MAD [CCSD(T)]': 0} for dft_xc in ['PBE-D3(BJ)','optB86b-vdW','SCAN+rVV10','revPBE0-D3','B3LYP-D4']}

for method in dft_rel_ene_mad_dict:
    dft_rel_ene_mad_dict[method]['MAD [DMC]'] = np.mean(abs(rel_jcp_dft_ice13_elatt.loc[method] - rel_jcp_dft_ice13_elatt.loc['DMC']))/kjmol
    dft_rel_ene_mad_dict[method]['MAD [CCSD(T)]'] = np.mean(abs(rel_jcp_dft_ice13_elatt.loc[method]/kjmol - np.array(list(ice13_final_rel_elatt_dict['Final'].values()))))

# Convert to DataFrame
dft_rel_ene_mad_df = pd.DataFrame.from_dict(dft_rel_ene_mad_dict, orient='index')
# Round to 1 decimal place
dft_rel_ene_mad_df = dft_rel_ene_mad_df.round(1)
# Save to LaTeX table
convert_df_to_latex_input(
    df = dft_rel_ene_mad_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:ice13_dft_rel_ene_mad",
    caption = r"Mean absolute deviations (MAD) with respect to LNO-MBE-CCSD(T) and DMC~\cite{dellapiaDMCICE13AmbientHigh2022b} for several DFT functionals on the relative lattice energies of the ICE13 set (using ice Ih as the reference). All values are in kJ/mol. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]"
    },
    index = True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-ICE13_DFT_Rel_Ene_MAD.tex")
display(dft_rel_ene_mad_df)

             MAD [DMC]  MAD [CCSD(T)]
PBE-D3(BJ)         3.5            3.3
optB86b-vdW        0.5            0.7
SCAN+rVV10         0.7            0.7
revPBE0-D3         1.0            1.0
B3LYP-D4           1.9            1.7

## Lattice energy convergence tests

### Illustrating 3B term buildup in previous MRCC versions

In [ ]:
cumulative_latte = {x:0 for x in [1,2,3,4]}
cumulative_latte_list = {x:[] for x in [0,1,2,3,4]} # 0 is the distance here
# Calculate the 3B terms

with connect('Data/cWFT_Convergence/ice8_3b_errors.db') as db2:
    for i in range(1,len(db2)+1):
        row = db2.get(id=i)
        count = row.data['count']
        dist = row.data['dist']
        cumulative_latte[1] += row.data['DF-CCSD(T)']*count/8
        cumulative_latte[2] += row.data['LNO-CCSD(T) vvtight']*count/8
        cumulative_latte[3] += row.data['LNO-CCSD(T) vvtight iesttol']*count/8
        cumulative_latte[4] += row.data['LNO-CCSD(T) laf iesttol']*count/8
        cumulative_latte_list[0].append(dist)
        cumulative_latte_list[1].append(cumulative_latte[1]/kjmol)
        cumulative_latte_list[2].append(cumulative_latte[2]/kjmol)
        cumulative_latte_list[3].append(cumulative_latte[3]/kjmol)
        cumulative_latte_list[4].append(cumulative_latte[4]/kjmol)

fig, axs = plt.subplots(figsize=(4.5,3),constrained_layout=True,dpi=450)

axs.plot(cumulative_latte_list[0],cumulative_latte_list[1],label='DF-CCSD(T)',color='black',linestyle='--',marker='x', alpha=0.5)
axs.plot(cumulative_latte_list[0],cumulative_latte_list[2],label='LNO-CCSD(T) vvtight',color='red',linestyle='--',marker='x', alpha=0.5)
axs.plot(cumulative_latte_list[0],cumulative_latte_list[3],label='LNO-CCSD(T) vvtight chtol=1d-5, iesttol=0.01, aocd=extra',color='blue',linestyle='--',marker='x', alpha=0.5)
axs.plot(cumulative_latte_list[0],cumulative_latte_list[4],label='LNO-CCSD(T) tight-vtight chtol=1d-5, iesttol=0.01, aocd=extra',color='green',linestyle='--',marker='x', alpha=0.5)

axs.set_ylim([0,20])

axs.legend(fontsize=8)

axs.set_xlabel(r'$R_{12}*R_{13}*R_{23}$ (Å$^3$)')
axs.set_ylabel(r'Cumulative 3B contribution to $E_\text{latt}$ (kJ/mol)')

plt.savefig('Figures/SI_Figure-3B_error_buildup.png')

In [ ]:
xlist_2b = np.arange(3,9,0.1)

cumulative_latte_2b = {x:0 for x in [1,2,3]}
cumulative_latte_2b_list = {x:[0 for idx_x in range(len(xlist_2b))] for x in [1,2,3]}

# Calculate the 2B terms

with connect('Data/ICE13/cWFT/Unitcell/ice13_08_2b.db') as db2:
    for i in range(1,len(db2)+1):
        row = db2.get(id=i)
        count = row.data['count']
        dist = row.data['dist']
        cumulative_latte_2b[1] += row.data['HF TZ']*count/8
        cumulative_latte_2b[2] += row.data['CCSD(T) vtight TZ']*count/8
        cumulative_latte_2b[3] += (row.data['HF TZ'] + row.data['CCSD(T) vtight TZ'])*count/8
        for idx_x in range(1,len(xlist_2b)):
            if dist <= xlist_2b[idx_x]:
                # cumulative_latte_list[0].append(xlist_2b[idx_x+1])
                cumulative_latte_2b_list[1][idx_x] = cumulative_latte_2b[1]/kjmol
                cumulative_latte_2b_list[2][idx_x] = cumulative_latte_2b[2]/kjmol
                cumulative_latte_2b_list[3][idx_x] = cumulative_latte_2b[3]/kjmol
            elif dist > xlist_2b[-1]:
                break

xlist_3b = np.arange(0,150,10)

cumulative_latte_3b = {x:0 for x in [1,2,3]}
cumulative_latte_3b_list = {x:[0 for idx_x in range(len(xlist_3b))] for x in [1,2,3]}

# Calculate the 3B terms
with connect('Data/ICE13/cWFT/Unitcell/ice13_08_3b.db') as db2:
    for i in range(1,len(db2)+1):
        row = db2.get(id=i)
        count = row.data['count']
        dist = row.data['dist']
        cumulative_latte_3b[1] += row.data['HF DZ']*count/8
        cumulative_latte_3b[2] += row.data['CCSD(T) vtight DZ']*count/8
        cumulative_latte_3b[3] += (row.data['HF DZ'] + row.data['CCSD(T) vtight DZ'])*count/8
        for idx_x in range(1,len(xlist_3b)):
            if dist <= xlist_3b[idx_x]:
                # cumulative_latte_list[0].append(xlist_2b[idx_x+1])
                cumulative_latte_3b_list[1][idx_x] = cumulative_latte_3b[1]/kjmol
                cumulative_latte_3b_list[2][idx_x] = cumulative_latte_3b[2]/kjmol
                cumulative_latte_3b_list[3][idx_x] = cumulative_latte_3b[3]/kjmol
            elif dist > xlist_3b[-1]:
                break

fig, axs = plt.subplots(3,2,figsize=(6.675,7),constrained_layout=True,dpi=450,sharex=False)

axs[0,0].plot(xlist_2b,cumulative_latte_2b_list[1],label='HF energy',color='blue',linestyle='--',marker='x', alpha=0.5)
axs[1,0].plot(xlist_2b,cumulative_latte_2b_list[2],label='Correlation energy',color='red',linestyle='--',marker='x', alpha=0.5)
axs[2,0].plot(xlist_2b,cumulative_latte_2b_list[3],label='Total energy',color='black',linestyle='--',marker='x', alpha=0.5)

axs[0,0].set_ylim([cumulative_latte_2b_list[1][-1]-5, cumulative_latte_2b_list[1][-1]+5])
axs[1,0].set_ylim([cumulative_latte_2b_list[2][-1]-5, cumulative_latte_2b_list[2][-1]+5])
axs[2,0].set_ylim([cumulative_latte_2b_list[3][-1]-5, cumulative_latte_2b_list[3][-1]+5])

axs[0,1].plot(xlist_3b,cumulative_latte_3b_list[1],label='HF energy',color='blue',linestyle='--',marker='x', alpha=0.5)
axs[1,1].plot(xlist_3b,cumulative_latte_3b_list[2],label='Correlation energy',color='red',linestyle='--',marker='x', alpha=0.5)
axs[2,1].plot(xlist_3b,cumulative_latte_3b_list[3],label='Total energy',color='black',linestyle='--',marker='x', alpha=0.5)

axs[0,1].set_ylim([cumulative_latte_3b_list[1][-1]-5, cumulative_latte_3b_list[1][-1]+5])
axs[1,1].set_ylim([cumulative_latte_3b_list[2][-1]-5, cumulative_latte_3b_list[2][-1]+5])
axs[2,1].set_ylim([cumulative_latte_3b_list[3][-1]-5, cumulative_latte_3b_list[3][-1]+5])

axs[0,0].legend(fontsize=8)
axs[1,0].legend(fontsize=8)
axs[2,0].legend(fontsize=8)

axs[2,0].set_xlabel(r'$R_{12}$ (\AA{})')
axs[2,1].set_xlabel(r'$R_{12}*R_{13}*R_{23}$ (Å$^3$)')
fig.supylabel(r'Cumulative contribution to $E_\text{latt}$ (kJ/mol)')
axs[0,0].set_title('2-body interactions', fontsize=10)
axs[0,1].set_title('3-body interactions', fontsize=10)

plt.savefig('Figures/SI_Figure-Total_vs_correlation_2B_3B.png')

### LNO threshold costs for anthracene dimer and trimer

In [44]:
# Compile a table of computational cost data
data = {
    ("Dimer", "Walltime (min)"): {
        "Loose": 121,
        "Normal": 233,
        "Tight": 763,
        "vTight": 2473,
        "vvTight": 7005,
    },
    ("Dimer", "Memory (Mb)"): {
        "Loose": 1328,
        "Normal": 3517,
        "Tight": 10696,
        "vTight": 26351,
        "vvTight": 52202,
    },
    ("Trimer", "Walltime (min)"): {
        "Loose": 465,
        "Normal": 840,
        "Tight": 2595,
        "vTight": 9493,
        "vvTight": 33822,
    },
    ("Trimer", "Memory (Mb)"): {
        "Loose": 1524,
        "Normal": 4652,
        "Tight": 15618,
        "vTight": 42048,
        "vvTight": 90182,
    },
}

df = pd.DataFrame.from_dict(data, orient="index")
df.index = pd.MultiIndex.from_tuples(df.index, names=["System", "Metric"])
display(df)

# Convert to LaTeX table
convert_df_to_latex_input(
    df = df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:anthracene_lno_costs",
    caption = r"Computational walltime and memory requirements for LNO-CCSD(T) calculations on a dimer and trimer of anthracene with various LNO thresholds. These estimates are given for a calculation involving 32 cores on an Intel Icelake node with 400 GB of available memory.",
    replace_input= {
        "[t]": "[c]"
    },
    index = True,
    float_fmt="%.0f",
    column_format="lrrrrrrr",
    filename = "Tables/SI_Table-Anthracene_LNO_Costs.tex")

                       Loose  Normal  Tight  vTight  vvTight
System Metric
Dimer  Walltime (min)    121     233    763    2473     7005
       Memory (Mb)      1328    3517  10696   26351    52202
Trimer Walltime (min)    465     840   2595    9493    33822
       Memory (Mb)      1524    4652  15618   42048    90182

### Effect of basis set, core electrons, beyond-CCSD(T) and LNO thresholds on Ice VIII

In [45]:
conv_2b_elatt_dict = {x:0 for x in ['DF-CCSD(T) DZ','DF-CCSDT(Q) DZ', 'DF-CCSD(T) TZ', 'DF-CCSD(T) QZ', 'DF-CCSD(T) CBS(DZ/TZ)', 'DF-CCSD(T) CBS(TZ/QZ)', 'LNO-CCSD(T) tight CBS(TZ/QZ)', 'LNO-CCSD(T) vtight CBS(TZ/QZ)', 'LNO-CCSD(T) LAF CBS(TZ/QZ)', 'DF-CCSD(T) smallcore CBS(TZ/QZ)']}


with connect('Data/cWFT_Convergence/ice8_2b_convergence.db') as db:
    for i in range(1,len(db)+1):
        row = db.get(id=i)
        conv_2b_elatt_dict['DF-CCSD(T) DZ'] += row.data['DF-CCSD(T) DZ']*row.data['count'] / (8 * kjmol)
        conv_2b_elatt_dict['DF-CCSDT(Q) DZ'] += row.data['DF-CCSDT(Q) DZ']*row.data['count'] / (8 * kjmol)
        conv_2b_elatt_dict['DF-CCSD(T) TZ'] += row.data['DF-CCSD(T) TZ']*row.data['count'] / (8 *  kjmol)
        conv_2b_elatt_dict['DF-CCSD(T) QZ'] += row.data['DF-CCSD(T) QZ']*row.data['count'] / (8 *  kjmol)
        conv_2b_elatt_dict['DF-CCSD(T) CBS(DZ/TZ)'] += row.data['DF-CCSD(T) DZ/TZ']*row.data['count'] / (8 *  kjmol)
        conv_2b_elatt_dict['DF-CCSD(T) CBS(TZ/QZ)'] += row.data['DF-CCSD(T) TZ/QZ']*row.data['count'] / (8 *  kjmol)
        conv_2b_elatt_dict['LNO-CCSD(T) tight CBS(TZ/QZ)'] += row.data['LNO-CCSD(T) TZ/QZ tight']*row.data['count'] / (8 *  kjmol)
        conv_2b_elatt_dict['LNO-CCSD(T) vtight CBS(TZ/QZ)'] += row.data['LNO-CCSD(T) TZ/QZ vtight']*row.data['count'] / (8 *  kjmol)
        conv_2b_elatt_dict['LNO-CCSD(T) LAF CBS(TZ/QZ)'] += row.data['LNO-CCSD(T) TZ/QZ LAF']*row.data['count'] / (8 *  kjmol)
        conv_2b_elatt_dict['DF-CCSD(T) smallcore CBS(TZ/QZ)'] += row.data['DF-CCSD(T) smallcore TZ/QZ']*row.data['count'] / (8 *  kjmol)

tq_df = pd.DataFrame({'CCSD(T) aug-cc-pVDZ': conv_2b_elatt_dict['DF-CCSD(T) DZ'],
                                'CCSDT(Q) aug-cc-pVDZ': conv_2b_elatt_dict['DF-CCSDT(Q) DZ']}, index=[r'2B contribution to $E_\text{latt}$ (kJ/mol)']
).T
# To nearest 1 d.p.
tq_df = tq_df.round(1)
# Write to latex table
display(tq_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = tq_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:tq_effect",
    caption = r"Effect of higher order correlation to the two-body contribution of the $E_\text{latt}$ of ice VIII.",
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Convergence_TQ_Effect.tex")

basis_df = pd.DataFrame({'CCSD(T) aug-cc-pVDZ': conv_2b_elatt_dict['DF-CCSD(T) DZ'], 'CCSD(T) aug-cc-pVTZ': conv_2b_elatt_dict['DF-CCSD(T) TZ'], 'CCSD(T) aug-cc-pVQZ': conv_2b_elatt_dict['DF-CCSD(T) QZ'], 'CCSD(T) CBS(aug-cc-pVDZ/aug-cc-pVTZ)': conv_2b_elatt_dict['DF-CCSD(T) CBS(DZ/TZ)'], 'CCSD(T) CBS(aug-cc-pVTZ/aug-cc-pVQZ)': conv_2b_elatt_dict['DF-CCSD(T) CBS(TZ/QZ)']}, index=[r'2B contribution to $E_\text{latt}$ (kJ/mol)']).T
# To nearest 1 d.p.
basis_df = basis_df.round(1)
# Write to latex table
display(basis_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = basis_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:basis_effect",
    caption = r"Effect of basis set to the two-body contribution of the $E_\text{latt}$ of ice VIII.",
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Convergence_Basis_Effect.tex")

lno_df = pd.DataFrame({'LNO-CCSD(T) tight CBS(aug-cc-pVTZ/aug-cc-pVQZ)': conv_2b_elatt_dict['LNO-CCSD(T) tight CBS(TZ/QZ)'], 'LNO-CCSD(T) vtight CBS(aug-cc-pVTZ/aug-cc-pVQZ)': conv_2b_elatt_dict['LNO-CCSD(T) vtight CBS(TZ/QZ)'], 'LNO-CCSD(T) LAF CBS(aug-cc-pVTZ/aug-cc-pVQZ)': conv_2b_elatt_dict['LNO-CCSD(T) LAF CBS(TZ/QZ)'], 'CCSD(T) CBS(aug-cc-pVTZ/aug-cc-pVQZ)': conv_2b_elatt_dict['DF-CCSD(T) CBS(TZ/QZ)']}, index=[r'2B contribution to $E_\text{latt}$ (kJ/mol)']).T
# To nearest 1 d.p.
lno_df = lno_df.round(1)
# Write to latex table
display(lno_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = lno_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:lno_effect",
    caption = r"Effect of LNO settings to the two-body contribution of the $E_\text{latt}$ of ice VIII.",
    replace_input= {
        r' vtight ': r' {\tt vTight} ',
        r' tight ': r' {\tt Tight} ',
        r' normal ': r' {\tt Normal} ',
        r' loose ': r' {\tt Loose} '},
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Convergence_LNO_Effect.tex")

core_df = pd.DataFrame({'CCSD(T) CBS(aug-cc-pVTZ/aug-cc-pVQZ)': conv_2b_elatt_dict['DF-CCSD(T) CBS(TZ/QZ)'] , 'CCSD(T) smallcore CBS(aug-cc-pwCVTZ/aug-cc-pwCVQZ)': conv_2b_elatt_dict['DF-CCSD(T) smallcore CBS(TZ/QZ)']},index=[r'2B contribution to $E_\text{latt}$ (kJ/mol)']).T
# To nearest 1 d.p.
core_df = core_df.round(1)
# Write to latex table
display(core_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = core_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:core_effect",
    caption = r"Effect of core correlation to the two-body contribution of the $E_\text{latt}$ of ice VIII.",
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Convergence_Core_Effect.tex")

                      2B contribution to $E_\text{latt}$ (kJ/mol)
CCSD(T) aug-cc-pVDZ                                         -20.7
CCSDT(Q) aug-cc-pVDZ                                        -20.9

                                      2B contribution to $E_\text{latt}$ (kJ/mol)
CCSD(T) aug-cc-pVDZ                                                         -20.7
CCSD(T) aug-cc-pVTZ                                                         -27.6
CCSD(T) aug-cc-pVQZ                                                         -29.6
CCSD(T) CBS(aug-cc-pVDZ/aug-cc-pVTZ)                                        -31.6
CCSD(T) CBS(aug-cc-pVTZ/aug-cc-pVQZ)                                        -31.0

                                                 2B contribution to $E_\text{latt}$ (kJ/mol)
LNO-CCSD(T) tight CBS(aug-cc-pVTZ/aug-cc-pVQZ)                                         -29.5
LNO-CCSD(T) vtight CBS(aug-cc-pVTZ/aug-cc-pVQZ)                                        -30.4
LNO-CCSD(T) LAF CBS(aug-cc-pVTZ/aug-cc-pVQZ)                                           -30.8
CCSD(T) CBS(aug-cc-pVTZ/aug-cc-pVQZ)                                                   -31.0

                                                    2B contribution to $E_\text{latt}$ (kJ/mol)
CCSD(T) CBS(aug-cc-pVTZ/aug-cc-pVQZ)                                                      -31.0
CCSD(T) smallcore CBS(aug-cc-pwCVTZ/aug-cc-pwCVQZ)                                        -31.3

### DeltaMP2, LAF and Canonical for all ice polymorphs

In [46]:
# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results


conv_basis_dict = {ice13_systems[y]:{('2B','TZ'): 0, ('2B','QZ'): 0 , ('2B','CBS'): 0, ('3B','DZ'): 0 , ('3B','TZ'): 0, ('3B','CBS'): 0} for y in ice13_systems.keys() if y != 7}
conv_2b_lno_dict = {ice13_systems[y]:{('TZ','tight'): 0, ('TZ','vtight'): 0 , ('TZ','LAF'): 0, ('TZ','Canonical'): 0 , ('QZ','tight'): 0, ('QZ','vtight'): 0 , ('QZ','LAF'): 0, ('QZ','Canonical'): 0,('CBS','tight'): 0, ('CBS','vtight'): 0 , ('CBS','LAF'): 0, ('CBS','Canonical'): 0} for y in ice13_systems.keys() if y != 7}
conv_3b_lno_dict = {ice13_systems[y]:{('DZ','tight'): 0, ('DZ','vtight'): 0 , ('DZ','LAF'): 0, ('DZ','Canonical'): 0 , ('TZ','tight'): 0, ('TZ','vtight'): 0 , ('TZ','LAF'): 0, ('TZ','Canonical'): 0,('CBS','tight'): 0, ('CBS','vtight'): 0 , ('CBS','LAF'): 0, ('CBS','Canonical'): 0} for y in ice13_systems.keys() if y != 7}



for ice13_idx in ice13_systems.keys():
    if ice13_idx == 7:
        continue
    with connect(f'Data/ICE13/cWFT/Unitcell/ice13_{ice13_idx:02d}_1b.db') as db1:
        num_monomers = len(db1) - 1

    for basis in ['TZ','QZ','CBS']:
        for lno_thresh in ['tight','vtight','LAF','Canonical']:
            with connect(f'Data/ICE13/cWFT/Unitcell/ice13_{ice13_idx:02d}_2b.db') as db2:
                elatt_cwft = 0
                for i in range(len(db2)):
                    row = db2.get(id=i+1)
                    elatt_cwft += row.data[f'CCSD(T) {lno_thresh} {basis}']*(row.data['count'])
            conv_2b_lno_dict[ice13_systems[ice13_idx]][(basis,lno_thresh)] = elatt_cwft/ (kjmol * num_monomers)  
        with connect(f'Data/ICE13/cWFT/Unitcell/ice13_{ice13_idx:02d}_2b.db') as db2:
            elatt_cwft = 0
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                elatt_cwft += row.data[f'CCSD(T) Canonical {basis}']*(row.data['count'])
        conv_basis_dict[ice13_systems[ice13_idx]][('2B',basis)] = elatt_cwft/ (kjmol * num_monomers)  
    for basis in ['DZ','TZ','CBS']:
        for lno_thresh in ['tight','vtight','LAF','Canonical']:
            with connect(f'Data/ICE13/cWFT/Unitcell/ice13_{ice13_idx:02d}_3b.db') as db3:
                elatt_cwft = 0
                for i in range(len(db3)):
                    row = db3.get(id=i+1)
                    elatt_cwft += row.data[f'CCSD(T) {lno_thresh} {basis}']*(row.data['count'])
            conv_3b_lno_dict[ice13_systems[ice13_idx]][(basis,lno_thresh)] = elatt_cwft/ (kjmol * num_monomers)         


        with connect(f'Data/ICE13/cWFT/Unitcell/ice13_{ice13_idx:02d}_3b.db') as db3:
            elatt_cwft = 0
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                elatt_cwft += row.data[f'CCSD(T) Canonical {basis}']*(row.data['count'])
        conv_basis_dict[ice13_systems[ice13_idx]][('3B',basis)] = elatt_cwft/ (kjmol * num_monomers)  

# Add MAD row
conv_basis_dict['MAD'] = {}
for basis_combination in conv_basis_dict['Ih']:
    if basis_combination[0] == '2B':
        conv_basis_dict['MAD'][basis_combination] = np.mean([abs(conv_basis_dict[x][basis_combination] - conv_basis_dict[x][('2B','CBS')]) for x in conv_basis_dict.keys() if x != 'MAD'])
    elif basis_combination[0] == '3B':
        conv_basis_dict['MAD'][basis_combination] = np.mean([abs(conv_basis_dict[x][basis_combination] - conv_basis_dict[x][('3B','CBS')]) for x in conv_basis_dict.keys() if x != 'MAD'])
conv_2b_lno_dict['MAD'] = {}
for lno_combination in conv_2b_lno_dict['Ih']:
    conv_2b_lno_dict['MAD'][lno_combination] = np.mean([abs(conv_2b_lno_dict[x][lno_combination] - conv_2b_lno_dict[x][(lno_combination[0],'Canonical')]) for x in conv_2b_lno_dict.keys() if x != 'MAD'])
conv_3b_lno_dict['MAD'] = {}
for lno_combination in conv_3b_lno_dict['Ih']:
    conv_3b_lno_dict['MAD'][lno_combination] = np.mean([abs(conv_3b_lno_dict[x][lno_combination] - conv_3b_lno_dict[x][(lno_combination[0],'Canonical')]) for x in conv_3b_lno_dict.keys() if x != 'MAD'])


basis_conv_df = pd.DataFrame(conv_basis_dict).T
# To nearest 1 d.p.
basis_conv_df = basis_conv_df.round(1)
# Write to latex table
display(basis_conv_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = basis_conv_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:2b_3b_basis_conv",
    caption = r"Three-body contributions have a significantly smaller basis set dependence than two-body contributions to the $E_\text{latt}$ of ice phases. These tests are for the aug-cc-pVXZ (X = D, T, Q) basis sets and their CBS, T/Q for 2B and D/T for 3B terms, extrapolations.",
    replace_input={
        r'{3B} \\': r'{3B} \\ \cmidrule(lr){2-4} \cmidrule(lr){5-7}',
        r'MAD': r'\midrule MAD'
    },
    float_fmt="%.1f",
    filename = "Tables/SI_Table-2B_3B_Basis_Conv_Effect.tex")

lno_2b_conv_df = pd.DataFrame(conv_2b_lno_dict).T
# To nearest 1 d.p.
lno_2b_conv_df = lno_2b_conv_df.round(1)
# Write to latex table
display(lno_2b_conv_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = lno_2b_conv_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:2b_lno_conv",
    caption = r"Convergence of 2B contribution for 12 ice phases with LNO thresholds: {\tt Tight}, {\tt vTight} and extrapolated locality approximation free (LAF) for aug-cc-pVTZ, aug-cc-pVQZ and CBS(aug-cc-pVTZ/aug-cc-pVQZ) basis sets",
    float_fmt="%.1f",
    replace_input={
        r'{CBS} \\': r'{CBS} \\ \cmidrule(lr){2-5} \cmidrule(lr){6-9} \cmidrule(lr){10-13}',
        r'MAD': r'\midrule MAD',
        r' vtight': r' {\tt vTight}',
        r' tight': r' {\tt Tight}',
        r' normal': r' {\tt Normal}',
        r' loose': r' {\tt Loose}',
    },
    filename = "Tables/SI_Table-2B_LNO_Conv_Effect.tex")


lno_3b_conv_df = pd.DataFrame(conv_3b_lno_dict).T
# To nearest 1 d.p.
lno_3b_conv_df = lno_3b_conv_df.round(1)
# Write to latex table
display(lno_3b_conv_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = lno_3b_conv_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:3b_lno_conv",
    caption = r"Convergence of 3B contribution for 12 ice phases with LNO thresholds: {\tt Tight}, {\tt vTight} and extrapolated locality approximation free (LAF) for aug-cc-pVDZ, aug-cc-pVTZ and CBS(aug-cc-pVDZ/aug-cc-pVTZ) basis sets",
    float_fmt="%.1f",
    replace_input={
        r'{CBS} \\': r'{CBS} \\ \cmidrule(lr){2-5} \cmidrule(lr){6-9} \cmidrule(lr){10-13}',
        r'MAD': r'\midrule MAD',
        r' vtight': r' {\tt vTight}',
        r' tight': r' {\tt Tight}',
        r' normal': r' {\tt Normal}',
        r' loose': r' {\tt Loose}',
    },
    filename = "Tables/SI_Table-3B_LNO_Conv_Effect.tex")

        2B               3B
        TZ    QZ   CBS   DZ   TZ  CBS
Ih   -20.3 -22.5 -24.0  0.1  0.1  0.1
II   -23.1 -25.2 -26.7  1.6  1.7  1.7
III  -22.2 -24.4 -26.0  0.6  0.7  0.7
IV   -24.1 -26.1 -27.6  1.3  1.4  1.5
VI   -25.3 -27.5 -29.0  1.8  1.9  1.9
VIII -27.6 -29.6 -31.0  2.3  2.4  2.5
IX   -21.4 -23.6 -25.1  1.0  1.0  1.1
XI   -20.7 -23.0 -24.6  0.0  0.0  0.0
XIII -23.3 -25.5 -27.0  1.3  1.4  1.5
XIV  -24.4 -26.6 -28.1  1.7  1.8  1.9
XV   -24.8 -26.9 -28.4  1.7  1.8  1.9
XVII -19.7 -21.9 -23.5  0.2  0.3  0.3
MAD    3.7   1.5   0.0  0.1  0.0  0.0

        TZ                           QZ                          CBS         \
     tight vtight   LAF Canonical tight vtight   LAF Canonical tight vtight
Ih   -19.5  -19.9 -20.1     -20.3 -21.6  -22.1 -22.4     -22.5 -23.1  -23.7
II   -21.9  -22.5 -22.8     -23.1 -24.0  -24.7 -25.0     -25.2 -25.5  -26.2
III  -21.5  -21.7 -21.8     -22.2 -23.6  -23.9 -24.1     -24.4 -25.0  -25.5
IV   -23.1  -23.5 -23.7     -24.1 -25.0  -25.6 -25.8     -26.1 -26.4  -27.1
VI   -24.0  -24.7 -25.1     -25.3 -26.1  -26.9 -27.2     -27.5 -27.6  -28.4
VIII -26.2  -27.0 -27.4     -27.6 -28.1  -29.0 -29.4     -29.6 -29.5  -30.4
IX   -20.6  -20.9 -21.0     -21.4 -22.7  -23.1 -23.2     -23.6 -24.2  -24.6
XI   -19.9  -20.3 -20.5     -20.7 -22.1  -22.6 -22.9     -23.0 -23.6  -24.3
XIII -22.3  -22.7 -23.0     -23.3 -24.3  -24.9 -25.2     -25.5 -25.8  -26.4
XIV  -23.2  -23.8 -24.0     -24.4 -25.3  -25.9 -26.2     -26.6 -26.8  -27.4
XV   -23.6  -24.2 -24.6     -24.8 -25.6  -26.4 -26.7     -26.9 -27.1  -27.9
XVII -18.9  -19.3 -19.6     -19.7 -21.1  -21.6 -21.9     -21.9 -22.6  -23.2
MAD    1.0    0.5   0.3       0.0   1.1    0.5   0.2       0.0   1.1    0.5


       LAF Canonical
Ih   -24.0     -24.0
II   -26.5     -26.7
III  -25.7     -26.0
IV   -27.4     -27.6
VI   -28.8     -29.0
VIII -30.9     -31.0
IX   -24.8     -25.1
XI   -24.6     -24.6
XIII -26.7     -27.0
XIV  -27.7     -28.1
XV   -28.2     -28.4
XVII -23.5     -23.5
MAD    0.2       0.0

        DZ                          TZ                         CBS         \
     tight vtight  LAF Canonical tight vtight  LAF Canonical tight vtight
Ih     0.6    0.3  0.1       0.1  -0.0    0.2  0.3       0.1  -0.4    0.1
II     1.5    1.7  1.8       1.6   1.5    1.7  1.8       1.7   1.5    1.7
III    0.6    0.7  0.8       0.6   0.7    0.8  0.8       0.7   0.8    0.8
IV     1.2    1.3  1.3       1.3   1.6    1.5  1.4       1.4   1.8    1.6
VI     1.5    1.8  2.0       1.8   1.7    1.9  2.0       1.9   1.8    2.0
VIII   3.0    2.6  2.4       2.3   2.7    2.3  2.1       2.4   2.6    2.1
IX     1.0    1.1  1.1       1.0   1.4    1.0  0.8       1.0   1.6    0.9
XI     0.2    0.2  0.2       0.0  -0.2   -0.0  0.1       0.0  -0.5   -0.2
XIII   0.9    1.4  1.7       1.3   1.4    1.4  1.5       1.4   1.7    1.5
XIV    1.5    1.8  1.9       1.7   1.6    1.8  1.8       1.8   1.7    1.8
XV     1.4    1.8  2.0       1.7   1.8    1.8  1.8       1.8   2.0    1.9
XVII  -0.2    0.3  0.6       0.2   0.0    0.3  0.5       0.3   0.1    0.3
MAD    0.3    0.1  0.2       0.0   0.2    0.1  0.1       0.0   0.3    0.1


      LAF Canonical
Ih    0.4       0.1
II    1.8       1.7
III   0.8       0.7
IV    1.5       1.5
VI    2.0       1.9
VIII  1.9       2.5
IX    0.6       1.1
XI   -0.0       0.0
XIII  1.3       1.5
XIV   1.8       1.9
XV    1.8       1.9
XVII  0.4       0.3
MAD   0.2       0.0

### Small effect of 4B contribution

In [ ]:
ice13_4b_data_dict = {ice13_idx : {'dist': [], 'cumulative_latte': []} for ice13_idx in [8,9]}

for ice13_idx in [8,9]:
    with connect(f'Data/ICE13/cWFT/Unitcell/ice13_{ice13_idx:02d}_1b.db') as db1:
        num_monomers = len(db1) - 1
    with connect(f'Data/cWFT_Convergence/ice{ice13_idx}_4b_convergence.db') as db1:
        total_ene = 0
        for i in range(1,len(db1)):
            row = db1.get(id=i)
            total_ene += row.data['DF-CCSD(T) aug-cc-pVDZ']*row.data['count']
            ice13_4b_data_dict[ice13_idx]['dist'].append(row.data['dist'])
            if ice13_idx == 8:
                ice13_4b_data_dict[ice13_idx]['cumulative_latte'].append(total_ene/(kjmol*8))
            elif ice13_idx == 9:
                ice13_4b_data_dict[ice13_idx]['cumulative_latte'].append(total_ene/(kjmol*12))

# Plot the 4B convergence for ice VIII and ice IX
fig, axs = plt.subplots(1,2,figsize=(6.69,3),constrained_layout=True,dpi=450,sharey=True)

axs[0].plot(ice13_4b_data_dict[8]['dist'],ice13_4b_data_dict[8]['cumulative_latte'],label='CCSD(T) aug-cc-pVDZ correlation',color='blue',linestyle='--',marker='x', alpha=0.5)
axs[0].plot([0,20000],[3.2217,3.2217],color='black',label='MBpol total',linestyle='--', alpha=0.5)
axs[1].plot(ice13_4b_data_dict[9]['dist'],ice13_4b_data_dict[9]['cumulative_latte'],label='CCSD(T) aug-cc-pVDZ correlation',color='blue',linestyle='--',marker='x', alpha=0.5)
axs[1].plot([0,20000],[0.50208,0.50208],color='black',label='MBpol total',linestyle='--', alpha=0.5)

axs[0].set_xlim([0,20000])
axs[1].set_xlim([0,14000])

axs[1].legend(fontsize=8)

axs[0].set_ylim([-4,4])
axs[1].set_ylim([-4,4])

axs[0].set_title('Ice VIII')
axs[1].set_title('Ice IX')
axs[0].set_ylabel(r'Cumulative 4B contribution to $E_\text{latt}$ (kJ/mol)')
axs[0].set_xlabel(r'$R_{12}*R_{13}*R_{14}*R_{23}*R_{24}*R_{34}$ (Å$^6$)')
axs[1].set_xlabel(r'$R_{12}*R_{13}*R_{14}*R_{23}*R_{24}*R_{34}$ (Å$^6$)')
plt.savefig('Figures/SI_Figure-4B_Elatt_Convergence.png')

## Ice VIII and Ih relative energy convergence tests

In [48]:
# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results

ice13_rel_ene_systems = {
    1: 'Ih',
    8: 'VIII',
}

max_2b_dist = '9.0'
max_3b_dist = 130

cutoff_2b_dists = np.arange(3.5,float(max_2b_dist)+0.2,0.2)
cutoff_3b_dists = np.arange(10,float(max_3b_dist)+5,5)

x_polymorph_2b_elatt_dict = {form: {f'{cutoff:.1f}': {method: 0 for method in ['tight','vtight','LAF']} for cutoff in cutoff_2b_dists} for form in ['expt','vaneijck']}
x_polymorph_3b_elatt_dict = {form: {cutoff: {method: 0 for method in ['tight','vtight','LAF']} for cutoff in cutoff_3b_dists} for form in ['expt','vaneijck']}


ice13_rel_ene_elatt_conv_dict = {ice13_idx: {method: {} for method in ['DeltaMP2 Small','LAF Large','Canonical Large', 'DeltaMP2 Large']} for ice13_idx in ice13_rel_ene_systems.keys()}
cumulative_rel_ene_mbe_dict = {ice13_idx: {method: {'2B contribution': [0 for _ in cutoff_2b_dists], '3B contribution': [0 for _ in cutoff_3b_dists]} for method in ['DeltaMP2 Small','LAF Large','Canonical Large', 'DeltaMP2 Large']} for ice13_idx in ice13_rel_ene_systems.keys()}

for ice13_idx in [1,8]:
    system_methods_erel_dict = {}
    for method in ['tight']:
        method_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
        with connect(f'Data/cWFT_Convergence/Rel_Ene_Convergence/ice13_{ice13_idx:02d}_1b.db') as db1:
            num_monomers = len(db1) - 1
            monomer_ene_list = []
            for i in range(len(db1)):
                row = db1.get(id=i+1)
                monomer_ene_list += [row.data[f'CCSD(T) {method} TZ'] - row.data[f'MP2 {method} TZ'] + row.data['MP2 Canonical CBS']]

            method_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/cWFT_Convergence/Rel_Ene_Convergence/ice13_{ice13_idx:02d}_2b.db') as db2:
            elatt_cwft = 0
            cumulative_mbe_dist_list = []
            cumulative_mbe_contribution_list = []
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                dist = row.data['dist']
                elatt_cwft += (row.data[f'CCSD(T) {method} DZ'] - row.data[f'MP2 {method} DZ'] + row.data['MP2 Canonical CBS'])*(row.data['count'])
                for cutoff_idx, cutoff in enumerate(cutoff_2b_dists):
                    if dist < cutoff + 0.01:
                        cumulative_rel_ene_mbe_dict[ice13_idx]['DeltaMP2 Small']['2B contribution'][cutoff_idx] = elatt_cwft/num_monomers

            method_elatt_dict['2B'] = elatt_cwft/num_monomers


        with connect(f'Data/cWFT_Convergence/Rel_Ene_Convergence/ice13_{ice13_idx:02d}_3b.db') as db3:
            elatt_cwft = 0
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                elatt_cwft += (row.data[f'CCSD(T) {method} DZ'] - row.data[f'MP2 {method} DZ'] + row.data['MP2 Canonical CBS'])*(row.data['count'])
                for cutoff_idx, cutoff in enumerate(cutoff_3b_dists):
                    if row.data['dist'] < cutoff + 0.01:
                        cumulative_rel_ene_mbe_dict[ice13_idx]['DeltaMP2 Small']['3B contribution'][cutoff_idx] = elatt_cwft/num_monomers


        method_elatt_dict['3B'] = elatt_cwft/num_monomers
        method_elatt_dict['Total'] = method_elatt_dict['1B'] + method_elatt_dict['2B'] + method_elatt_dict['3B']
        ice13_rel_ene_elatt_conv_dict[ice13_idx]['DeltaMP2 Small'] = method_elatt_dict.copy()
    cell_size = 'Unitcell'
    for method in ['LAF','Canonical', 'DeltaMP2']:
        method_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
        with connect(f'Data/ICE13/cWFT/{cell_size}/ice13_{ice13_idx:02d}_1b.db') as db1:
            num_monomers = len(db1) - 1
            monomer_ene_list = []
            for i in range(len(db1)):
                row = db1.get(id=i+1)
                if 'DeltaMP2' in method:
                    monomer_ene_list += [row.data['CCSD(T) Canonical QZ'] - row.data['MP2 Canonical QZ'] + row.data['MP2 Canonical CBS']]
                else:
                    monomer_ene_list += [row.data[f'CCSD(T) {method} CBS']]
            method_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/ICE13/cWFT/{cell_size}/ice13_{ice13_idx:02d}_2b.db') as db2:
            elatt_cwft = 0
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                if 'DeltaMP2' in method:
                    elatt_cwft += (row.data['CCSD(T) Canonical TZ'] - row.data['MP2 Canonical TZ'] + row.data['MP2 Canonical CBS'])*(row.data['count'])
                else:
                    elatt_cwft += row.data[f'CCSD(T) {method} CBS']*(row.data['count'])

                for cutoff_idx, cutoff in enumerate(cutoff_2b_dists):
                    if row.data['dist'] < cutoff + 0.01:
                        cumulative_rel_ene_mbe_dict[ice13_idx][f'{method} Large']['2B contribution'][cutoff_idx] = elatt_cwft/num_monomers
                
            method_elatt_dict['2B'] = elatt_cwft/num_monomers


        with connect(f'Data/ICE13/cWFT/{cell_size}/ice13_{ice13_idx:02d}_3b.db') as db3:
            elatt_cwft = 0
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                if 'DeltaMP2' in method:
                    elatt_cwft += (row.data['CCSD(T) Canonical DZ'] - row.data['MP2 Canonical DZ'] + row.data['MP2 Canonical CBS'])*(row.data['count'])
                else:
                    elatt_cwft += row.data[f'CCSD(T) {method} CBS']*(row.data['count'])
                for cutoff_idx, cutoff in enumerate(cutoff_3b_dists):
                    if row.data['dist'] < cutoff + 0.01:
                        cumulative_rel_ene_mbe_dict[ice13_idx][f'{method} Large']['3B contribution'][cutoff_idx] = elatt_cwft/num_monomers


        method_elatt_dict['3B'] = elatt_cwft/num_monomers
        method_elatt_dict['Total'] = method_elatt_dict['1B'] + method_elatt_dict['2B'] + method_elatt_dict['3B']
        ice13_rel_ene_elatt_conv_dict[ice13_idx][f'{method} Large'] = method_elatt_dict.copy()

### 2B and 3B distance cutoff dependence

In [49]:
# Plot convergence of 2B and 3B contributions

fig, axs = plt.subplots(2,2,figsize=(6.695,6),dpi=450, constrained_layout=True)

axs[0,0].plot(cutoff_2b_dists, np.array(cumulative_rel_ene_mbe_dict[1]['DeltaMP2 Small']['2B contribution']) / kjmol, label=r'Composite (Reduced) Ih', color=color_dict['blue'],marker='x')
axs[0,0].plot(cutoff_2b_dists, np.array(cumulative_rel_ene_mbe_dict[8]['DeltaMP2 Small']['2B contribution']) / kjmol, label=r'Composite (Reduced) VIII', color=color_dict['red'],marker='x')


axs[0,0].plot(cutoff_2b_dists, np.array(cumulative_rel_ene_mbe_dict[1]['DeltaMP2 Large']['2B contribution']) / kjmol, label=r'Composite (Full) Ih', color=color_dict['blue'],marker='o',markerfacecolor='none',alpha=0.7)
axs[0,0].plot(cutoff_2b_dists, np.array(cumulative_rel_ene_mbe_dict[8]['DeltaMP2 Large']['2B contribution']) / kjmol, label=r'Composite (Full) VIII', color=color_dict['red'],marker='o',markerfacecolor='none',alpha=0.7)


axs[0,0].set_ylabel(f'{method} 2B (kJ/mol)')
axs[0,0].set_ylim([-35,-15])

axs[0,1].plot(cutoff_3b_dists, np.array(cumulative_rel_ene_mbe_dict[1]['DeltaMP2 Small']['3B contribution']) / kjmol, label=r'Composite (Reduced) Ih', color=color_dict['blue'],marker='x')
axs[0,1].plot(cutoff_3b_dists, np.array(cumulative_rel_ene_mbe_dict[8]['DeltaMP2 Small']['3B contribution']) / kjmol, label=r'Composite (Reduced) VIII', color=color_dict['red'],marker='x')

axs[0,1].plot(cutoff_3b_dists, np.array(cumulative_rel_ene_mbe_dict[1]['DeltaMP2 Large']['3B contribution']) / kjmol, label=r'Composite (Full) Ih', color=color_dict['blue'],marker='o',markerfacecolor='none',alpha=0.7)
axs[0,1].plot(cutoff_3b_dists, np.array(cumulative_rel_ene_mbe_dict[8]['DeltaMP2 Large']['3B contribution']) / kjmol, label=r'Composite (Full) VIII', color=color_dict['red'],marker='o',markerfacecolor='none',alpha=0.7)

# Plot the difference between DeltaMP2 Small and DeltaMP2 Large for 2B and 3B contributions
axs[1,0].plot(cutoff_2b_dists, (np.array(cumulative_rel_ene_mbe_dict[8]['DeltaMP2 Small']['2B contribution']) - np.array(cumulative_rel_ene_mbe_dict[1]['DeltaMP2 Small']['2B contribution'])) / kjmol, label=r'Composite (Reduced)', color=color_dict['purple'],marker='x')
axs[1,0].plot(cutoff_2b_dists, (np.array(cumulative_rel_ene_mbe_dict[8]['DeltaMP2 Large']['2B contribution']) - np.array(cumulative_rel_ene_mbe_dict[1]['DeltaMP2 Large']['2B contribution'])) / kjmol, label=r'Composite (Full)', color=color_dict['purple'],marker='o',markerfacecolor='none',alpha=0.7)

axs[1,1].plot(cutoff_3b_dists, (np.array(cumulative_rel_ene_mbe_dict[8]['DeltaMP2 Small']['3B contribution']) - np.array(cumulative_rel_ene_mbe_dict[1]['DeltaMP2 Small']['3B contribution'])) / kjmol, label=r'Composite (Reduced)', color=color_dict['purple'],marker='x')
axs[1,1].plot(cutoff_3b_dists, (np.array(cumulative_rel_ene_mbe_dict[8]['DeltaMP2 Large']['3B contribution']) - np.array(cumulative_rel_ene_mbe_dict[1]['DeltaMP2 Large']['3B contribution'])) / kjmol, label=r'Composite (Full)', color=color_dict['purple'],marker='o',markerfacecolor='none',alpha=0.7)

axs[0,0].set_ylabel(r'2B contribution to $E_\text{latt}$ (kJ/mol)')
axs[0,1].set_ylabel(r'3B contribution to $E_\text{latt}$ (kJ/mol)')
axs[1,0].set_ylabel(r'2B contribution to $E_\text{rel}$ (kJ/mol)')
axs[1,1].set_ylabel(r'3B contribution to $E_\text{rel}$ (kJ/mol)')
axs[0,1].set_ylim([-1,3])

# axs[0,1].set_title(f'{method}')
axs[0,0].legend(fontsize=8)
axs[1,0].legend(fontsize=8)

axs[1,0].set_xlabel('2B distance cutoff (Å)')
axs[1,1].set_xlabel('3B distance cutoff (Å)')

axs[0,1].set_ylim([-2,4])
axs[1,1].set_ylim([-2,4])
axs[0,0].set_ylim([-40,-10])
axs[1,0].set_ylim([-10,-2])


plt.savefig('Figures/SI_Figure-Ice_Rel_Ene_2B_3B_Convergence.png')

### Basis set and LNO threshold dependence

In [50]:
ice13_erel_convergence_dict = {}
for ice13_idx in [1,8]:
    ice13_erel_convergence_dict[f'{ice13_systems[ice13_idx]} ' + r'$E_\text{latt}$'] = {(mbe_type,method): ice13_rel_ene_elatt_conv_dict[ice13_idx][method][mbe_type] / kjmol for mbe_type in ['1B','2B','3B','Total'] for method in ['DeltaMP2 Small','LAF Large','Canonical Large', 'DeltaMP2 Large'] }

# Add the difference between ice VIII and ice Ih for each method and mbe_type
ice13_erel_convergence_dict['(VIII - Ih) ' + r'$E_\text{rel}$'] = {(mbe_type,method): ice13_rel_ene_elatt_conv_dict[8][method][mbe_type] / kjmol - ice13_rel_ene_elatt_conv_dict[1][method][mbe_type] / kjmol for mbe_type in ['1B','2B','3B','Total'] for method in ['DeltaMP2 Small','LAF Large','Canonical Large', 'DeltaMP2 Large'] }



methods_df = pd.DataFrame(ice13_erel_convergence_dict)
# To nearest 1 d.p.
methods_df = methods_df.round(1)
# Write to latex table
display(methods_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = methods_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:ice_rel_ene_mbe_conv",
    caption = r"The MBE contributions to the lattice energy of ice Ih and VIII for several LNO approximations ({\tt Tight}, {\tt vTight} and LAF extrapolated) to the CCSD(T) in the Composite `Reduced' approach.",
    replace_input = {'DeltaMP2':r'Composite', "[t]": "[c]", r"Small": r"Reduced", r"Large": r"Full"},
    float_fmt="%.1f",
    column_format="lrrrr",
    filename = "Tables/SI_Table-Ice_Rel_Ene_Elatt_Convergence.tex")

                       Ih $E_\text{latt}$  VIII $E_\text{latt}$  \
1B    DeltaMP2 Small                 -7.9                  -5.2
      LAF Large                      -8.0                  -5.3
      Canonical Large                -8.0                  -5.3
      DeltaMP2 Large                 -8.1                  -5.3
2B    DeltaMP2 Small                -21.5                 -28.8
      LAF Large                     -24.0                 -30.9
      Canonical Large               -24.0                 -31.0
      DeltaMP2 Large                -23.7                 -30.7
3B    DeltaMP2 Small                 -0.3                   1.3
      LAF Large                       0.4                   1.9
      Canonical Large                 0.1                   2.5
      DeltaMP2 Large                  0.1                   2.6
Total DeltaMP2 Small                -29.8                 -32.7
      LAF Large                     -31.6                 -34.3
      Canonical Large               -31.9                 -33.8
      DeltaMP2 Large                -31.7                 -33.4

                       (VIII - Ih) $E_\text{rel}$
1B    DeltaMP2 Small                          2.7
      LAF Large                               2.8
      Canonical Large                         2.8
      DeltaMP2 Large                          2.8
2B    DeltaMP2 Small                         -7.2
      LAF Large                              -6.9
      Canonical Large                        -7.0
      DeltaMP2 Large                         -7.0
3B    DeltaMP2 Small                          1.6
      LAF Large                               1.5
      Canonical Large                         2.4
      DeltaMP2 Large                          2.5
Total DeltaMP2 Small                         -2.9
      LAF Large                              -2.7
      Canonical Large                        -1.8
      DeltaMP2 Large                         -1.8

# Optimizing B86bPBE50-revXDM

In [51]:
ccsdt_latte_list = [-955.7877725874953, -728.4462259203218, -699.6156811751055, -399.89286818073487, -1180.958306944111, -547.3519963988629, -288.9570099343434, -854.0090433857645, -1678.1083282236273, -881.1074883226162, -837.2021714601619, -920.6209863237934, -868.3946147078077, -1029.4984747546537, -1024.2913652419652, -657.740158153093, -814.0224259356071, -637.3627293860278, -664.520332662539, -1421.5386459006331, -1109.1884578585082, -912.993955431994, -1295.6791278542448] # CC with D4

x23_num_mon = np.array([2,4,2,4,2,4,4,8,4,2,4,4,2,4,2,2,8,6,6,4,2,1,8])

x23_elatt_opt_dict = {}
x23_elatt_opt_mad_2d_array = {}
for opt_strat in ['loose','normal','tight']:

    xdm_x23_energies = np.loadtxt(f'Data/X23/revXDM/energies_x23_{opt_strat}',dtype='str')
    if opt_strat == 'loose':
        a1_list = '0.70 0.72 0.74 0.76 0.78 0.80 0.82 0.84 0.86 0.88 0.90 0.92 0.94 0.96 0.98 1.00'.split()
        a2_list = '0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60'.split()
    elif opt_strat == 'normal':
        a1_list = '0.66 0.68 0.70 0.72 0.74 0.76 0.78 0.80'.split()
        a2_list = '1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80'.split()
    elif opt_strat == 'tight':
        a1_list = '0.73 0.74 0.75 0.76 0.77'.split()
        a2_list = '1.58 1.60 1.62 1.64 1.66 1.68 1.70 1.72 1.74 1.76 1.78 1.80'.split()
    a1a2_size = int(len(a1_list)*len(a2_list))
    total_counter = 0 
    x23_elatt_opt_dict[opt_strat] = {y: {z: {'rmsd': 0, 'mad':0, 'mad_list': [], 'latte_list': []} for z in a2_list} for y in a1_list}
    x23_elatt_opt_mad_2d_array[opt_strat] = np.zeros((len(a1_list), len(a2_list)))
    for j, a1 in enumerate(a1_list):
        for k, a2 in enumerate(a2_list):
            abs_err_list = []
            sq_err_list = []
            raw_latte_list = []
            for system in range(1,24):
                sys_label = system-1
                system_latte = (float(xdm_x23_energies[total_counter+sys_label*a1a2_size][3]) - x23_num_mon[sys_label]*float(xdm_x23_energies[total_counter+sys_label*a1a2_size][4]))*1000/x23_num_mon[sys_label]
                raw_latte_list += [system_latte]
                abs_err = abs(ccsdt_latte_list[system-1] - system_latte)
                abs_err_list += [abs_err]
                sq_err_list += [abs_err**2]
            mad = np.mean(abs_err_list)
            rmsd = np.sqrt(np.mean(sq_err_list))
            x23_elatt_opt_dict[opt_strat][a1][a2]['mad'] = mad
            x23_elatt_opt_dict[opt_strat][a1][a2]['rmsd'] = rmsd
            x23_elatt_opt_dict[opt_strat][a1][a2]['mad_list'] = abs_err_list
            x23_elatt_opt_dict[opt_strat][a1][a2]['latte_list'] = raw_latte_list
            x23_elatt_opt_mad_2d_array[opt_strat][j,k] = mad/kjmol
            total_counter += 1

### Optimization parameters

In [52]:
fig, axs = plt.subplots(3,1,figsize=(5,8),dpi=300,height_ratios=[0.9,0.6,0.5],tight_layout=True)
# Set colormap from white to black
cmap = plt.get_cmap('Greys')
a1_list = '0.70 0.72 0.74 0.76 0.78 0.80 0.82 0.84 0.86 0.88 0.90 0.92 0.94 0.96 0.98 1.00'.split()
a2_list = '0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60'.split()

im = axs[0].imshow(x23_elatt_opt_mad_2d_array['loose'], vmin=0,vmax=50, aspect='auto', cmap=cmap, interpolation='nearest')
axs[0].set_xticks(np.arange(len(a2_list)), labels=a2_list, fontsize=8)
axs[0].set_yticks(np.arange(len(a1_list)), labels=a1_list, fontsize=8)


axs[0].add_patch(plt.Rectangle((11.5,-3), 6,8, fill=False, edgecolor='red', lw=2))
axs[0].set_ylabel(r'XDM $a_1$ (\AA{})', fontsize=8)

# Add colorbar to the top
cbar = fig.colorbar(im, ax=axs[0], orientation='vertical', pad=0.01)
cbar.set_label('Mean Absolute Deviation (meV)', fontsize=8)
cbar.ax.tick_params(labelsize=8)

a1_list = '0.66 0.68 0.70 0.72 0.74 0.76 0.78 0.80'.split()
a2_list = '1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80'.split()

im = axs[1].imshow(x23_elatt_opt_mad_2d_array['normal'], vmin=0,vmax=25, aspect='auto', cmap=cmap, interpolation='nearest')
axs[1].set_xticks(np.arange(len(a2_list)), labels=a2_list, fontsize=8)
axs[1].set_yticks(np.arange(len(a1_list)), labels=a1_list, fontsize=8)
axs[1].set_ylabel(r'XDM $a_1$ (\AA{})', fontsize=8)

# Add colorbar to the top
cbar1 = fig.colorbar(im, ax=axs[1], orientation='vertical', pad=0.01)
cbar1.set_label('Mean Absolute Deviation (meV)', fontsize=8)
cbar1.ax.tick_params(labelsize=8)

# Write down the MAD in the middle of each cell
for i in range(len(a1_list)):
    for j in range(len(a2_list)):
        axs[1].text(j, i, f"{round(x23_elatt_opt_mad_2d_array['normal'][i,j],1):.1f}", ha='center', va='center', color='black', fontsize=6)

# Draw a red square around the cell with the lowest MAD
axs[1].add_patch(plt.Rectangle((3.5, 3+0.5), 4.95, 3.9, fill=False, edgecolor='red', lw=2))

a1_list = '0.73 0.74 0.75 0.76 0.77'.split()
a2_list = '1.58 1.60 1.62 1.64 1.66 1.68 1.70 1.72 1.74 1.76 1.78 1.80'.split()

im = axs[2].imshow(x23_elatt_opt_mad_2d_array['tight'], vmin=0,vmax=7, aspect='auto', cmap=cmap, interpolation='nearest')
axs[2].set_xticks(np.arange(len(a2_list)), labels=a2_list, fontsize=8)
axs[2].set_yticks(np.arange(len(a1_list)), labels=a1_list, fontsize=8)
axs[2].set_ylabel(r'XDM $a_1$ (\AA{})', fontsize=8)
axs[2].set_xlabel(r'XDM $a_2$ (\AA{})', fontsize=8)

# Add colorbar to the top
cbar2 = fig.colorbar(im, ax=axs[2], orientation='vertical', pad=0.01)
cbar2.set_label('Mean Absolute Deviation (meV)', fontsize=8)
cbar2.ax.tick_params(labelsize=8)

# Write down the MAD in the middle of each cell
for i in range(len(a1_list)):
    for j in range(len(a2_list)):
        axs[2].text(j, i, f"{round(x23_elatt_opt_mad_2d_array['tight'][i,j],1):.1f}", ha='center', va='center', color='black', fontsize=6)
axs[2].add_patch(plt.Rectangle((6.5,0.5), 1,1, fill=False, edgecolor='red', lw=2))


plt.savefig('Figures/SI_Figure-XDM_Optimisation.png')

### Comparison to original B86bPBE50-XDM

In [53]:
# Get the default X23 results
x23_xdm_default_elatt_dict = {x23_idx: 0 for x23_idx in range(1,24)}
ice13_xdm_default_elatt_dict = {ice13_idx: 0 for ice13_idx in [1,2,3,4,6,7,8,9,11,13,14,15,17]}
ice13_xdm_opt_elatt_dict = {ice13_idx: 0 for ice13_idx in [1,2,3,4,6,7,8,9,11,13,14,15,17]}

dmc_ice13_latte_list = [x*kjmol for x in [-59.45,-59.14,-58.2,-55.62,-57.67,-54.46,-55.22,-58.85,-59.29,-57.33,-57.75,-57.71,-57.7]]

for x23_idx in range(1,24):

    molecule = read_aims_output_gz(f'Data/X23/DFT/AIMS/{x23_idx:02d}/molecule/aims_03.out.gz')
    solid = read_aims_output_gz(f'Data/X23/DFT/AIMS/{x23_idx:02d}/solid/aims_03.out.gz')
    num_monomers = len(solid)/len(molecule)
    x23_xdm_default_elatt_dict[x23_idx] = (solid.get_potential_energy()/num_monomers - molecule.get_potential_energy())*1000
# Get ICE13 results
for ice13_idx in ice13_xdm_default_elatt_dict:
    molecule = read_aims_output_gz(f'Data/ICE13/DFT/AIMS/Molecule/aims_03.out.gz')
    solid = read_aims_output_gz(f'Data/ICE13/DFT/AIMS/{ice13_idx:02d}/aims_03.out.gz')
    num_monomers = len(solid)/len(molecule)
    ice13_xdm_default_elatt_dict[ice13_idx] = (solid.get_potential_energy()/num_monomers - molecule.get_potential_energy())*1000


# Get the MAD and RMSD w.r.t. CCSD(T)
x23_xdm_default_mad = np.mean([abs(x23_xdm_default_elatt_dict[x23_idx] - ccsdt_latte_list[x23_idx-1]) for x23_idx in range(1,24)])
x23_xdm_default_rmsd = np.sqrt(np.mean([(x23_xdm_default_elatt_dict[x23_idx] - ccsdt_latte_list[x23_idx-1])**2 for x23_idx in range(1,24)]))
ice13_xdm_default_mad = np.mean([abs(ice13_xdm_default_elatt_dict[ice13_idx] - dmc_ice13_latte_list[idx]) for idx, ice13_idx in enumerate(ice13_xdm_default_elatt_dict)])
ice13_xdm_default_rmsd = np.sqrt(np.mean([(ice13_xdm_default_elatt_dict[ice13_idx] - dmc_ice13_latte_list[idx])**2 for idx, ice13_idx in enumerate(ice13_xdm_default_elatt_dict)]))

# Get the XDM optimized ICE13 lattice energies
xdm_ice13_energies = np.loadtxt(f'Data/ICE13/revXDM/energies_ice13',dtype='str')
for line in xdm_ice13_energies:
    ice13_idx = int(line[0])
    if line[1] != '0.74' and line[2] != '1.72':
        continue
    # The energy is in the 4th column, the number of monomers is in the 5th column
    solid_energy = float(line[3])
    molecule_energy = float(line[4])
    num_monomers = len(read_aims_output_gz(f'Data/ICE13/DFT/AIMS/{ice13_idx:02d}/aims_03.out.gz')) / len(read_aims_output_gz(f'Data/ICE13/DFT/AIMS/Molecule/aims_03.out.gz'))
    ice13_xdm_opt_elatt_dict[ice13_idx] = (solid_energy/num_monomers - molecule_energy)*1000

ice13_xdm_opt_mad = np.mean([abs(ice13_xdm_opt_elatt_dict[ice13_idx] - dmc_ice13_latte_list[idx]) for idx, ice13_idx in enumerate(ice13_xdm_opt_elatt_dict)])
ice13_xdm_opt_rmsd = np.sqrt(np.mean([(ice13_xdm_opt_elatt_dict[ice13_idx] - dmc_ice13_latte_list[idx])**2 for idx, ice13_idx in enumerate(ice13_xdm_opt_elatt_dict)]))

In [54]:
# Create a table of the XDM results for X23 and ICE13

# The original data from Phys. Rev. Lett. 133, 046401 put hexamine and succinic acid in the wrong order, which we will correct here
prl_names_order={idx+1: x for idx,x in enumerate(["1,4-cyclohexanedione" ,"Acetic Acid" ,"Adamantane" ,"Ammonia" ,"Anthracene" ,"Benzene" ,"CO$_2$" ,"Cyanamide" ,"Cytosine" ,"Ethyl carbamate" ,"Formamide" ,"Imidazole" ,"Naphthalene" ,r"Oxalic Acid $\alpha$" ,r"Oxalic Acid $\beta$" ,"Pyrazine" ,"Pyrazole" ,"Triazine" ,"Trioxane" ,"Uracil" ,"Urea" ,"Hexamine" ,"Succinic Acid" ])}
prl_to_x23_order = {idx+1: x for idx, x in enumerate([1,2,3,4,5,6,7,8,9,10,11,22,12,13,14,15,16,17,23,18,19,20,21])}
x23_labels = {x23_idx: prl_names_order[prl_to_x23_order[x23_idx]] for x23_idx in range(1,24)}

x23_xdm_compare_dict = {}
for x23_idx in range(1,24):
    x23_xdm_compare_dict[x23_labels[x23_idx]] = {
        'CCSD(T)': round(ccsdt_latte_list[prl_to_x23_order[x23_idx]-1]/kjmol,1),
        'B86bPBE50-XDM (lightdense)': round(x23_xdm_default_elatt_dict[prl_to_x23_order[x23_idx]]/kjmol,1),
        'B86bPBE50-revXDM': round(x23_elatt_opt_dict['tight']['0.74']['1.72']['latte_list'][prl_to_x23_order[x23_idx]-1]/kjmol,1),
    }
x23_xdm_compare_dict['MAD (kJ/mol)'] = {
    'CCSD(T)': '',
    'B86bPBE50-XDM (lightdense)': round(x23_xdm_default_mad/kjmol,1),
    'B86bPBE50-revXDM': round(x23_elatt_opt_dict['tight']['0.74']['1.72']['mad']/kjmol,1),
}

# Create a dataframe from the dictionary
x23_xdm_df = pd.DataFrame(x23_xdm_compare_dict).T
# Round to 1 d.p.
x23_xdm_df = x23_xdm_df.round(1)
# Display the dataframe
display(x23_xdm_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = x23_xdm_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_xdm_compare",
    caption = r"Comparison of X23 lattice energies (kJ/mol) calculated with B86bPBE50-XDM using the `lightdense' basis sets and associated XDM parameters against B86bPBE50-revXDM parameters ($a_1 = 0.74$ \AA{} and $a_2 = 1.72$ \AA{}) with `lightdense' basis sets in FHI-aims. The reference (LNO-MBE-)CCSD(T) lattice energies are also shown.",
    replace_input = {"[t]": "[c]"},
    float_fmt="%.1f",
    column_format="lrrr",
    filename = "Tables/SI_Table-X23_XDM_Comparison.tex")

                     CCSD(T) B86bPBE50-XDM (lightdense) B86bPBE50-revXDM
1,4-cyclohexanedione   -92.2                      -85.6            -91.2
Acetic Acid            -70.3                      -69.5            -73.6
Adamantane             -67.5                      -59.2            -63.5
Ammonia                -38.6                      -34.4            -36.5
Anthracene            -113.9                     -106.0           -112.8
Benzene                -52.8                      -50.2            -53.4
CO$_2$                 -27.9                      -24.6            -27.7
Cyanamide              -82.4                      -79.7            -82.8
Cytosine              -161.9                     -154.0           -160.4
Ethyl carbamate        -85.0                      -79.6            -84.2
Formamide              -80.8                      -76.2            -79.8
Hexamine               -88.1                      -86.7            -91.2
Imidazole              -88.8                      -86.1            -89.6
Naphthalene            -83.8                      -78.0            -82.8
Oxalic Acid $\alpha$   -99.3                      -97.3           -104.0
Oxalic Acid $\beta$    -98.8                      -94.8           -101.4
Pyrazine               -63.5                      -59.8            -63.8
Pyrazole               -78.5                      -76.0            -79.6
Succinic Acid         -125.0                     -123.8           -131.4
Triazine               -61.5                      -56.3            -60.1
Trioxane               -64.1                      -58.0            -63.4
Uracil                -137.2                     -132.4           -138.7
Urea                  -107.0                     -100.4           -104.5
MAD (kJ/mol)                                        4.4              1.8

In [55]:
# Create a table for ICE13

ice13_systems = {
    1: 'Ih',
    2: 'II',
    3: 'III',
    4: 'IV',
    6: 'VI',
    7: 'VII',
    8: 'VIII',
    9: 'IX',
    11: 'XI',
    13: 'XIII',
    14: 'XIV',
    15: 'XV',
    17: 'XVII'
}

ice13_xdm_compare_dict = {}
for idx, ice13_idx in enumerate(ice13_xdm_default_elatt_dict):
    ice13_xdm_compare_dict[ice13_systems[ice13_idx]] = {
        'DMC': round(dmc_ice13_latte_list[idx]/kjmol,1),
        'B86bPBE50-XDM (lightdense)': round(ice13_xdm_default_elatt_dict[ice13_idx]/kjmol,1),
        'B86bPBE50-revXDM': round(ice13_xdm_opt_elatt_dict[ice13_idx]/kjmol,1),
    }
ice13_xdm_compare_dict['MAD (kJ/mol)'] = {
    'DMC': '',
    'B86bPBE50-XDM (lightdense)': round(ice13_xdm_default_mad/kjmol,1),
    'B86bPBE50-revXDM': round(ice13_xdm_opt_mad/kjmol,1),
}

# Create a dataframe from the dictionary
ice13_xdm_df = pd.DataFrame(ice13_xdm_compare_dict).T
# Round to 1 d.p.
ice13_xdm_df = ice13_xdm_df.round(1)
# Display the dataframe
display(ice13_xdm_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = ice13_xdm_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:ice13_xdm_compare",
    caption = r"Comparison of ICE13 lattice energies (in kJ/mol) calculated with B86bPBE50-XDM using the `lightdense' basis sets and associated XDM parameters against B86bPBE50-revXDM parameters ($a_1 = 0.74$ \AA{} and $a_2 = 1.72$ \AA{}) obtained in this work, against the DMC-ICE13 reference values.",
    replace_input = {"[t]": "[c]"},
    float_fmt="%.1f",
    column_format="lrrr",
    filename = "Tables/SI_Table-ICE13_XDM_Comparison.tex")

               DMC B86bPBE50-XDM (lightdense) B86bPBE50-revXDM
Ih           -59.5                      -59.7            -60.9
II           -59.1                      -57.5            -59.1
III          -58.2                      -56.9            -58.3
IV           -55.6                      -54.4            -56.1
VI           -57.7                      -55.0            -56.8
VII          -54.5                      -50.9            -53.0
VIII         -55.2                      -52.0            -54.1
IX           -58.9                      -57.6            -59.1
XI           -59.3                      -59.6            -60.8
XIII         -57.3                      -56.5            -58.2
XIV          -57.7                      -55.9            -57.6
XV           -57.7                      -55.1            -56.9
XVII         -57.7                      -58.4            -59.5
MAD (kJ/mol)                              1.6              0.8

## Computational cost for X23 dataset

In [56]:
revxdm_x23_cpuh_list = {x23_idx: 0 for x23_idx in range(1,24)}

for x23_idx in range(1,24):
    revxdm_x23_cpuh_list[x23_idx] = read_total_time_from_aims_output_file(f'Data/X23/DFT/AIMS/{prl_to_x23_order[x23_idx]:02d}/molecule/aims_03.out.gz')/3600*128 + read_total_time_from_aims_output_file(f'Data/X23/DFT/AIMS/{prl_to_x23_order[x23_idx]:02d}/solid/aims_03.out.gz')/3600*512

# Create a dataframe from the dictionary
x23_xdm_cpuh_df = pd.DataFrame.from_dict(revxdm_x23_cpuh_list, orient='index', columns=['B86bPBE50-revXDM CPUh'])
# Round to 1 d.p.
x23_xdm_cpuh_df = x23_xdm_cpuh_df.round(0).astype(int)
# Add a column for system names
x23_xdm_cpuh_df.insert(0, 'System', [x23_labels[x23_idx] for x23_idx in x23_xdm_cpuh_df.index])
# Set index to system names
x23_xdm_cpuh_df.set_index('System', inplace=True)
# Add row for mean
x23_xdm_cpuh_df.loc['Mean'] = x23_xdm_cpuh_df['B86bPBE50-revXDM CPUh'].mean().round(0).astype(int)
# Display the dataframe
display(x23_xdm_cpuh_df)

# Convert to LaTeX table
convert_df_to_latex_input(
    df = x23_xdm_cpuh_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_xdm_cpuh",
    caption = r"Computational cost in CPU core-hours (CPUh) required for B86bPBE50-revXDM calculations with `lightdense' basis sets in FHI-aims for the X23 set on 128 cores for the molecular calculations and 512 cores for the molecular crystal calculations. These were performed on AMD EPYC 7742 2.25 GHz processors.",
    replace_input = {"[t]": "[c]"},
    float_fmt="%.0f",
    column_format="lr",
    filename = "Tables/SI_Table-X23_XDM_CPUh.tex")

                      B86bPBE50-revXDM CPUh
System
1,4-cyclohexanedione                      9
Acetic Acid                               8
Adamantane                               11
Ammonia                                   5
Anthracene                               12
Benzene                                   9
CO$_2$                                    6
Cyanamide                                10
Cytosine                                 14
Ethyl carbamate                           7
Formamide                                 8
Hexamine                                 11
Imidazole                                 9
Naphthalene                              11
Oxalic Acid $\alpha$                     11
Oxalic Acid $\beta$                       7
Pyrazine                                  7
Pyrazole                                 15
Succinic Acid                             8
Triazine                                 13
Trioxane                                 17
Uracil                                   14
Urea                                      7
Mean                                     10

# Relative energies of pharmaceutical polymorphs

## Sublimation enthalpy corrections from MLIPs

### MLIP convergence (EOS)

In [57]:
molecule_form = {
    'Axitinib': ['XLI','VI'],
    'ROY': ['R','Y']
}

gen_to_path = {
    "gen1": "gen1",
    "gen2": "gen2",
    "gen3": "gen1gen2gen3",
    "gen4": "gen1gen2gen3gen4",
    "gen5": "gen1gen2gen3gen4gen5",
}

eos_datasets = {molecule: {form: {} for form in forms} for molecule, forms in molecule_form.items()}

for molecule in ['Axitinib', 'ROY']:
    for form in molecule_form[molecule]:
        for gen in ['gen1', 'gen2', 'gen3', 'gen4']:
            eos_datasets[molecule][form][gen] = np.loadtxt(f'Data/Pharmaceutical/MLIP/{molecule}/eos/{gen_to_path[gen]}/{molecule}_{form}_EOS_{gen_to_path[gen]}.dat.gz')

In [58]:

fig, ax = plt.subplots(1,2,figsize=(6.69,4),dpi=450,constrained_layout=True)


ax[0].plot(eos_datasets['ROY']['R']['gen2'][:,0],1000*(eos_datasets['ROY']['R']['gen2'][:,2]-np.min(eos_datasets['ROY']['R']['gen2'][:,2])),
           'o--',label='Reference',ms=12)

ax[0].plot(eos_datasets['ROY']['R']['gen1'][:,0],1000*(eos_datasets['ROY']['R']['gen1'][:,1]-np.min(eos_datasets['ROY']['R']['gen1'][:,1])),
           'o--',label='gen1',mfc='none',ms=10)
ax[0].plot(eos_datasets['ROY']['R']['gen2'][:,0],1000*(eos_datasets['ROY']['R']['gen2'][:,1]-np.min(eos_datasets['ROY']['R']['gen2'][:,1])),
           'o--',label='gen2',mfc='none',ms=10)
ax[0].plot(eos_datasets['ROY']['R']['gen3'][:,0],1000*(eos_datasets['ROY']['R']['gen3'][:,1]-np.min(eos_datasets['ROY']['R']['gen3'][:,1])),
           'o--',label='gen3',mfc='none',ms=10)
ax[0].plot(eos_datasets['ROY']['R']['gen4'][:,0],1000*(eos_datasets['ROY']['R']['gen4'][:,1]-np.min(eos_datasets['ROY']['R']['gen4'][:,1])),
           'o--',label='gen4',mfc='none',ms=10)
    


ax[1].plot(eos_datasets['ROY']['Y']['gen2'][:,0],1000*(eos_datasets['ROY']['Y']['gen2'][:,2]-np.min(eos_datasets['ROY']['Y']['gen2'][:,2])),
           'o--',label='Reference',ms=12)


ax[1].plot(eos_datasets['ROY']['Y']['gen1'][:,0],1000*(eos_datasets['ROY']['Y']['gen1'][:,1]-np.min(eos_datasets['ROY']['Y']['gen1'][:,1])),
           'o--',label='gen1',mfc='none',ms=10)
ax[1].plot(eos_datasets['ROY']['Y']['gen2'][:,0],1000*(eos_datasets['ROY']['Y']['gen2'][:,1]-np.min(eos_datasets['ROY']['Y']['gen2'][:,1])),
           'o--',label='gen2',mfc='none',ms=10)
ax[1].plot(eos_datasets['ROY']['Y']['gen3'][:,0],1000*(eos_datasets['ROY']['Y']['gen3'][:,1]-np.min(eos_datasets['ROY']['Y']['gen3'][:,1])),
           'o--',label='gen3',mfc='none',ms=10)
ax[1].plot(eos_datasets['ROY']['Y']['gen4'][:,0],1000*(eos_datasets['ROY']['Y']['gen4'][:,1]-np.min(eos_datasets['ROY']['Y']['gen4'][:,1])),
           'o--',label='gen4',mfc='none',ms=10)


ax[0].set_ylabel('Energy [meV/mol]',fontsize=14)
ax[0].set_xlabel('Volume [$\AA^3$]',fontsize=14)
ax[1].set_xlabel('Volume [$\AA^3$]',fontsize=14)

ax[0].set_title('ROY-R',fontsize=14)
ax[1].set_title('ROY-Y',fontsize=14)

ax[0].grid(ls='dotted',alpha=.6)
ax[1].grid(ls='dotted',alpha=.6)

ax[0].legend(edgecolor='black',fontsize=12,fancybox=False)

ax[0].tick_params(labelsize=12)
ax[1].tick_params(labelsize=12)

plt.savefig('Figures/SI_Figure-ROY_EOS.png')

In [59]:
fig, ax = plt.subplots(1,2,figsize=(6.69,4),dpi=450,constrained_layout=True)


ax[0].plot(eos_datasets['Axitinib']['VI']['gen2'][:,0],1000*(eos_datasets['Axitinib']['VI']['gen2'][:,2]-np.min(eos_datasets['Axitinib']['VI']['gen2'][:,2])),
           'o--',label='Reference',ms=12)


ax[0].plot(eos_datasets['Axitinib']['VI']['gen1'][:,0],1000*(eos_datasets['Axitinib']['VI']['gen1'][:,1]-np.min(eos_datasets['Axitinib']['VI']['gen1'][:,1])),
           'o--',label='gen1',mfc='none',ms=10)
ax[0].plot(eos_datasets['Axitinib']['VI']['gen2'][:,0],1000*(eos_datasets['Axitinib']['VI']['gen2'][:,1]-np.min(eos_datasets['Axitinib']['VI']['gen2'][:,1])),
           'o--',label='gen2',mfc='none',ms=10)
ax[0].plot(eos_datasets['Axitinib']['VI']['gen3'][:,0],1000*(eos_datasets['Axitinib']['VI']['gen3'][:,1]-np.min(eos_datasets['Axitinib']['VI']['gen3'][:,1])),
           'o--',label='gen3',mfc='none',ms=10)
ax[0].plot(eos_datasets['Axitinib']['VI']['gen4'][:,0],1000*(eos_datasets['Axitinib']['VI']['gen4'][:,1]-np.min(eos_datasets['Axitinib']['VI']['gen4'][:,1])),
           'o--',label='gen4',mfc='none',ms=10)


ax[1].plot(eos_datasets['Axitinib']['XLI']['gen2'][:,0],1000*(eos_datasets['Axitinib']['XLI']['gen2'][:,2]-np.min(eos_datasets['Axitinib']['XLI']['gen2'][:,2])),
           'o--',label='Reference',ms=12)

ax[1].plot(eos_datasets['Axitinib']['XLI']['gen1'][:,0],1000*(eos_datasets['Axitinib']['XLI']['gen1'][:,1]-np.min(eos_datasets['Axitinib']['XLI']['gen1'][:,1])),
           'o--',label='gen1',mfc='none',ms=10)
ax[1].plot(eos_datasets['Axitinib']['XLI']['gen2'][:,0],1000*(eos_datasets['Axitinib']['XLI']['gen2'][:,1]-np.min(eos_datasets['Axitinib']['XLI']['gen2'][:,1])),
           'o--',label='gen2',mfc='none',ms=10)
ax[1].plot(eos_datasets['Axitinib']['XLI']['gen3'][:,0],1000*(eos_datasets['Axitinib']['XLI']['gen3'][:,1]-np.min(eos_datasets['Axitinib']['XLI']['gen3'][:,1])),
           'o--',label='gen3',mfc='none',ms=10)
ax[1].plot(eos_datasets['Axitinib']['XLI']['gen4'][:,0],1000*(eos_datasets['Axitinib']['XLI']['gen4'][:,1]-np.min(eos_datasets['Axitinib']['XLI']['gen4'][:,1])),
           'o--',label='gen4',mfc='none',ms=10)

ax[0].set_ylabel('Energy [meV/mol]',fontsize=14)
ax[0].set_xlabel('Volume [$\AA^3$]',fontsize=14)
ax[1].set_xlabel('Volume [$\AA^3$]',fontsize=14)

ax[0].set_title('Axitinib-VI',fontsize=14)
ax[1].set_title('Axitinib-XLI',fontsize=14)

ax[0].grid(ls='dotted',alpha=.6)
ax[1].grid(ls='dotted',alpha=.6)

ax[0].legend(edgecolor='black',fontsize=12,fancybox=False)

ax[0].tick_params(labelsize=12)
ax[1].tick_params(labelsize=12)

plt.savefig('Figures/SI_Figure-Axitinib_EOS.png')

### MLIP convergence (DeltaH)

In [60]:
# Define all the systems, polymorphs, and generations
systems = {
    "ROY": {
        "R": ["gen1", "gen2", "gen3", "gen4", "gen5"],
        "Y": ["gen1", "gen2", "gen3", "gen4", "gen5"]
    },
    "Axitinib": {
        "VI": ["gen1", "gen2", "gen3", "gen4", "gen5"],
        "XLI": ["gen1", "gen2", "gen3", "gen4", "gen5"]
    }
}

gen_to_path = {
    "gen1": "gen1",
    "gen2": "gen1gen2",
    "gen3": "gen1gen2gen3",
    "gen4": "gen1gen2gen3gen4",
    "gen5": "gen1gen2gen3gen4gen5",
}

# Template paths
paths = {
    "MD": "Data/Pharmaceutical/MLIP/{sys}/deltaH/cmd/{poly}/{gen}/simulation.out.gz",
    "Elatt": "Data/Pharmaceutical/MLIP/{sys}/deltaH/0K/{gen}/Energy_{poly}.gz",
    "ZPE": "Data/Pharmaceutical/MLIP/{sys}/deltaH/qha/{poly}/{gen}/thermo/THERMO.gz",
    "QHA": "Data/Pharmaceutical/MLIP/{sys}/deltaH/qha/{poly}/{gen}/thermo/THERMO.gz"
}

# Load everything into one big nested dict
pharma_delta_data = {}
for sys, polymorphs in systems.items():
    pharma_delta_data[sys] = {}
    for poly, gens in polymorphs.items():
        pharma_delta_data[sys][poly] = {}
        for gen in gens:
            pharma_delta_data[sys][poly][gen] = {}
            # MD trajectory
            md_path = paths["MD"].format(sys=sys, poly=poly, gen=gen_to_path[gen])
            pharma_delta_data[sys][poly][gen]["MD"] = np.loadtxt(md_path)
            # 0K energy
            en_path = paths["Elatt"].format(sys=sys, poly=poly, gen=gen_to_path[gen])
            pharma_delta_data[sys][poly][gen]["Elatt"] = np.loadtxt(en_path)
            # Vibrational energy at 300K (skiprows=31, column 1)
            vib_path = paths["ZPE"].format(sys=sys, poly=poly, gen=gen_to_path[gen])
            pharma_delta_data[sys][poly][gen]["ZPE"] = np.loadtxt(vib_path, usecols=1, skiprows=2, max_rows=1)
            # Load QHA (same file, distinguished separately for logical grouping)
            qha_path = paths["QHA"].format(sys=sys, poly=poly, gen=gen_to_path[gen])
            pharma_delta_data[sys][poly][gen]["QHA"] = np.loadtxt(qha_path, usecols=1, skiprows=31)

In [61]:
# number of molecules in unit cells:

n_mol_ROY_R_unit_cell = 2
n_mol_ROY_Y_unit_cell = 4

n_mol_ROY_R_simulated_cell = n_mol_ROY_R_unit_cell * 2 * 2 * 2
n_mol_ROY_Y_simulated_cell = n_mol_ROY_Y_unit_cell * 2 * 1 * 2

n_mol_Axitinib_VI_unit_cell = 2
n_mol_Axitinib_XLI_unit_cell = 4

n_mol_Axitinib_VI_simulated_cell = n_mol_Axitinib_VI_unit_cell * 2 * 2 * 2
n_mol_Axitinib_XLI_simulated_cell = n_mol_Axitinib_XLI_unit_cell * 1 * 2 * 1

ev_to_kjmol = 96.4853 

# compute the difference ∆H = H_R - H_Y

final_delta_dict = {
    'ROY': {gen: {'Elatt':0,  'Elatt + ZPE': 0, 'QHA': 0 , 'MD DeltaH': 0, 'PIMD DeltaH': 0,} for gen in pharma_delta_data['ROY']['R'].keys()},
    'Axitinib': {gen: {'Elatt':0,  'Elatt + ZPE': 0, 'QHA': 0 , 'MD DeltaH': 0, 'PIMD DeltaH': 0,} for gen in pharma_delta_data['ROY']['R'].keys()}
}

for gen in pharma_delta_data['ROY']['R'].keys():
    
    H_R = get_enthalpy_classical_md(kinetic_energy = pharma_delta_data['ROY']['R'][gen]['MD'][:,5],
                          potential_energy = pharma_delta_data['ROY']['R'][gen]['MD'][:,4],
                          volume = pharma_delta_data['ROY']['R'][gen]['MD'][:,7],
                          number_of_molecules = n_mol_ROY_R_simulated_cell,
                          pressure_bar = 1)                      

    H_Y = get_enthalpy_classical_md(kinetic_energy = pharma_delta_data['ROY']['Y'][gen]['MD'][:,5],
                          potential_energy = pharma_delta_data['ROY']['Y'][gen]['MD'][:,4],
                          volume = pharma_delta_data['ROY']['Y'][gen]['MD'][:,7],
                          number_of_molecules = n_mol_ROY_Y_simulated_cell,
                          pressure_bar = 1)  

    final_delta_dict['ROY'][gen]['MD DeltaH'] = np.array([(H_R[0] - H_Y[0]) * ev_to_kjmol, 
                               np.sqrt(H_R[1]**2 + H_Y[1]**2)*ev_to_kjmol])
    
# compute the difference ∆H = H_VI - H_XLI
for gen in pharma_delta_data['Axitinib']['VI'].keys():
    
    H_VI = get_enthalpy_classical_md(kinetic_energy = pharma_delta_data['Axitinib']['VI'][gen]['MD'][:,5],
                          potential_energy = pharma_delta_data['Axitinib']['VI'][gen]['MD'][:,4],
                          volume = pharma_delta_data['Axitinib']['VI'][gen]['MD'][:,7],
                          number_of_molecules = n_mol_Axitinib_VI_simulated_cell,
                          pressure_bar = 1)                      

    H_XLI = get_enthalpy_classical_md(kinetic_energy = pharma_delta_data['Axitinib']['XLI'][gen]['MD'][:,5],
                          potential_energy = pharma_delta_data['Axitinib']['XLI'][gen]['MD'][:,4],
                          volume = pharma_delta_data['Axitinib']['XLI'][gen]['MD'][:,7],
                          number_of_molecules = n_mol_Axitinib_XLI_simulated_cell,
                          pressure_bar = 1)  

    final_delta_dict['Axitinib'][gen]['MD DeltaH'] = np.array([(H_VI[0] - H_XLI[0]) * ev_to_kjmol, 
                               np.sqrt(H_VI[1]**2 + H_XLI[1]**2)*ev_to_kjmol])
    
# compute the difference ∆E = E_R - E_Y

for gen in pharma_delta_data['ROY']['R'].keys():
    
    E_R = pharma_delta_data['ROY']['R'][gen]['Elatt']
    E_Y = pharma_delta_data['ROY']['Y'][gen]['Elatt']                 

    final_delta_dict['ROY'][gen]['Elatt'] = (E_R-E_Y)*ev_to_kjmol
    
# compute the difference ∆E = E_VI - E_XLI
    
for gen in pharma_delta_data['Axitinib']['VI'].keys():
    
    E_VI = pharma_delta_data['Axitinib']['VI'][gen]['Elatt']              
    E_XLI = pharma_delta_data['Axitinib']['XLI'][gen]['Elatt']                 

    final_delta_dict['Axitinib'][gen]['Elatt'] = (E_VI-E_XLI)*ev_to_kjmol

# save ∆E_zpe = E_zpe_R - E_zpe_Y

deltaZPE_ROY = {}

for gen in pharma_delta_data['ROY']['R'].keys():
    
    ZPE_R = pharma_delta_data['ROY']['R'][gen]['ZPE']                 

    ZPE_Y = pharma_delta_data['ROY']['Y'][gen]['ZPE']                      

    final_delta_dict['ROY'][gen]['Elatt + ZPE'] = final_delta_dict['ROY'][gen]['Elatt'] + (ZPE_R/n_mol_ROY_R_unit_cell - ZPE_Y/n_mol_ROY_Y_unit_cell)*ev_to_kjmol

# save ∆E_zpe = E_zpe_VI - E_zpe_XLI
 
deltaZPE_Axitinib = {}

for gen in pharma_delta_data['Axitinib']['VI'].keys():
    
    ZPE_VI = pharma_delta_data['Axitinib']['VI'][gen]['ZPE']                 

    ZPE_XLI = pharma_delta_data['Axitinib']['XLI'][gen]['ZPE']                 

    final_delta_dict['Axitinib'][gen]['Elatt + ZPE'] = final_delta_dict['Axitinib'][gen]['Elatt'] + (ZPE_VI/n_mol_Axitinib_VI_unit_cell - ZPE_XLI/n_mol_Axitinib_XLI_unit_cell)*ev_to_kjmol

# compute ∆E_vib = E_vib_R - E_vib_Y
deltaEVIB_ROY = {}

for gen in pharma_delta_data['ROY']['R'].keys():
    
    EVIB_R = pharma_delta_data['ROY']['R'][gen]['QHA']                 

    EVIB_Y = pharma_delta_data['ROY']['Y'][gen]['QHA']                  

    final_delta_dict['ROY'][gen]['QHA'] = final_delta_dict['ROY'][gen]['Elatt'] + (EVIB_R/n_mol_ROY_R_unit_cell - EVIB_Y/n_mol_ROY_Y_unit_cell)*ev_to_kjmol

# compute ∆E_vib = E_vib_VI - E_vib_XLI

deltaEVIB_Axitinib = {}

for gen in pharma_delta_data['Axitinib']['VI'].keys():
    
    EVIB_VI = pharma_delta_data['Axitinib']['VI'][gen]['QHA']                 

    EVIB_XLI = pharma_delta_data['Axitinib']['XLI'][gen]['QHA']                  

    final_delta_dict['Axitinib'][gen]['QHA'] = final_delta_dict['Axitinib'][gen]['Elatt'] + (EVIB_VI/n_mol_Axitinib_VI_unit_cell - EVIB_XLI/n_mol_Axitinib_XLI_unit_cell)*ev_to_kjmol

In [62]:
# Compute PIMD corrections

H_R_pimd = np.loadtxt('Data/Pharmaceutical/MLIP/ROY/deltaH/pimd/R/gen1gen2gen3gen4gen5/simulation.out.gz')
H_Y_pimd = np.loadtxt('Data/Pharmaceutical/MLIP/ROY/deltaH/pimd/Y/gen1gen2gen3gen4gen5/simulation.out.gz')

H_R_pimd_final = get_enthalpy_classical_md(kinetic_energy = H_R_pimd[:,5],
                      potential_energy = H_R_pimd[:,4],
                      volume = H_R_pimd[:,7],
                      number_of_molecules = n_mol_ROY_R_simulated_cell,
                      pressure_bar = 1)

H_Y_pimd_final = get_enthalpy_classical_md(kinetic_energy = H_Y_pimd[:,5],
                      potential_energy = H_Y_pimd[:,4],
                      volume = H_Y_pimd[:,7],
                      number_of_molecules = n_mol_ROY_Y_simulated_cell,
                      pressure_bar = 1)

final_delta_dict['ROY']['gen5']['PIMD DeltaH'] = np.array([(H_R_pimd_final[0] - H_Y_pimd_final[0]) * ev_to_kjmol, 
                           np.sqrt(H_R_pimd_final[1]**2 + H_Y_pimd_final[1]**2)*ev_to_kjmol])


H_VI_pimd = np.loadtxt('Data/Pharmaceutical/MLIP/Axitinib/deltaH/pimd/VI/gen1gen2gen3gen4gen5/simulation.out.gz')
H_XLI_pimd = np.loadtxt('Data/Pharmaceutical/MLIP/Axitinib/deltaH/pimd/XLI/gen1gen2gen3gen4gen5/simulation.out.gz')

H_VI_pimd_final = get_enthalpy_classical_md(kinetic_energy = H_VI_pimd[:,5],
                      potential_energy = H_VI_pimd[:,4],
                      volume = H_VI_pimd[:,7],
                      number_of_molecules = n_mol_Axitinib_VI_simulated_cell,
                      pressure_bar = 1)
H_XLI_pimd_final = get_enthalpy_classical_md(kinetic_energy = H_XLI_pimd[:,5],
                      potential_energy = H_XLI_pimd[:,4],
                      volume = H_XLI_pimd[:,7],
                      number_of_molecules = n_mol_Axitinib_XLI_simulated_cell,
                      pressure_bar = 1)

final_delta_dict['Axitinib']['gen5']['PIMD DeltaH'] = np.array([(H_VI_pimd_final[0] - H_XLI_pimd_final[0]) * ev_to_kjmol, 
                           np.sqrt(H_VI_pimd_final[1]**2 + H_XLI_pimd_final[1]**2)*ev_to_kjmol])

In [63]:
# ROY

fig, ax = plt.subplots(figsize=(6.69,4),dpi=450,constrained_layout=True)

for i,j in enumerate(final_delta_dict['ROY'].keys()):
    
    label_e = r'$E_\text{latt}$' if i == 0 else None
    label_zpe = r'$E_\text{latt}$+ZPE' if i == 0 else None
    label_qha = 'QHA' if i == 0 else None
    label_md = 'MD' if i == 0 else None


    #0K - electrons
    ax.plot(i+1,final_delta_dict['ROY'][j]['Elatt'],
                marker='o',ms=12,
                mfc='none',
                color='firebrick',label=label_e)
    
    #0K - with zpe
    ax.plot(i+1,final_delta_dict['ROY'][j]['Elatt + ZPE'],
                marker='s',ms=12,
                mfc='none',
                color='orange',label=label_zpe)   
    
    #QHA
    ax.plot(i+1,final_delta_dict['ROY'][j]['QHA'],
                marker='^',ms=10,
                mfc='none',
                color='royalblue',label=label_qha)

    # MD
    ax.errorbar(i+1,final_delta_dict['ROY'][j]['MD DeltaH'][0],
                final_delta_dict['ROY'][j]['MD DeltaH'][1],
                marker='>',ms=10,
                capsize=6,
                mfc='none',
                color='navy', label=label_md)
    
# PIMD
ax.errorbar(5,final_delta_dict['ROY']['gen5']['PIMD DeltaH'][0],
            final_delta_dict['ROY']['gen5']['PIMD DeltaH'][1],
            marker='x',ms=10,
            capsize=6,
            color='darkgreen', label='PIMD')
    
ax.set_ylabel(r'$\Delta H = H_\text{R} - H_\text{Y}$ [kJ/mol]',fontsize=14)
ax.set_xlabel('MLIP Iteration',fontsize=16)

ax.set_xlim([0.5,5.5])
ax.set_xticks([1,2,3,4,5])
ax.set_ylim([0,6])
ax.tick_params(labelsize=14)
plt.grid(ls='dotted',alpha=.4)
plt.legend(edgecolor='black',fancybox=False,ncols=2,fontsize=10)
plt.title('ROY',fontsize=16)
plt.savefig('Figures/SI_Figure-ROY_deltaH.png')

In [64]:
# Axitinib

fig, ax = plt.subplots(figsize=(6.69,4),dpi=450,constrained_layout=True)

for i,j in enumerate(final_delta_dict['Axitinib'].keys()):
    
    label_e = r'$E_\text{latt}$' if i == 0 else None
    label_zpe = r'$E_\text{latt}$+ZPE' if i == 0 else None
    label_qha = 'QHA' if i == 0 else None
    label_md = 'MD' if i == 0 else None

    #0K - electrons
    ax.plot(i+1,final_delta_dict['Axitinib'][j]['Elatt'],
                marker='o',ms=12,
                mfc='none',
                color='firebrick',label=label_e)
    
    #0K - with zpe
    ax.plot(i+1,final_delta_dict['Axitinib'][j]['Elatt + ZPE'],
                marker='s',ms=12,
                mfc='none',
                color='orange',label=label_zpe)   
    
    #QHA
    ax.plot(i+1,final_delta_dict['Axitinib'][j]['QHA'],
                marker='^',ms=10,
                mfc='none',
                color='royalblue',label=label_qha)

    # MD
    ax.errorbar(i+1,final_delta_dict['Axitinib'][j]['MD DeltaH'][0],
                final_delta_dict['Axitinib'][j]['MD DeltaH'][1],
                marker='>',ms=10,
                mfc='none',
                capsize=6,
                color='navy', label=label_md)    
    

# PIMD
ax.errorbar(5,final_delta_dict['Axitinib']['gen5']['PIMD DeltaH'][0],
            final_delta_dict['Axitinib']['gen5']['PIMD DeltaH'][1],
            marker='x',ms=10,
            capsize=6,
            mfc='none',
            color='darkgreen', label='PIMD')
    
ax.set_ylabel(r'$\Delta H = H_\text{VI} - H_\text{XLI}$ [kJ/mol]',fontsize=14)
ax.set_xlabel('MLIP Iteration',fontsize=16)

ax.set_xlim([0.5,5.5])
ax.set_xticks([1,2,3,4,5])
ax.set_ylim([0,6])
ax.tick_params(labelsize=14)
plt.grid(ls='dotted',alpha=.4)
plt.legend(edgecolor='black',fancybox=False,ncols=2,fontsize=10)
plt.title('Axitinib',fontsize=16)
plt.savefig('Figures/SI_Figure-Axitinib_deltaH.png')

### MLIP convergence (VDOS)

In [65]:
# Path template for DOS.cm files
vdos_template = "Data/Pharmaceutical/MLIP/{system}/deltaH/qha/{poly}/{gen}/thermo/DOS.cm.gz"

# Compact loader
pharma_vdos_data = {}

for system, polymorphs in systems.items():
    pharma_vdos_data[system] = {}
    for poly, generations in polymorphs.items():
        pharma_vdos_data[system][poly] = {}
        for gen in generations:
            path = vdos_template.format(system=system, poly=poly, gen=gen_to_path[gen])
            pharma_vdos_data[system][poly][gen] = np.loadtxt(path)

In [66]:
# PLOT for ROY

fig, ax = plt.subplots(2,1,figsize=(6.69,7),dpi=450,constrained_layout=True)

# ax[0] for polymorph R
ax[0].plot(pharma_vdos_data['ROY']['R']['gen1'][:,0], 
           pharma_vdos_data['ROY']['R']['gen1'][:,1],color='black',label='1')
shift = 0.004
ax[0].plot(pharma_vdos_data['ROY']['R']['gen2'][:,0], 
           pharma_vdos_data['ROY']['R']['gen2'][:,1]+shift,color='blue',label='2')
ax[0].plot(pharma_vdos_data['ROY']['R']['gen3'][:,0], 
           pharma_vdos_data['ROY']['R']['gen3'][:,1]+2*shift,color='cyan',label='3')
ax[0].plot(pharma_vdos_data['ROY']['R']['gen4'][:,0], 
           pharma_vdos_data['ROY']['R']['gen4'][:,1]+3*shift,color='orange',label='4')
ax[0].plot(pharma_vdos_data['ROY']['R']['gen5'][:,0], 
           pharma_vdos_data['ROY']['R']['gen5'][:,1]+4*shift,color='red',label='5')

# ax[1] for polymorph R
ax[1].plot(pharma_vdos_data['ROY']['Y']['gen1'][:,0], 
           pharma_vdos_data['ROY']['Y']['gen1'][:,1],color='black',label='1')
shift = 0.004
ax[1].plot(pharma_vdos_data['ROY']['Y']['gen2'][:,0], 
           pharma_vdos_data['ROY']['Y']['gen2'][:,1]+shift,color='blue',label='2')
ax[1].plot(pharma_vdos_data['ROY']['Y']['gen3'][:,0], 
           pharma_vdos_data['ROY']['Y']['gen3'][:,1]+2*shift,color='cyan',label='3')
ax[1].plot(pharma_vdos_data['ROY']['Y']['gen4'][:,0], 
           pharma_vdos_data['ROY']['Y']['gen4'][:,1]+3*shift,color='orange',label='4')
ax[1].plot(pharma_vdos_data['ROY']['Y']['gen5'][:,0], 
           pharma_vdos_data['ROY']['Y']['gen5'][:,1]+4*shift,color='red',label='5')


ax[0].set_ylabel('VDOS [au]',fontsize=16)
ax[1].set_ylabel('VDOS [au]',fontsize=16)
ax[1].set_xlabel('Frequency [cm$^{-1}$]',fontsize=16)

ax[0].tick_params(labelsize=14)
ax[1].tick_params(labelsize=14)

ax[0].set_title('ROY - R',fontsize=16)
ax[1].set_title('ROY - Y',fontsize=16)

ax[0].set_xlim([-50,4000])
ax[1].set_xlim([-50,4000])

ax[0].set_yticks([])
ax[1].set_yticks([])

ax[0].legend(fontsize=12,edgecolor='black',fancybox=False,ncols=3,loc='center')
ax[0].grid(ls='dotted',alpha=.6)
ax[1].grid(ls='dotted',alpha=.6)

plt.savefig('Figures/SI_Figure-ROY_VDOS.png')

In [ ]:
# PLOT for Axitinib

fig, ax = plt.subplots(2,1,figsize=(6.69,7),dpi=450,constrained_layout=True)

# ax[0] for polymorph VI
ax[0].plot(pharma_vdos_data['Axitinib']['VI']['gen1'][:,0], 
           pharma_vdos_data['Axitinib']['VI']['gen1'][:,1],color='black',label='1')
shift = 0.004
ax[0].plot(pharma_vdos_data['Axitinib']['VI']['gen2'][:,0], 
           pharma_vdos_data['Axitinib']['VI']['gen2'][:,1]+shift,color='blue',label='2')
ax[0].plot(pharma_vdos_data['Axitinib']['VI']['gen3'][:,0], 
           pharma_vdos_data['Axitinib']['VI']['gen3'][:,1]+2*shift,color='cyan',label='3')
ax[0].plot(pharma_vdos_data['Axitinib']['VI']['gen4'][:,0], 
           pharma_vdos_data['Axitinib']['VI']['gen4'][:,1]+3*shift,color='orange',label='4')
ax[0].plot(pharma_vdos_data['Axitinib']['VI']['gen5'][:,0], 
           pharma_vdos_data['Axitinib']['VI']['gen5'][:,1]+4*shift,color='red',label='5')

# ax[1] for polymorph XLI
ax[1].plot(pharma_vdos_data['Axitinib']['XLI']['gen1'][:,0], 
           pharma_vdos_data['Axitinib']['XLI']['gen1'][:,1],color='black',label='1')
shift = 0.004
ax[1].plot(pharma_vdos_data['Axitinib']['XLI']['gen2'][:,0], 
           pharma_vdos_data['Axitinib']['XLI']['gen2'][:,1]+shift,color='blue',label='2')
ax[1].plot(pharma_vdos_data['Axitinib']['XLI']['gen3'][:,0], 
           pharma_vdos_data['Axitinib']['XLI']['gen3'][:,1]+2*shift,color='cyan',label='3')
ax[1].plot(pharma_vdos_data['Axitinib']['XLI']['gen4'][:,0], 
           pharma_vdos_data['Axitinib']['XLI']['gen4'][:,1]+3*shift,color='orange',label='4')
ax[1].plot(pharma_vdos_data['Axitinib']['XLI']['gen5'][:,0], 
           pharma_vdos_data['Axitinib']['XLI']['gen5'][:,1]+4*shift,color='red',label='5')


ax[0].set_ylabel('VDOS [au]',fontsize=16)
ax[1].set_ylabel('VDOS [au]',fontsize=16)
ax[1].set_xlabel('Frequency [cm$^{-1}$]',fontsize=16)

ax[0].tick_params(labelsize=14)
ax[1].tick_params(labelsize=14)

ax[0].set_title('Axitinib - VI',fontsize=16)
ax[1].set_title('Axitinib - XLI',fontsize=16)

ax[0].set_xlim([-50,4000])
ax[1].set_xlim([-50,4000])

ax[0].set_yticks([])
ax[1].set_yticks([])

ax[0].legend(fontsize=12,edgecolor='black',fancybox=False,ncols=3,loc='center')
ax[0].grid(ls='dotted',alpha=.6)
ax[1].grid(ls='dotted',alpha=.6)

plt.savefig('Figures/SI_Figure-Axitinib_VDOS.png')

### Final DeltaH estimates

In [67]:
# Pandas DataFrame for the final results
final_delta_df = pd.DataFrame.from_dict(
    {
        (i, j): {
            ('MLIP Generation', k[-1:]):
                (
                    '-' if (j == 'PIMD DeltaH' and k != 'gen5')
                    else f'{final_delta_dict[i][k][j]:.1f}'
                    if j not in ['MD DeltaH', 'PIMD DeltaH']
                    else f'{final_delta_dict[i][k][j][0]:.1f}$\\pm${final_delta_dict[i][k][j][1]:.1f}'
                )
            for k in ['gen1', 'gen2', 'gen3', 'gen4', 'gen5']
        }
        for i in final_delta_dict.keys()
        for j in final_delta_dict[i]['gen1'].keys()
    },
    orient='index'
)

display(final_delta_df)

# Write to LaTeX table
convert_df_to_latex_input(
    df = final_delta_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:pharma_deltaH",
    caption = r"Relative between ROY (forms R and Y) and Axitinib (forms VI and XLI)as predicted by MLIPs of different generations. All values are in kJ/mol. Statistical uncertainties ($1\sigma$) are reported for MD and PIMD results.",
    float_fmt="%.1f",
    replace_input = {
        "[t]": "[c]"
    },
    column_format = "lrrrrrr",
    filename = "Tables/SI_Table-Pharma_DeltaH.tex")

                     MLIP Generation                                         \
                                   1            2            3            4
ROY      Elatt                   2.8          1.6          1.6          1.2
         Elatt + ZPE             2.8          2.3          1.5          1.6
         QHA                     2.9          2.1          1.5          1.5
         MD DeltaH       1.5$\pm$0.1  2.1$\pm$0.1  1.5$\pm$0.1  0.9$\pm$0.1
         PIMD DeltaH               -            -            -            -
Axitinib Elatt                   5.6          2.8          2.7          2.9
         Elatt + ZPE             5.0          2.9          3.7          3.4
         QHA                     5.1          2.4          3.2          2.8
         MD DeltaH       1.4$\pm$0.2  3.9$\pm$0.2  4.1$\pm$0.2  3.7$\pm$0.2
         PIMD DeltaH               -            -            -            -


                                5
ROY      Elatt                1.6
         Elatt + ZPE          2.2
         QHA                  2.0
         MD DeltaH    1.6$\pm$0.1
         PIMD DeltaH  1.5$\pm$0.5
Axitinib Elatt                3.4
         Elatt + ZPE          3.2
         QHA                  3.0
         MD DeltaH    3.3$\pm$0.2
         PIMD DeltaH  2.1$\pm$0.6

## Final experimental relative energy estimates

In [68]:
experimental_rel_energy_dict = {
    'Rotigotine': {'DFT DeltaE': 7.1 , 'DFT DeltaHMD': 7.6 ,'Expt. DeltaH': r"7.5$\pm$0.5~\cite{mortazaviComputationalPolymorphScreening2019}", 'Expt. DeltaE': r"7.0$\pm$0.5"},
    'Axitinib': {'DFT DeltaE': final_delta_dict['Axitinib']['gen5']['Elatt'] , 'DFT DeltaHMD':  final_delta_dict['Axitinib']['gen5']['MD DeltaH'][0],'Expt. DeltaH': f"{19*386.47/(1000):.1f}$\pm$0.8" + r"~\cite{campetaDevelopmentTargetedPolymorph2010a}", 'Expt. DeltaE': f"{19*386.47/(1000) + final_delta_dict['Axitinib']['gen5']['Elatt'] - final_delta_dict['Axitinib']['gen5']['MD DeltaH'][0]:.1f}$\pm$0.8"},
    'ROY': {'DFT DeltaE': final_delta_dict['ROY']['gen5']['Elatt'] , 'DFT DeltaHMD':  final_delta_dict['ROY']['gen5']['MD DeltaH'][0],'Expt. DeltaH': r"1.2$\pm$0.5~\cite{yuPolymorphismMolecularSolids2010b}", 'Expt. DeltaE': f"{1.2 + final_delta_dict['ROY']['gen5']['Elatt'] - final_delta_dict['ROY']['gen5']['MD DeltaH'][0]:.1f}$\pm$0.5"}
}

experimental_rel_energy_num_dict = {
    'Rotigotine': {'DFT DeltaE': 7.1 , 'DFT DeltaHMD': 7.6 ,'Expt. DeltaH': 7.5, 'Expt. DeltaE': 7.0},
    'Axitinib': {'DFT DeltaE': final_delta_dict['Axitinib']['gen5']['Elatt'] , 'DFT DeltaHMD':  final_delta_dict['Axitinib']['gen5']['MD DeltaH'][0],'Expt. DeltaH': 19*386.47/(1000), 'Expt. DeltaE': 19*386.47/(1000) + final_delta_dict['Axitinib']['gen5']['Elatt'] - final_delta_dict['Axitinib']['gen5']['MD DeltaH'][0]},
    'ROY': {'DFT DeltaE': final_delta_dict['ROY']['gen5']['Elatt'] , 'DFT DeltaHMD':  final_delta_dict['ROY']['gen5']['MD DeltaH'][0],'Expt. DeltaH': 1.2, 'Expt. DeltaE': 1.2 + final_delta_dict['ROY']['gen5']['Elatt'] - final_delta_dict['ROY']['gen5']['MD DeltaH'][0]}
}

# Create DataFrame
exp_rel_ene_df = pd.DataFrame.from_dict(experimental_rel_energy_dict, orient='index')
# Convert to 1 d.p.
exp_rel_ene_df = exp_rel_ene_df.round(1)
# Display the DataFrame
display(exp_rel_ene_df)
# Write to LaTeX table
convert_df_to_latex_input(
    df = exp_rel_ene_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:pharma_expt_deltaH",
    caption = r"DFT static relative energy and relative enthalpy from MD simulations. Their difference is used to correct experimental enthalpies for the polymorph pairs of rotigotine (I and II), axitinib (VI and XLI) and ROY (R and Y).",
    float_fmt="%.1f",
    replace_input = {
        "DeltaHMD": r"$\Delta H^\text{MD}$",
        "DeltaE": r"$\Delta E$",
        "DeltaH": r"$\Delta H$",
    },
    filename = "Tables/SI_Table-Pharma_Expt_DeltaH.tex")

,DFT DeltaE,DFT DeltaHMD,Expt. DeltaH,Expt. DeltaE
Rotigotine,7.1,7.6,7.5$\pm$0.5~\cite{mortazaviComputationalPolymo...,7.0$\pm$0.5
Axitinib,3.4,3.3,7.3$\pm$0.8~\cite{campetaDevelopmentTargetedPo...,7.5$\pm$0.8
ROY,1.6,1.6,1.2$\pm$0.5~\cite{yuPolymorphismMolecularSolid...,1.2$\pm$0.5

## Periodic HF analysis

In [ ]:
# Analyse the periodic HF data for all of the polymorphs

pharma_polymorph_systems = {
    'ROY': ['R', 'Y'],
    'Axitinib': ['VI','XLI'],
    'Rotigotine': ['I_1','I_2','II_1','II_2'],
    'X': ['expt','vaneijck']
}

pharma_polymorph_num_molecules = {
    'ROY': {'R':2, 'Y':4},
    'Axitinib': {'VI': 2,'XLI': 4},
    'Rotigotine': {'I_1': 4, 'I_2': 4,'II_1': 4, 'II_2': 4},
    'X': {'expt':4,'vaneijck':2}
}

pharma_polymorph_ene_dict = {x: {} for x in pharma_polymorph_systems.keys()}
pharma_polymorph_method_ene_dict = {x: {} for x in pharma_polymorph_systems.keys()}

cutoff_2b_dists = np.arange(3.5,20.5,0.5)
cutoff_3b_dists = np.arange(100,810,10)

pharma_polymorph_2b_elatt_dict = {molecule: {form: {f'{cutoff:.1f}': {method: 0 for method in ['D4','Final','Delta']} for cutoff in cutoff_2b_dists} for form in pharma_polymorph_systems[molecule]} for molecule in pharma_polymorph_systems.keys()}
pharma_polymorph_3b_elatt_dict = {molecule: {form: {cutoff: {method: 0 for method in ['D4','Final','Delta']} for cutoff in cutoff_3b_dists} for form in pharma_polymorph_systems[molecule]} for molecule in pharma_polymorph_systems.keys()}

# Read the VASP OUTCAR files for the HF data
for molecule in ['ROY','Axitinib','Rotigotine','X']:
    for form in pharma_polymorph_systems[molecule]:
        struct = read(f'Data/Pharmaceutical/HF/VASP_Hard_Default/{molecule}/{form}/OUTCAR_HF.gz')
        struct_ene_1 = get_vasp_energy(f'Data/Pharmaceutical/HF/VASP_Hard_Default/{molecule}/{form}/OUTCAR_HF.gz')
        struct_ene_2 = get_vasp_energy(f'Data/Pharmaceutical/HF/VASP_Std_Default/{molecule}/{form}/OUTCAR_HF.gz')
        struct_ene_3 = get_vasp_energy(f'Data/Pharmaceutical/HF/VASP_Std_High/{molecule}/{form}/OUTCAR_HF.gz')

        struct_ene = (struct_ene_1 + struct_ene_3 - struct_ene_2)*1000/pharma_polymorph_num_molecules[molecule][form]

        d4_ene =  np.loadtxt(f'Data/Pharmaceutical/HF/VASP_Hard_Default/{molecule}/{form}/D4_HF.out.gz')*Hartree*1000/pharma_polymorph_num_molecules[molecule][form]

        pharma_polymorph_ene_dict[molecule][form] = {'Periodic HF': struct_ene, 'Periodic HF + D4': struct_ene + d4_ene}

## MBE cWFT analysis

### 2B and 3B distance cutoff convergence

#### ROY

In [77]:
# Calculating MP2, CCSD and CCSD(T) results
method_final_elatt_dict = {y:{x:{} for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical','Final']} for y in ['R','Y']}

method_basis = {
    '1B': { x: 'TZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] },
    '2B': { x: 'DZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] },
    '3B': { x: 'DZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] }
}

max_2b_cutoff = '16.0'
max_3b_cutoff = 800

for pharma_struct in ['R','Y']:

    for method in ['HF','MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'MP2 Canonical', 'Final','D4']:
        final_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
        with connect(f'Data/Pharmaceutical/cWFT/ROY_Form_{pharma_struct}_1b.db') as db1:
            monomer_ene_list = []
            for i in range(len(db1)):
                row = db1.get(id=i+1)
                if method == 'Final':
                    monomer_ene_list += [row.data[f'CCSD(T) LAF {method_basis["1B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["1B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["1B"]["MP2 LAF"]}']]
                else:
                    monomer_ene_list += [row.data[f'{method} {method_basis["1B"][method]}']]
            final_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/Pharmaceutical/cWFT/ROY_Form_{pharma_struct}_2b.db') as db2:
            elatt_cwft = 0
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                dist = row.data['distance']
                if dist <= float(max_2b_cutoff)+0.1:
                    if method == 'Final':
                        elatt_cwft += (row.data[f'CCSD(T) LAF {method_basis["2B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["2B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["2B"]["MP2 LAF"]}'])*(row.data['count'])
                    else:
                        elatt_cwft += row.data[f'{method} {method_basis["2B"][method]}']*(row.data['count'])

                if method in ['D4','Final']:
                    for cutoff in cutoff_2b_dists:
                        if dist < cutoff:
                            pharma_polymorph_2b_elatt_dict['ROY'][pharma_struct][f'{cutoff:.1f}'][method] = elatt_cwft/kjmol

                            if method == 'D4':
                                pharma_polymorph_2b_elatt_dict['ROY'][pharma_struct][f'{cutoff:.1f}']['Delta'] = pharma_polymorph_2b_elatt_dict['ROY'][pharma_struct][f'{cutoff:.1f}']['Final'] - pharma_polymorph_2b_elatt_dict['ROY'][pharma_struct][f'{cutoff:.1f}']['D4']

            final_elatt_dict['2B'] = elatt_cwft

        with connect(f'Data/Pharmaceutical/cWFT/ROY_Form_{pharma_struct}_3b.db') as db3:
            elatt_cwft = 0
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                if row.data['distance'] <= max_3b_cutoff+1:
                    if method == 'Final':
                        elatt_cwft += (row.data[f'CCSD(T) LAF {method_basis["3B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["3B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["3B"]["MP2 LAF"]}'])*(row.data['count'])
                    else:
                        elatt_cwft += row.data[f'{method} {method_basis["3B"][method]}']*(row.data['count'])
                if method in ['D4','Final']:
                    for cutoff in cutoff_3b_dists:
                        if row.data['distance'] < cutoff:
                            pharma_polymorph_3b_elatt_dict['ROY'][pharma_struct][cutoff][method] = elatt_cwft/kjmol
                            if method == 'D4':
                                pharma_polymorph_3b_elatt_dict['ROY'][pharma_struct][cutoff]['Delta'] = pharma_polymorph_3b_elatt_dict['ROY'][pharma_struct][cutoff]['Final'] - pharma_polymorph_3b_elatt_dict['ROY'][pharma_struct][cutoff]['D4']

            final_elatt_dict['3B'] = elatt_cwft
        final_elatt_dict['Total'] = final_elatt_dict['1B'] + final_elatt_dict['2B'] + final_elatt_dict['3B']
        method_final_elatt_dict[pharma_struct][method] = final_elatt_dict.copy()
    
    pharma_polymorph_method_ene_dict['ROY'] = method_final_elatt_dict.copy()

    pharma_polymorph_ene_dict['ROY'][pharma_struct]['CCSD(T) corr.'] = method_final_elatt_dict[pharma_struct]['Final']['Total']
    pharma_polymorph_ene_dict['ROY'][pharma_struct]['CCSD(T) corr. - D4'] = method_final_elatt_dict[pharma_struct]['Final']['Total'] - method_final_elatt_dict[pharma_struct]['D4']['Total']

In [78]:
# Make a plot of cutoff distance vs interaction energy for 2B and 3B for ROY Y and R and relative energy difference

fig, axs = plt.subplots(3,2,figsize=(6.69,6.5),constrained_layout=True,dpi=450, sharey=True)

for form_idx, pharma_struct in enumerate(['R','Y','R-Y']):
    if pharma_struct in ['R','Y']:
        elatt_2b_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['ROY'][pharma_struct][f'{cutoff:.1f}']['Final'] for cutoff in cutoff_2b_dists}
        elatt_3b_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['ROY'][pharma_struct][cutoff]['Final'] for cutoff in cutoff_3b_dists}
        elatt_2b_delta_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['ROY'][pharma_struct][f'{cutoff:.1f}']['Delta'] for cutoff in cutoff_2b_dists}
        elatt_3b_delta_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['ROY'][pharma_struct][cutoff]['Delta'] for cutoff in cutoff_3b_dists}
    else:
        elatt_2b_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['ROY']['R'][f'{cutoff:.1f}']['Final'] - pharma_polymorph_2b_elatt_dict['ROY']['Y'][f'{cutoff:.1f}']['Final'] for cutoff in cutoff_2b_dists}
        elatt_3b_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['ROY']['R'][cutoff]['Final'] - pharma_polymorph_3b_elatt_dict['ROY']['Y'][cutoff]['Final'] for cutoff in cutoff_3b_dists}
        elatt_2b_delta_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['ROY']['R'][f'{cutoff:.1f}']['Delta'] - pharma_polymorph_2b_elatt_dict['ROY']['Y'][f'{cutoff:.1f}']['Delta'] for cutoff in cutoff_2b_dists}
        elatt_3b_delta_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['ROY']['R'][cutoff]['Delta'] - pharma_polymorph_3b_elatt_dict['ROY']['Y'][cutoff]['Delta'] for cutoff in cutoff_3b_dists}

    # Plot the 2B convergence
    axs[form_idx,0].plot(cutoff_2b_dists,np.array([elatt_2b_cutoff_dict[f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - elatt_2b_cutoff_dict[max_2b_cutoff],label=r'CCSD(T) [$E_\text{int}^\text{2b}=$' + f"{elatt_2b_cutoff_dict[max_2b_cutoff]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

    axs[form_idx,0].plot(cutoff_2b_dists,np.array([elatt_2b_delta_cutoff_dict[f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - elatt_2b_delta_cutoff_dict[max_2b_cutoff],label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{2b}=$' + f"{elatt_2b_delta_cutoff_dict[max_2b_cutoff]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

    # Plot the 3B convergence
    axs[form_idx,1].plot(cutoff_3b_dists,np.array([elatt_3b_cutoff_dict[cutoff] for cutoff in cutoff_3b_dists]) - elatt_3b_cutoff_dict[max_3b_cutoff] , label=r'CCSD(T) [$E_\text{int}^\text{3b}=$' + f"{elatt_3b_cutoff_dict[max_3b_cutoff]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

    axs[form_idx,1].plot(cutoff_3b_dists,np.array([elatt_3b_delta_cutoff_dict[cutoff] for cutoff in cutoff_3b_dists]) - elatt_3b_delta_cutoff_dict[max_3b_cutoff],label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{3b}=$' + f"{elatt_3b_delta_cutoff_dict[max_3b_cutoff]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

    # Fill between -1 and 1 kJ/mol
    axs[form_idx,0].fill_between([0,16],-1,1,color='grey',alpha=0.3,edgecolor='none')
    axs[form_idx,1].fill_between([0,800],-1,1,color='grey',alpha=0.3,edgecolor='none')


    axs[form_idx,0].set_ylim([-20,20])
    axs[form_idx,0].set_xlim([3.5,float(max_2b_cutoff)])
    axs[form_idx,1].set_xlim([300,float(max_3b_cutoff)])

    axs[form_idx,0].set_ylabel(f'{pharma_struct} (kJ/mol)')
    axs[form_idx,0].set_xlabel(r'2B Distance cutoff (\AA{})')
    axs[form_idx,1].set_xlabel(r'3B Distance cutoff (\AA{}$^3$)')

    axs[form_idx,0].legend(fontsize=8)
    axs[form_idx,1].legend(fontsize=8)

    # Make a title over both plots
    # fig.suptitle(f'{x23_labels[x23_idx]}',fontsize=10)

plt.savefig(f'Figures/SI_Figure-ROY_2b_3b_distance_convergence.png')

#### Axitinib

In [79]:
# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results

max_2b_dist = '20.0'
max_3b_dist = 720

method_final_elatt_dict = {y:{x:{} for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical','Final', 'cT Final']} for y in ['VI','XLI']}

method_basis = {
    '1B': { x: 'TZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] },
    '2B': { x: 'DZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] },
    '3B': { x: 'DZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] }
}

for pharma_struct in ['VI','XLI']:

    for method in ['HF','MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'MP2 Canonical','Final','D4']:
        final_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
        with connect(f'Data/Pharmaceutical/cWFT/Axitinib_Form_{pharma_struct}_1b.db') as db1:
            monomer_ene_list = []
            for i in range(len(db1)):
                row = db1.get(id=i+1)
                if method == 'Final':
                    monomer_ene_list += [row.data[f'CCSD(T) LAF {method_basis["1B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["1B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["1B"]["MP2 LAF"]}']]
                else:
                    monomer_ene_list += [row.data[f'{method} {method_basis["1B"][method]}']]
            final_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/Pharmaceutical/cWFT/Axitinib_Form_{pharma_struct}_2b.db') as db2:
            elatt_cwft = 0
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                dist = row.data['distance']
                if dist <= float(max_2b_dist)+0.1:
                    if method == 'Final':
                        elatt_cwft += (row.data[f'CCSD(T) LAF {method_basis["2B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["2B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["2B"]["MP2 LAF"]}'])*(row.data['count'])
                    else:
                        elatt_cwft += row.data[f'{method} {method_basis["2B"][method]}']*(row.data['count'])

                if method in ['D4','Final']:
                    for cutoff in cutoff_2b_dists:
                        if dist < cutoff:
                            pharma_polymorph_2b_elatt_dict['Axitinib'][pharma_struct][f'{cutoff:.1f}'][method] = elatt_cwft/kjmol
                            if method == 'D4':
                                pharma_polymorph_2b_elatt_dict['Axitinib'][pharma_struct][f'{cutoff:.1f}']['Delta'] = pharma_polymorph_2b_elatt_dict['Axitinib'][pharma_struct][f'{cutoff:.1f}']['Final'] - pharma_polymorph_2b_elatt_dict['Axitinib'][pharma_struct][f'{cutoff:.1f}']['D4']

            final_elatt_dict['2B'] = elatt_cwft

        with connect(f'Data/Pharmaceutical/cWFT/Axitinib_Form_{pharma_struct}_3b.db') as db3:
            elatt_cwft = 0
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                if row.data['distance'] <= max_3b_dist+1:
                    if method == 'Final':
                        elatt_cwft += (row.data[f'CCSD(T) LAF {method_basis["3B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["3B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["3B"]["MP2 LAF"]}'])*(row.data['count'])
                    else:
                        elatt_cwft += row.data[f'{method} {method_basis["3B"][method]}']*(row.data['count'])
                if method in ['D4','Final']:
                    for cutoff in cutoff_3b_dists:
                        if row.data['distance'] < cutoff:
                            pharma_polymorph_3b_elatt_dict['Axitinib'][pharma_struct][cutoff][method] = elatt_cwft/kjmol
                            if method == 'D4':
                                pharma_polymorph_3b_elatt_dict['Axitinib'][pharma_struct][cutoff]['Delta'] = pharma_polymorph_3b_elatt_dict['Axitinib'][pharma_struct][cutoff]['Final'] - pharma_polymorph_3b_elatt_dict['Axitinib'][pharma_struct][cutoff]['D4']

            final_elatt_dict['3B'] = elatt_cwft
        final_elatt_dict['Total'] = final_elatt_dict['1B'] + final_elatt_dict['2B'] + final_elatt_dict['3B']
        method_final_elatt_dict[pharma_struct][method] = final_elatt_dict.copy()
    
    pharma_polymorph_method_ene_dict['Axitinib'] = method_final_elatt_dict.copy()

    pharma_polymorph_ene_dict['Axitinib'][pharma_struct]['CCSD(T) corr.'] = method_final_elatt_dict[pharma_struct]['Final']['Total']
    pharma_polymorph_ene_dict['Axitinib'][pharma_struct]['CCSD(T) corr. - D4'] = method_final_elatt_dict[pharma_struct]['Final']['Total'] - method_final_elatt_dict[pharma_struct]['D4']['Total']

In [80]:
# Make a plot of cutoff distance vs interaction energy for 2B and 3B for ROY Y and R and relative energy difference

fig, axs = plt.subplots(3,2,figsize=(6.69,6.5),constrained_layout=True,dpi=450, sharey=True)


for form_idx, pharma_struct in enumerate(['VI','XLI','VI-XLI']):
    if pharma_struct in ['VI','XLI']:
        elatt_2b_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['Axitinib'][pharma_struct][f'{cutoff:.1f}']['Final'] for cutoff in cutoff_2b_dists}
        elatt_3b_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['Axitinib'][pharma_struct][cutoff]['Final'] for cutoff in cutoff_3b_dists}
        elatt_2b_delta_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['Axitinib'][pharma_struct][f'{cutoff:.1f}']['Delta'] for cutoff in cutoff_2b_dists}
        elatt_3b_delta_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['Axitinib'][pharma_struct][cutoff]['Delta'] for cutoff in cutoff_3b_dists}
    else:
        elatt_2b_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['Axitinib']['VI'][f'{cutoff:.1f}']['Final'] - pharma_polymorph_2b_elatt_dict['Axitinib']['XLI'][f'{cutoff:.1f}']['Final'] for cutoff in cutoff_2b_dists}
        elatt_3b_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['Axitinib']['VI'][cutoff]['Final'] - pharma_polymorph_3b_elatt_dict['Axitinib']['XLI'][cutoff]['Final'] for cutoff in cutoff_3b_dists}
        elatt_2b_delta_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['Axitinib']['VI'][f'{cutoff:.1f}']['Delta'] - pharma_polymorph_2b_elatt_dict['Axitinib']['XLI'][f'{cutoff:.1f}']['Delta'] for cutoff in cutoff_2b_dists}
        elatt_3b_delta_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['Axitinib']['VI'][cutoff]['Delta'] - pharma_polymorph_3b_elatt_dict['Axitinib']['XLI'][cutoff]['Delta'] for cutoff in cutoff_3b_dists}


    # Plot the 2B convergence 15.5 max
    axs[form_idx,0].plot(cutoff_2b_dists,np.array([elatt_2b_cutoff_dict[f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - elatt_2b_cutoff_dict[max_2b_dist],label=r'CCSD(T) [$E_\text{int}^\text{2b}=$' + f"{elatt_2b_cutoff_dict[max_2b_dist]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

    axs[form_idx,0].plot(cutoff_2b_dists,np.array([elatt_2b_delta_cutoff_dict[f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - elatt_2b_delta_cutoff_dict[max_2b_dist],label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{2b}=$' + f"{elatt_2b_delta_cutoff_dict[max_2b_dist]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

    # Plot the 3B convergence 790 max
    axs[form_idx,1].plot(cutoff_3b_dists,np.array([elatt_3b_cutoff_dict[cutoff] for cutoff in cutoff_3b_dists]) - elatt_3b_cutoff_dict[max_3b_dist] , label=r'CCSD(T) [$E_\text{int}^\text{3b}=$' + f"{elatt_3b_cutoff_dict[max_3b_dist]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

    axs[form_idx,1].plot(cutoff_3b_dists,np.array([elatt_3b_delta_cutoff_dict[cutoff] for cutoff in cutoff_3b_dists]) - elatt_3b_delta_cutoff_dict[max_3b_dist],label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{3b}=$' + f"{elatt_3b_delta_cutoff_dict[max_3b_dist]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

    # Fill between -1 and 1 kJ/mol
    axs[form_idx,0].fill_between([0,20],-1,1,color='grey',alpha=0.3,edgecolor='none')
    axs[form_idx,1].fill_between([0,720],-1,1,color='grey',alpha=0.3,edgecolor='none')


    axs[form_idx,0].set_ylim([-20,20])
    axs[form_idx,0].set_xlim([3.5,float(max_2b_dist)])
    axs[form_idx,1].set_xlim([400,float(max_3b_dist)])

    axs[form_idx,0].set_ylabel(f'{pharma_struct} (kJ/mol)')
    axs[form_idx,0].set_xlabel(r'2B Distance cutoff (Å)')
    axs[form_idx,1].set_xlabel(r'3B Distance cutoff (Å$^3$)')

    axs[form_idx,0].legend(fontsize=8)
    axs[form_idx,1].legend(fontsize=8)


plt.savefig(f'Figures/SI_Figure-Axitinib_2b_3b_distance_convergence.png')

#### Rotigotine

In [81]:
# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results

max_2b_dist = '19.0'
max_3b_dist = 750

rotigotine_forms = ['I_1','I_2','II_1','II_2']

method_final_elatt_dict = {y:{x:{} for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical','Final', 'cT Final']} for y in rotigotine_forms}

method_basis = {
    '1B': { x: 'TZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] },
    '2B': { x: 'DZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] },
    '3B': { x: 'DZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] }
}

for pharma_struct in rotigotine_forms:

    for method in ['HF','MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'MP2 Canonical','Final','D4']:
        final_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
        with connect(f'Data/Pharmaceutical/cWFT/Rotigotine_Form_{pharma_struct}_1b.db') as db1:
            monomer_ene_list = []
            for i in range(len(db1)):
                row = db1.get(id=i+1)
                if method == 'Final':
                    monomer_ene_list += [row.data[f'CCSD(T) LAF {method_basis["1B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["1B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["1B"]["MP2 LAF"]}']]
                else:
                    monomer_ene_list += [row.data[f'{method} {method_basis["1B"][method]}']]

            final_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/Pharmaceutical/cWFT/Rotigotine_Form_{pharma_struct}_2b.db') as db2:
            elatt_cwft = 0
            dist_reached_bool = {cutoff: False for cutoff in cutoff_2b_dists}
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                if row.data['distance'] <= float(max_2b_dist)+0.1:
                    if method == 'Final':
                        elatt_cwft += (row.data[f'CCSD(T) LAF {method_basis["2B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["2B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["2B"]["MP2 LAF"]}'])*(row.data['count'])
                    else:
                        elatt_cwft += row.data[f'{method} {method_basis["2B"][method]}']*(row.data['count'])

                if method in ['D4','Final']:
                    for cutoff in cutoff_2b_dists:
                        if row.data['distance'] < cutoff:
                            pharma_polymorph_2b_elatt_dict['Rotigotine'][pharma_struct][f'{cutoff:.1f}'][method] = elatt_cwft/kjmol

                            if method == 'D4':
                                pharma_polymorph_2b_elatt_dict['Rotigotine'][pharma_struct][f'{cutoff:.1f}']['Delta'] = pharma_polymorph_2b_elatt_dict['Rotigotine'][pharma_struct][f'{cutoff:.1f}']['Final'] - pharma_polymorph_2b_elatt_dict['Rotigotine'][pharma_struct][f'{cutoff:.1f}']['D4']

            final_elatt_dict['2B'] = elatt_cwft

        with connect(f'Data/Pharmaceutical/cWFT/Rotigotine_Form_{pharma_struct}_3b.db') as db3:
            elatt_cwft = 0
            dist_reached_bool = {cutoff: False for cutoff in cutoff_3b_dists}
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                if row.data['distance'] <= max_3b_dist+1:
                    if method == 'Final':
                        elatt_cwft += (row.data[f'CCSD(T) LAF {method_basis["3B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["3B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["3B"]["MP2 LAF"]}'])*(row.data['count'])

                    else:
                        elatt_cwft += row.data[f'{method} {method_basis["3B"][method]}']*(row.data['count'])
                if method in ['D4','Final']:
                    for cutoff in cutoff_3b_dists:
                        if row.data['distance'] < cutoff:
                            pharma_polymorph_3b_elatt_dict['Rotigotine'][pharma_struct][cutoff][method] = elatt_cwft/kjmol
                            if method == 'D4':
                                pharma_polymorph_3b_elatt_dict['Rotigotine'][pharma_struct][cutoff]['Delta'] = pharma_polymorph_3b_elatt_dict['Rotigotine'][pharma_struct][cutoff]['Final'] - pharma_polymorph_3b_elatt_dict['Rotigotine'][pharma_struct][cutoff]['D4']

            final_elatt_dict['3B'] = elatt_cwft
        final_elatt_dict['Total'] = final_elatt_dict['1B'] + final_elatt_dict['2B'] + final_elatt_dict['3B']
        method_final_elatt_dict[pharma_struct][method] = final_elatt_dict.copy()

    pharma_polymorph_method_ene_dict['Rotigotine'] = method_final_elatt_dict.copy()

    pharma_polymorph_ene_dict['Rotigotine'][pharma_struct]['CCSD(T) corr.'] = method_final_elatt_dict[pharma_struct]['Final']['Total']
    pharma_polymorph_ene_dict['Rotigotine'][pharma_struct]['CCSD(T) corr. - D4'] = method_final_elatt_dict[pharma_struct]['Final']['Total'] - method_final_elatt_dict[pharma_struct]['D4']['Total']

In [82]:
# Make a plot of cutoff distance vs interaction energy for 2B and 3B for Rotigotine I and II and relative energy difference

fig, axs = plt.subplots(5,2,figsize=(6.69,8.5),constrained_layout=True,dpi=450, sharey=True)

for form_idx, pharma_struct in enumerate(['I_1','I_2','II_1','II_2','I-II']):
    if pharma_struct in ['I_1','I_2','II_1','II_2']:
        elatt_2b_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['Rotigotine'][pharma_struct][f'{cutoff:.1f}']['Final'] for cutoff in cutoff_2b_dists}
        elatt_3b_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['Rotigotine'][pharma_struct][cutoff]['Final'] for cutoff in cutoff_3b_dists}
        elatt_2b_delta_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['Rotigotine'][pharma_struct][f'{cutoff:.1f}']['Delta'] for cutoff in cutoff_2b_dists}
        elatt_3b_delta_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['Rotigotine'][pharma_struct][cutoff]['Delta'] for cutoff in cutoff_3b_dists}
    else:
        elatt_2b_cutoff_dict = {f'{cutoff:.1f}': (pharma_polymorph_2b_elatt_dict['Rotigotine']['I_1'][f'{cutoff:.1f}']['Final'] + pharma_polymorph_2b_elatt_dict['Rotigotine']['I_2'][f'{cutoff:.1f}']['Final'])/2 - (pharma_polymorph_2b_elatt_dict['Rotigotine']['II_1'][f'{cutoff:.1f}']['Final'] + pharma_polymorph_2b_elatt_dict['Rotigotine']['II_2'][f'{cutoff:.1f}']['Final'])/2 for cutoff in cutoff_2b_dists}
        elatt_3b_cutoff_dict = {cutoff: (pharma_polymorph_3b_elatt_dict['Rotigotine']['I_1'][cutoff]['Final'] + pharma_polymorph_3b_elatt_dict['Rotigotine']['I_2'][cutoff]['Final'])/2 - (pharma_polymorph_3b_elatt_dict['Rotigotine']['II_1'][cutoff]['Final'] + pharma_polymorph_3b_elatt_dict['Rotigotine']['II_2'][cutoff]['Final'])/2 for cutoff in cutoff_3b_dists}
        elatt_2b_delta_cutoff_dict = {f'{cutoff:.1f}': (pharma_polymorph_2b_elatt_dict['Rotigotine']['I_1'][f'{cutoff:.1f}']['Delta'] + pharma_polymorph_2b_elatt_dict['Rotigotine']['I_2'][f'{cutoff:.1f}']['Delta'])/2 - (pharma_polymorph_2b_elatt_dict['Rotigotine']['II_1'][f'{cutoff:.1f}']['Delta'] + pharma_polymorph_2b_elatt_dict['Rotigotine']['II_2'][f'{cutoff:.1f}']['Delta'])/2 for cutoff in cutoff_2b_dists}
        elatt_3b_delta_cutoff_dict = {cutoff: (pharma_polymorph_3b_elatt_dict['Rotigotine']['I_1'][cutoff]['Delta'] + pharma_polymorph_3b_elatt_dict['Rotigotine']['I_2'][cutoff]['Delta'])/2 - (pharma_polymorph_3b_elatt_dict['Rotigotine']['II_1'][cutoff]['Delta'] + pharma_polymorph_3b_elatt_dict['Rotigotine']['II_2'][cutoff]['Delta'])/2 for cutoff in cutoff_3b_dists}


    # Plot the 2B convergence 19.5 max
    axs[form_idx,0].plot(cutoff_2b_dists,np.array([elatt_2b_cutoff_dict[f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - elatt_2b_cutoff_dict[max_2b_dist],label=r'CCSD(T) [$E_\text{int}^\text{2b}=$' + f"{elatt_2b_cutoff_dict[max_2b_dist]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

    axs[form_idx,0].plot(cutoff_2b_dists,np.array([elatt_2b_delta_cutoff_dict[f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - elatt_2b_delta_cutoff_dict[max_2b_dist],label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{2b}=$' + f"{elatt_2b_delta_cutoff_dict[max_2b_dist]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

    # Plot the 3B convergence 800 max
    axs[form_idx,1].plot(cutoff_3b_dists,np.array([elatt_3b_cutoff_dict[cutoff] for cutoff in cutoff_3b_dists]) - elatt_3b_cutoff_dict[max_3b_dist] , label=r'CCSD(T) [$E_\text{int}^\text{3b}=$' + f"{elatt_3b_cutoff_dict[max_3b_dist]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

    axs[form_idx,1].plot(cutoff_3b_dists,np.array([elatt_3b_delta_cutoff_dict[cutoff] for cutoff in cutoff_3b_dists]) - elatt_3b_delta_cutoff_dict[max_3b_dist],label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{3b}=$' + f"{elatt_3b_delta_cutoff_dict[max_3b_dist]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

    # Fill between -1 and 1 kJ/mol
    axs[form_idx,0].fill_between([0,20],-1,1,color='grey',alpha=0.3,edgecolor='none')
    axs[form_idx,1].fill_between([0,810],-1,1,color='grey',alpha=0.3,edgecolor='none')


    axs[form_idx,0].set_ylim([-20,20])
    axs[form_idx,0].set_xlim([8.5,float(max_2b_dist)])
    axs[form_idx,1].set_xlim([500,float(max_3b_dist)])

    axs[form_idx,0].set_ylabel(f'{pharma_struct} (kJ/mol)')
    axs[form_idx,0].set_xlabel(r'2B Distance cutoff (Å)')
    axs[form_idx,1].set_xlabel(r'3B Distance cutoff (Å$^3$)')

    axs[form_idx,0].legend(fontsize=8)
    axs[form_idx,1].legend(fontsize=8)

    # Make a title over both plots
    # fig.suptitle(f'{x23_labels[x23_idx]}',fontsize=10)

plt.savefig(f'Figures/SI_Figure-Rotigotine_2b_3b_distance_convergence.png')

## Molecule X convergence tests

In [83]:
# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results

max_2b_dist = '16.0'
max_3b_dist = 450

method_final_elatt_dict = {y:{x:{} for x in ['MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical','Final', 'cT Final']} for y in ['expt','vaneijck']}

method_basis = {
    '1B': { x: 'TZ' if x not in  ['MP2 Canonical', 'HF'] else 'CBS' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] },
    '2B': { x: 'DZ' if x not in  ['MP2 Canonical', 'HF'] else 'TZ' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] },
    '3B': { x: 'DZ' if x not in  ['MP2 Canonical', 'HF'] else 'TZ' for x in ['HF', 'MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'CCSD(cT) LAF', 'MP2 Canonical', 'D4'] }
}


for pharma_struct in ['expt','vaneijck']:

    for method in ['HF','MP2 LAF', 'CCSD LAF', 'CCSD(T) LAF', 'MP2 Canonical','Final','D4']:
        final_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
        with connect(f'Data/Pharmaceutical/cWFT/X_Form_{pharma_struct}_1b.db') as db1:
            monomer_ene_list = []
            for i in range(len(db1)):
                row = db1.get(id=i+1)
                if method == 'Final':
                    monomer_ene_list += [row.data[f'CCSD(T) LAF {method_basis["1B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["1B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["1B"]["MP2 LAF"]}']]
                else:
                    monomer_ene_list += [row.data[f'{method} {method_basis["1B"][method]}']]
            final_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/Pharmaceutical/cWFT/X_Form_{pharma_struct}_2b.db') as db2:
            elatt_cwft = 0
            dist_reached_bool = {f'{cutoff:.1f}': False for cutoff in cutoff_2b_dists}
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                if row.data['distance'] <= float(max_2b_dist)+0.1:
                    if method == 'Final':
                        elatt_cwft += (row.data[f'CCSD(T) LAF {method_basis["2B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["2B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["2B"]["MP2 LAF"]}'])*(row.data['count'])
                    else:
                        elatt_cwft += row.data[f'{method} {method_basis["2B"][method]}']*(row.data['count'])
                
                if method in ['D4','Final']:
                    for cutoff in cutoff_2b_dists:
                        if row.data['distance'] < cutoff: 
                            pharma_polymorph_2b_elatt_dict['X'][pharma_struct][f'{cutoff:.1f}'][method] = elatt_cwft/kjmol

                            if method == 'D4':
                                pharma_polymorph_2b_elatt_dict['X'][pharma_struct][f'{cutoff:.1f}']['Delta'] = pharma_polymorph_2b_elatt_dict['X'][pharma_struct][f'{cutoff:.1f}']['Final'] - pharma_polymorph_2b_elatt_dict['X'][pharma_struct][f'{cutoff:.1f}']['D4']

            final_elatt_dict['2B'] = elatt_cwft

        with connect(f'Data/Pharmaceutical/cWFT/X_Form_{pharma_struct}_3b.db') as db3:
            elatt_cwft = 0
            dist_reached_bool = {cutoff: False for cutoff in cutoff_3b_dists}
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                if row.data['distance'] <= max_3b_dist+1:
                    if method == 'Final':
                        elatt_cwft += (row.data[f'CCSD(T) LAF {method_basis["3B"]["CCSD(T) LAF"]}'] + row.data[f'MP2 Canonical {method_basis["3B"]["MP2 Canonical"]}'] - row.data[f'MP2 LAF {method_basis["3B"]["MP2 LAF"]}'])*(row.data['count'])
                    else:
                        elatt_cwft += row.data[f'{method} {method_basis["3B"][method]}']*(row.data['count'])
                if method in ['D4','Final']:
                    for cutoff in cutoff_3b_dists:
                        if row.data['distance'] < cutoff:
                            pharma_polymorph_3b_elatt_dict['X'][pharma_struct][cutoff][method] = elatt_cwft/kjmol
                            if method == 'D4':
                                pharma_polymorph_3b_elatt_dict['X'][pharma_struct][cutoff]['Delta'] = pharma_polymorph_3b_elatt_dict['X'][pharma_struct][cutoff]['Final'] - pharma_polymorph_3b_elatt_dict['X'][pharma_struct][cutoff]['D4']


            final_elatt_dict['3B'] = elatt_cwft
        final_elatt_dict['Total'] = final_elatt_dict['1B'] + final_elatt_dict['2B'] + final_elatt_dict['3B']
        method_final_elatt_dict[pharma_struct][method] = final_elatt_dict.copy()

    pharma_polymorph_method_ene_dict['X'] = method_final_elatt_dict.copy()

    pharma_polymorph_ene_dict['X'][pharma_struct]['CCSD(T) corr.'] = method_final_elatt_dict[pharma_struct]['Final']['Total']
    pharma_polymorph_ene_dict['X'][pharma_struct]['CCSD(T) corr. - D4'] = method_final_elatt_dict[pharma_struct]['Final']['Total'] - method_final_elatt_dict[pharma_struct]['D4']['Total']

In [84]:
# Make a plot of cutoff distance vs interaction energy for 2B and 3B for X expt and vaneijck and relative energy difference

fig, axs = plt.subplots(3,2,figsize=(6.69,6.5),constrained_layout=True,dpi=450, sharey=True)

for form_idx, pharma_struct in enumerate(['expt','vaneijck','expt-vaneijck']):
    if pharma_struct in ['expt','vaneijck']:
        elatt_2b_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['X'][pharma_struct][f'{cutoff:.1f}']['Final'] for cutoff in cutoff_2b_dists}
        elatt_3b_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['X'][pharma_struct][cutoff]['Final'] for cutoff in cutoff_3b_dists}
        elatt_2b_delta_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['X'][pharma_struct][f'{cutoff:.1f}']['Delta'] for cutoff in cutoff_2b_dists}
        elatt_3b_delta_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['X'][pharma_struct][cutoff]['Delta'] for cutoff in cutoff_3b_dists}
    else:
        elatt_2b_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['X']['expt'][f'{cutoff:.1f}']['Final'] - pharma_polymorph_2b_elatt_dict['X']['vaneijck'][f'{cutoff:.1f}']['Final'] for cutoff in cutoff_2b_dists}
        elatt_3b_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['X']['expt'][cutoff]['Final'] - pharma_polymorph_3b_elatt_dict['X']['vaneijck'][cutoff]['Final'] for cutoff in cutoff_3b_dists}
        elatt_2b_delta_cutoff_dict = {f'{cutoff:.1f}': pharma_polymorph_2b_elatt_dict['X']['expt'][f'{cutoff:.1f}']['Delta'] - pharma_polymorph_2b_elatt_dict['X']['vaneijck'][f'{cutoff:.1f}']['Delta'] for cutoff in cutoff_2b_dists}
        elatt_3b_delta_cutoff_dict = {cutoff: pharma_polymorph_3b_elatt_dict['X']['expt'][cutoff]['Delta'] - pharma_polymorph_3b_elatt_dict['X']['vaneijck'][cutoff]['Delta'] for cutoff in cutoff_3b_dists}

    # Plot the 2B convergence
    axs[form_idx,0].plot(cutoff_2b_dists,np.array([elatt_2b_cutoff_dict[f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - elatt_2b_cutoff_dict[max_2b_dist],label=r'CCSD(T) [$E_\text{int}^\text{2b}=$' + f"{elatt_2b_cutoff_dict[max_2b_dist]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

    axs[form_idx,0].plot(cutoff_2b_dists,np.array([elatt_2b_delta_cutoff_dict[f'{cutoff:.1f}'] for cutoff in cutoff_2b_dists]) - elatt_2b_delta_cutoff_dict[max_2b_dist],label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{2b}=$' + f"{elatt_2b_delta_cutoff_dict[max_2b_dist]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

    # Plot the 3B convergence
    axs[form_idx,1].plot(cutoff_3b_dists,np.array([elatt_3b_cutoff_dict[cutoff] for cutoff in cutoff_3b_dists]) - elatt_3b_cutoff_dict[max_3b_dist] , label=r'CCSD(T) [$E_\text{int}^\text{3b}=$' + f"{elatt_3b_cutoff_dict[max_3b_dist]:.1f} kJ/mol]",c=color_dict['red'],alpha=0.5,marker='x')

    axs[form_idx,1].plot(cutoff_3b_dists,np.array([elatt_3b_delta_cutoff_dict[cutoff] for cutoff in cutoff_3b_dists]) - elatt_3b_delta_cutoff_dict[max_3b_dist],label=r'$\Delta^\text{CCSD(T)}_\text{D4}$ [$E_\text{int}^\text{3b}=$' + f"{elatt_3b_delta_cutoff_dict[max_3b_dist]:.1f} kJ/mol]",c=color_dict['blue'],alpha=0.7,marker='x')

    # Fill between -1 and 1 kJ/mol
    axs[form_idx,0].fill_between([0,20],-1,1,color='grey',alpha=0.3,edgecolor='none')
    axs[form_idx,1].fill_between([0,810],-1,1,color='grey',alpha=0.3,edgecolor='none')


    axs[form_idx,0].set_ylim([-20,20])
    axs[form_idx,0].set_xlim([3.5,float(max_2b_dist)])
    axs[form_idx,1].set_xlim([100,float(max_3b_dist)])

    axs[form_idx,0].set_ylabel(f'{pharma_struct} (kJ/mol)')


    axs[form_idx,0].legend(fontsize=8)
    axs[form_idx,1].legend(fontsize=8)

axs[2,0].set_xlabel(r'2B Distance cutoff (\AA{})')
axs[2,1].set_xlabel(r'3B Distance cutoff (\AA{}$^3$)')

plt.savefig(f'Figures/SI_Figure-X_2b_3b_distance_convergence.png')

/var/folders/zp/fz7h39h554nb51_blfh6qmqw0000gp/T/ipykernel_53515/1171251292.py:3: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig, axs = plt.subplots(3,2,figsize=(6.69,6.5),constrained_layout=True,dpi=450, sharey=True)

In [85]:
# X convergence tests with bigger basis sets

# Calculating MP2, CCSD, CCSD(T) and CCSD(cT) results

max_2b_dist = '14.0'
max_3b_dist = 450

x_method_conv_elatt_dict = {y:{x:{} for x in ['tight','vtight','LAF']} for y in ['expt','vaneijck']}
x_polymorph_2b_elatt_dict = {form: {f'{cutoff:.1f}': {method: 0 for method in ['tight','vtight','LAF']} for cutoff in cutoff_2b_dists} for form in ['expt','vaneijck']}
x_polymorph_3b_elatt_dict = {form: {cutoff: {method: 0 for method in ['tight','vtight','LAF']} for cutoff in cutoff_3b_dists} for form in ['expt','vaneijck']}



for pharma_struct in ['expt','vaneijck']:

    for method in ['tight','vtight','LAF']:
        final_elatt_dict = {'1B': 0, '2B': 0, '3B': 0, 'Total': 0}
        with connect(f'Data/cWFT_Convergence/X_Form_{pharma_struct}_1b.db') as db1:
            monomer_ene_list = []
            for i in range(len(db1)):
                row = db1.get(id=i+1)
                monomer_ene_list += [row.data[f'CCSD(T) {method} QZ'] + row.data[f'MP2 Canonical CBS'] - row.data[f'MP2 {method} QZ']]
            final_elatt_dict['1B'] = np.mean(monomer_ene_list[1:]) - monomer_ene_list[0]

        with connect(f'Data/cWFT_Convergence/X_Form_{pharma_struct}_2b.db') as db2:
            elatt_cwft = 0
            dist_reached_bool = {f'{cutoff:.1f}': False for cutoff in cutoff_2b_dists}
            for i in range(len(db2)):
                row = db2.get(id=i+1)
                if row.data['distance'] <= float(max_2b_dist)+0.1:
                    elatt_cwft += (row.data[f'CCSD(T) {method} TZ'] + row.data[f'MP2 Canonical CBS'] - row.data[f'MP2 {method} TZ'])*(row.data['count'])
                for cutoff in cutoff_2b_dists:
                    if row.data['distance'] < cutoff: 
                        x_polymorph_2b_elatt_dict[pharma_struct][f'{cutoff:.1f}'][method] = elatt_cwft/kjmol

            final_elatt_dict['2B'] = elatt_cwft

        with connect(f'Data/cWFT_Convergence/X_Form_{pharma_struct}_3b.db') as db3:
            elatt_cwft = 0
            dist_reached_bool = {cutoff: False for cutoff in cutoff_3b_dists}
            for i in range(len(db3)):
                row = db3.get(id=i+1)
                if row.data['distance'] <= max_3b_dist+1:
                    elatt_cwft += (row.data[f'CCSD(T) {method} DZ'] + row.data[f'MP2 Canonical CBS'] - row.data[f'MP2 {method} DZ'])*(row.data['count'])

                for cutoff in cutoff_3b_dists:
                    if row.data['distance'] < cutoff:
                        x_polymorph_3b_elatt_dict[pharma_struct][cutoff][method] = elatt_cwft/kjmol


            final_elatt_dict['3B'] = elatt_cwft
        final_elatt_dict['Total'] = final_elatt_dict['1B'] + final_elatt_dict['2B'] + final_elatt_dict['3B']
        x_method_conv_elatt_dict[pharma_struct][method] = final_elatt_dict.copy()

### Basis set

In [86]:
# Plot distance convergence for X with different basis sets
fig, axs = plt.subplots(2,2,figsize=(6.69,5),constrained_layout=True,dpi=450,sharex='col')

x_elatt_2b_cutoff_list = [f'{cutoff:.1f}' for cutoff in cutoff_2b_dists if cutoff < float(max_2b_dist)+0.1]
x_elatt_3b_cutoff_list = [cutoff for cutoff in cutoff_3b_dists[::3] if cutoff < max_3b_dist+1]

x_elatt_big_basis_2b_cutoff_dict = {polymorph: [x_polymorph_2b_elatt_dict[polymorph][cutoff]['LAF'] for cutoff in x_elatt_2b_cutoff_list] for polymorph in ['expt','vaneijck']}
x_elatt_big_basis_3b_cutoff_dict = {polymorph: [x_polymorph_3b_elatt_dict[polymorph][cutoff]['LAF'] for cutoff in x_elatt_3b_cutoff_list] for polymorph in ['expt','vaneijck']}
x_elatt_small_basis_2b_cutoff_dict = {polymorph: [pharma_polymorph_2b_elatt_dict['X'][polymorph][cutoff]['Final'] for cutoff in x_elatt_2b_cutoff_list] for polymorph in ['expt','vaneijck']}
x_elatt_small_basis_3b_cutoff_dict = {polymorph: [pharma_polymorph_3b_elatt_dict['X'][polymorph][cutoff]['Final'] for cutoff in x_elatt_3b_cutoff_list] for polymorph in ['expt','vaneijck']}

# Plot the 2B convergence
axs[0,0].plot([float(x) for x in x_elatt_2b_cutoff_list],x_elatt_big_basis_2b_cutoff_dict['expt'],label=f'Expt (Reduced)',c=color_dict['red'],alpha=0.7,marker='x')
axs[0,0].plot([float(x) for x in x_elatt_2b_cutoff_list],x_elatt_big_basis_2b_cutoff_dict['vaneijck'],label=f'vanEijck-3 (Reduced)',c=color_dict['blue'],alpha=0.7,marker='x')
axs[0,0].plot([float(x) for x in x_elatt_2b_cutoff_list],x_elatt_small_basis_2b_cutoff_dict['expt'],label=f'Expt (Full)',c=color_dict['red'],alpha=0.7,marker='o',linestyle='--',markerfacecolor='none')
axs[0,0].plot([float(x) for x in x_elatt_2b_cutoff_list],x_elatt_small_basis_2b_cutoff_dict['vaneijck'],label=f'vanEijck-3 (Full)',c=color_dict['blue'],alpha=0.7,marker='o',linestyle='--',markerfacecolor='none')

# Plot the 3B convergence
axs[0,1].plot(x_elatt_3b_cutoff_list,x_elatt_big_basis_3b_cutoff_dict['expt'],label=f'Expt (Reduced)',c=color_dict['red'],alpha=0.7,marker='x')
axs[0,1].plot(x_elatt_3b_cutoff_list,x_elatt_big_basis_3b_cutoff_dict['vaneijck'],label=f'vanEijck-3 (Reduced)',c=color_dict['blue'],alpha=0.7,marker='x')
axs[0,1].plot(x_elatt_3b_cutoff_list,x_elatt_small_basis_3b_cutoff_dict['expt'],label=f'Expt (Full)',c=color_dict['red'],alpha=0.7,marker='o',linestyle='--',markerfacecolor='none')
axs[0,1].plot(x_elatt_3b_cutoff_list,x_elatt_small_basis_3b_cutoff_dict['vaneijck'],label=f'vanEijck-3 (Full)',c=color_dict['blue'],alpha=0.7,marker='o', markerfacecolor='none',linestyle='--')

# Plot the difference between expt and vaneijck-3 for 2B and 3B
axs[1,0].plot([float(x) for x in x_elatt_2b_cutoff_list],np.array(x_elatt_big_basis_2b_cutoff_dict['expt']) - np.array(x_elatt_big_basis_2b_cutoff_dict['vaneijck']),label=f'Reduced',c='purple',alpha=0.7,marker='x')
axs[1,0].plot([float(x) for x in x_elatt_2b_cutoff_list],np.array(x_elatt_small_basis_2b_cutoff_dict['expt']) - np.array(x_elatt_small_basis_2b_cutoff_dict['vaneijck']),label=f'Full',c='purple',alpha=0.7,marker='o',linestyle='--',markerfacecolor='none')
axs[1,1].plot(x_elatt_3b_cutoff_list,np.array(x_elatt_big_basis_3b_cutoff_dict['expt']) - np.array(x_elatt_big_basis_3b_cutoff_dict['vaneijck']),label=f'Reduced',c='purple',alpha=0.7,marker='x')
axs[1,1].plot(x_elatt_3b_cutoff_list,np.array(x_elatt_small_basis_3b_cutoff_dict['expt']) - np.array(x_elatt_small_basis_3b_cutoff_dict['vaneijck']),label=f'Full',c='purple',alpha=0.7,marker='o',linestyle='--',markerfacecolor='none')

axs[0,0].set_ylim([-200,-100])
axs[0,1].set_ylim([-6,6])
axs[1,0].set_ylim([-60,60])
axs[1,1].set_ylim([-6,6])
axs[0,0].set_xlim([3.5,15])
axs[0,1].set_xlim([100,500])
axs[1,0].set_xlim([3.5,15])
axs[1,1].set_xlim([100,500])


axs[0,1].legend(fontsize=8)
axs[1,1].legend(fontsize=8)


axs[0,0].set_ylabel(r'2B contribution to $E_\text{latt}$ (kJ/mol)')
axs[0,1].set_ylabel(r'3B contribution to $E_\text{latt}$ (kJ/mol)')
axs[1,0].set_ylabel(r'2B contribution to $E_\text{rel}$ (kJ/mol)')
axs[1,1].set_ylabel(r'3B contribution to $E_\text{rel}$ (kJ/mol)')
axs[1,0].set_xlabel(r'2B Distance cutoff (\AA{})')
axs[1,1].set_xlabel(r'3B Distance cutoff (\AA{}$^3$)')

plt.savefig('Figures/SI_Figure-X_2b_3b_distance_convergence_different_basis_sets.png')

In [87]:
# DataFrame of expt, vaneijck and difference for each method
x_method_conv_df = pd.DataFrame.from_dict({
    ('Small basis', 'Experimental') : {key: value/kjmol for key, value in pharma_polymorph_method_ene_dict['X']['expt']['Final'].items()},
    ('Small basis', 'vanEijck-3') : {key: value/kjmol for key, value in pharma_polymorph_method_ene_dict['X']['vaneijck']['Final'].items()},
    ('Small basis', r'$E_\text{rel}$') : {key: (pharma_polymorph_method_ene_dict['X']['expt']['Final'][key] - pharma_polymorph_method_ene_dict['X']['vaneijck']['Final'][key])/kjmol for key in pharma_polymorph_method_ene_dict['X']['expt']['Final'].keys()},
    ('Large basis', 'Experimental') : {key: value/kjmol for key, value in x_method_conv_elatt_dict['expt']['LAF'].items()},
    ('Large basis', 'vanEijck-3') : {key: value/kjmol for key, value in x_method_conv_elatt_dict['vaneijck']['LAF'].items()},
    ('Large basis', r'$E_\text{rel}$') : {key: (x_method_conv_elatt_dict['expt']['LAF'][key] - x_method_conv_elatt_dict['vaneijck']['LAF'][key])/kjmol for key in x_method_conv_elatt_dict['expt']['LAF'].keys()}
}, orient='index')


# Convert to nearest 1 decimal place
x_method_conv_df = x_method_conv_df.round(1)

# Write to LaTeX table
convert_df_to_latex_input(
    df = x_method_conv_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x_method_convergence",
    caption = r"Convergence of the relative energies between the experimental and vanEijck-3 polymorphs of X arising from CCSD(T) correlation with respect to basis set size. Both the results with the `Reduced' basis set (used in the main text) and `Full' basis sets are given. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]",
        r"Small": r"Reduced",
        r"Large": r"Full"
    },
    float_fmt="%.1f",
    column_format="lrrrrr",
    filename = "Tables/SI_Table-X_Method_Convergence.tex")

display(x_method_conv_df)

                             1B     2B   3B  Total
Small basis Experimental   -0.0 -152.4  1.6 -150.8
            vanEijck-3      0.6 -165.1  1.9 -162.6
            $E_\text{rel}$ -0.6   12.8 -0.3   11.8
Large basis Experimental   -0.0 -181.2  1.6 -179.6
            vanEijck-3      1.2 -190.8  1.5 -188.1
            $E_\text{rel}$ -1.2    9.6  0.1    8.5

## Final MBE contributions

### ROY

In [88]:
# Give the 1B, 2B, 3B and total CCSD(T) as well as CCSD(T)-D4 corrected interaction energies for all ROY polymorphs in a table

roy_mbe_contributions_dict = {
    ('without D4', 'HF', 'Periodic'): {x: pharma_polymorph_ene_dict['ROY'][x]['Periodic HF']/kjmol for x in ['R','Y']},
    ('without D4', 'CCSD(T) corr', '1B'): {x: pharma_polymorph_method_ene_dict['ROY'][x]['Final']['1B']/kjmol for x in ['R','Y']},
    ('without D4', 'CCSD(T) corr', '2B'): {x: pharma_polymorph_method_ene_dict['ROY'][x]['Final']['2B']/kjmol for x in ['R','Y']},
    ('without D4', 'CCSD(T) corr', '3B'): {x: pharma_polymorph_method_ene_dict['ROY'][x]['Final']['3B']/kjmol for x in ['R','Y']},
    ('without D4', 'CCSD(T) corr', 'Sum'): {x: pharma_polymorph_method_ene_dict['ROY'][x]['Final']['Total']/kjmol for x in ['R','Y']},
    ('without D4', 'Final', 'Total'): {x: (pharma_polymorph_ene_dict['ROY'][x]['Periodic HF'] + pharma_polymorph_method_ene_dict['ROY'][x]['Final']['Total'])/kjmol for x in ['R','Y']},
    ('with D4', 'HF', 'Periodic'): {x: pharma_polymorph_ene_dict['ROY'][x]['Periodic HF + D4']/kjmol for x in ['R','Y']},
    ('with D4', 'CCSD(T) corr - D4', '1B'): {x: pharma_polymorph_method_ene_dict['ROY'][x]['Final']['1B']/kjmol - pharma_polymorph_method_ene_dict['ROY'][x]['D4']['1B']/kjmol for x in ['R','Y']},
    ('with D4', 'CCSD(T) corr - D4', '2B'): {x: pharma_polymorph_method_ene_dict['ROY'][x]['Final']['2B']/kjmol - pharma_polymorph_method_ene_dict['ROY'][x]['D4']['2B']/kjmol for x in ['R','Y']},
    ('with D4', 'CCSD(T) corr - D4', '3B'): {x: pharma_polymorph_method_ene_dict['ROY'][x]['Final']['3B']/kjmol - pharma_polymorph_method_ene_dict['ROY'][x]['D4']['3B']/kjmol for x in ['R','Y']},
    ('with D4', 'CCSD(T) corr - D4', 'Sum'): {x: pharma_polymorph_method_ene_dict['ROY'][x]['Final']['Total']/kjmol - pharma_polymorph_method_ene_dict['ROY'][x]['D4']['Total']/kjmol for x in ['R','Y']},
    ('with D4', 'Final', 'Total'): {x: (pharma_polymorph_ene_dict['ROY'][x]['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['ROY'][x]['Final']['Total'] - pharma_polymorph_method_ene_dict['ROY'][x]['D4']['Total'])/kjmol for x in ['R','Y']}
}

# Convert to a dataframe
roy_mbe_contributions_df = pd.DataFrame(roy_mbe_contributions_dict)
roy_mbe_contributions_df = roy_mbe_contributions_df.reindex(index=['R','Y'])
# roy_mbe_contributions_df.index.name = 'Polymorph'
roy_mbe_contributions_df.columns.names = ['D4 Correction','Method','MBE Level']
roy_mbe_contributions_df = roy_mbe_contributions_df.round(2)
display(roy_mbe_contributions_df)

# Convert to LaTeX table
convert_df_to_latex_input(
    df = roy_mbe_contributions_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:roy_mbe_contributions",
    caption = r"Contributions to the CCSD(T) relative energies between the R and Y polymorphs of ROY from the many-body expansion (MBE) up to 3-body terms. Both the results without and with (corrections from HF with) D4 dispersion corrections are given. 1B terms are computed relative to the monomer taken from polymorph Y. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]",
        r"Final \\": r"Final \\ \cmidrule(lr){2-2} \cmidrule(lr){3-6} \cmidrule(lr){7-7} \cmidrule(lr){8-8} \cmidrule(lr){9-12} \cmidrule(lr){13-13}",
        r"& HF &": r"& \multicolumn{1}{c}{HF} &",
        r"& Final": r"& \multicolumn{1}{c}{Final}",
        r"\multicolumn{6}{c}{with D4} \\": r"\multicolumn{6}{c}{with D4} \\ \cmidrule(lr){2-7} \cmidrule(lr){8-13}",
    },
    float_fmt="%.1f",
    filename = "Tables/SI_Table-ROY_MBE_contributions.tex")

D4 Correction without D4                                               \
Method                HF CCSD(T) corr                           Final
MBE Level       Periodic           1B      2B    3B     Sum     Total
R              -31437.14        -4.56 -215.03  3.78 -215.80 -31652.95
Y              -31435.74        -0.00 -224.35  6.24 -218.11 -31653.86

D4 Correction   with D4
Method               HF CCSD(T) corr - D4                         Final
MBE Level      Periodic                1B     2B    3B    Sum     Total
R             -31978.27             -4.17  -8.91 -4.02 -17.10 -31995.37
Y             -31980.56             -0.00 -13.96 -1.61 -15.57 -31996.13

### Axitinib

In [89]:
# Give the 1B, 2B, 3B and total CCSD(T) as well as CCSD(T)-D4 corrected interaction energies for all Axitinib polymorphs in a table

axitinib_mbe_contributions_dict = {
    ('without D4', 'HF', 'Periodic'): {x: pharma_polymorph_ene_dict['Axitinib'][x]['Periodic HF']/kjmol for x in ['VI','XLI']},
    ('without D4', 'CCSD(T) corr', '1B'): {x: pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['1B']/kjmol for x in ['VI','XLI']},
    ('without D4', 'CCSD(T) corr', '2B'): {x: pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['2B']/kjmol for x in ['VI','XLI']},
    ('without D4', 'CCSD(T) corr', '3B'): {x: pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['3B']/kjmol for x in ['VI','XLI']},
    ('without D4', 'CCSD(T) corr', 'Sum'): {x: pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['Total']/kjmol for x in ['VI','XLI']},
    ('without D4', 'Final', 'Total'): {x: (pharma_polymorph_ene_dict['Axitinib'][x]['Periodic HF'] + pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['Total'])/kjmol for x in ['VI','XLI']},
    ('with D4', 'HF', 'Periodic'): {x: pharma_polymorph_ene_dict['Axitinib'][x]['Periodic HF + D4']/kjmol for x in ['VI','XLI']},
    ('with D4', 'CCSD(T) corr - D4', '1B'): {x: pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['1B']/kjmol - pharma_polymorph_method_ene_dict['Axitinib'][x]['D4']['1B']/kjmol for x in ['VI','XLI']},
    ('with D4', 'CCSD(T) corr - D4', '2B'): {x: pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['2B']/kjmol - pharma_polymorph_method_ene_dict['Axitinib'][x]['D4']['2B']/kjmol for x in ['VI','XLI']},
    ('with D4', 'CCSD(T) corr - D4', '3B'): {x: pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['3B']/kjmol - pharma_polymorph_method_ene_dict['Axitinib'][x]['D4']['3B']/kjmol for x in ['VI','XLI']},
    ('with D4', 'CCSD(T) corr - D4', 'Sum'): {x: pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['Total']/kjmol - pharma_polymorph_method_ene_dict['Axitinib'][x]['D4']['Total']/kjmol for x in ['VI','XLI']},
    ('with D4', 'Final', 'Total'): {x: (pharma_polymorph_ene_dict['Axitinib'][x]['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Axitinib'][x]['Final']['Total'] - pharma_polymorph_method_ene_dict['Axitinib'][x]['D4']['Total'])/kjmol for x in ['VI','XLI']}
}

# Convert to a dataframe
axitinib_mbe_contributions_df = pd.DataFrame(axitinib_mbe_contributions_dict)
axitinib_mbe_contributions_df = axitinib_mbe_contributions_df.reindex(index=['VI','XLI'])
# axitinib_mbe_contributions_df.index.name = 'Polymorph'
axitinib_mbe_contributions_df.columns.names = ['D4 Correction','Method','MBE Level']
axitinib_mbe_contributions_df = axitinib_mbe_contributions_df.round(2)
display(axitinib_mbe_contributions_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = axitinib_mbe_contributions_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:axitinib_mbe_contributions",
    caption = r"Contributions to the CCSD(T) relative energies between the VI and XLI polymorphs of Axitinib from the many-body expansion (MBE) up to 3-body terms. Both the results without and with (corrections from HF with) D4 dispersion corrections are given. 1B terms are computed relative to the monomer taken from polymorph XLI. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]",
        r"Final \\": r"Final \\ \cmidrule(lr){2-2} \cmidrule(lr){3-6} \cmidrule(lr){7-7} \cmidrule(lr){8-8} \cmidrule(lr){9-12} \cmidrule(lr){13-13}",
        r"& HF &": r"& \multicolumn{1}{c}{HF} &",
        r"& Final": r"& \multicolumn{1}{c}{Final}",
        r"\multicolumn{6}{c}{with D4} \\": r"\multicolumn{6}{c}{with D4} \\ \cmidrule(lr){2-7} \cmidrule(lr){8-13}",
    },
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Axitinib_MBE_contributions.tex")

D4 Correction without D4                                               \
Method                HF CCSD(T) corr                           Final
MBE Level       Periodic           1B      2B    3B     Sum     Total
VI             -51601.73         1.92 -344.85  3.24 -339.68 -51941.41
XLI            -51600.34         0.00 -350.94  3.31 -347.63 -51947.97

D4 Correction   with D4
Method               HF CCSD(T) corr - D4                         Final
MBE Level      Periodic                1B     2B    3B    Sum     Total
VI            -52506.27             -6.26 -22.71 -1.32 -30.29 -52536.55
XLI           -52516.97              0.00 -22.92 -4.20 -27.12 -52544.09

### Rotigotine

In [90]:
# Give the 1B, 2B, 3B and total CCSD(T) as well as CCSD(T)-D4 corrected interaction energies for all Rotigotine polymorphs in a table

rotigotine_mbe_contributions_dict = {
    ('without D4', 'HF', 'Periodic'): {x: pharma_polymorph_ene_dict['Rotigotine'][x]['Periodic HF']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('without D4', 'CCSD(T) corr', '1B'): {x: pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['1B']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('without D4', 'CCSD(T) corr', '2B'): {x: pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['2B']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('without D4', 'CCSD(T) corr', '3B'): {x: pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['3B']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('without D4', 'CCSD(T) corr', 'Sum'): {x: pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['Total']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('without D4', 'Final', 'Total'): {x: (pharma_polymorph_ene_dict['Rotigotine'][x]['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['Total'])/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('with D4', 'HF', 'Periodic'): {x: pharma_polymorph_ene_dict['Rotigotine'][x]['Periodic HF + D4']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('with D4', 'CCSD(T) corr - D4', '1B'): {x: pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['1B']/kjmol - pharma_polymorph_method_ene_dict['Rotigotine'][x]['D4']['1B']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('with D4', 'CCSD(T) corr - D4', '2B'): {x: pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['2B']/kjmol - pharma_polymorph_method_ene_dict['Rotigotine'][x]['D4']['2B']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('with D4', 'CCSD(T) corr - D4', '3B'): {x: pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['3B']/kjmol - pharma_polymorph_method_ene_dict['Rotigotine'][x]['D4']['3B']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('with D4', 'CCSD(T) corr - D4', 'Sum'): {x: pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['Total']/kjmol - pharma_polymorph_method_ene_dict['Rotigotine'][x]['D4']['Total']/kjmol for x in ['I_1','I_2','II_1','II_2']},
    ('with D4', 'Final', 'Total'): {x: (pharma_polymorph_ene_dict['Rotigotine'][x]['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine'][x]['Final']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine'][x]['D4']['Total'])/kjmol for x in ['I_1','I_2','II_1','II_2']}
}
# Convert to a dataframe
rotigotine_mbe_contributions_df = pd.DataFrame(rotigotine_mbe_contributions_dict)
rotigotine_mbe_contributions_df = rotigotine_mbe_contributions_df.reindex(index=['I_1','I_2','II_1','II_2'])
# rotigotine_mbe_contributions_df.index.name = 'Polymorph'
rotigotine_mbe_contributions_df.columns.names = ['D4 Correction','Method','MBE Level']
rotigotine_mbe_contributions_df = rotigotine_mbe_contributions_df.round(2)
display(rotigotine_mbe_contributions_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = rotigotine_mbe_contributions_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:rotigotine_mbe_contributions",
    caption = r"Contributions to the CCSD(T) relative energies between the I and II polymorphs of Rotigotine from the many-body expansion (MBE) up to 3-body terms. Both the results without and with (corrections from HF with) D4 dispersion corrections are given. 1B terms are computed relative to the monomer taken from polymorph II\textsubscript{1}. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]",
        "_1": r"\textsubscript{1}",
        "_2": r"\textsubscript{2}",
        r"Final \\": r"Final \\ \cmidrule(lr){2-2} \cmidrule(lr){3-6} \cmidrule(lr){7-7} \cmidrule(lr){8-8} \cmidrule(lr){9-12} \cmidrule(lr){13-13}",
        r"& HF &": r"& \multicolumn{1}{c}{HF} &",
        r"& Final": r"& \multicolumn{1}{c}{Final}",
        r"\multicolumn{6}{c}{with D4} \\": r"\multicolumn{6}{c}{with D4} \\ \cmidrule(lr){2-7} \cmidrule(lr){8-13}",
    },
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Rotigotine_MBE_contributions.tex")

D4 Correction without D4                                               \
Method                HF CCSD(T) corr                           Final
MBE Level       Periodic           1B      2B    3B     Sum     Total
I_1            -46115.89        -1.42 -252.02  2.33 -251.11 -46367.00
I_2            -46114.46         0.05 -254.66  3.10 -251.51 -46365.97
II_1           -46105.40        -0.00 -273.44  4.89 -268.55 -46373.95
II_2           -46104.80        -1.27 -270.72  3.75 -268.24 -46373.04

D4 Correction   with D4
Method               HF CCSD(T) corr - D4                         Final
MBE Level      Periodic                1B     2B    3B    Sum     Total
I_1           -46865.82             -0.59 -22.74 -2.13 -25.46 -46891.28
I_2           -46866.88             -0.71 -21.19 -2.65 -24.55 -46891.43
II_1          -46874.68              0.00 -21.72 -2.66 -24.37 -46899.05
II_2          -46874.27              0.53 -20.85 -2.60 -22.91 -46897.18

### Molecule X

In [91]:
# Give the 1B, 2B, 3B and total CCSD(T) as well as CCSD(T)-D4 corrected interaction energies for all X polymorphs in a table
x_mbe_contributions_dict = {
    ('without D4', 'HF', 'Periodic'): {x: pharma_polymorph_ene_dict['X'][x]['Periodic HF']/kjmol for x in ['expt','vaneijck']},
    ('without D4', 'CCSD(T) corr', '1B'): {x: pharma_polymorph_method_ene_dict['X'][x]['Final']['1B']/kjmol for x in ['expt','vaneijck']},
    ('without D4', 'CCSD(T) corr', '2B'): {x: pharma_polymorph_method_ene_dict['X'][x]['Final']['2B']/kjmol for x in ['expt','vaneijck']},
    ('without D4', 'CCSD(T) corr', '3B'): {x: pharma_polymorph_method_ene_dict['X'][x]['Final']['3B']/kjmol for x in ['expt','vaneijck']},
    ('without D4', 'CCSD(T) corr', 'Sum'): {x: pharma_polymorph_method_ene_dict['X'][x]['Final']['Total']/kjmol for x in ['expt','vaneijck']},
    ('without D4', 'Final', 'Total'): {x: (pharma_polymorph_ene_dict['X'][x]['Periodic HF'] + pharma_polymorph_method_ene_dict['X'][x]['Final']['Total'])/kjmol for x in ['expt','vaneijck']},
    ('with D4', 'HF', 'Periodic'): {x: pharma_polymorph_ene_dict['X'][x]['Periodic HF + D4']/kjmol for x in ['expt','vaneijck']},
    ('with D4', 'CCSD(T) corr - D4', '1B'): {x: pharma_polymorph_method_ene_dict['X'][x]['Final']['1B']/kjmol - pharma_polymorph_method_ene_dict['X'][x]['D4']['1B']/kjmol for x in ['expt','vaneijck']},
    ('with D4', 'CCSD(T) corr - D4', '2B'): {x: pharma_polymorph_method_ene_dict['X'][x]['Final']['2B']/kjmol - pharma_polymorph_method_ene_dict['X'][x]['D4']['2B']/kjmol for x in ['expt','vaneijck']},
    ('with D4', 'CCSD(T) corr - D4', '3B'): {x: pharma_polymorph_method_ene_dict['X'][x]['Final']['3B']/kjmol - pharma_polymorph_method_ene_dict['X'][x]['D4']['3B']/kjmol for x in ['expt','vaneijck']},
    ('with D4', 'CCSD(T) corr - D4', 'Sum'): {x: pharma_polymorph_method_ene_dict['X'][x]['Final']['Total']/kjmol - pharma_polymorph_method_ene_dict['X'][x]['D4']['Total']/kjmol for x in ['expt','vaneijck']},
    ('with D4', 'Final', 'Total'): {x: (pharma_polymorph_ene_dict['X'][x]['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['X'][x]['Final']['Total'] - pharma_polymorph_method_ene_dict['X'][x]['D4']['Total'])/kjmol for x in ['expt','vaneijck']}
}
# Convert to a dataframe
x_mbe_contributions_df = pd.DataFrame(x_mbe_contributions_dict)
x_mbe_contributions_df = x_mbe_contributions_df.reindex(index=['expt','vaneijck'])
# x_mbe_contributions_df.index.name = 'Polymorph'
x_mbe_contributions_df.columns.names = ['D4 Correction','Method','MBE Level']
x_mbe_contributions_df = x_mbe_contributions_df.round(2)
display(x_mbe_contributions_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = x_mbe_contributions_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x_mbe_contributions",
    caption = r"Contributions to the CCSD(T) relative energies between the experimental and vanEijck-3 polymorphs of X from the many-body expansion (MBE) up to 3-body terms. Both the results without and with (corrections from HF with) D4 dispersion corrections are given. 1B terms are computed relative to the monomer taken from the vanEijck-3 polymorph. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]",
        r"Final \\": r"Final \\ \cmidrule(lr){2-2} \cmidrule(lr){3-6} \cmidrule(lr){7-7} \cmidrule(lr){8-8} \cmidrule(lr){9-12} \cmidrule(lr){13-13}",
        r"& HF &": r"& \multicolumn{1}{c}{HF} &",
        r"& Final": r"& \multicolumn{1}{c}{Final}",
        r"\multicolumn{6}{c}{with D4} \\": r"\multicolumn{6}{c}{with D4} \\ \cmidrule(lr){2-7} \cmidrule(lr){8-13}",
    },
    float_fmt="%.1f",
    filename = "Tables/SI_Table-X_MBE_contributions.tex")

D4 Correction without D4                                               \
Method                HF CCSD(T) corr                           Final
MBE Level       Periodic           1B      2B    3B     Sum     Total
expt           -30679.53        -0.00 -152.36  1.60 -150.76 -30830.29
vaneijck       -30669.82         0.61 -165.12  1.93 -162.58 -30832.40

D4 Correction   with D4
Method               HF CCSD(T) corr - D4                       Final
MBE Level      Periodic                1B    2B    3B   Sum     Total
expt          -31124.85              -0.0  8.72 -1.62  7.10 -31117.75
vaneijck      -31122.98               0.4  5.46 -2.98  2.88 -31120.10

## Final relative energies

In [95]:
# Give a table of the final relative energies for all polymorphs with CCSD(T) and CCSD(T)-D4 corrections

pharma_exp_relative_ene_dict = {
    'ROY': [experimental_rel_energy_num_dict['ROY']['Expt. DeltaE'],0.5], # https://pubs-acs-org.ezp.lib.cam.ac.uk/doi/10.1021/ar100040r
    'Axitinib': [experimental_rel_energy_num_dict['Axitinib']['Expt. DeltaE'],2*386.47/(1000)], # Development of a targeted polymorph screening approach for a complex polymorphic and highly solvating API
    'Rotigotine': [experimental_rel_energy_num_dict['Rotigotine']['Expt. DeltaE'],0.5], # Relative enthalpy is 7.5 and correct for temperature effects of 0.5 https://www.nature.com/articles/s42004-019-0171-y#MOESM3
    'X': [0,0]
}


final_relative_energies_dict = {
    ('Experiment', '(kJ/mol)'): {
        'ROY R - Y': rf"{pharma_exp_relative_ene_dict['ROY'][0]:.1f}$\pm${pharma_exp_relative_ene_dict['ROY'][1]}"+ r"~\cite{yuPolymorphismMolecularSolids2010b}",
        'Axitinib VI - XLI': rf"{pharma_exp_relative_ene_dict['Axitinib'][0]:.1f}$\pm${pharma_exp_relative_ene_dict['Axitinib'][1]:.1f}" + r"~\cite{campetaDevelopmentTargetedPolymorph2010a}",
        'Rotigotine I - II': rf"{pharma_exp_relative_ene_dict['Rotigotine'][0]:.1f}$\pm${pharma_exp_relative_ene_dict['Rotigotine'][1]:.1f}" + r"~\cite{mortazaviComputationalPolymorphScreening2019}",
        'X vanEijck-3 - Expt': 'N/A'
    },
    ('without D4', 'MP2'): {
        'ROY R - Y': (pharma_polymorph_ene_dict['ROY']['R']['Periodic HF'] + pharma_polymorph_method_ene_dict['ROY']['R']['MP2 Canonical']['Total'])/kjmol - (pharma_polymorph_ene_dict['ROY']['Y']['Periodic HF'] + pharma_polymorph_method_ene_dict['ROY']['Y']['MP2 Canonical']['Total'])/kjmol,
        'Axitinib VI - XLI': (pharma_polymorph_ene_dict['Axitinib']['VI']['Periodic HF'] + pharma_polymorph_method_ene_dict['Axitinib']['VI']['MP2 Canonical']['Total'])/kjmol - (pharma_polymorph_ene_dict['Axitinib']['XLI']['Periodic HF'] + pharma_polymorph_method_ene_dict['Axitinib']['XLI']['MP2 Canonical']['Total'])/kjmol,
        'Rotigotine I - II': (pharma_polymorph_ene_dict['Rotigotine']['I_1']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['MP2 Canonical']['Total'])/(2*kjmol) +  (pharma_polymorph_ene_dict['Rotigotine']['I_2']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['MP2 Canonical']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_1']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['MP2 Canonical']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_2']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['MP2 Canonical']['Total'])/(2*kjmol),
        'X vanEijck-3 - Expt': (pharma_polymorph_ene_dict['X']['vaneijck']['Periodic HF'] + pharma_polymorph_method_ene_dict['X']['vaneijck']['MP2 Canonical']['Total'])/kjmol - (pharma_polymorph_ene_dict['X']['expt']['Periodic HF'] + pharma_polymorph_method_ene_dict['X']['expt']['MP2 Canonical']['Total'])/kjmol
    },
    ('without D4', 'CCSD'): {
        'ROY R - Y': (pharma_polymorph_ene_dict['ROY']['R']['Periodic HF'] + pharma_polymorph_method_ene_dict['ROY']['R']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['ROY']['R']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['ROY']['R']['MP2 LAF']['Total'])/kjmol - (pharma_polymorph_ene_dict['ROY']['Y']['Periodic HF'] + pharma_polymorph_method_ene_dict['ROY']['Y']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['ROY']['Y']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['ROY']['Y']['MP2 LAF']['Total'])/kjmol,
        'Axitinib VI - XLI': (pharma_polymorph_ene_dict['Axitinib']['VI']['Periodic HF'] + pharma_polymorph_method_ene_dict['Axitinib']['VI']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Axitinib']['VI']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['VI']['MP2 LAF']['Total'])/kjmol - (pharma_polymorph_ene_dict['Axitinib']['XLI']['Periodic HF'] + pharma_polymorph_method_ene_dict['Axitinib']['XLI']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Axitinib']['XLI']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['XLI']['MP2 LAF']['Total'])/kjmol,
        'Rotigotine I - II': (pharma_polymorph_ene_dict['Rotigotine']['I_1']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['MP2 LAF']['Total'])/(2*kjmol) +  (pharma_polymorph_ene_dict['Rotigotine']['I_2']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['MP2 LAF']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_1']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['MP2 LAF']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_2']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['MP2 LAF']['Total'])/(2*kjmol),
        'X vanEijck-3 - Expt': (pharma_polymorph_ene_dict['X']['vaneijck']['Periodic HF'] + pharma_polymorph_method_ene_dict['X']['vaneijck']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['X']['vaneijck']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['X']['vaneijck']['MP2 LAF']['Total'])/kjmol - (pharma_polymorph_ene_dict['X']['expt']['Periodic HF'] + pharma_polymorph_method_ene_dict['X']['expt']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['X']['expt']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['X']['expt']['MP2 LAF']['Total'])/kjmol
    },
    ('without D4', 'CCSD(T)'): {
        'ROY R - Y': (pharma_polymorph_ene_dict['ROY']['R']['Periodic HF'] + pharma_polymorph_method_ene_dict['ROY']['R']['Final']['Total'])/kjmol - (pharma_polymorph_ene_dict['ROY']['Y']['Periodic HF'] + pharma_polymorph_method_ene_dict['ROY']['Y']['Final']['Total'])/kjmol,
        'Axitinib VI - XLI': (pharma_polymorph_ene_dict['Axitinib']['VI']['Periodic HF'] + pharma_polymorph_method_ene_dict['Axitinib']['VI']['Final']['Total'])/kjmol - (pharma_polymorph_ene_dict['Axitinib']['XLI']['Periodic HF'] + pharma_polymorph_method_ene_dict['Axitinib']['XLI']['Final']['Total'])/kjmol,
        'Rotigotine I - II': (pharma_polymorph_ene_dict['Rotigotine']['I_1']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['Final']['Total'])/(2*kjmol) +  (pharma_polymorph_ene_dict['Rotigotine']['I_2']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['Final']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_1']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['Final']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_2']['Periodic HF'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['Final']['Total'])/(2*kjmol),
        'X vanEijck-3 - Expt': (pharma_polymorph_ene_dict['X']['vaneijck']['Periodic HF'] + pharma_polymorph_method_ene_dict['X']['vaneijck']['Final']['Total'])/kjmol - (pharma_polymorph_ene_dict['X']['expt']['Periodic HF'] + pharma_polymorph_method_ene_dict['X']['expt']['Final']['Total'])/kjmol},
    ('with D4', 'MP2'): {
        'ROY R - Y': (pharma_polymorph_ene_dict['ROY']['R']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['ROY']['R']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['ROY']['R']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['ROY']['Y']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['ROY']['Y']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['ROY']['Y']['D4']['Total'])/kjmol,
        'Axitinib VI - XLI': (pharma_polymorph_ene_dict['Axitinib']['VI']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Axitinib']['VI']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['VI']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['Axitinib']['XLI']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Axitinib']['XLI']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['XLI']['D4']['Total'])/kjmol,
        'Rotigotine I - II': (pharma_polymorph_ene_dict['Rotigotine']['I_1']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['D4']['Total'])/(2*kjmol) +  (pharma_polymorph_ene_dict['Rotigotine']['I_2']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['D4']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_1']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['D4']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_2']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['D4']['Total'])/(2*kjmol),
        'X vanEijck-3 - Expt': (pharma_polymorph_ene_dict['X']['vaneijck']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['X']['vaneijck']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['X']['vaneijck']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['X']['expt']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['X']['expt']['MP2 Canonical']['Total'] - pharma_polymorph_method_ene_dict['X']['expt']['D4']['Total'])/kjmol
    },
    ('with D4', 'CCSD'): {
        'ROY R - Y': (pharma_polymorph_ene_dict['ROY']['R']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['ROY']['R']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['ROY']['R']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['ROY']['R']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['ROY']['R']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['ROY']['Y']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['ROY']['Y']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['ROY']['Y']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['ROY']['Y']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['ROY']['Y']['D4']['Total'])/kjmol,
        'Axitinib VI - XLI': (pharma_polymorph_ene_dict['Axitinib']['VI']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Axitinib']['VI']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Axitinib']['VI']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['VI']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['VI']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['Axitinib']['XLI']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Axitinib']['XLI']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Axitinib']['XLI']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['XLI']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['XLI']['D4']['Total'])/kjmol,
        'Rotigotine I - II': (pharma_polymorph_ene_dict['Rotigotine']['I_1']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['D4']['Total'])/(2*kjmol) +  (pharma_polymorph_ene_dict['Rotigotine']['I_2']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['D4']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_1']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['D4']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_2']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['D4']['Total'])/(2*kjmol),
        'X vanEijck-3 - Expt': (pharma_polymorph_ene_dict['X']['vaneijck']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['X']['vaneijck']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['X']['vaneijck']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['X']['vaneijck']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['X']['vaneijck']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['X']['expt']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['X']['expt']['MP2 Canonical']['Total'] + pharma_polymorph_method_ene_dict['X']['expt']['CCSD LAF']['Total'] - pharma_polymorph_method_ene_dict['X']['expt']['MP2 LAF']['Total'] - pharma_polymorph_method_ene_dict['X']['expt']['D4']['Total'])/kjmol
    },
    ('with D4', 'CCSD(T)'): {
        'ROY R - Y': (pharma_polymorph_ene_dict['ROY']['R']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['ROY']['R']['Final']['Total'] - pharma_polymorph_method_ene_dict['ROY']['R']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['ROY']['Y']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['ROY']['Y']['Final']['Total'] - pharma_polymorph_method_ene_dict['ROY']['Y']['D4']['Total'])/kjmol,
        'Axitinib VI - XLI': (pharma_polymorph_ene_dict['Axitinib']['VI']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Axitinib']['VI']['Final']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['VI']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['Axitinib']['XLI']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Axitinib']['XLI']['Final']['Total'] - pharma_polymorph_method_ene_dict['Axitinib']['XLI']['D4']['Total'])/kjmol,
        'Rotigotine I - II': (pharma_polymorph_ene_dict['Rotigotine']['I_1']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['Final']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_1']['D4']['Total'])/(2*kjmol) +  (pharma_polymorph_ene_dict['Rotigotine']['I_2']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['Final']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['I_2']['D4']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_1']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['Final']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_1']['D4']['Total'])/(2*kjmol) - (pharma_polymorph_ene_dict['Rotigotine']['II_2']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['Final']['Total'] - pharma_polymorph_method_ene_dict['Rotigotine']['II_2']['D4']['Total'])/(2*kjmol),
        'X vanEijck-3 - Expt': (pharma_polymorph_ene_dict['X']['vaneijck']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['X']['vaneijck']['Final']['Total'] - pharma_polymorph_method_ene_dict['X']['vaneijck']['D4']['Total'])/kjmol - (pharma_polymorph_ene_dict['X']['expt']['Periodic HF + D4'] + pharma_polymorph_method_ene_dict['X']['expt']['Final']['Total'] - pharma_polymorph_method_ene_dict['X']['expt']['D4']['Total'])/kjmol
    },

}

# Convert to dataframe
final_relative_energies_df = pd.DataFrame(final_relative_energies_dict)
display(final_relative_energies_df)
# Convert to LaTeX table
convert_df_to_latex_input(
    df = final_relative_energies_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:final_relative_energies",
    caption = r"Final relative energies between the most stable polymorphs of each pharmaceutical molecule studied here with different levels of theory, both without and with (corrections from HF with) D4 dispersion corrections. All values are in kJ/mol.",
    replace_input= {
        "[t]": "[c]",
        r"\multicolumn{3}{c}{with D4} \\": r"\multicolumn{3}{c}{with D4} \\ \cmidrule(lr){3-5} \cmidrule(lr){6-8}",
    },
    float_fmt="%.1f",
    filename = "Tables/SI_Table-Final_Relative_Energies.tex")

                                                            Experiment  \
                                                              (kJ/mol)
ROY R - Y            1.2$\pm$0.5~\cite{yuPolymorphismMolecularSolid...
Axitinib VI - XLI    7.5$\pm$0.8~\cite{campetaDevelopmentTargetedPo...
Rotigotine I - II    7.0$\pm$0.5~\cite{mortazaviComputationalPolymo...
X vanEijck-3 - Expt                                                N/A

                    without D4                        with D4            \
                           MP2      CCSD   CCSD(T)        MP2      CCSD
ROY R - Y             1.637755  1.951373  0.911038   1.483689  1.797307
Axitinib VI - XLI    11.378269  5.816703  6.560902  12.353972  6.792407
Rotigotine I - II     7.838926  4.373686  7.012768   7.587992  4.122752
X vanEijck-3 - Expt  -2.519328 -0.024637 -2.110585  -2.761416 -0.266725


                      CCSD(T)
ROY R - Y            0.756972
Axitinib VI - XLI    7.536606
Rotigotine I - II    6.761834
X vanEijck-3 - Expt -2.352673

## Errors from DFT geometry

In [97]:
xc_func_dict = {
    '01': 'B86bPBE-XDM',
    '02': 'B86bPBE25-XDM',
    '03': 'B86bPBE50-XDM',
    '04': 'PBE-D3(BJ)',
    '05': 'PBE-MBD',
    '06': 'PBE0-MBD'
}

# Get the relative energies

xc_func_geom_erel_dict = { system : {xc_func: {xc_func: 0 for xc_func in xc_func_dict.values()} for xc_func in xc_func_dict.values()} for system in ['ROY', 'Axitinib', 'Rotigotine', 'Molecule X']}

xc_func_geom_err_dict = { system : {xc_func: {xc_func: 0 for xc_func in list(xc_func_dict.values()) + ['MAD']} for xc_func in list(xc_func_dict.values()) + ['MAD']} for system in ['ROY', 'Axitinib', 'Rotigotine', 'Molecule X']}

for calc_xc_func in xc_func_dict.keys():
    for geom_xc_func in xc_func_dict.keys():
        for system in ['ROY', 'Axitinib', 'Rotigotine', 'Molecule X']:
            # Analyse the revXDM AIMS calculations first
            if system == 'ROY':
                form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/ROY_R/aims.out.gz').get_potential_energy()/2
                form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/ROY_Y/aims.out.gz').get_potential_energy()/4
            elif system == 'Axitinib':
                form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/Axitinib_VI/aims.out.gz').get_potential_energy()/2
                form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/Axitinib_XLI/aims.out.gz').get_potential_energy()/4
            elif system == 'Rotigotine':
                form_1_ene = (read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/Rotigotine_I_1/aims.out.gz').get_potential_energy() + read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/Rotigotine_I_2/aims.out.gz').get_potential_energy())/8
                form_2_ene = (read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/Rotigotine_II_1/aims.out.gz').get_potential_energy() + read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/Rotigotine_II_2/aims.out.gz').get_potential_energy())/8
            elif system == 'Molecule X':
                form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/X_expt/aims.out.gz').get_potential_energy()/4
                form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/Geometry_Effect/{calc_xc_func}/{geom_xc_func}/X_vaneijck/aims.out.gz').get_potential_energy()/2

            xc_func_geom_erel_dict[system][xc_func_dict[calc_xc_func]][xc_func_dict[geom_xc_func]] = (form_1_ene - form_2_ene)*1000/kjmol

# Calculate errors with respect to correct functional and also add the MAD
for system in ['ROY', 'Axitinib', 'Rotigotine', 'Molecule X']:
    for calc_xc_func in xc_func_dict.values():
        for geom_xc_func in xc_func_dict.values():
            correct_erel = xc_func_geom_erel_dict[system][calc_xc_func][calc_xc_func]
            xc_func_geom_err_dict[system][calc_xc_func][geom_xc_func] = xc_func_geom_erel_dict[system][calc_xc_func][geom_xc_func] - correct_erel
    
        mad = np.mean(np.abs([xc_func_geom_err_dict[system][calc_xc_func][geom_xc_func] for geom_xc_func in xc_func_dict.values()]))
        xc_func_geom_err_dict[system][calc_xc_func]['MAD'] = mad
    
    for geom_xc_func in xc_func_dict.values():
        mad = np.mean(np.abs([xc_func_geom_err_dict[system][calc_xc_func][geom_xc_func] for calc_xc_func in xc_func_dict.values()]))
        xc_func_geom_err_dict[system]['MAD'][geom_xc_func] = mad

In [98]:
fig, axs = plt.subplots(2,2,figsize=(7.5,9.6),dpi=450,constrained_layout=True)
plt.set_cmap('bwr')

system_list = []
system_idx = 0

system_title_list = ['ROY', 'Axitinib', 'Rotigotine', 'Molecule X']

for system in ['ROY', 'Axitinib', 'Rotigotine', 'Molecule X']:
    system_geom_error = np.zeros(np.array([7,7]))
    system_mad_error = np.zeros(np.array([7,7]))
    for i, calc_xc_func in enumerate(xc_func_dict.values()):
        for j, geom_xc_func in enumerate(xc_func_dict.values()):
            system_geom_error[i,j] = xc_func_geom_err_dict[system][calc_xc_func][geom_xc_func]
        system_geom_error[i,6] = 0
        system_mad_error[i,6] = xc_func_geom_err_dict[system][calc_xc_func]['MAD']
    for j, geom_xc_func in enumerate(xc_func_dict.values()):
        system_geom_error[6,j] = 0
        system_mad_error[6,j] = xc_func_geom_err_dict[system]['MAD'][geom_xc_func]
    
    divmodi = divmod(system_idx,2)

    fig_ylabels = []
    xc_nice_list_vals = []
    counter = 0
    for xc_idx, xc_func in  enumerate(xc_func_dict.values()):
        if divmodi[1] == 0:
            fig_ylabels += ['{0} ({1:.1f})'.format(xc_func,xc_func_geom_erel_dict[system][xc_func][xc_func])]
            counter += 1 
        else:
            fig_ylabels += ['({0:.1f})'.format(xc_func_geom_erel_dict[system][xc_func][xc_func])]
            counter += 1 

    fig_ylabels += ['MAD']
    fig_xlabels = list(xc_func_dict.values()) + ['MAD']

    im = axs[divmodi[0],divmodi[1]].imshow(system_geom_error, vmin=-2,vmax=2)

    # Define custom colormap that transitions from invisible to black
    colors = [(1, 1, 1, 0), (0, 0, 0, 0.7)]  # RGBA tuples: transparent to black
    n_bins = 100  # Discretize into 100 steps
    cmap_custom = LinearSegmentedColormap.from_list('invisible_to_black', colors, N=n_bins)
    im_custom = axs[divmodi[0],divmodi[1]].imshow(system_mad_error, cmap=cmap_custom, alpha=1,vmin=0,vmax=1)  # Use 

    # Show all ticks and label them with the respective list entries
    axs[divmodi[0],divmodi[1]].set_xticks(np.arange(7), labels=fig_xlabels)
    axs[divmodi[0],divmodi[1]].set_yticks(np.arange(7), labels=fig_ylabels)

    for i12 in range(7):
        for j in range(7):
            if j == 7-1 and i12 == 7-1:
                continue
            elif j == 7-1 or i12 == 7-1:
                text = axs[divmodi[0],divmodi[1]].text(j, i12, f'{system_mad_error[i12,j]:.1f}',
                        ha="center", va="center", color="k")
            else:
                text = axs[divmodi[0],divmodi[1]].text(j, i12, f'{system_geom_error[i12,j]:.1f}',
                        ha="center", va="center", color="k")
    axs[divmodi[0],divmodi[1]].set_title(system_title_list[system_idx])

    axs[divmodi[0],divmodi[1]].set_xticklabels(fig_xlabels, rotation=45, ha="right",rotation_mode="anchor")
    if divmodi[0] == 1:
        axs[divmodi[0],divmodi[1]].set_xlabel(r'XC Functional (XC2) for generating ' + textbf('geometries'))
    system_idx += 1


axs[0,0].set_ylabel(r'XC Functional (XC1) for ' + textbf('calculating') + r' $E_\text{ads}^\text{approx}$')
axs[1,0].set_ylabel(r'XC Functional (XC1) for ' + textbf('calculating') + r' $E_\text{ads}^\text{approx}$')

cbar = fig.colorbar(im, ax=axs, orientation='horizontal', fraction=0.02)
cbar.ax.set_xlabel(r'$E_\text{ads}^\text{approx}[\text{XC1//XC2}]$ - $E_\text{ads}^\text{True}[\text{XC1//XC1}]$ [kJ/mol]')
cbar_custom = fig.colorbar(im_custom, ax=axs, orientation='horizontal', fraction=0.02)
cbar_custom.ax.set_xlabel('Mean Absolute Deviation [kJ/mol]')

plt.savefig('Figures/SI_Figure-Geometry_Error.png')

### Comparison to density functional approximations

In [107]:
pharma_polymorph_dft_xc_dict = {
    system: {dft_xc: 0 for dft_xc in ['PBE-D3BJ','PBE-TS','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','B86bPBE50-revXDM','PBE0-MBD']} for system in ['ROY','Axitinib','Rotigotine','X']
}

vasp_dft_xc_label_dict = {
    'PBE-D3BJ': '01_PBED3BJ',
    'revPBE-D30': '02_revPBED30',
    'R2SCAN-D4': '03_R2SCAND4',
    'optB86b-vdW': '04_optB86bvdW',
    'vdW-DF2': '05_vdWDF2'
}

for system in pharma_polymorph_dft_xc_dict:
    # Analyse the revXDM AIMS calculations first
    if system == 'ROY':
        form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/revXDM/ROY_R/aims.out.gz').get_potential_energy()/2
        form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/revXDM/ROY_Y/aims.out.gz').get_potential_energy()/4
    elif system == 'Axitinib':
        form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/revXDM/Axitinib_VI/aims.out.gz').get_potential_energy()/2
        form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/revXDM/Axitinib_XLI/aims.out.gz').get_potential_energy()/4
    elif system == 'Rotigotine':
        form_1_ene = (read_aims_output_gz(f'Data/Pharmaceutical/revXDM/Rotigotine_I_1/aims.out.gz').get_potential_energy() + read_aims_output_gz(f'Data/Pharmaceutical/revXDM/Rotigotine_I_2/aims.out.gz').get_potential_energy())/8
        form_2_ene = (read_aims_output_gz(f'Data/Pharmaceutical/revXDM/Rotigotine_II_1/aims.out.gz').get_potential_energy() + read_aims_output_gz(f'Data/Pharmaceutical/revXDM/Rotigotine_II_2/aims.out.gz').get_potential_energy())/8
    elif system == 'X':
        form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/revXDM/X_expt/aims.out.gz').get_potential_energy()/4
        form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/revXDM/X_vaneijck/aims.out.gz').get_potential_energy()/2
    pharma_polymorph_dft_xc_dict[system]['B86bPBE50-revXDM'] = (form_1_ene - form_2_ene)*1000/kjmol

    aims_dft_erel_dict = {calc_idx: 0 for calc_idx in range(1,10)}
    for calc_idx in range(1,12):
        if calc_idx in [5,6,7]:
            continue

        if system == 'ROY':
            form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/ROY/R/aims_{calc_idx:02d}.out.gz').get_potential_energy()/2
            form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/ROY/Y/aims_{calc_idx:02d}.out.gz').get_potential_energy()/4
        elif system == 'Axitinib':
            form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/Axitinib/VI/aims_{calc_idx:02d}.out.gz').get_potential_energy()/2
            form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/Axitinib/XLI/aims_{calc_idx:02d}.out.gz').get_potential_energy()/4
        elif system == 'Rotigotine':
            form_1_ene = (read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/Rotigotine/I_1/aims_{calc_idx:02d}.out.gz').get_potential_energy() + read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/Rotigotine/I_2/aims_{calc_idx:02d}.out.gz').get_potential_energy())/8
            form_2_ene = (read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/Rotigotine/II_1/aims_{calc_idx:02d}.out.gz').get_potential_energy() + read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/Rotigotine/II_2/aims_{calc_idx:02d}.out.gz').get_potential_energy())/8
        elif system == 'X':
            form_1_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/X/expt/aims_{calc_idx:02d}.out.gz').get_potential_energy()/4
            form_2_ene = read_aims_output_gz(f'Data/Pharmaceutical/DFT/AIMS/X/vaneijck/aims_{calc_idx:02d}.out.gz').get_potential_energy()/2

        aims_dft_erel_dict[calc_idx] = (form_1_ene - form_2_ene)*1000/kjmol

    pharma_polymorph_dft_xc_dict[system]['PBE-TS'] = aims_dft_erel_dict[5]
    pharma_polymorph_dft_xc_dict[system]['B86bPBE-XDM'] = aims_dft_erel_dict[4]
    pharma_polymorph_dft_xc_dict[system]['B86bPBE25-XDM'] = aims_dft_erel_dict[2] + aims_dft_erel_dict[4] - aims_dft_erel_dict[1]
    pharma_polymorph_dft_xc_dict[system]['B86bPBE50-XDM'] = aims_dft_erel_dict[3] + aims_dft_erel_dict[4] - aims_dft_erel_dict[1]
    pharma_polymorph_dft_xc_dict[system]['PBE-MBD'] = aims_dft_erel_dict[11]
    pharma_polymorph_dft_xc_dict[system]['PBE0-MBD'] = aims_dft_erel_dict[10] + aims_dft_erel_dict[11] - aims_dft_erel_dict[9]

    # Now analyse the VASP calculations
    for dft_xc in vasp_dft_xc_label_dict:

        if system == 'ROY':
            form_1_ene = get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/ROY/R/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz')/2
            form_2_ene = get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/ROY/Y/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz')/4
        elif system == 'Axitinib':
            form_1_ene = get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/Axitinib/VI/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz')/2
            form_2_ene = get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/Axitinib/XLI/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz')/4
        elif system == 'Rotigotine':
            form_1_ene = (get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/Rotigotine/I_1/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz') + get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/Rotigotine/I_2/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz'))/8
            form_2_ene = (get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/Rotigotine/II_1/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz') + get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/Rotigotine/II_2/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz'))/8
        elif system == 'X':
            form_1_ene = get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/X/expt/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz')/4
            form_2_ene = get_vasp_energy(f'Data/Pharmaceutical/DFT/VASP/X/vaneijck/OUTCAR_{vasp_dft_xc_label_dict[dft_xc]}.gz')/2
        pharma_polymorph_dft_xc_dict[system][dft_xc] = (form_1_ene - form_2_ene)*1000/kjmol

system_to_full_label = {
    'ROY': 'ROY R - Y',
    'Axitinib': 'Axitinib VI - XLI',
    'Rotigotine': 'Rotigotine I - II',
    'X': 'X vanEijck-3 - Expt'
}

pharma_polymorph_dft_xc_df_dict = {}
for xc_func in ['PBE-D3BJ','PBE-TS','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','B86bPBE50-revXDM','PBE0-MBD']:
    pharma_polymorph_dft_xc_df_dict[xc_func] = {}
    for system in ['ROY','Axitinib','Rotigotine','X']:
        pharma_polymorph_dft_xc_df_dict[xc_func][(system, 'Erel')] = pharma_polymorph_dft_xc_dict[system][xc_func]
        pharma_polymorph_dft_xc_df_dict[xc_func][(system, 'Error')] = pharma_polymorph_dft_xc_dict[system][xc_func] - (final_relative_energies_dict[('without D4', 'CCSD(T)')][system_to_full_label[system]] + final_relative_energies_dict[('with D4', 'CCSD(T)')][system_to_full_label[system]])/2

In [108]:
# Make a DataFrame of the results
pharma_polymorphs_dft_xc_df = pd.DataFrame(pharma_polymorph_dft_xc_df_dict).T
pharma_polymorphs_dft_xc_df = pharma_polymorphs_dft_xc_df.round(1).astype(str)

display(pharma_polymorphs_dft_xc_df)
# Convert to LaTeX
convert_df_to_latex_input(
    df = pharma_polymorphs_dft_xc_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:pharma_dft_comparison",
    caption = "Relative lattice energies (in kJ/mol) for polymorph pairs of the four molecular crystals with various density functional approximation, together with their error with respect to the CCSD(T) estimates.",
    replace_input= {
        "[t]": "[c]",
        r"Erel": r"$E_\text{rel}$",
        r"{X} \\" : r"{X} \\ \cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7} \cmidrule(lr){8-9}",
        r'D3BJ': r'D3(BJ)',
        r'R2SCAN': r'r$^2$SCAN',
    },
    index = True,
    filename = "Tables/SI_Table-Pharma_Polymorphs_DFT_Comparison.tex",)

                   ROY       Axitinib       Rotigotine          X
                  Erel Error     Erel Error       Erel Error Erel Error
PBE-D3BJ          -6.2  -7.0     -2.4  -9.5        5.1  -1.8  0.8   3.1
PBE-TS             0.0  -0.8      0.0  -7.0        0.0  -6.9  0.0   2.2
revPBE-D30        -5.7  -6.5      7.8   0.8        7.6   0.8  1.1   3.3
B86bPBE-XDM       -5.9  -6.7     -2.0  -9.0        7.4   0.5  1.6   3.8
R2SCAN-D4         -6.3  -7.1     -1.6  -8.6        7.3   0.4  0.2   2.5
optB86b-vdW       -5.8  -6.6      0.6  -6.5       11.9   5.0  2.4   4.6
vdW-DF2           -6.3  -7.1      0.6  -6.4       10.0   3.1  0.5   2.7
B86bPBE25-XDM     -2.5  -3.3      1.3  -5.7        7.9   1.0  1.4   3.6
B86bPBE50-XDM     -0.1  -0.9      3.4  -3.7        8.1   1.2  0.6   2.8
B86bPBE50-revXDM   1.4   0.6      3.3  -3.8        7.5   0.6  0.3   2.5
PBE0-MBD          -2.7  -3.6      1.4  -5.7        7.3   0.4  0.7   2.9

### Figure 4

In [109]:
# Figure of comparison for all systems (swapped axes)

fig, ax = plt.subplots(3, 1, figsize=(2.1,6), dpi=1200, tight_layout=True)

# Define DFT functional colors
dft_colors = {
    'PBE-D3BJ': '#1b9e77',
    'R2SCAN-D4': '#7570b3',
    'B86bPBE25-XDM': '#d95f02',
    'PBE0-MBD': '#66a61e',
    'B86bPBE50-revXDM': '#e6ab02'
}

# ---------------------------- ROY ----------------------------
ax[0].barh([1], [pharma_exp_relative_ene_dict['ROY'][0]], xerr=pharma_exp_relative_ene_dict['ROY'][1],
            height=0.6, capsize=3, linewidth=1, facecolor='grey', edgecolor='none', alpha = 0.3, label='Experiment')
ax[0].barh([1], [pharma_exp_relative_ene_dict['ROY'][0]], xerr=pharma_exp_relative_ene_dict['ROY'][1],
            height=0.6, capsize=3, linewidth=1, facecolor='none', edgecolor='k', label='Experiment')
ax[0].fill_betweenx([0, 8],
                    [pharma_exp_relative_ene_dict['ROY'][0]-pharma_exp_relative_ene_dict['ROY'][1]]*2,
                    [pharma_exp_relative_ene_dict['ROY'][0]+pharma_exp_relative_ene_dict['ROY'][1]]*2,
                    color=color_dict['grey'], alpha=0.5, edgecolor='none')

ax[0].barh([2], [final_relative_energies_dict[('with D4', 'CCSD(T)')]['ROY R - Y']],
            edgecolor='none', facecolor=color_dict['red'], alpha=0.3, height=0.6, zorder=5, label='CCSD(T)')
ax[0].barh([2], [final_relative_energies_dict[('with D4', 'CCSD(T)')]['ROY R - Y']],
            edgecolor=color_dict['red'], facecolor='none', height=0.6, zorder=5, label='CCSD(T)')

# DFT functionals
ax[0].barh([7], [pharma_polymorph_dft_xc_df_dict['PBE-D3BJ'][('ROY','Erel')]],
            edgecolor=dft_colors['PBE-D3BJ'], facecolor='none', height=0.6, zorder=5, label='PBE-D3BJ')
ax[0].barh([6], [pharma_polymorph_dft_xc_df_dict['R2SCAN-D4'][('ROY','Erel')]],
            edgecolor=dft_colors['R2SCAN-D4'], facecolor='none', height=0.6, zorder=5, label='R2SCAN-D4')

# B86bPBE25-XDM (ROY): hatched overlay + existing outline
ax[0].barh([5], [pharma_polymorph_dft_xc_df_dict['B86bPBE25-XDM'][('ROY','Erel')]],
            edgecolor=dft_colors['B86bPBE25-XDM'], facecolor='none', hatch='///',
            height=0.6, zorder=5, alpha=0.5, label='B86bPBE25-XDM')
ax[0].barh([5], [pharma_polymorph_dft_xc_df_dict['B86bPBE25-XDM'][('ROY','Erel')]],
            edgecolor=dft_colors['B86bPBE25-XDM'], facecolor='none', height=0.6, zorder=5, label='B86bPBE25-XDM')

# PBE0-MBD (ROY): hatched overlay + existing outline
ax[0].barh([4], [pharma_polymorph_dft_xc_df_dict['PBE0-MBD'][('ROY','Erel')]],
            edgecolor=dft_colors['PBE0-MBD'], facecolor='none', hatch='///',
            height=0.6, zorder=5, alpha=0.5, label='PBE0-MBD')
ax[0].barh([4], [pharma_polymorph_dft_xc_df_dict['PBE0-MBD'][('ROY','Erel')]],
            edgecolor=dft_colors['PBE0-MBD'], facecolor='none', height=0.6, zorder=5, label='PBE0-MBD')

# B86bPBE50-revXDM (ROY): hatched overlay + existing outline
ax[0].barh([3], [pharma_polymorph_dft_xc_df_dict['B86bPBE50-revXDM'][('ROY','Erel')]],
            edgecolor=dft_colors['B86bPBE50-revXDM'], facecolor='none', hatch='///',
            height=0.6, zorder=5, alpha=0.5, label='B86bPBE50-revXDM')
ax[0].barh([3], [pharma_polymorph_dft_xc_df_dict['B86bPBE50-revXDM'][('ROY','Erel')]],
            edgecolor=dft_colors['B86bPBE50-revXDM'], facecolor='none', height=0.6, zorder=5, label='B86bPBE50-revXDM')


# -------------------------- ROTIGOTINE ------------------------
ax[1].barh([1], [pharma_exp_relative_ene_dict['Rotigotine'][0]], xerr=pharma_exp_relative_ene_dict['Rotigotine'][1],
            height=0.6, capsize=3, linewidth=1, facecolor='grey', edgecolor='none', alpha = 0.3, label='Experiment')
ax[1].barh([1], [pharma_exp_relative_ene_dict['Rotigotine'][0]], xerr=pharma_exp_relative_ene_dict['Rotigotine'][1],
            height=0.6, capsize=3, linewidth=1, facecolor='none', edgecolor='k')
ax[1].fill_betweenx([0, 8],
                    [pharma_exp_relative_ene_dict['Rotigotine'][0]-pharma_exp_relative_ene_dict['Rotigotine'][1]]*2,
                    [pharma_exp_relative_ene_dict['Rotigotine'][0]+pharma_exp_relative_ene_dict['Rotigotine'][1]]*2,
                    color=color_dict['grey'], alpha=0.5, edgecolor='none')
ax[1].barh([2], [final_relative_energies_dict[('with D4', 'CCSD(T)')]['Rotigotine I - II']],
            edgecolor='none', facecolor=color_dict['red'], alpha = 0.3,  height=0.6, zorder=5, label='CCSD(T)')
ax[1].barh([2], [final_relative_energies_dict[('with D4', 'CCSD(T)')]['Rotigotine I - II']],
            edgecolor=color_dict['red'], facecolor='none', height=0.6, zorder=5, label='CCSD(T)')

# DFT functionals
ax[1].barh([7], [pharma_polymorph_dft_xc_df_dict['PBE-D3BJ'][('Rotigotine','Erel')]],
            edgecolor=dft_colors['PBE-D3BJ'], facecolor='none', height=0.6, zorder=5, label='PBE-D3BJ')
ax[1].barh([6], [pharma_polymorph_dft_xc_df_dict['R2SCAN-D4'][('Rotigotine','Erel')]],
            edgecolor=dft_colors['R2SCAN-D4'], facecolor='none', height=0.6, zorder=5, label='R2SCAN-D4')

# B86bPBE25-XDM (Rotigotine): you already added hatched + outline
ax[1].barh(
    [5],
    [pharma_polymorph_dft_xc_df_dict['B86bPBE25-XDM'][('Rotigotine','Erel')]],
    edgecolor=dft_colors['B86bPBE25-XDM'],
    facecolor='none',
    hatch='///',
    height=0.6,
    zorder=5,
    label='B86bPBE25-XDM',
    alpha=0.5
)
ax[1].barh([5], [pharma_polymorph_dft_xc_df_dict['B86bPBE25-XDM'][('Rotigotine','Erel')]],
            edgecolor=dft_colors['B86bPBE25-XDM'], facecolor='none', height=0.6, zorder=5, label='B86bPBE25-XDM')

# PBE0-MBD (Rotigotine): hatched overlay + existing outline
ax[1].barh([4], [pharma_polymorph_dft_xc_df_dict['PBE0-MBD'][('Rotigotine','Erel')]],
            edgecolor=dft_colors['PBE0-MBD'], facecolor='none', hatch='///',
            height=0.6, zorder=5, alpha=0.5, label='PBE0-MBD')
ax[1].barh([4], [pharma_polymorph_dft_xc_df_dict['PBE0-MBD'][('Rotigotine','Erel')]],
            edgecolor=dft_colors['PBE0-MBD'], facecolor='none', height=0.6, zorder=5, label='PBE0-MBD')

# B86bPBE50-revXDM (Rotigotine): hatched overlay + existing outline
ax[1].barh([3], [pharma_polymorph_dft_xc_df_dict['B86bPBE50-revXDM'][('Rotigotine','Erel')]],
            edgecolor=dft_colors['B86bPBE50-revXDM'], facecolor='none', hatch='///',
            height=0.6, zorder=5, alpha=0.5, label='B86bPBE50-revXDM')
ax[1].barh([3], [pharma_polymorph_dft_xc_df_dict['B86bPBE50-revXDM'][('Rotigotine','Erel')]],
            edgecolor=dft_colors['B86bPBE50-revXDM'], facecolor='none', height=0.6, zorder=5, label='B86bPBE50-revXDM')

# -------------------------- AXITINIB --------------------------
ax[2].barh([1], [pharma_exp_relative_ene_dict['Axitinib'][0]], xerr=pharma_exp_relative_ene_dict['Axitinib'][1],
            height=0.6, capsize=3, linewidth=1, facecolor='grey', edgecolor='none', alpha=0.3)
ax[2].barh([1], [pharma_exp_relative_ene_dict['Axitinib'][0]], xerr=pharma_exp_relative_ene_dict['Axitinib'][1],
            height=0.6, capsize=3, linewidth=1, facecolor='none', edgecolor='k', label='Experiment')
ax[2].fill_betweenx([0, 8],
                    [pharma_exp_relative_ene_dict['Axitinib'][0]-pharma_exp_relative_ene_dict['Axitinib'][1]]*2,
                    [pharma_exp_relative_ene_dict['Axitinib'][0]+pharma_exp_relative_ene_dict['Axitinib'][1]]*2,
                    color=color_dict['grey'], alpha=0.5, edgecolor='none')
ax[2].barh([2], [final_relative_energies_dict[('with D4', 'CCSD(T)')]['Axitinib VI - XLI']],
            edgecolor='none', facecolor=color_dict['red'], alpha= 0.3, height=0.6, zorder=5, label='CCSD(T)')
ax[2].barh([2], [final_relative_energies_dict[('with D4', 'CCSD(T)')]['Axitinib VI - XLI']],
            edgecolor=color_dict['red'], facecolor='none', height=0.6, zorder=5, label='CCSD(T)')

# DFT functionals
ax[2].barh([7], [pharma_polymorph_dft_xc_df_dict['PBE-D3BJ'][('Axitinib','Erel')]],
            edgecolor=dft_colors['PBE-D3BJ'], facecolor='none', height=0.6, zorder=5, label='PBE-D3BJ')
ax[2].barh([6], [pharma_polymorph_dft_xc_df_dict['R2SCAN-D4'][('Axitinib','Erel')]],
            edgecolor=dft_colors['R2SCAN-D4'], facecolor='none', height=0.6, zorder=5, label='R2SCAN-D4')

# B86bPBE25-XDM (Axitinib): hatched overlay + existing outline
ax[2].barh([5], [pharma_polymorph_dft_xc_df_dict['B86bPBE25-XDM'][('Axitinib','Erel')]],
            edgecolor=dft_colors['B86bPBE25-XDM'], facecolor='none', hatch='///',
            height=0.6, zorder=5, alpha=0.5, label='B86bPBE25-XDM')
ax[2].barh([5], [pharma_polymorph_dft_xc_df_dict['B86bPBE25-XDM'][('Axitinib','Erel')]],
            edgecolor=dft_colors['B86bPBE25-XDM'], facecolor='none', height=0.6, zorder=5, label='B86bPBE25-XDM')

# PBE0-MBD (Axitinib): hatched overlay + existing outline
ax[2].barh([4], [pharma_polymorph_dft_xc_df_dict['PBE0-MBD'][('Axitinib','Erel')]],
            edgecolor=dft_colors['PBE0-MBD'], facecolor='none', hatch='///',
            height=0.6, zorder=5, alpha=0.5, label='PBE0-MBD')
ax[2].barh([4], [pharma_polymorph_dft_xc_df_dict['PBE0-MBD'][('Axitinib','Erel')]],
            edgecolor=dft_colors['PBE0-MBD'], facecolor='none', height=0.6, zorder=5, label='PBE0-MBD')

# B86bPBE50-revXDM (Axitinib): hatched overlay + existing outline
ax[2].barh([3], [pharma_polymorph_dft_xc_df_dict['B86bPBE50-revXDM'][('Axitinib','Erel')]],
            edgecolor=dft_colors['B86bPBE50-revXDM'], facecolor='none', hatch='///',
            height=0.6, zorder=5, alpha=0.5, label='B86bPBE50-revXDM')
ax[2].barh([3], [pharma_polymorph_dft_xc_df_dict['B86bPBE50-revXDM'][('Axitinib','Erel')]],
            edgecolor=dft_colors['B86bPBE50-revXDM'], facecolor='none', height=0.6, zorder=5, label='B86bPBE50-revXDM')

# Adjust limits and ticks (swapped)
ax[0].set_xlim([10, -10])
ax[1].set_xlim([10, -10])
ax[2].set_xlim([10, -10])
ax[0].set_ylim([8,0])
ax[1].set_ylim([8,0])
ax[2].set_ylim([8,0])

# Customize appearance
for a in ax:
    # Hide unwanted spines
    a.spines['top'].set_visible(True)
    a.spines['bottom'].set_visible(False)
    a.spines['left'].set_visible(False)
    # a.spines['right'].set_visible(False)

    # Place the y-axis spine (and thus the ticks) at x = 0
    a.spines['right'].set_position(('data', 0))

    # Now ticks and labels will be drawn along x=0
    a.yaxis.set_ticks_position('right')
    a.yaxis.set_label_position('right')

    # Move x-ticks and labels to top
    a.xaxis.tick_top()
    a.xaxis.set_label_position('top')

    # Define ticks
    a.set_xticks([-8, -4, 0, 4, 8])
    a.set_yticks([1, 2,3,4,5,6,7])

ax[0].set_yticklabels([])
ax[2].set_yticklabels([])
ax[1].set_yticklabels([r'Expt $\pm$ Error', 'LNO-MBE-CCSD(T)','B86bPBE50-revXDM','PBE0-MBD', 'B86bPBE25-XDM', r'r$^2$SCAN-D4','PBE-D3'],fontsize=7)


plt.savefig('Figures/MAIN_Figure-Pharma_Polymorph_Comparison.png')

# DFT Benchmarks

## X23

In [112]:
# Load the X23 data
x23_final_compare_dict = np.load('Data/X23/X23_Final_Data.npy', allow_pickle=True).item()

# These results are in PRL order and must be converted.
prl_names_order={idx+1: x for idx,x in enumerate(["1,4-cyclohexanedione" ,"Acetic Acid" ,"Adamantane" ,"Ammonia" ,"Anthracene" ,"Benzene" ,"CO$_2$" ,"Cyanamide" ,"Cytosine" ,"Ethyl carbamate" ,"Formamide" ,"Imidazole" ,"Naphthalene" ,r"Oxalic Acid $\alpha$" ,r"Oxalic Acid $\beta$" ,"Pyrazine" ,"Pyrazole" ,"Triazine" ,"Trioxane" ,"Uracil" ,"Urea" ,"Hexamine" ,"Succinic Acid" ])}
prl_to_x23_order = {idx+1: x for idx, x in enumerate([1,2,3,4,5,6,7,8,9,10,11,22,12,13,14,15,16,17,23,18,19,20,21])}
x23_labels = {x23_idx: prl_names_order[prl_to_x23_order[x23_idx]] for x23_idx in range(1,24)}

x23_semilocal_dft_xc_dict = {
    x23_idx: {dft_xc: 0 for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2']} for x23_idx in range(1,24)
}

x23_hybrid_dft_xc_dict = {
    x23_idx: {dft_xc: 0 for dft_xc in ['B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']} for x23_idx in range(1,24)
}

# Calculation list
# 1: B86bPBE-XDM lightdense
# 2: B86bPBE25-XDM lightdense
# 3: B86bPBE50-XDM lightdense
# 4: B86bPBE-XDM tight
# 8: PBE-TS tight
# 9: PBE-MBD lightdense
# 10: PBE0-MBD lightdense
# 11: PBE-MBD tight


for x23_idx in range(1,24):
    # First analyse the AIMS calculations
    aims_dft_elatt_dict = {calc_idx: 0 for calc_idx in range(1,10)}
    for calc_idx in range(1,12):
        if calc_idx in [5,6,7]:
            continue
        molecule = read_aims_output_gz(f'Data/X23/DFT/AIMS/{prl_to_x23_order[x23_idx]:02d}/molecule/aims_{calc_idx:02d}.out.gz')
        solid = read_aims_output_gz(f'Data/X23/DFT/AIMS/{prl_to_x23_order[x23_idx]:02d}/solid/aims_{calc_idx:02d}.out.gz')
        num_monomers = len(solid)/len(molecule)
        aims_dft_elatt_dict[calc_idx] = (solid.get_potential_energy()/num_monomers - molecule.get_potential_energy())*1000/kjmol
    x23_semilocal_dft_xc_dict[x23_idx]['PBE-TS'] = aims_dft_elatt_dict[8]
    x23_semilocal_dft_xc_dict[x23_idx]['B86bPBE-XDM'] = aims_dft_elatt_dict[4]
    x23_hybrid_dft_xc_dict[x23_idx]['B86bPBE25-XDM'] = aims_dft_elatt_dict[2] + aims_dft_elatt_dict[4] - aims_dft_elatt_dict[1]
    x23_hybrid_dft_xc_dict[x23_idx]['B86bPBE50-XDM'] = aims_dft_elatt_dict[3] + aims_dft_elatt_dict[4] - aims_dft_elatt_dict[1]
    x23_semilocal_dft_xc_dict[x23_idx]['PBE-MBD'] = aims_dft_elatt_dict[11]
    x23_hybrid_dft_xc_dict[x23_idx]['PBE0-MBD'] = aims_dft_elatt_dict[10] + aims_dft_elatt_dict[11] - aims_dft_elatt_dict[9]

    # Now analyse the VASP calculations
    x23_semilocal_dft_xc_dict[x23_idx]['PBE-D3BJ'] = get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/solid/OUTCAR_01_PBED3BJ.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/molecule/OUTCAR_01_PBED3BJ.gz')*1000/kjmol
    x23_semilocal_dft_xc_dict[x23_idx]['revPBE-D30'] = get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/solid/OUTCAR_02_revPBED30.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/molecule/OUTCAR_02_revPBED30.gz')*1000/kjmol
    x23_semilocal_dft_xc_dict[x23_idx]['R2SCAN-D4'] = get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/solid/OUTCAR_03_R2SCAND4.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/molecule/OUTCAR_03_R2SCAND4.gz')*1000/kjmol
    x23_semilocal_dft_xc_dict[x23_idx]['optB86b-vdW'] = get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/solid/OUTCAR_04_optB86bvdW.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/molecule/OUTCAR_04_optB86bvdW.gz')*1000/kjmol
    x23_semilocal_dft_xc_dict[x23_idx]['vdW-DF2'] = get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/solid/OUTCAR_05_vdWDF2.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/X23/DFT/VASP/{prl_to_x23_order[x23_idx]:02d}/molecule/OUTCAR_05_vdWDF2.gz')*1000/kjmol

x23_semilocal_dft_xc_dict['MAD [CCSD(T)]'] = {dft_xc: np.mean(np.abs([x23_semilocal_dft_xc_dict[x23_idx][dft_xc] - x23_final_compare_dict[x23_labels[x23_idx]]['CCSD(T)'] for x23_idx in range(1,24)])) for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2']}
x23_semilocal_dft_xc_dict['MAD [DMC]'] = {dft_xc: np.mean(np.abs([x23_semilocal_dft_xc_dict[x23_idx][dft_xc] - x23_final_compare_dict[x23_labels[x23_idx]]['DMC'] for x23_idx in range(1,24)])) for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2']}
x23_semilocal_dft_xc_dict['MAD [Expt]'] = {dft_xc: np.mean(np.abs([x23_semilocal_dft_xc_dict[x23_idx][dft_xc] - float(x23_final_compare_dict[x23_labels[x23_idx]]['Expt']) for x23_idx in range(1,24)])) for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2']}
x23_hybrid_dft_xc_dict['MAD [CCSD(T)]'] = {dft_xc: np.mean(np.abs([x23_hybrid_dft_xc_dict[x23_idx][dft_xc] - x23_final_compare_dict[x23_labels[x23_idx]]['CCSD(T)'] for x23_idx in range(1,24)])) for dft_xc in ['B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']}
x23_hybrid_dft_xc_dict['MAD [DMC]'] = {dft_xc: np.mean(np.abs([x23_hybrid_dft_xc_dict[x23_idx][dft_xc] - x23_final_compare_dict[x23_labels[x23_idx]]['DMC'] for x23_idx in range(1,24)])) for dft_xc in ['B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']}
x23_hybrid_dft_xc_dict['MAD [Expt]'] = {dft_xc: np.mean(np.abs([x23_hybrid_dft_xc_dict[x23_idx][dft_xc] - float(x23_final_compare_dict[x23_labels[x23_idx]]['Expt']) for x23_idx in range(1,24)])) for dft_xc in ['B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']}

In [113]:
# Make a DataFrame of the results
x23_semilocal_dft_xc_df = pd.DataFrame(x23_semilocal_dft_xc_dict).T

# Round to nearest integer
x23_semilocal_dft_xc_df = x23_semilocal_dft_xc_df.round(1)
# Change index to the x23 labels
x23_semilocal_dft_xc_df.index = [x23_labels[x23_idx] for x23_idx in range(1,24)] + ['MAD [CCSD(T)]', 'MAD [DMC]', 'MAD [Expt]']

display(x23_semilocal_dft_xc_df)
# Convert to LaTeX
convert_df_to_latex_input(
    df = x23_semilocal_dft_xc_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_dft_comparison",
    caption = "Comparison of several semilocal density functional approximations to experiments, LNO-MBE-CCSD(T) and DMC (in kJ/mol) for the X23 dataset",
    replace_input= {
        "[t]": "[c]",
        r'D3BJ': r'D3(BJ)',
        'R2SCAN': r'r$^2$SCAN',
        'D30': 'D3(0)',
    },
    rotate_column_header = True,
    index = True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-X23_semilocal_DFT_Comparison.tex",)

x23_hybrid_dft_xc_df = pd.DataFrame(x23_hybrid_dft_xc_dict).T
# Round to nearest integer
x23_hybrid_dft_xc_df = x23_hybrid_dft_xc_df.round(1)
# Change index to the x23 labels
x23_hybrid_dft_xc_df.index = [x23_labels[x23_idx] for x23_idx in range(1,24)] + ['MAD [CCSD(T)]', 'MAD [DMC]', 'MAD [Expt]']
display(x23_hybrid_dft_xc_df)
# Convert to LaTeX
convert_df_to_latex_input(
    df = x23_hybrid_dft_xc_df,
    start_input = '\\begin{table}[h]\n',
    label = "tab:x23_hybrid_dft_comparison",
    caption = "Comparison of several hybrid density functional approximations to experiments, LNO-MBE-CCSD(T) and DMC (in kJ/mol) for the X23 dataset",
    replace_input= {
        "[t]": "[c]",
        r'D3BJ': r'D3(BJ)',
        'R2SCAN': r'r$^2$SCAN',
        'D30': 'D3(0)',
    },
    rotate_column_header = True,
    index = True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-X23_hybrid_DFT_Comparison.tex",)

,PBE-D3BJ,PBE-TS,PBE-MBD,revPBE-D30,B86bPBE-XDM,R2SCAN-D4,optB86b-vdW,vdW-DF2
"1,4-cyclohexanedione",-88.6,-105.6,-91.9,-90.6,-88.4,-90.6,-115.1,-99.5
Acetic Acid,-74.3,-81.9,-76.4,-67.7,-73.5,-74.9,-87.3,-73.4
Adamantane,-71.4,-105.5,-77.7,-73.9,-70.5,-63.5,-98.9,-82.0
Ammonia,-42.6,-43.7,-42.3,-38.4,-40.5,-40.5,-44.1,-39.7
Anthracene,-106.7,-135.9,-107.6,-115.1,-102.6,-103.1,-135.3,-103.7
Benzene,-54.9,-66.7,-54.5,-58.4,-51.6,-51.2,-67.3,-54.4
CO$_2$,-24.2,-24.6,-23.1,-22.6,-24.6,-28.9,-34.5,-32.8
Cyanamide,-92.7,-93.4,-91.4,-84.5,-89.2,-91.0,-99.3,-86.9
Cytosine,-160.4,-172.5,-161.0,-153.7,-156.8,-159.9,-179.2,-152.6
Ethyl carbamate,-87.8,-98.5,-90.9,-82.6,-86.3,-85.8,-104.6,-91.1
Formamide,-82.3,-85.9,-82.4,-75.9,-80.5,-81.8,-90.0,-79.7
Hexamine,-86.3,-115.5,-90.7,-87.2,-87.9,-84.6,-112.5,-92.7
Imidazole,-92.1,-101.7,-93.4,-87.4,-90.9,-89.6,-103.0,-87.2
Naphthalene,-80.1,-101.2,-80.7,-86.8,-76.6,-77.4,-101.3,-77.9
Oxalic Acid $\alpha$,-91.0,-98.4,-94.1,-83.2,-93.6,-103.8,-116.7,-104.1
Oxalic Acid $\beta$,-94.8,-102.3,-97.4,-87.4,-96.7,-105.5,-119.3,-102.6
Pyrazine,-65.3,-74.8,-62.5,-63.1,-62.7,-60.4,-78.2,-66.0
Pyrazole,-81.0,-88.7,-82.2,-78.7,-79.1,-78.4,-91.6,-76.0
Succinic Acid,-130.5,-146.8,-135.8,-120.4,-130.6,-136.4,-156.7,-124.8
Triazine,-60.2,-67.3,-57.1,-58.4,-57.8,-57.2,-73.7,-64.6
Trioxane,-58.2,-75.3,-63.8,-59.0,-62.1,-58.3,-80.2,-72.9
Uracil,-137.2,-148.2,-137.7,-128.7,-134.5,-138.5,-156.5,-133.8
Urea,-108.0,-111.9,-109.8,-100.0,-105.1,-110.5,-117.7,-104.0
MAD [CCSD(T)],3.9,12.4,4.2,4.2,3.5,4.1,17.1,5.0
MAD [DMC],4.4,14.6,5.4,5.9,2.9,2.8,18.9,4.4
MAD [Expt],4.8,15.0,5.9,5.2,3.8,4.8,19.7,5.3

                      B86bPBE25-XDM  B86bPBE50-XDM  PBE0-MBD
1,4-cyclohexanedione          -88.5          -89.7     -94.2
Acetic Acid                   -71.9          -71.3     -76.1
Adamantane                    -68.2          -64.7     -77.3
Ammonia                       -36.7          -33.9     -39.0
Anthracene                   -106.5         -107.9    -115.2
Benzene                       -52.1          -51.6     -56.4
CO$_2$                        -24.1          -23.9     -23.7
Cyanamide                     -85.2          -82.2     -88.3
Cytosine                     -155.9         -155.5    -162.8
Ethyl carbamate               -83.7          -81.8     -89.9
Formamide                     -78.2          -76.7     -81.4
Hexamine                      -89.3          -90.5     -95.3
Imidazole                     -88.7          -86.3     -92.6
Naphthalene                   -79.2          -80.1     -85.9
Oxalic Acid $\alpha$          -94.7          -97.4     -97.9
Oxalic Acid $\beta$           -94.9          -95.0     -98.2
Pyrazine                      -61.3          -59.6     -62.9
Pyrazole                      -77.5          -76.0     -82.0
Succinic Acid                -127.8         -127.1    -136.0
Triazine                      -57.2          -56.9     -58.0
Trioxane                      -60.4          -59.4     -64.5
Uracil                       -134.0         -133.8    -139.6
Urea                         -103.5         -103.1    -109.4
MAD [CCSD(T)]                   3.0            3.4       3.5
MAD [DMC]                       2.8            3.2       5.8
MAD [Expt]                      3.1            3.3       6.3

## ICE13

In [115]:
ice13_final_elatt_dict = np.load('Data/ICE13/ICE13_Final_Data.npy', allow_pickle=True).item()

ice13_systems = {
    1: 'Ih',
    2: 'II',
    3: 'III',
    4: 'IV',
    6: 'VI',
    7: 'VII',
    8: 'VIII',
    9: 'IX',
    11: 'XI',
    13: 'XIII',
    14: 'XIV',
    15: 'XV',
    17: 'XVII'
}

ice13_dft_xc_dict = {
    ice13_idx: {dft_xc: 0 for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']} for ice13_idx in ice13_systems}

for ice13_idx in ice13_systems:
    # First analyse the AIMS calculations
    aims_dft_elatt_dict = {calc_idx: 0 for calc_idx in range(1,10)}
    for calc_idx in range(1,12):
        if calc_idx in [5,6,7]:
            continue
        molecule = read_aims_output_gz(f'Data/ICE13/DFT/AIMS/Molecule/aims_{calc_idx:02d}.out.gz')
        solid = read_aims_output_gz(f'Data/ICE13/DFT/AIMS/{ice13_idx:02d}/aims_{calc_idx:02d}.out.gz')
        num_monomers = len(solid)/len(molecule)
        aims_dft_elatt_dict[calc_idx] = (solid.get_potential_energy()/num_monomers - molecule.get_potential_energy())*1000/kjmol
    ice13_dft_xc_dict[ice13_idx]['PBE-TS'] = aims_dft_elatt_dict[8]
    ice13_dft_xc_dict[ice13_idx]['B86bPBE-XDM'] = aims_dft_elatt_dict[4]
    ice13_dft_xc_dict[ice13_idx]['B86bPBE25-XDM'] = aims_dft_elatt_dict[2] + aims_dft_elatt_dict[4] - aims_dft_elatt_dict[1]
    ice13_dft_xc_dict[ice13_idx]['B86bPBE50-XDM'] = aims_dft_elatt_dict[3] + aims_dft_elatt_dict[4] - aims_dft_elatt_dict[1]
    ice13_dft_xc_dict[ice13_idx]['PBE-MBD'] = aims_dft_elatt_dict[11]
    ice13_dft_xc_dict[ice13_idx]['PBE0-MBD'] = aims_dft_elatt_dict[10] + aims_dft_elatt_dict[11] - aims_dft_elatt_dict[9]
    


    # Now analyse the VASP calculations
    ice13_dft_xc_dict[ice13_idx]['PBE-D3BJ'] = get_vasp_energy(f'Data/ICE13/DFT/VASP/{ice13_idx:02d}/OUTCAR_01_PBED3BJ.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/ICE13/DFT/VASP/Molecule/OUTCAR_01_PBED3BJ.gz')*1000/kjmol
    ice13_dft_xc_dict[ice13_idx]['revPBE-D30'] = get_vasp_energy(f'Data/ICE13/DFT/VASP/{ice13_idx:02d}/OUTCAR_02_revPBED30.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/ICE13/DFT/VASP/Molecule/OUTCAR_02_revPBED30.gz')*1000/kjmol
    ice13_dft_xc_dict[ice13_idx]['R2SCAN-D4'] = get_vasp_energy(f'Data/ICE13/DFT/VASP/{ice13_idx:02d}/OUTCAR_03_R2SCAND4.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/ICE13/DFT/VASP/Molecule/OUTCAR_03_R2SCAND4.gz')*1000/kjmol
    ice13_dft_xc_dict[ice13_idx]['optB86b-vdW'] = get_vasp_energy(f'Data/ICE13/DFT/VASP/{ice13_idx:02d}/OUTCAR_04_optB86bvdW.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/ICE13/DFT/VASP/Molecule/OUTCAR_04_optB86bvdW.gz')*1000/kjmol
    ice13_dft_xc_dict[ice13_idx]['vdW-DF2'] = get_vasp_energy(f'Data/ICE13/DFT/VASP/{ice13_idx:02d}/OUTCAR_05_vdWDF2.gz')/num_monomers*1000/kjmol - get_vasp_energy(f'Data/ICE13/DFT/VASP/Molecule/OUTCAR_05_vdWDF2.gz')*1000/kjmol

# Now calculate the MAD values
ice13_dft_xc_dict['MAD [CCSD(T)]'] = {dft_xc: np.mean(np.abs([ice13_dft_xc_dict[ice13_idx][dft_xc] - float(ice13_final_elatt_dict[ice13_idx]['CCSD(T) [Final]']) for ice13_idx in ice13_systems])) for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']}
ice13_dft_xc_dict['MAD [DMC]'] = {dft_xc: np.mean(np.abs([ice13_dft_xc_dict[ice13_idx][dft_xc] - float(ice13_final_elatt_dict[ice13_idx]['DMC (Unitcell)'].split()[0]) for ice13_idx in ice13_systems])) for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']}

In [116]:
# Make a DataFrame of the results
ice13_dft_xc_df = pd.DataFrame(ice13_dft_xc_dict).T
# Round to nearest integer
ice13_dft_xc_df = ice13_dft_xc_df.round(1)
# Rename the index to the ice phase names
ice13_dft_xc_df.index = [ice13_systems[idx] for idx in ice13_systems] + ['MAD [CCSD(T)]', 'MAD [DMC]']
display(ice13_dft_xc_df)

# Convert to LaTeX
convert_df_to_latex_input(
    df = ice13_dft_xc_df,
    start_input = '\\begin{turnpage}\n\\begin{table}[h]\n',
    end_input = '\n\\end{table}\n\\end{turnpage}',
    label = "tab:ice13_dft_comparison",
    caption = "Comparison of several density functional approximations to LNO-MBE-CCSD(T) and DMC (in kJ/mol) for the ICE13 dataset",
    replace_input= {
        "[t]": "[c]",
        r'D3BJ': r'D3(BJ)',
        'R2SCAN': r'r$^2$SCAN',
        'D30': 'D3(0)',
    },
    rotate_column_header = True,
    index = True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-ICE13_DFT_Comparison.tex")

,PBE-D3BJ,PBE-TS,PBE-MBD,revPBE-D30,B86bPBE-XDM,R2SCAN-D4,optB86b-vdW,vdW-DF2,B86bPBE25-XDM,B86bPBE50-XDM,PBE0-MBD
Ih,-70.4,-69.5,-70.5,-59.1,-68.2,-66.5,-68.7,-59.5,-60.7,-55.3,-63.0
II,-66.6,-67.8,-67.4,-57.8,-65.3,-65.8,-67.9,-60.2,-58.7,-54.0,-61.3
III,-67.5,-67.4,-67.8,-56.7,-65.6,-64.6,-67.5,-58.4,-58.1,-52.7,-60.6
IV,-64.1,-65.3,-64.8,-55.1,-62.7,-63.2,-65.8,-58.0,-55.9,-51.0,-58.4
VI,-64.0,-65.9,-64.9,-56.2,-63.0,-64.4,-66.9,-59.2,-56.5,-51.9,-59.1
VII,-57.9,-59.1,-59.2,-55.0,-57.6,-61.6,-63.0,-56.6,-52.2,-48.7,-54.6
VIII,-58.9,-60.4,-60.2,-55.8,-58.7,-62.7,-64.0,-57.8,-53.3,-49.9,-55.8
IX,-67.7,-68.0,-68.2,-57.5,-66.0,-65.4,-68.3,-59.9,-58.9,-53.7,-61.4
XI,-70.9,-70.0,-71.0,-59.3,-68.6,-66.9,-69.2,-59.5,-60.8,-55.1,-63.2
XIII,-66.0,-67.3,-66.7,-56.7,-64.6,-65.1,-67.7,-60.0,-57.9,-53.0,-60.5
XIV,-65.2,-66.8,-65.9,-56.3,-64.0,-64.9,-67.5,-59.9,-57.3,-52.5,-59.9
XV,-63.8,-65.7,-64.7,-56.1,-62.8,-64.3,-66.7,-59.3,-56.5,-52.0,-59.0
XVII,-69.3,-68.5,-69.5,-58.0,-67.2,-65.5,-67.3,-58.1,-59.5,-54.0,-61.9
MAD [CCSD(T)],8.3,9.1,9.0,0.5,7.0,7.5,9.7,1.7,1.0,4.6,2.7
MAD [DMC],8.0,8.7,8.6,0.9,6.6,7.1,9.4,1.4,1.0,5.0,2.3

In [117]:
ice_final_erel_dict = np.load('Data/ICE13/ICE13_Final_Relative_Data.npy', allow_pickle=True).item()

ice13_dft_xc_erel_dict = {
    ice13_idx: {dft_xc: 0 for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']} for ice13_idx in ice13_systems if ice13_idx != 1}

for ice13_idx in ice13_systems:
    if ice13_idx == 1:
        continue
    for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']:
        ice13_dft_xc_erel_dict[ice13_idx][dft_xc] = ice13_dft_xc_dict[ice13_idx][dft_xc] - ice13_dft_xc_dict[1][dft_xc]

# Now calculate the MAD values
ice13_dft_xc_erel_dict['MAD [CCSD(T)]'] = {dft_xc: np.mean(np.abs([ice13_dft_xc_erel_dict[ice13_idx][dft_xc] - float(ice_final_erel_dict[ice13_idx]['CCSD(T) [Final]']) for ice13_idx in ice13_systems if ice13_idx != 1])) for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']}
ice13_dft_xc_erel_dict['MAD [DMC]'] = {dft_xc: np.mean(np.abs([ice13_dft_xc_erel_dict[ice13_idx][dft_xc] - float(ice_final_erel_dict[ice13_idx]['DMC (Unitcell)'].split()[0]) for ice13_idx in ice13_systems if ice13_idx != 1])) for dft_xc in ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM','R2SCAN-D4','optB86b-vdW','vdW-DF2','B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']}

# Make a DataFrame of the results
ice13_dft_xc_erel_df = pd.DataFrame(ice13_dft_xc_erel_dict).T
# Round to nearest integer
ice13_dft_xc_erel_df = ice13_dft_xc_erel_df.round(1)
# Rename the index to the ice phase names
ice13_dft_xc_erel_df.index = [ice13_systems[idx] for idx in ice13_systems if idx != 1] + ['MAD [CCSD(T)]', 'MAD [DMC]']
display(ice13_dft_xc_erel_df)

# Convert to LaTeX
convert_df_to_latex_input(
    df = ice13_dft_xc_erel_df,
    start_input = '\\begin{turnpage}\n\\begin{table}[h]\n',
    end_input = '\n\\end{table}\n\\end{turnpage}',
    label = "tab:ice13_dft_erel_comparison",
    caption = r"Comparison of several density functional approximations to LNO-MBE-CCSD(T) and DMC~\cite{dellapiaDMCICE13AmbientHigh2022b} (in kJ/mol) for the relative energy of the ICE13 dataset",
    replace_input= {
        "[t]": "[c]",
        r'D3BJ': r'D3(BJ)',
        'R2SCAN': r'r$^2$SCAN',
        'D30': 'D3(0)',
    },
    rotate_column_header = True,
    index = True,
    float_fmt="%.1f",
    filename = "Tables/SI_Table-ICE13_DFT_Erel_Comparison.tex")

,PBE-D3BJ,PBE-TS,PBE-MBD,revPBE-D30,B86bPBE-XDM,R2SCAN-D4,optB86b-vdW,vdW-DF2,B86bPBE25-XDM,B86bPBE50-XDM,PBE0-MBD
II,3.8,1.8,3.1,1.3,2.9,0.7,0.8,-0.7,2.0,1.3,1.7
III,2.9,2.1,2.7,2.3,2.6,1.9,1.2,1.0,2.5,2.6,2.4
IV,6.3,4.2,5.7,4.0,5.5,3.3,3.0,1.5,4.8,4.3,4.6
VI,6.4,3.7,5.6,2.8,5.2,2.1,1.9,0.3,4.2,3.4,3.9
VII,12.5,10.5,11.3,4.1,10.6,4.9,5.8,2.9,8.5,6.6,8.4
VIII,11.5,9.1,10.3,3.3,9.5,3.8,4.8,1.6,7.3,5.3,7.2
IX,2.7,1.5,2.3,1.6,2.2,1.2,0.5,-0.4,1.8,1.6,1.6
XI,-0.5,-0.5,-0.5,-0.2,-0.4,-0.3,-0.5,-0.0,-0.1,0.2,-0.2
XIII,4.4,2.2,3.8,2.3,3.6,1.5,1.0,-0.5,2.8,2.3,2.6
XIV,5.2,2.7,4.5,2.7,4.2,1.7,1.3,-0.4,3.4,2.7,3.2
XV,6.6,3.8,5.8,2.9,5.4,2.3,2.1,0.1,4.2,3.3,4.0
XVII,1.1,1.1,1.0,1.0,1.0,1.0,1.5,1.4,1.2,1.3,1.2
MAD [CCSD(T)],3.3,1.6,2.7,0.4,2.4,0.3,0.7,1.6,1.5,0.8,1.4
MAD [DMC],3.4,1.7,2.9,0.8,2.6,0.5,0.5,1.5,1.7,1.0,1.5

## Overall Comparison

In [119]:
x23_costs_dict = np.load('Data/X23/X23_Costs.npy', allow_pickle=True).item()

gga_dft_xc_list = ['PBE-D3BJ','PBE-TS','PBE-MBD','revPBE-D30','B86bPBE-XDM']
mgga_vdw_inc_dft_xc_list = ['R2SCAN-D4','optB86b-vdW','vdW-DF2']
hybrid_dft_xc_list = ['B86bPBE25-XDM','B86bPBE50-XDM','PBE0-MBD']

fig, axs = plt.subplots(1,2, figsize=(6.675,3.4),dpi=450, constrained_layout=True)

# Plot MAD of ICE13 on y-axis and X23 on x-axis
axs[1].plot([x23_semilocal_dft_xc_dict['MAD [CCSD(T)]'][dft_xc] for dft_xc in gga_dft_xc_list],
            [ice13_dft_xc_dict['MAD [CCSD(T)]'][dft_xc] for dft_xc in gga_dft_xc_list],
            'o', color='#1b9e77', label='GGA',markeredgecolor='k', markersize=5)
axs[1].plot([x23_semilocal_dft_xc_dict['MAD [CCSD(T)]'][dft_xc] for dft_xc in mgga_vdw_inc_dft_xc_list],
            [ice13_dft_xc_dict['MAD [CCSD(T)]'][dft_xc] for dft_xc in mgga_vdw_inc_dft_xc_list],
            'o', color='#7570b3', label='Meta-GGA \&\nvdW-inclusive',markeredgecolor='k', markersize=5)
axs[1].plot([x23_hybrid_dft_xc_dict['MAD [CCSD(T)]'][dft_xc] for dft_xc in hybrid_dft_xc_list],
            [ice13_dft_xc_dict['MAD [CCSD(T)]'][dft_xc] for dft_xc in hybrid_dft_xc_list],
            'o', color='#d95f02', label='Hybrids',markeredgecolor='k', markersize=5)

# Add DFT functional labels
axs[1].text(x23_semilocal_dft_xc_dict['MAD [CCSD(T)]']['PBE-D3BJ']-2.3,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['PBE-D3BJ']-0.15,
            'PBE-D3(BJ)', fontsize=8)
axs[1].text(x23_semilocal_dft_xc_dict['MAD [CCSD(T)]']['PBE-MBD']-2.1,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['PBE-MBD']-0.15,
            'PBE-MBD', fontsize=8)
axs[1].text(x23_semilocal_dft_xc_dict['MAD [CCSD(T)]']['B86bPBE-XDM']-2.95,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['B86bPBE-XDM']-0.15,
            'B86bPBE-XDM', fontsize=8)
axs[1].text(x23_semilocal_dft_xc_dict['MAD [CCSD(T)]']['revPBE-D30']+0.3,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['revPBE-D30']-0.15,
            'revPBE-D3', fontsize=8)
axs[1].text(x23_semilocal_dft_xc_dict['MAD [CCSD(T)]']['R2SCAN-D4']-2.35,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['R2SCAN-D4']-0.15,
            r'r$^2$SCAN-D4', fontsize=8)
axs[1].text(x23_semilocal_dft_xc_dict['MAD [CCSD(T)]']['vdW-DF2']+0.3,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['vdW-DF2']-0.15,
            'vdW-DF2', fontsize=8)
axs[1].text(x23_hybrid_dft_xc_dict['MAD [CCSD(T)]']['B86bPBE25-XDM']+0.3,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['B86bPBE25-XDM']-0.15,
            'B86bPBE25-XDM', fontsize=8)
axs[1].text(x23_hybrid_dft_xc_dict['MAD [CCSD(T)]']['B86bPBE50-XDM']+0.3,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['B86bPBE50-XDM']-0.15,
            'B86bPBE50-XDM', fontsize=8)
axs[1].text(x23_hybrid_dft_xc_dict['MAD [CCSD(T)]']['PBE0-MBD']+0.3,
            ice13_dft_xc_dict['MAD [CCSD(T)]']['PBE0-MBD']-0.15,
            'PBE0-MBD', fontsize=8)

axs[1].plot(1.8,0.8, '^', color=color_dict['yellow'],markeredgecolor='k', label= 'B86bPBE50-revXDM', markersize=7)
axs[1].plot(3.1,0.5, 's', color=color_dict['blue'],markeredgecolor='k', label = 'DMC', markersize=7)



axs[1].set_xlim([0,10])
axs[1].set_ylim([0,10])

axs[1].legend(fontsize=8, loc='upper right', handletextpad=0.2)

axs[1].set_xlabel('MAD [w.r.t. LNO-MBE-CCSD(T)] on X23 (kJ/mol)')
axs[1].set_ylabel('MAD [w.r.t. LNO-MBE-CCSD(T)] on ICE13 (kJ/mol)')

axs[1].set_yticks([0,5,10])
axs[1].set_xticks([0,5,10])

# Remove top and right spines
axs[1].spines['top'].set_visible(False)
axs[1].spines['right'].set_visible(False)

# Add gridlines and also minor gridlines
axs[1].grid(axis='both', linestyle='--', alpha=0.3)
axs[1].minorticks_on()
axs[1].grid(axis='both', which='minor', linestyle=':', alpha=0.2)

# Make violin plots of the x23 costs
box_specs = [
    (np.log10([x23_costs_dict[i]['DFT (GGA)'] for i in range(1, 24)]), 0, 0.4, '#1b9e77'),
    (np.log10([x23_costs_dict[i]['HF'] for i in range(1, 24)]), 1, 0.4, '#d95f02'),
    (np.log10([x23_costs_dict[i]['CCSD(T) [low]'] for i in range(1, 24)]), 2, 0.4, color_dict['red']),
    (np.log10([x23_costs_dict[i]['CCSD(T) [moderate]'] for i in range(1, 24)]), 2.5, 0.4, color_dict['red']),
    (np.log10([x23_costs_dict[i]['CCSD(T) [high]'] for i in range(1, 24)]), 3, 0.4, color_dict['red']),
    (np.log10([x23_costs_dict[i]['DMC [4]'] for i in range(1, 24)]), 4, 0.4, color_dict['blue']),
    (np.log10([x23_costs_dict[i]['DMC [2]'] for i in range(1, 24)]), 4.5, 0.4, color_dict['blue']),
    (np.log10([x23_costs_dict[i]['DMC [1]'] for i in range(1, 24)]), 5, 0.4, color_dict['blue']),
]

# Loop through and plot each boxplot
for data, pos, width, color in box_specs:
    axs[0].boxplot(
        data,
        positions=[pos],
        widths=width,
        patch_artist=True,
        showmeans=True,             # <-- show mean line
        meanline=True,              # show as line instead of point
        showfliers=False,
        boxprops=dict(facecolor=color, edgecolor='k', linewidth=1.2),
        medianprops=dict(color=(0,0,0,0)),   # <-- hide median (transparent)
        meanprops=dict(color='k', linewidth=1.5, linestyle='-'),
        whiskerprops=dict(color='k', linewidth=1.2),
        capprops=dict(color='k', linewidth=1.2),
    )


# Set y-ticks to scientific notation
axs[0].set_yticks([0,1,2,3,4,5,6])
axs[0].set_yticklabels(['1','10','100','1,000','10,000','100,000','1,000,000'])
axs[0].set_ylim([0,6])

# Make log scale y-axis
axs[0].set_ylabel('Cost for X23 dataset (CPU core-hours)')

# Remove top and right spines
axs[0].spines['top'].set_visible(False)
axs[0].spines['right'].set_visible(False)

# Add gridlines
axs[0].grid(axis='y', linestyle='--', alpha=0.3)

axs[0].set_xticks([0,1,2.5,4.5])
axs[0].set_xticklabels(['GGA','Hybrid','LNO-MBE-\nCCSD(T)','DMC'])

# Add vertical text for CCSD(T) and DMC
axs[0].text(2+0.02, 3.7, r'low [$2\,$kJ/mol w.r.t.\ high]', fontsize=8, rotation=90, ha='center')
axs[0].text(2.5+0.02, 4, r'moderate [$1\,$kJ/mol]', fontsize=8, rotation=90, ha='center')
axs[0].text(3+0.02, 4.5, r'high', fontsize=8, rotation=90, ha='center')

axs[0].text(4+0.02, 0.7, r'$2{\sigma}=4\,$kJ/mol', fontsize=8, rotation=90, ha='center')
axs[0].text(4.5+0.02, 1.8, r'$2{\sigma}=2\,$kJ/mol', fontsize=8, rotation=90, ha='center')
axs[0].text(5+0.02, 2.9, r'$2{\sigma}=1\,$kJ/mol', fontsize=8, rotation=90, ha='center')


# Add a and b labels
axs[1].text(-0.15, 1.05, 'b', transform=axs[1].transAxes, fontsize=12, fontweight='bold')
axs[0].text(-0.15, 1.05, 'a', transform=axs[0].transAxes, fontsize=12, fontweight='bold')

plt.savefig('Figures/MAIN_Figure-Accuracy_and_Cost.png')